-- Phase 77: 2000s Britrock / indie-Britannia completeness, verified per-part tone data.

with target(artist_name, artist_slug, song_title, song_slug, album, release_year) as (
  values
    ('Kasabian','kasabian','Club Foot','club-foot','Kasabian',2004),
    ('Stereophonics','stereophonics','Dakota','dakota','Language. Sex. Violence. Other?',2005),
    ('Stereophonics','stereophonics','Maybe Tomorrow','maybe-tomorrow','You Gotta Go There to Come Back',2003),
    ('Feeder','feeder','Buck Rogers','buck-rogers','Echo Park',2001),
    ('Travis','travis','Why Does It Always Rain on Me?','why-does-it-always-rain-on-me','The Man Who',1999),
    ('Travis','travis','Sing','sing','The Invisible Band',2001),
    ('Snow Patrol','snow-patrol','Run','run','Final Straw',2003),
    ('Doves','doves','There Goes the Fear','there-goes-the-fear','The Last Broadcast',2002),
    ('Elbow','elbow','One Day Like This','one-day-like-this','The Seldom Seen Kid',2008),
    ('Razorlight','razorlight','Golden Touch','golden-touch','Up All Night',2004),
    ('The Libertines','the-libertines','Don''t Look Back into the Sun','dont-look-back-into-the-sun','Don''t Look Back into the Sun',2003),
    ('The Libertines','the-libertines','Can''t Stand Me Now','cant-stand-me-now','The Libertines',2004),
    ('Kaiser Chiefs','kaiser-chiefs','I Predict a Riot','i-predict-a-riot','Employment',2004),
    ('Kaiser Chiefs','kaiser-chiefs','Ruby','ruby','Yours Truly, Angry Mob',2007),
    ('The Fratellis','the-fratellis','Chelsea Dagger','chelsea-dagger','Costello Music',2006),
    ('The Fratellis','the-fratellis','Whistle for the Choir','whistle-for-the-choir','Costello Music',2006),
    ('The Zutons','the-zutons','Valerie','valerie','Tired of Hanging Around',2006),
    ('Editors','editors','Munich','munich','The Back Room',2005),
    ('Maximo Park','maximo-park','Apply Some Pressure','apply-some-pressure','A Certain Trigger',2005),
    ('The View','the-view','Same Jeans','same-jeans','Hats Off to the Buskers',2007),
    ('The Coral','the-coral','Dreaming of You','dreaming-of-you','The Coral',2002),
    ('Supergrass','supergrass','Alright','alright','I Should Coco',1995),
    ('Ash','ash','Girl from Mars','girl-from-mars','1977',1995),
    ('Placebo','placebo','Every You Every Me','every-you-every-me','Without You I''m Nothing',1998),
    ('Manic Street Preachers','manic-street-preachers','Motorcycle Emptiness','motorcycle-emptiness','Generation Terrorists',1992)
),
ins_artists as (
  insert into public.artists (name, slug, search_text, is_active)
  select distinct artist_name, artist_slug, artist_name, true from target
  on conflict (slug) do update set name = excluded.name, is_active = true
  returning id, slug
)
insert into public.songs (artist_id, title, slug, album, release_year, search_text, is_active)
select a.id, t.song_title, t.song_slug, t.album, t.release_year,
       concat_ws(' ', t.song_title, t.artist_name, t.album), true
from target t join ins_artists a on a.slug = t.artist_slug
on conflict (artist_id, slug) do update set
  title = excluded.title, album = excluded.album, release_year = excluded.release_year,
  is_active = true, updated_at = now();

delete from public.tone_profile_effects e where e.profile_id in (
  select p.id from public.song_tone_profiles p
  join public.songs s on s.id = p.song_id join public.artists a on a.id = s.artist_id
  join (values
    ('kasabian','club-foot'),('stereophonics','dakota'),('stereophonics','maybe-tomorrow'),('feeder','buck-rogers'),
    ('travis','why-does-it-always-rain-on-me'),('travis','sing'),('snow-patrol','run'),('doves','there-goes-the-fear'),
    ('elbow','one-day-like-this'),('razorlight','golden-touch'),('the-libertines','dont-look-back-into-the-sun'),
    ('the-libertines','cant-stand-me-now'),('kaiser-chiefs','i-predict-a-riot'),('kaiser-chiefs','ruby'),
    ('the-fratellis','chelsea-dagger'),('the-fratellis','whistle-for-the-choir'),('the-zutons','valerie'),
    ('editors','munich'),('maximo-park','apply-some-pressure'),('the-view','same-jeans'),('the-coral','dreaming-of-you'),
    ('supergrass','alright'),('ash','girl-from-mars'),('placebo','every-you-every-me'),
    ('manic-street-preachers','motorcycle-emptiness')
  ) as t(artist_slug, song_slug) on t.artist_slug = a.slug and t.song_slug = s.slug
);
delete from public.tone_profile_sources src where src.profile_id in (
  select p.id from public.song_tone_profiles p
  join public.songs s on s.id = p.song_id join public.artists a on a.id = s.artist_id
  join (values
    ('kasabian','club-foot'),('stereophonics','dakota'),('stereophonics','maybe-tomorrow'),('feeder','buck-rogers'),
    ('travis','why-does-it-always-rain-on-me'),('travis','sing'),('snow-patrol','run'),('doves','there-goes-the-fear'),
    ('elbow','one-day-like-this'),('razorlight','golden-touch'),('the-libertines','dont-look-back-into-the-sun'),
    ('the-libertines','cant-stand-me-now'),('kaiser-chiefs','i-predict-a-riot'),('kaiser-chiefs','ruby'),
    ('the-fratellis','chelsea-dagger'),('the-fratellis','whistle-for-the-choir'),('the-zutons','valerie'),
    ('editors','munich'),('maximo-park','apply-some-pressure'),('the-view','same-jeans'),('the-coral','dreaming-of-you'),
    ('supergrass','alright'),('ash','girl-from-mars'),('placebo','every-you-every-me'),
    ('manic-street-preachers','motorcycle-emptiness')
  ) as t(artist_slug, song_slug) on t.artist_slug = a.slug and t.song_slug = s.slug
);
delete from public.song_tone_profiles p where p.id in (
  select p2.id from public.song_tone_profiles p2
  join public.songs s on s.id = p2.song_id join public.artists a on a.id = s.artist_id
  join (values
    ('kasabian','club-foot'),('stereophonics','dakota'),('stereophonics','maybe-tomorrow'),('feeder','buck-rogers'),
    ('travis','why-does-it-always-rain-on-me'),('travis','sing'),('snow-patrol','run'),('doves','there-goes-the-fear'),
    ('elbow','one-day-like-this'),('razorlight','golden-touch'),('the-libertines','dont-look-back-into-the-sun'),
    ('the-libertines','cant-stand-me-now'),('kaiser-chiefs','i-predict-a-riot'),('kaiser-chiefs','ruby'),
    ('the-fratellis','chelsea-dagger'),('the-fratellis','whistle-for-the-choir'),('the-zutons','valerie'),
    ('editors','munich'),('maximo-park','apply-some-pressure'),('the-view','same-jeans'),('the-coral','dreaming-of-you'),
    ('supergrass','alright'),('ash','girl-from-mars'),('placebo','every-you-every-me'),
    ('manic-street-preachers','motorcycle-emptiness')
  ) as t(artist_slug, song_slug) on t.artist_slug = a.slug and t.song_slug = s.slug
);

insert into public.song_tone_profiles (
  song_id, song_title, artist_name, mode, part_type, part_label, tone_type,
  genre, tone_category, difficulty,
  original_guitar, original_amp, original_cab, original_pickup,
  original_effects, original_settings, adaptation_notes, playing_notes,
  source_summary, confidence, verification_status, search_text, is_public
)
select
  s.id, s.title, a.name, c.mode, c.part_type, c.part_label, c.tone_type,
  c.genre, c.tone_category, c.difficulty,
  c.original_guitar, c.original_amp, c.original_cab, c.original_pickup,
  c.original_effects, c.original_settings, c.adaptation_notes, c.playing_notes,
  c.source_summary, c.confidence, 'admin_verified',
  concat_ws(' ', s.title, a.name, c.part_label, c.tone_type, c.original_guitar, c.original_amp, 'researched verified tone'),
  true
from (
  values
    ('club-foot','kasabian','guitar','riff','main riff','distorted','britrock','rhythm','intermediate',
     'Fender/Gibson electric (Sergio Pizzorno)','Driven amp with electro menace','Closed-back cab','bridge pickup',
     '[]'::jsonb,'{"gain":6,"bass":6,"mids":5,"treble":6,"presence":6,"reverb":1,"delay":0,"master":8}'::jsonb,
     array['The Leicester swagger-stomp — driving electro-rock riff over the pulsing bass.','Tight aggressive drive; football-terrace menace.'],
     array['Stab the riff with the electronic pulse.','Play it like a floodlit night match.'],
     'Studio recording, 2004. The electro-rock terrace stomp.',74),
    ('dakota','stereophonics','guitar','riff','main riff','crunch','britrock','rhythm','beginner',
     'Fender/Gibson electric (Kelly Jones)','Tube amp, anthemic drive','Closed-back cab','bridge pickup',
     '[]'::jsonb,'{"gain":5,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":2,"delay":1,"master":8}'::jsonb,
     array['The Welsh arena anthem — driving warm crunch under the you-made-me-feel-like-the-one chorus.','Big open drive; motorway momentum.'],
     array['Drive the eighth-note chords relentlessly.','The chorus lifts — take everyone with you.'],
     'Studio recording, 2005. The motorway arena anthem.',75),
    ('maybe-tomorrow','stereophonics','guitar','main','soul-ballad progression','clean','britrock','rhythm','beginner',
     'Gibson electric (Kelly Jones)','Clean amp, warm soul color','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":6,"treble":5,"presence":4,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['The closing-credits soul ballad — warm rounded clean under the rasp.','Soft mellow clean; so-I-look-in-the-sky patience.'],
     array['Gentle soul comping throughout.','Maybe tomorrow I''ll find my way home — unhurried.'],
     'Studio recording, 2003. The closing-credits soul ballad.',75),
    ('buck-rogers','feeder','guitar','riff','main riff','distorted','britrock','rhythm','beginner',
     'Fender/Gibson electric (Grant Nicholas)','Driven amp, chunky pop-rock','Closed-back cab','bridge humbucker',
     '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":1,"delay":0,"master":8}'::jsonb,
     array['The he''s-got-a-brand-new-car single — chunky saturated pop-rock riffing.','Thick bright drive; grinning power chords.'],
     array['Punch the chord riff on the grid.','We''ll start over again — full energy.'],
     'Studio recording, 2001. The brand-new-car single.',74),
    ('why-does-it-always-rain-on-me','travis','guitar','main','melancholy strums','acoustic','britrock','rhythm','beginner',
     'Acoustic + electric (Fran Healy / Andy Dunlop)','Acoustic with warm electric color','Open-back combo cab','neck pickup',
     '[]'::jsonb,'{"gain":0,"bass":5,"mids":5,"treble":6,"presence":5,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['The Glastonbury rain-summoner — warm melancholy strums that famously started the downpour.','Soft open acoustic; Scottish drizzle in D.'],
     array['Roll the strums gently under the sigh.','Is it because I lied when I was seventeen? — that rueful.'],
     'Studio recording, 1999. The rain-summoning anthem.',75),
    ('sing','travis','guitar','main','banjo-folk pop','acoustic','britrock','rhythm','beginner',
     'Acoustic + banjo (Fran Healy / Andy Dunlop)','Acoustic — mic''d, warm pop','No cab (acoustic)','n/a (acoustic)',
     '[]'::jsonb,'{"gain":0,"bass":5,"mids":5,"treble":6,"presence":5,"reverb":2,"delay":0,"master":6}'::jsonb,
     array['The banjo-kissed love note — gentle strums with the rolling banjo hook.','Warm soft acoustic; for the love you bring.'],
     array['Easy strums; pick the banjo figure high if solo.','Sing, sing, siiing — softly.'],
     'Studio recording, 2001. The banjo love note.',75),
    ('run','snow-patrol','guitar','riff','ballad build','clean','britrock','rhythm','beginner',
     'Electric guitar (Nathan Connolly / Gary Lightbody)','Clean-to-wall rig','Closed-back cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"hall reverb","placement":"post_gain","settings":{"mix":4}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":4,"delay":1,"master":6}'::jsonb,
     array['The light-up anthem — hushed clean arpeggios (settings shown) into the soaring wall (gain 6).','Wet gentle clean; the chorus asks for the sky.'],
     array['Arpeggiate the verses softly.','Light up, light up — full wall, full heart.'],
     'Studio recording, 2003. The light-up anthem.',75),
    ('there-goes-the-fear','doves','guitar','riff','chiming build','clean','britrock','rhythm','intermediate',
     'Fender electric (Jez Williams)','Clean amp with chiming delay','Open-back combo cab','bridge pickup',
     '[{"effect_type":"delay","effect_name":"rhythmic delay","placement":"post_gain","settings":{"time":4,"mix":4,"feedback":4}},{"effect_type":"reverb","effect_name":"hall reverb","placement":"post_gain","settings":{"mix":4}}]'::jsonb,
     '{"gain":3,"bass":5,"mids":5,"treble":7,"presence":6,"reverb":4,"delay":4,"master":7}'::jsonb,
     array['The Mancunian sunrise — chiming delayed figures building to the percussion-storm outro.','Bright wet clean; the delay is half the riff.'],
     array['Time the picking to the delay repeats.','There goes the fear — let it go loudly.'],
     'Studio recording, 2002. The chiming Mancunian sunrise.',74),
    ('one-day-like-this','elbow','guitar','main','string-swell anthem','clean','britrock','rhythm','beginner',
     'Electric guitar (Mark Potter)','Clean amp under orchestra','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"hall reverb","placement":"post_gain","settings":{"mix":4}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":5,"presence":4,"reverb":4,"delay":0,"master":6}'::jsonb,
     array['The wedding-and-Olympics closer — gentle clean support under the string swell.','Warm unobtrusive clean; throw those curtains wide.'],
     array['Comp softly; the strings and choir carry it.','One day like this a year would see me right.'],
     'Studio recording, 2008. The curtains-wide anthem.',74),
    ('golden-touch','razorlight','guitar','riff','jangle riff','clean','britrock','rhythm','beginner',
     'Fender electric (Johnny Borrell / Bjorn Agren)','Clean amp, wiry jangle','Open-back combo cab','bridge pickup',
     '[]'::jsonb,'{"gain":3,"bass":4,"mids":5,"treble":7,"presence":6,"reverb":2,"delay":0,"master":6}'::jsonb,
     array['The indie-disco staple — wiry jangle riff with strutting confidence.','Bright thin-wire clean; the riff skips.'],
     array['The picked riff hooks in one bar.','She''s got the golden touch — play it slick.'],
     'Studio recording, 2004. The indie-disco jangle staple.',73),
    ('dont-look-back-into-the-sun','the-libertines','guitar','riff','main riff','crunch','britrock','rhythm','intermediate',
     'Epiphone Coronet/Gibson (Pete Doherty / Carl Barat)','Tube amp, shambling crunch','Open-back cab','bridge pickup',
     '[]'::jsonb,'{"gain":5,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":2,"delay":0,"master":7}'::jsonb,
     array['The Albion anthem — shambling romantic crunch, gloriously loose.','Warm ragged drive; Arcadian chaos with hooks.'],
     array['The riff staggers charmingly — don''t over-tighten.','They''ll never forgive you but they won''t forget.'],
     'Studio recording, 2003. The shambling Albion anthem.',74),
    ('cant-stand-me-now','the-libertines','guitar','riff','duelling riffs','crunch','britrock','rhythm','intermediate',
     'Epiphone/Gibson (Pete Doherty / Carl Barat)','Tube amps, frayed duet crunch','Open-back cabs','bridge pickup',
     '[]'::jsonb,'{"gain":5,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":2,"delay":0,"master":7}'::jsonb,
     array['The friendship autopsy — two frayed guitars arguing like their owners.','Loose warm crunch; the tension is the arrangement.'],
     array['Trade the riffs conversationally.','An ending fitting for the start.'],
     'Studio recording, 2004. The friendship-autopsy duet.',74),
    ('i-predict-a-riot','kaiser-chiefs','guitar','riff','main riff','distorted','britrock','rhythm','beginner',
     'Fender/Gibson electric (Andrew White)','Driven amp, yelping crunch','Closed-back cab','bridge pickup',
     '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":1,"delay":0,"master":8}'::jsonb,
     array['The Leeds prophecy — jittery saturated riffing at kick-out time.','Bright punchy drive; watch out for the tracksuits.'],
     array['Stab the verse riff nervous and tight.','La-ah-ah-ah — riot responsibly.'],
     'Studio recording, 2004. The kick-out-time prophecy.',74),
    ('ruby','kaiser-chiefs','guitar','riff','main riff','distorted','britrock','rhythm','beginner',
     'Fender/Gibson electric (Andrew White)','Driven amp, stomping crunch','Closed-back cab','bridge humbucker',
     '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":1,"delay":0,"master":8}'::jsonb,
     array['The Ruby-Ruby-Ruby stomp — massive simple riff under the chant.','Thick bright drive; the name is the hook.'],
     array['Stomp the riff with the kick.','Due to lack of interest tomorrow is cancelled.'],
     'Studio recording, 2007. The name-chant stomp.',74),
    ('chelsea-dagger','the-fratellis','guitar','riff','main riff','crunch','britrock','rhythm','beginner',
     'Gibson hollow-body (Jon Fratelli)','Tube amp, barroom crunch','Open-back cab','bridge pickup',
     '[]'::jsonb,'{"gain":5,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":2,"delay":0,"master":8}'::jsonb,
     array['The stadium goal-song — swaggering barroom riff under the del-del-del chant.','Warm rowdy crunch; every arena knows it.'],
     array['Swing the riff like last orders.','Duh duh duh — you''ve sung it at a match already.'],
     'Studio recording, 2006. The goal-song barroom riff.',75),
    ('whistle-for-the-choir','the-fratellis','guitar','main','waltz serenade','clean','britrock','rhythm','beginner',
     'Hollow-body electric (Jon Fratelli)','Clean amp, tender waltz','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['The 3 a.m. serenade — gentle waltzing clean from the rowdiest band in Glasgow.','Soft warm clean; well it''s a big big city.'],
     array['Waltz the chords tenderly.','So if you''re lonely — sing it to someone.'],
     'Studio recording, 2006. The 3 a.m. waltz serenade.',74),
    ('valerie','the-zutons','guitar','riff','soul-pop riff','clean','britrock','rhythm','beginner',
     'Fender electric (Boyan Chowdhury)','Clean amp, soul-pop bounce','Open-back combo cab','bridge pickup',
     '[]'::jsonb,'{"gain":3,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":2,"delay":0,"master":6}'::jsonb,
     array['The original Valerie — bouncing soul-pop chords before Winehouse made it eternal.','Bright springy clean; Liverpool soul revue.'],
     array['Bounce the chord stabs with the horns.','Why don''t you come on over, Valerie?'],
     'Studio recording, 2006. The original Valerie bounce.',75),
    ('munich','editors','guitar','riff','dark jangle riff','crunch','britrock','rhythm','intermediate',
     'Fender Telecaster (Chris Urbanowicz)','Bright amp, dark post-punk chime','Closed-back cab','bridge pickup',
     '[{"effect_type":"delay","effect_name":"subtle delay","placement":"post_gain","settings":{"time":3,"mix":2,"feedback":2}}]'::jsonb,
     '{"gain":4,"bass":4,"mids":5,"treble":8,"presence":7,"reverb":2,"delay":2,"master":7}'::jsonb,
     array['The people-are-fragile-things chime — icy trebly riffing in the Interpol lineage.','Ultra-bright cutting drive; the riff pierces.'],
     array['Pick the high riff needle-precise.','Cold hands, big chorus.'],
     'Studio recording, 2005. The icy chime single.',74),
    ('apply-some-pressure','maximo-park','guitar','riff','angular riff','crunch','britrock','rhythm','intermediate',
     'Fender electric (Duncan Lloyd)','Driven amp, angular art-punk','Closed-back cab','bridge pickup',
     '[]'::jsonb,'{"gain":5,"bass":4,"mids":6,"treble":7,"presence":6,"reverb":1,"delay":0,"master":8}'::jsonb,
     array['The Newcastle head-spinner — jerky angular crunch riffing.','Trebly twitchy drive; art-punk calisthenics.'],
     array['The riff zigzags — count the jumps.','What happens when you lose everything? You start again.'],
     'Studio recording, 2005. The angular head-spinner.',73),
    ('same-jeans','the-view','guitar','riff','jangle strums','crunch','britrock','rhythm','beginner',
     'Fender/Gibson electric (Pete Reilly)','Tube amp, jangly crunch','Open-back cab','bridge pickup',
     '[]'::jsonb,'{"gain":4,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":2,"delay":0,"master":7}'::jsonb,
     array['The Dundee singalong — warm jangle-crunch about four-day denim.','Loose bright drive; charm over polish.'],
     array['Strum the progression carefree.','I''ve had the same jeans on for four days now — relatable tempo.'],
     'Studio recording, 2007. The four-day-denim singalong.',73),
    ('dreaming-of-you','the-coral','guitar','riff','merseybeat-noir riff','clean','britrock','rhythm','beginner',
     'Hollow-body electric (Bill Ryder-Jones / James Skelly)','Clean amp, spooky Merseybeat','Open-back combo cab','bridge pickup',
     '[{"effect_type":"reverb","effect_name":"spring reverb","placement":"post_gain","settings":{"mix":4}}]'::jsonb,
     '{"gain":3,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":4,"delay":0,"master":6}'::jsonb,
     array['The spooky Merseybeat earworm (Scrubs made it global) — springy minor-key riffing.','Springy vintage clean; haunted-jukebox charm.'],
     array['The riff bounces in minor.','Up in my lonely room — but make it danceable.'],
     'Studio recording, 2002. The haunted-jukebox earworm.',74),
    ('alright','supergrass','guitar','riff','piano-pop riff','clean','britpop','rhythm','beginner',
     'Fender electric (Gaz Coombes)','Clean amp, cheeky bounce','Open-back combo cab','bridge pickup',
     '[]'::jsonb,'{"gain":3,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":2,"delay":0,"master":7}'::jsonb,
     array['The young-and-clean-teeth romp — bouncing bright riffing with the piano.','Snappy grinning clean-crunch; eternal youth in G.'],
     array['Bounce with the piano vamp.','We are young, we run green — keep it springy.'],
     'Studio recording, 1995. The eternal-youth romp.',75),
    ('girl-from-mars','ash','guitar','riff','main riff','distorted','britpop','rhythm','beginner',
     'Gibson/Fender electric (Tim Wheeler)','Driven amp, teenage fireworks','Closed-back cab','bridge humbucker',
     '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":2,"delay":0,"master":8}'::jsonb,
     array['The teenage-firework single — bright saturated power-pop from actual teenagers.','Sparkling drive; summer-night rocket fuel.'],
     array['Drive the chords with joy.','Do you remember the girl from Mars?'],
     'Studio recording, 1995. The teenage-firework single.',74),
    ('every-you-every-me','placebo','guitar','riff','main riff','distorted','alternative rock','rhythm','intermediate',
     'Fender Jaguar (Brian Molko)','Driven amp, wiry androgynous bite','Closed-back cab','bridge pickup',
     '[]'::jsonb,'{"gain":6,"bass":4,"mids":5,"treble":8,"presence":7,"reverb":1,"delay":0,"master":8}'::jsonb,
     array['The Cruel Intentions single — needling wiry drive in open tuning.','Thin sharp saturation; sucker love at 140.'],
     array['Molko''s open tuning shapes the riff — adapt the drones.','Needle-pick the verse figure.'],
     'Studio recording, 1998. The needling Cruel Intentions single.',74),
    ('motorcycle-emptiness','manic-street-preachers','guitar','riff','lead theme','clean','britrock','lead','intermediate',
     'Gibson Les Paul (James Dean Bradfield)','Clean-to-crunch with singing lead','Closed-back cab','bridge humbucker',
     '[{"effect_type":"chorus","effect_name":"gloss chorus","placement":"post_gain","settings":{"rate":3,"depth":4,"mix":4}},{"effect_type":"delay","effect_name":"lead delay","placement":"post_gain","settings":{"time":3,"mix":3,"feedback":2}}]'::jsonb,
     '{"gain":4,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":3,"delay":3,"master":7}'::jsonb,
     array['The glam-rage elegy — Bradfield''s glossy singing lead theme over six minutes of neon.','Chorused semi-clean lead voice; despair in designer clothes.'],
     array['The lead theme recurs — phrase it like the second vocal.','Under neon loneliness, motorcycle emptiness.'],
     'Studio recording, 1992. Bradfield''s neon lead elegy.',75)
) as c(
  song_slug, artist_slug, mode, part_type, part_label, tone_type, genre, tone_category, difficulty,
  original_guitar, original_amp, original_cab, original_pickup,
  original_effects, original_settings, adaptation_notes, playing_notes, source_summary, confidence
)
join public.artists a on a.slug = c.artist_slug
join public.songs s on s.artist_id = a.id and s.slug = c.song_slug;
