begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('bass_amp', 'Ampeg', 'Heritage SVT-CL', 'Heritage SVT', false, 'US made Heritage SVT-CL 300 watt tube head.'),
  ('bass_amp', 'Ampeg', 'SVT-7PRO', 'SVT', true, '1000 watt SVT-7PRO hybrid bass head.'),
  ('bass_amp', 'Ampeg', 'SVT-3PRO', 'SVT', true, '450 watt SVT-3PRO hybrid bass head.'),
  ('bass_amp', 'Ampeg', 'PF-20T', 'Portaflex', false, '20 watt Portaflex all tube head.'),
  ('bass_amp', 'Ampeg', 'PF-50T', 'Portaflex', false, '50 watt Portaflex all tube head.'),
  ('bass_amp', 'Ampeg', 'PF-350', 'Portaflex', false, '350 watt Portaflex head.'),
  ('bass_amp', 'Ampeg', 'PF-500', 'Portaflex', true, '500 watt Portaflex head.'),
  ('bass_amp', 'Ampeg', 'PF-800', 'Portaflex', false, '800 watt Portaflex head.'),
  ('bass_amp', 'Ampeg', 'BA-108v2', 'BA', false, '20 watt BA-108v2 practice combo.'),
  ('bass_amp', 'Ampeg', 'BA-110v2', 'BA', false, '40 watt BA-110v2 practice combo.'),
  ('bass_amp', 'Ampeg', 'BA-112v2', 'BA', false, '75 watt BA-112v2 combo.'),
  ('bass_amp', 'Ampeg', 'BA-115v2', 'BA', false, '150 watt BA-115v2 combo.'),
  ('bass_amp', 'Ampeg', 'BA-210v2', 'BA', false, '450 watt BA-210v2 2x10 combo.'),
  ('bass_amp', 'Ampeg', 'Micro-VR', 'Micro', true, 'Ultra compact 200 watt Micro-VR SVT style head.'),
  ('bass_amp', 'Ampeg', 'Micro-CL', 'Micro', true, 'Ultra compact 100 watt Micro-CL bass stack.'),
  ('bass_amp', 'Ampeg', 'RB-108', 'Rocket Bass', false, '30 watt Rocket Bass RB-108 practice combo.'),
  ('bass_amp', 'Ampeg', 'RB-110', 'Rocket Bass', false, '50 watt Rocket Bass RB-110 combo.'),
  ('bass_amp', 'Ampeg', 'RB-112', 'Rocket Bass', false, '100 watt Rocket Bass RB-112 combo.'),
  ('bass_amp', 'Ampeg', 'RB-115', 'Rocket Bass', false, '200 watt Rocket Bass RB-115 combo.'),
  ('bass_amp', 'Ampeg', 'V-4B', 'V', false, '100 watt V-4B all tube head reissue.'),
  ('bass_amp', 'Ampeg', 'Venture V3', 'Venture', false, '300 watt Venture V3 lightweight head.'),
  ('bass_amp', 'Ampeg', 'Venture V7', 'Venture', false, '700 watt Venture V7 lightweight head.'),
  ('bass_amp', 'Ampeg', 'Venture V12', 'Venture', false, '1200 watt Venture V12 lightweight flagship head.'),
  ('bass_amp', 'Hartke', 'LX5500', 'LX', false, '500 watt LX5500 bass head with tube preamp.'),
  ('bass_amp', 'Hartke', 'LX8500', 'LX', false, '800 watt LX8500 bass head.'),
  ('bass_amp', 'Hartke', 'TX600', 'TX', false, '600 watt TX600 lightweight bass head.'),
  ('bass_amp', 'Hartke', 'HD15', 'HD', false, '15 watt HD15 practice bass combo.'),
  ('bass_amp', 'Hartke', 'HD25', 'HD', false, '25 watt HD25 bass combo.'),
  ('bass_amp', 'Hartke', 'HD50', 'HD', false, '50 watt HD50 bass combo.'),
  ('bass_amp', 'Hartke', 'HD75', 'HD', false, '75 watt HD75 bass combo.'),
  ('bass_amp', 'Hartke', 'HD150', 'HD', false, '150 watt HD150 bass combo.'),
  ('bass_amp', 'Hartke', 'HD500', 'HD', false, '500 watt HD500 bass combo.'),
  ('bass_amp', 'Hartke', 'Kickback KB12', 'Kickback', false, 'Kickback KB12 angled bass combo.'),
  ('bass_amp', 'Hartke', 'Kickback KB15', 'Kickback', false, 'Kickback KB15 angled bass combo.'),
  ('bass_amp', 'Gallien Krueger', 'MB108', 'MB', false, '25 watt MB108 practice bass combo.'),
  ('bass_amp', 'Gallien Krueger', 'MB110', 'MB', false, '100 watt MB110 lightweight combo.'),
  ('bass_amp', 'Gallien Krueger', 'MB112-II', 'MB', false, '200 watt MB112-II lightweight combo.'),
  ('bass_amp', 'Gallien Krueger', 'MB115-II', 'MB', false, '200 watt MB115-II lightweight combo.'),
  ('bass_amp', 'Gallien Krueger', 'MB800', 'MB', true, '800 watt MB800 ultra lightweight bass head.'),
  ('bass_amp', 'Gallien Krueger', 'Legacy 500', 'Legacy', false, '500 watt Legacy 500 lightweight bass head.'),
  ('bass_amp', 'Gallien Krueger', 'Legacy 800', 'Legacy', false, '800 watt Legacy 800 lightweight bass head.'),
  ('bass_amp', 'Gallien Krueger', 'Legacy 1200', 'Legacy', false, '1200 watt Legacy 1200 lightweight bass head.'),
  ('bass_amp', 'Gallien Krueger', 'RB700-II', 'RB', false, '480 watt RB700-II bass head.'),
  ('bass_amp', 'Gallien Krueger', 'RB1001-II', 'RB', false, '540 watt RB1001-II bass head.'),
  ('bass_amp', 'Markbass', 'Little Mark III', 'Little Mark', false, '500 watt Little Mark III lightweight bass head.'),
  ('bass_amp', 'Markbass', 'Little Mark 58R', 'Little Mark', false, '500 watt Little Mark 58R with reverb.'),
  ('bass_amp', 'Markbass', 'Little Mark Vintage', 'Little Mark', false, '500 watt Little Mark Vintage with vintage voicing.'),
  ('bass_amp', 'Markbass', 'Little Marcus 58R', 'Little Marcus', false, 'Marcus Miller signature Little Marcus 58R with reverb.'),
  ('bass_amp', 'Markbass', 'Little Marcus 500', 'Little Marcus', false, '500 watt Marcus Miller signature head.'),
  ('bass_amp', 'Markbass', 'Little Marcus 1000', 'Little Marcus', false, '1000 watt Marcus Miller flagship head.'),
  ('bass_amp', 'Markbass', 'CMD 101 Micro 60', 'CMD', false, '60 watt CMD 101 Micro 1x10 combo.'),
  ('bass_amp', 'Markbass', 'CMD 102P', 'CMD', false, '300 watt CMD 102P 2x10 combo.'),
  ('bass_amp', 'Markbass', 'Mini CMD 121P', 'CMD', false, '500 watt Mini CMD 121P 1x12 combo.'),
  ('bass_amp', 'Markbass', 'MB58R CMD 102 Pure', 'CMD', false, 'MB58R CMD 102 Pure 2x10 combo.'),
  ('bass_amp', 'Markbass', 'Nano Mark 300', 'Nano', false, '300 watt Nano Mark ultra compact bass head.'),
  ('bass_amp', 'Markbass', 'Big Bang III', 'Big Bang', false, 'Big Bang III lightweight bass head.'),
  ('bass_amp', 'Darkglass', 'Alpha Omega 900', 'Alpha Omega', false, '900 watt Alpha Omega 900 bass head with dual channels.'),
  ('bass_amp', 'Darkglass', 'Exponent 500', 'Exponent', false, '500 watt Exponent 500 modeling bass amp.'),
  ('bass_amp', 'Darkglass', 'Microtubes X 900', 'Microtubes', false, '900 watt Microtubes X flagship bass head.'),
  ('bass_amp', 'Darkglass', 'Element', 'Element', false, 'Element cabinet simulator DI pedal.'),
  ('bass_amp', 'Aguilar', 'Tone Hammer 350', 'Tone Hammer', true, '350 watt Tone Hammer lightweight bass head.'),
  ('bass_amp', 'Aguilar', 'Tone Hammer 500', 'Tone Hammer', true, '500 watt Tone Hammer bass head.'),
  ('bass_amp', 'Aguilar', 'Tone Hammer 700', 'Tone Hammer', false, '700 watt Tone Hammer bass head.'),
  ('bass_amp', 'Aguilar', 'AG 700', 'AG', false, '700 watt AG 700 lightweight bass head.'),
  ('bass_amp', 'Aguilar', 'DB 751', 'DB', false, '975 watt DB 751 tube preamp bass head.'),
  ('bass_amp', 'TC Electronic', 'BH250', 'BH', false, '250 watt BH250 lightweight bass head.'),
  ('bass_amp', 'TC Electronic', 'BH550', 'BH', false, '550 watt BH550 lightweight bass head.'),
  ('bass_amp', 'TC Electronic', 'BH800', 'BH', false, '800 watt BH800 lightweight bass head with TubeDrive.'),
  ('bass_amp', 'TC Electronic', 'RH450', 'RH', false, '450 watt RH450 bass head with TonePrint effects.'),
  ('bass_amp', 'TC Electronic', 'BG250-112', 'BG', false, '250 watt BG250-112 combo.'),
  ('bass_amp', 'TC Electronic', 'BG250-115', 'BG', false, '250 watt BG250-115 combo.'),
  ('bass_amp', 'Trace Elliot', 'ELF', 'ELF', true, '200 watt ELF ultra portable bass head.'),
  ('bass_amp', 'Trace Elliot', 'ELF Combo 1x10', 'ELF', false, 'ELF Combo 1x10 with 200 watt ELF head.'),
  ('bass_amp', 'Trace Elliot', 'ELF Combo 2x8', 'ELF', false, 'ELF Combo 2x8 with 200 watt ELF head.'),
  ('bass_amp', 'Trace Elliot', 'Transit B', 'Transit', false, 'Transit B pedal format bass preamp.'),
  ('bass_amp', 'Ashdown', 'ABM 300 EVO IV', 'ABM', false, '300 watt ABM 300 EVO IV bass head.'),
  ('bass_amp', 'Ashdown', 'RM-500 EVO II', 'RM', false, '500 watt Rootmaster RM-500 EVO II head.'),
  ('bass_amp', 'Ashdown', 'Rootmaster RM-C112T-500', 'Rootmaster', false, 'Rootmaster RM-C112T-500 combo.'),
  ('bass_amp', 'Ashdown', 'Studio 8', 'Studio', false, '10 watt Studio 8 practice combo.'),
  ('bass_amp', 'Ashdown', 'Studio 10', 'Studio', false, '30 watt Studio 10 practice combo.'),
  ('bass_amp', 'Ashdown', 'Studio 12', 'Studio', false, '60 watt Studio 12 practice combo.'),
  ('bass_amp', 'Ashdown', 'OriginAL HD-1', 'OriginAL', false, '300 watt OriginAL HD-1 lightweight bass head.'),
  ('bass_amp', 'Ashdown', 'OriginAL C112T-300', 'OriginAL', false, '300 watt OriginAL C112T combo.'),
  ('bass_amp', 'Ashdown', 'Five Fifteen', 'Five Fifteen', false, '15 watt Five Fifteen practice combo.'),
  ('bass_amp', 'Ashdown', 'CTM-100', 'CTM', false, '100 watt CTM-100 all tube bass head.'),
  ('bass_amp', 'Fender', 'Rumble 15', 'Rumble', false, '15 watt Rumble 15 practice combo.'),
  ('bass_amp', 'Fender', 'Rumble 25', 'Rumble', false, '25 watt Rumble 25 practice combo.'),
  ('bass_amp', 'Fender', 'Rumble 200', 'Rumble', false, '200 watt Rumble 200 combo.'),
  ('bass_amp', 'Fender', 'Rumble 800 Combo', 'Rumble', false, '800 watt Rumble 800 combo.'),
  ('bass_amp', 'Fender', 'Rumble LT25', 'Rumble', false, '25 watt Rumble LT25 modeling combo.'),
  ('bass_amp', 'Fender', 'Rumble Stage 800', 'Rumble', false, '800 watt Rumble Stage modeling combo.'),
  ('bass_amp', 'Fender', 'Rumble Studio 40', 'Rumble', false, '40 watt Rumble Studio modeling combo.'),
  ('bass_amp', 'Fender', 'Rumble 800 HD', 'Rumble', false, '800 watt Rumble 800 HD lightweight bass head.'),
  ('bass_amp', 'Orange', 'OB1-300', 'OB1', false, '300 watt OB1-300 bass head with blendable overdrive.'),
  ('bass_amp', 'Orange', 'Crush Bass 25', 'Crush Bass', false, '25 watt Crush Bass 25 practice combo.'),
  ('bass_amp', 'Orange', 'Crush Bass 50', 'Crush Bass', false, '50 watt Crush Bass 50 combo.'),
  ('bass_amp', 'Orange', 'Crush Bass 100', 'Crush Bass', false, '100 watt Crush Bass 100 combo.'),
  ('bass_amp', 'Orange', '4 Stroke 300', '4 Stroke', false, '300 watt 4 Stroke bass head with 4 band parametric EQ.'),
  ('bass_amp', 'Orange', '4 Stroke 500', '4 Stroke', false, '500 watt 4 Stroke bass head.'),
  ('bass_amp', 'Peavey', 'MAX 100', 'MAX', false, '100 watt MAX 100 bass combo.'),
  ('bass_amp', 'Peavey', 'MAX 150', 'MAX', false, '150 watt MAX 150 bass combo.'),
  ('bass_amp', 'Peavey', 'MAX 208', 'MAX', false, '200 watt MAX 208 2x8 combo.'),
  ('bass_amp', 'Peavey', 'MAX 300', 'MAX', false, '300 watt MAX 300 bass combo.'),
  ('bass_amp', 'Peavey', 'MiniMEGA 600', 'MiniMEGA', false, '600 watt MiniMEGA bass head.'),
  ('bass_amp', 'Warwick', 'Gnome', 'Gnome', true, '200 watt Gnome pocket bass head.'),
  ('bass_amp', 'Warwick', 'Gnome i', 'Gnome', false, '200 watt Gnome i with integrated audio interface.'),
  ('bass_amp', 'Warwick', 'Gnome i Pro', 'Gnome', false, '300 watt Gnome i Pro with expanded features.'),
  ('bass_amp', 'Warwick', 'LWA 500', 'LWA', false, '500 watt LWA 500 lightweight bass head.'),
  ('bass_amp', 'Warwick', 'LWA 1000', 'LWA', false, '1000 watt LWA 1000 lightweight bass head.'),
  ('bass_amp', 'Warwick', 'BC 10', 'BC', false, '10 watt BC 10 practice bass combo.'),
  ('bass_amp', 'Warwick', 'BC 20', 'BC', false, '20 watt BC 20 practice bass combo.'),
  ('bass_amp', 'Warwick', 'BC 40', 'BC', false, '40 watt BC 40 bass combo.'),
  ('bass_amp', 'Warwick', 'BC 80', 'BC', false, '80 watt BC 80 bass combo.'),
  ('bass_amp', 'Warwick', 'BC 150', 'BC', false, '150 watt BC 150 bass combo.'),
  ('bass_amp', 'Phil Jones', 'Double Four BG-75', 'Double Four', false, '70 watt Double Four ultra compact bass combo.'),
  ('bass_amp', 'Phil Jones', 'Bass Cub BG-100', 'Bass Cub', true, '100 watt Bass Cub compact bass combo.'),
  ('bass_amp', 'Phil Jones', 'Bass Cub Pro BG-120', 'Bass Cub', false, '120 watt Bass Cub Pro with expanded features.'),
  ('bass_amp', 'Phil Jones', 'Suitcase Compact BG-400', 'Suitcase', false, '350 watt Suitcase Compact bass combo.'),
  ('bass_amp', 'Phil Jones', 'Briefcase BG-100', 'Briefcase', false, '100 watt Briefcase portable bass combo.'),
  ('bass_amp', 'Eden', 'WTX-264', 'WTX', false, '250 watt WTX-264 lightweight bass head.'),
  ('bass_amp', 'Eden', 'WTX500', 'WTX', false, '500 watt WTX500 lightweight bass head.'),
  ('bass_amp', 'Eden', 'Terra Nova TN226', 'Terra Nova', false, '225 watt Terra Nova TN226 bass head.'),
  ('bass_amp', 'Eden', 'Terra Nova TN501', 'Terra Nova', false, '500 watt Terra Nova TN501 bass head.'),
  ('bass_amp', 'EBS', 'Reidmar 502', 'Reidmar', false, '500 watt Reidmar 502 lightweight bass head.'),
  ('bass_amp', 'EBS', 'Reidmar 752', 'Reidmar', false, '750 watt Reidmar 752 lightweight bass head.'),
  ('bass_amp', 'EBS', 'Magni 500 210', 'Magni', false, '500 watt Magni 500 combo with 2x10 speakers.'),
  ('bass_amp', 'EBS', 'Session 30 MkII', 'Session', false, '30 watt Session 30 MkII practice combo.'),
  ('bass_amp', 'EBS', 'Session 60 MkII', 'Session', false, '60 watt Session 60 MkII practice combo.'),
  ('bass_amp', 'EBS', 'Session 120', 'Session', false, '120 watt Session 120 bass combo.'),
  ('bass_amp', 'Bergantino', 'Forte HP2', 'Forte', false, '1200 watt Forte HP2 flagship bass head.'),
  ('bass_amp', 'Bergantino', 'B|Amp II', 'B|Amp', false, 'B|Amp II digital bass head with MIDI control.'),
  ('bass_amp', 'Genzler', 'Magellan 350', 'Magellan', false, '350 watt Magellan 350 lightweight bass head.'),
  ('bass_amp', 'Genzler', 'Magellan 800', 'Magellan', false, '800 watt Magellan 800 lightweight bass head.'),
  ('bass_amp', 'Genzler', 'Magellan 800 Combo', 'Magellan', false, '800 watt Magellan 800 combo with 1x12 speaker.'),
  ('bass_amp', 'Mesa Boogie', 'Subway D-800', 'Subway', true, '800 watt Subway D-800 ultra light bass head.'),
  ('bass_amp', 'Mesa Boogie', 'Subway D-800+', 'Subway', false, '800 watt Subway D-800+ with expanded features.'),
  ('bass_amp', 'Mesa Boogie', 'Subway WD-800', 'Subway', false, '800 watt Subway WD-800 with tube preamp.'),
  ('bass_amp', 'Mesa Boogie', 'Subway TT-800', 'Subway', false, '800 watt Subway TT-800 dual tube preamp head.'),
  ('bass_amp', 'Laney', 'Digbeth DB500H', 'Digbeth', false, '500 watt Digbeth DB500H bass head.'),
  ('bass_amp', 'Laney', 'Digbeth DB200-210', 'Digbeth', false, '200 watt Digbeth DB200 combo with 2x10 speakers.'),
  ('bass_amp', 'Laney', 'Digbeth DB300-210', 'Digbeth', false, '300 watt Digbeth DB300 combo with 2x10 speakers.'),
  ('bass_amp', 'Blackstar', 'Unity 30', 'Unity', false, '30 watt Unity 30 bass practice combo.'),
  ('bass_amp', 'Blackstar', 'Unity 60', 'Unity', false, '60 watt Unity 60 bass combo.'),
  ('bass_amp', 'Blackstar', 'Unity 120', 'Unity', false, '120 watt Unity 120 bass combo.'),
  ('bass_amp', 'Blackstar', 'Unity 250', 'Unity', false, '250 watt Unity 250 bass combo.'),
  ('bass_amp', 'Blackstar', 'Unity 500', 'Unity', false, '500 watt Unity 500 bass head.'),
  ('bass_amp', 'Boss', 'Katana-110 Bass', 'Katana Bass', false, '60 watt Katana-110 Bass combo with 10 inch speaker.'),
  ('bass_amp', 'Boss', 'Katana-210 Bass', 'Katana Bass', false, '160 watt Katana-210 Bass combo with dual 10 inch speakers.'),
  ('bass_amp', 'Boss', 'Dual Cube Bass LX', 'Dual Cube', false, '10 watt Dual Cube Bass LX practice combo.'),
  ('bass_amp', 'Vox', 'Pathfinder Bass 10', 'Pathfinder', false, '10 watt Pathfinder Bass 10 practice combo.'),
  ('bass_amp', 'Vox', 'VX50 BA', 'VX', false, '50 watt VX50 BA bass combo with Nutube preamp.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
