begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  -- Yamaha
  ('electric_guitar', 'Yamaha', 'Pacifica 112J', 'Pacifica', false, 'Affordable double cut HSS with ceramic pickups and vintage tremolo.'),
  ('electric_guitar', 'Yamaha', 'Pacifica 112VM', 'Pacifica', false, 'Maple fingerboard version of the classic HSS Pacifica with alnico pickups.'),
  ('electric_guitar', 'Yamaha', 'Pacifica 120H', 'Pacifica', false, 'T style body with dual humbuckers and hardtail bridge.'),
  ('electric_guitar', 'Yamaha', 'Pacifica 212VFM', 'Pacifica', false, 'Flame maple top HSS with coil split and vintage style tremolo.'),
  ('electric_guitar', 'Yamaha', 'Pacifica 212VQM', 'Pacifica', false, 'Quilted maple top version of the 212 with HSS pickups.'),
  ('electric_guitar', 'Yamaha', 'Pacifica 311H', 'Pacifica', true, 'HS configuration with soapbar neck pickup and hardtail bridge.'),
  ('electric_guitar', 'Yamaha', 'Pacifica 510V', 'Pacifica', false, 'HS Pacifica with Seymour Duncan pickups and Wilkinson tremolo.'),
  ('electric_guitar', 'Yamaha', 'Pacifica 611HFM', 'Pacifica', false, 'Flame maple hardtail with Seymour Duncan humbucker and soapbar pair.'),
  ('electric_guitar', 'Yamaha', 'Pacifica 611VFM', 'Pacifica', false, 'Tremolo equipped version of the 611 with Seymour Duncan pickups.'),
  ('electric_guitar', 'Yamaha', 'Pacifica 1611MS Mike Stern', 'Pacifica', false, 'Mike Stern signature T style with Seymour Duncan pickups.'),
  ('electric_guitar', 'Yamaha', 'Pacifica Standard Plus', 'Pacifica', true, 'Modern HSS with Reflectone pickups developed with Rupert Neve Designs.'),
  ('electric_guitar', 'Yamaha', 'Pacifica Professional', 'Pacifica', true, 'Japan built flagship Pacifica with Reflectone pickups and premium build.'),
  ('electric_guitar', 'Yamaha', 'Revstar Element RSE20', 'Revstar', true, 'Entry level Revstar with dual humbuckers and chambered body.'),
  ('electric_guitar', 'Yamaha', 'Revstar Standard RSS02T', 'Revstar', true, 'Standard Revstar with dual P90 pickups and carbon reinforced neck.'),
  ('electric_guitar', 'Yamaha', 'Revstar Professional RSP02T', 'Revstar', false, 'Japan made Revstar with P90 pickups and tailpiece bridge.'),
  ('electric_guitar', 'Yamaha', 'Revstar RS320', 'Revstar', false, 'First generation Revstar with dual ceramic humbuckers.'),
  ('electric_guitar', 'Yamaha', 'Revstar RS420', 'Revstar', false, 'First generation Revstar with dry switch tone circuit.'),
  ('electric_guitar', 'Yamaha', 'Revstar RS502', 'Revstar', false, 'First generation Revstar with soapbar P90 pickups.'),
  ('electric_guitar', 'Yamaha', 'Revstar RS502T', 'Revstar', false, 'P90 equipped Revstar with aluminum tailpiece.'),
  ('electric_guitar', 'Yamaha', 'Revstar RS620', 'Revstar', false, 'First generation Revstar with alnico humbuckers and push pull tone control.'),
  ('electric_guitar', 'Yamaha', 'Revstar RS720B', 'Revstar', false, 'Revstar fitted with a Bigsby vibrato and vintage voiced pickups.'),
  ('electric_guitar', 'Yamaha', 'Revstar RS820CR', 'Revstar', false, 'Flagship first generation Revstar with brushed aluminum pickguard.'),
  ('electric_guitar', 'Yamaha', 'SG1820', 'SG', false, 'Japan built solid body with mahogany body and dual humbuckers.'),
  ('electric_guitar', 'Yamaha', 'SG1802', 'SG', false, 'SG series solid body loaded with soapbar P90 pickups.'),
  ('electric_guitar', 'Yamaha', 'SG2000', 'SG', true, 'Iconic neck through solid body made famous by Carlos Santana.'),
  ('electric_guitar', 'Yamaha', 'SA2200', 'SA', true, 'Japan built semi hollow with gold hardware and coil taps.'),
  ('electric_guitar', 'Yamaha', 'RGXA2', 'RGX', false, 'Ultra lightweight double cut with alternative internal resonance construction.'),
  ('electric_guitar', 'Yamaha', 'RGX220DZ', 'RGX', false, 'Affordable double cut rock guitar with humbucking pickups and tremolo.'),
  ('electric_guitar', 'Yamaha', 'AES620', 'AES', false, 'Set neck solid body from the AES line with dual humbuckers.'),
  -- Cort
  ('electric_guitar', 'Cort', 'G110', 'G', false, 'Entry level double cut with HSS pickups and tremolo.'),
  ('electric_guitar', 'Cort', 'G200', 'G', false, 'Affordable G series with poplar body and HSS layout.'),
  ('electric_guitar', 'Cort', 'G250', 'G', false, 'Versatile double cut with HSS pickups and coil split.'),
  ('electric_guitar', 'Cort', 'G260CS', 'G', false, 'Alder body G series with Voiced Tone pickups and vintage tremolo.'),
  ('electric_guitar', 'Cort', 'G280 Select', 'G', false, 'Premium tier G series double cut with flame maple top.'),
  ('electric_guitar', 'Cort', 'G290 FAT', 'G', true, 'High performance double cut with roasted maple neck and locking tuners.'),
  ('electric_guitar', 'Cort', 'G300 Pro', 'G', true, 'Flagship G series double cut with coil splitting humbuckers.'),
  ('electric_guitar', 'Cort', 'G300 Glam', 'G', false, 'Sparkle finished G series aimed at modern pop and session players.'),
  ('electric_guitar', 'Cort', 'KX100', 'KX', false, 'Entry KX model with dual humbuckers and hardtail bridge.'),
  ('electric_guitar', 'Cort', 'KX300', 'KX', false, 'Modern rock double cut with EMG RetroActive pickups.'),
  ('electric_guitar', 'Cort', 'KX300 Etched', 'KX', false, 'Etched ash top version of the KX300 with EMG pickups.'),
  ('electric_guitar', 'Cort', 'KX500', 'KX', true, 'Flagship KX metal guitar with active humbuckers and ergonomic body.'),
  ('electric_guitar', 'Cort', 'KX507MS', 'KX', false, 'Multiscale seven string with Fishman Fluence Modern pickups.'),
  ('electric_guitar', 'Cort', 'X100', 'X', false, 'Affordable X series shredder with deep cutaways and sculpted heel.'),
  ('electric_guitar', 'Cort', 'X250', 'X', false, 'Mid level X series rock guitar with humbucker power.'),
  ('electric_guitar', 'Cort', 'X300', 'X', false, 'Fast playing X series double cut aimed at rock and metal.'),
  ('electric_guitar', 'Cort', 'X700 Duality', 'X', true, 'Flagship X series praised for versatile dual voice pickup design.'),
  ('electric_guitar', 'Cort', 'X700 Duality II', 'X', false, 'Second generation Duality with refined pickups and playability.'),
  ('electric_guitar', 'Cort', 'CR100', 'CR', false, 'Entry single cut with classic rock voiced humbuckers.'),
  ('electric_guitar', 'Cort', 'CR200', 'CR', false, 'Affordable single cut with arched top and dual humbuckers.'),
  ('electric_guitar', 'Cort', 'CR250', 'CR', false, 'Vintage voiced single cut with flame maple top and coil splits.'),
  ('electric_guitar', 'Cort', 'CR300', 'CR', false, 'Upscale CR single cut with premium finish and alnico humbuckers.'),
  ('electric_guitar', 'Cort', 'MBC-1', 'Manson', false, 'Original Matt Bellamy signature developed with Manson Guitar Works.'),
  ('electric_guitar', 'Cort', 'MBM-1', 'Manson', true, 'Accessible Matt Bellamy META series model designed with Manson.'),
  ('electric_guitar', 'Cort', 'MBM-2', 'Manson', false, 'Upgraded META series Bellamy model available with Sustainiac.'),
  ('electric_guitar', 'Cort', 'Classic TC', 'Classic', false, 'Vintage styled T model with worn finish options.'),
  ('electric_guitar', 'Cort', 'Yorktown', 'Yorktown', false, 'Full sized semi hollow with vintage voiced humbuckers.'),
  ('electric_guitar', 'Cort', 'Source', 'Source', false, 'Double cut semi hollow with center block and classic looks.'),
  -- Harley Benton
  ('electric_guitar', 'Harley Benton', 'SC-450Plus', 'SC', false, 'Flame top single cut upgrade of the entry SC line.'),
  ('electric_guitar', 'Harley Benton', 'SC-550', 'SC', true, 'Popular single cut with flamed top and Roswell humbuckers.'),
  ('electric_guitar', 'Harley Benton', 'SC-550 II', 'SC', false, 'Updated SC-550 with improved hardware and binding.'),
  ('electric_guitar', 'Harley Benton', 'SC-1000', 'SC', false, 'Progressive line single cut with modern appointments.'),
  ('electric_guitar', 'Harley Benton', 'SC-Custom II', 'SC', false, 'Custom styled single cut available with active electronics.'),
  ('electric_guitar', 'Harley Benton', 'TE-20', 'TE', false, 'Entry level T style known for extreme value.'),
  ('electric_guitar', 'Harley Benton', 'TE-52', 'TE', true, 'Vintage series T style with ash body and classic twang.'),
  ('electric_guitar', 'Harley Benton', 'TE-62CC', 'TE', false, 'Custom line T style with vintage sixties styling.'),
  ('electric_guitar', 'Harley Benton', 'TE-70RW Deluxe', 'TE', false, 'Deluxe T style with rosewood fingerboard and upgraded parts.'),
  ('electric_guitar', 'Harley Benton', 'TE-90FLT', 'TE', false, 'Flame top T style from the deluxe series.'),
  ('electric_guitar', 'Harley Benton', 'ST-20', 'ST', false, 'Ultra affordable S style for first time players.'),
  ('electric_guitar', 'Harley Benton', 'ST-20 HSS', 'ST', false, 'HSS version of the entry level S style.'),
  ('electric_guitar', 'Harley Benton', 'ST-62', 'ST', false, 'Vintage series S style with sixties inspired specs.'),
  ('electric_guitar', 'Harley Benton', 'DC-60', 'DC', false, 'Double cut rock guitar in classic sixties style.'),
  ('electric_guitar', 'Harley Benton', 'DC-580', 'DC', false, 'Vintage series double cut with dual humbuckers.'),
  ('electric_guitar', 'Harley Benton', 'DC-Junior', 'DC', false, 'Single pickup double cut with TV yellow finish option.'),
  ('electric_guitar', 'Harley Benton', 'Fusion-III HSH', 'Fusion', true, 'Modern player HSH with roasted neck and stainless steel frets.'),
  ('electric_guitar', 'Harley Benton', 'Fusion-T HH', 'Fusion', false, 'T shaped modern guitar with roasted maple neck.'),
  ('electric_guitar', 'Harley Benton', 'Amarok-6', 'Amarok', true, 'Aggressive modern metal model with sculpted mahogany body.'),
  ('electric_guitar', 'Harley Benton', 'Dullahan-FT 24', 'Dullahan', false, 'Headless modern guitar with fixed bridge and roasted neck.'),
  ('electric_guitar', 'Harley Benton', 'Dullahan-AT 24', 'Dullahan', false, 'Arch top variant of the headless Dullahan platform.'),
  ('electric_guitar', 'Harley Benton', 'Extreme-84', 'Extreme', false, 'Eighties inspired rock machine with humbucker and double locking tremolo.'),
  ('electric_guitar', 'Harley Benton', 'JA-60', 'JA', false, 'Offset classic with dual soapbar style pickups and tremolo.'),
  ('electric_guitar', 'Harley Benton', 'CST-24', 'CST', false, 'Double cut with 24 frets and versatile coil split humbuckers.'),
  ('electric_guitar', 'Harley Benton', 'CST-24T', 'CST', false, 'Tremolo equipped version of the 24 fret double cut.'),
  ('electric_guitar', 'Harley Benton', 'R-446', 'R', false, 'Modern rock six string with sharp styling and high output pickups.'),
  ('electric_guitar', 'Harley Benton', 'R-457', 'R', false, 'Seven string version of the modern R series.'),
  ('electric_guitar', 'Harley Benton', 'R-458', 'R', false, 'Eight string R series built for low tuned metal.'),
  ('electric_guitar', 'Harley Benton', 'HB-35', 'HB-35', true, 'Semi hollow double cut inspired by classic archtop designs.'),
  ('electric_guitar', 'Harley Benton', 'HB-35Plus', 'HB-35', false, 'Upgraded semi hollow with flamed top and improved hardware.'),
  ('electric_guitar', 'Harley Benton', 'EX-76 Classic', 'EX', false, 'Angular seventies inspired body with dual humbuckers.'),
  -- Sire
  ('electric_guitar', 'Sire', 'Larry Carlton S3', 'Larry Carlton', false, 'Double cut with HSS pickups and rolled fingerboard edges.'),
  ('electric_guitar', 'Sire', 'Larry Carlton S7', 'Larry Carlton', true, 'S style with premium alder body and versatile five way switching.'),
  ('electric_guitar', 'Sire', 'Larry Carlton S7 FM', 'Larry Carlton', false, 'Flame maple top version of the S7 platform.'),
  ('electric_guitar', 'Sire', 'Larry Carlton T7', 'Larry Carlton', true, 'T style with swamp ash body and vintage voiced single coils.'),
  ('electric_guitar', 'Sire', 'Larry Carlton T7 FM', 'Larry Carlton', false, 'Flame maple topped T7 with modern C neck.'),
  ('electric_guitar', 'Sire', 'Larry Carlton H7', 'Larry Carlton', true, 'Semi hollow double cut praised for value and smooth jazz tones.'),
  ('electric_guitar', 'Sire', 'Larry Carlton H7V', 'Larry Carlton', false, 'H7 variant with vintage style appointments.'),
  ('electric_guitar', 'Sire', 'Larry Carlton L7', 'Larry Carlton', false, 'Single cut with carved maple top and dual humbuckers.'),
  ('electric_guitar', 'Sire', 'Larry Carlton L7V', 'Larry Carlton', false, 'P90 loaded version of the L7 single cut.'),
  -- Chapman
  ('electric_guitar', 'Chapman', 'ML1 Modern', 'ML1', true, 'Flagship double cut with modern humbuckers and sleek neck.'),
  ('electric_guitar', 'Chapman', 'ML1 Traditional', 'ML1', false, 'Vintage voiced version of the ML1 with classic styling.'),
  ('electric_guitar', 'Chapman', 'ML1 Pro Modern', 'ML1', false, 'Pro series ML1 with upgraded tonewoods and electronics.'),
  ('electric_guitar', 'Chapman', 'ML1 Pro Traditional', 'ML1', false, 'Pro tier ML1 with figured tops and vintage voicing.'),
  ('electric_guitar', 'Chapman', 'ML1 CAP10 America', 'ML1', false, 'Rob Chapman signature ML1 with versatile switching.'),
  ('electric_guitar', 'Chapman', 'ML1 Modern Baritone', 'ML1', false, 'Baritone scale ML1 built for low tunings.'),
  ('electric_guitar', 'Chapman', 'ML1 Norseman', 'ML1', false, 'Leo Moracchioli signature with Norse inspired details.'),
  ('electric_guitar', 'Chapman', 'ML1 X', 'ML1', false, 'Streamlined X series version of the ML1 platform.'),
  ('electric_guitar', 'Chapman', 'ML2', 'ML2', false, 'Single cut with carved top and rock voiced humbuckers.'),
  ('electric_guitar', 'Chapman', 'ML3 Traditional', 'ML3', false, 'T style with vintage voiced pickups and classic bridge.'),
  ('electric_guitar', 'Chapman', 'ML3 Modern', 'ML3', false, 'Contemporary T style with humbucker power.'),
  ('electric_guitar', 'Chapman', 'ML3 Pro Traditional', 'ML3', false, 'Pro series T style with premium woods.'),
  ('electric_guitar', 'Chapman', 'ML3 Bea', 'ML3', true, 'Rabea Massaad signature T style with high output bridge humbucker.'),
  ('electric_guitar', 'Chapman', 'ML3 Pro Bea', 'ML3', false, 'Pro tier version of the Rabea Massaad signature.'),
  ('electric_guitar', 'Chapman', 'Ghost Fret', 'Ghost Fret', true, 'Angular modern body with ergonomic contours and humbuckers.'),
  ('electric_guitar', 'Chapman', 'Ghost Fret Pro', 'Ghost Fret', false, 'Pro series version of the angular Ghost Fret design.'),
  ('electric_guitar', 'Chapman', 'Ghost Fret 7', 'Ghost Fret', false, 'Seven string version of the angular Ghost Fret.'),
  -- Washburn
  ('electric_guitar', 'Washburn', 'N24 Nuno Bettencourt', 'N', true, 'Affordable Nuno Bettencourt signature with distressed finish.'),
  ('electric_guitar', 'Washburn', 'N4', 'N', true, 'Legendary Nuno Bettencourt stage model with Stephens extended cutaway.'),
  ('electric_guitar', 'Washburn', 'N2', 'N', false, 'Accessible version of the Nuno Bettencourt signature platform.'),
  ('electric_guitar', 'Washburn', 'N1', 'N', false, 'Entry model in the Nuno Bettencourt signature line.'),
  ('electric_guitar', 'Washburn', 'Parallaxe Solar 160', 'Parallaxe', false, 'Ola Englund designed metal model from the Parallaxe line.'),
  ('electric_guitar', 'Washburn', 'Sonamaster S1', 'Sonamaster', false, 'Budget friendly double cut aimed at beginners.'),
  ('electric_guitar', 'Washburn', 'HB35', 'HB', false, 'Semi hollow double cut with vintage styling.'),
  ('electric_guitar', 'Washburn', 'HB30', 'HB', false, 'Affordable semi hollow with classic appointments.'),
  ('electric_guitar', 'Washburn', 'Idol WI64', 'Idol', false, 'Single cut Idol body with dual humbuckers.'),
  ('electric_guitar', 'Washburn', 'Dime 333', 'Dime', true, 'Dimebag Darrell signature with pointed body styling.'),
  ('electric_guitar', 'Washburn', 'X50 Pro', 'X', false, 'Double cut rock model from the X series.'),
  -- Hagstrom
  ('electric_guitar', 'Hagstrom', 'Viking', 'Viking', true, 'Swedish designed semi hollow with H-Expander truss rod.'),
  ('electric_guitar', 'Hagstrom', 'Viking Deluxe', 'Viking', false, 'Upscale Viking with flame maple veneer and block inlays.'),
  ('electric_guitar', 'Hagstrom', 'Super Viking', 'Viking', false, 'Enhanced Viking with upgraded pickups and resinator fingerboard.'),
  ('electric_guitar', 'Hagstrom', 'Tremar Viking Deluxe', 'Viking', false, 'Viking Deluxe fitted with the Tremar vibrato tailpiece.'),
  ('electric_guitar', 'Hagstrom', 'Swede', 'Swede', false, 'Classic Swedish single cut with mahogany body.'),
  ('electric_guitar', 'Hagstrom', 'Super Swede', 'Swede', true, 'Flagship single cut with long scale and coil splits.'),
  ('electric_guitar', 'Hagstrom', 'Ultra Swede', 'Swede', false, 'Modern take on the Swede with slim lightweight body.'),
  ('electric_guitar', 'Hagstrom', 'Ultra Max', 'Ultra', false, 'Affordable modern single cut with ceramic humbuckers.'),
  ('electric_guitar', 'Hagstrom', 'Fantomen', 'Fantomen', true, 'Distinctive solid body developed with the band Ghost.'),
  ('electric_guitar', 'Hagstrom', 'Impala', 'Impala', false, 'Retro reissue of the sixties Impala with sliding switch panel.'),
  ('electric_guitar', 'Hagstrom', 'Alvar', 'Alvar', false, 'Retro inspired solid body based on classic Hagstrom designs.'),
  ('electric_guitar', 'Hagstrom', 'Condor', 'Condor', false, 'Reissue of the vintage Condor with retro control panel.'),
  ('electric_guitar', 'Hagstrom', 'Pat Smear Signature', 'Signature', false, 'Pat Smear model based on the vintage H-II platform.'),
  ('electric_guitar', 'Hagstrom', 'Retroscape H-II', 'Retroscape', false, 'Modern reissue of the classic H-II double cut.'),
  ('electric_guitar', 'Hagstrom', 'Retroscape H-III', 'Retroscape', false, 'Three pickup version of the Retroscape series.'),
  -- Duesenberg
  ('electric_guitar', 'Duesenberg', 'Starplayer TV', 'Starplayer', true, 'German designed semi hollow with humbucker and Domino P90 pairing.'),
  ('electric_guitar', 'Duesenberg', 'Starplayer TV Plus', 'Starplayer', false, 'Starplayer TV with added piezo bridge system.'),
  ('electric_guitar', 'Duesenberg', 'Starplayer TV Phonic', 'Starplayer', false, 'Fully hollow version of the Starplayer TV with spruce top.'),
  ('electric_guitar', 'Duesenberg', 'Starplayer Special', 'Starplayer', false, 'Single cutaway variant of the Starplayer platform.'),
  ('electric_guitar', 'Duesenberg', 'Falken', 'Falken', false, 'Elegant solid body with art deco styling.'),
  ('electric_guitar', 'Duesenberg', 'Paloma', 'Paloma', false, 'Triple pickup solid body with unique toggle switching.'),
  ('electric_guitar', 'Duesenberg', 'Julia', 'Julia', true, 'Compact semi hollow with P90 style pickups and art deco styling.'),
  ('electric_guitar', 'Duesenberg', 'Fullerton Elite', 'Fullerton', false, 'Double cutaway semi hollow with elegant appointments.'),
  ('electric_guitar', 'Duesenberg', 'Alliance Joe Walsh', 'Alliance', false, 'Joe Walsh signature from the Alliance series.'),
  ('electric_guitar', 'Duesenberg', 'Bonneville', 'Bonneville', false, 'Thinline hollow body with vintage inspired design.'),
  ('electric_guitar', 'Duesenberg', '49er', '49er', false, 'Single cut with carved top and vintage voiced pickups.'),
  ('electric_guitar', 'Duesenberg', 'Caribou', 'Caribou', false, 'Chambered single cut with elegant German engineering.'),
  ('electric_guitar', 'Duesenberg', 'Gran Majesto', 'Gran Majesto', false, 'Large semi hollow with center block and modern electronics.'),
  ('electric_guitar', 'Duesenberg', 'Double Cat', 'Double Cat', false, 'Double cutaway semi hollow available in six and twelve string.'),
  -- Vintage
  ('electric_guitar', 'Vintage', 'V100', 'V100', true, 'Single cut with Wilkinson pickups and classic looks.'),
  ('electric_guitar', 'Vintage', 'V100 Icon', 'V100', false, 'Distressed finish version of the V100 single cut.'),
  ('electric_guitar', 'Vintage', 'V100AFD Paradise', 'V100', true, 'Flame top V100 inspired by late eighties hard rock.'),
  ('electric_guitar', 'Vintage', 'V100 Lemon Drop', 'V100', false, 'Aged lemon finish V100 honoring a famous late fifties single cut.'),
  ('electric_guitar', 'Vintage', 'V120', 'V120', false, 'Dual P90 single cut with vintage styling.'),
  ('electric_guitar', 'Vintage', 'V130', 'V130', false, 'Single P90 student style solid body.'),
  ('electric_guitar', 'Vintage', 'V6', 'V6', true, 'S style with Wilkinson single coils and vintage tremolo.'),
  ('electric_guitar', 'Vintage', 'V6 Icon', 'V6', false, 'Relic finished version of the V6 S style.'),
  ('electric_guitar', 'Vintage', 'V6M24', 'V6', false, 'Modern 24 fret version of the V6 platform.'),
  ('electric_guitar', 'Vintage', 'V52', 'V52', false, 'T style with Wilkinson pickups and fifties character.'),
  ('electric_guitar', 'Vintage', 'V52 Icon', 'V52', false, 'Aged finish version of the V52 T style.'),
  ('electric_guitar', 'Vintage', 'VSA500', 'VSA', false, 'Semi hollow double cut with vintage voiced humbuckers.'),
  -- Jet
  ('electric_guitar', 'Jet', 'JT-300', 'JT', true, 'Value packed T style with roasted maple neck.'),
  ('electric_guitar', 'Jet', 'JT-350', 'JT', false, 'T style with roasted neck and upgraded pickups.'),
  ('electric_guitar', 'Jet', 'JT-450', 'JT', false, 'Feature upgraded T style from the JT line.'),
  ('electric_guitar', 'Jet', 'JS-300', 'JS', false, 'Affordable S style with roasted maple neck.'),
  ('electric_guitar', 'Jet', 'JS-400', 'JS', false, 'HSS S style known for strong value.'),
  -- Eastman
  ('electric_guitar', 'Eastman', 'SB59', 'SB', true, 'Hand carved single cut with Seymour Duncan humbuckers.'),
  ('electric_guitar', 'Eastman', 'SB59/v', 'SB', false, 'Antique varnish finished version of the SB59.'),
  ('electric_guitar', 'Eastman', 'SB55/v', 'SB', false, 'Single P90 slab body with antique varnish finish.'),
  ('electric_guitar', 'Eastman', 'SB55DC/v', 'SB', false, 'Double cut version of the SB55 with dogear P90.'),
  ('electric_guitar', 'Eastman', 'SB56/v', 'SB', false, 'Dual P90 gold top style with varnish finish.'),
  ('electric_guitar', 'Eastman', 'T486', 'T', true, 'Laminate semi hollow with center block and humbuckers.'),
  ('electric_guitar', 'Eastman', 'T486B', 'T', false, 'Bigsby equipped version of the T486 semi hollow.'),
  ('electric_guitar', 'Eastman', 'T386', 'T', false, 'Affordable semi hollow with classic double cut styling.'),
  ('electric_guitar', 'Eastman', 'T484', 'T', false, 'Compact semi hollow with smaller body and premium pickups.'),
  ('electric_guitar', 'Eastman', 'T64/v', 'T', false, 'Vintage styled thinline with Bigsby and antique varnish.'),
  ('electric_guitar', 'Eastman', 'T59/v', 'T', false, 'Premium thinline hollow body with hand applied varnish.'),
  ('electric_guitar', 'Eastman', 'T185MX', 'T', false, 'Solid carved top thinline with maple back and sides.'),
  ('electric_guitar', 'Eastman', 'Romeo', 'Romeo', true, 'Modern thinline semi hollow with lightweight build.'),
  ('electric_guitar', 'Eastman', 'Romeo LA', 'Romeo', false, 'Alternate voiced Romeo with vintage style appointments.'),
  ('electric_guitar', 'Eastman', 'Romeo SC', 'Romeo', false, 'Single cutaway version of the Romeo thinline.'),
  ('electric_guitar', 'Eastman', 'Juliet', 'Juliet', false, 'Solid body offset with vintage inspired styling.'),
  ('electric_guitar', 'Eastman', 'AR372CE', 'AR', false, 'Sixteen inch archtop electric with single humbucker.'),
  -- FGN
  ('electric_guitar', 'FGN', 'Boundary Odyssey', 'Boundary', true, 'Japan built S style with circle fretting system.'),
  ('electric_guitar', 'FGN', 'Boundary Iliad', 'Boundary', false, 'Japan built T style with circle fretting system.'),
  ('electric_guitar', 'FGN', 'J-Standard Odyssey', 'J-Standard', false, 'Mid line S style made in the Fujigen factory.'),
  ('electric_guitar', 'FGN', 'J-Standard Iliad', 'J-Standard', false, 'T style from the J-Standard line with vintage voicing.'),
  ('electric_guitar', 'FGN', 'J-Standard Mythic', 'J-Standard', false, 'Single cut J-Standard with carved top and humbuckers.'),
  ('electric_guitar', 'FGN', 'Neo Classic NST10', 'Neo Classic', false, 'Traditional S style with vintage correct appointments.'),
  ('electric_guitar', 'FGN', 'Neo Classic NTL10', 'Neo Classic', false, 'Traditional T style with vintage correct appointments.'),
  -- Aria
  ('electric_guitar', 'Aria', 'Pro II PE-350', 'Pro II', true, 'Modern version of the classic PE single cut.'),
  ('electric_guitar', 'Aria', 'STG-003', 'STG', false, 'Entry level S style popular with beginners.'),
  ('electric_guitar', 'Aria', 'STG-004', 'STG', false, 'Humbucker equipped variant of the entry level STG platform.'),
  ('electric_guitar', 'Aria', 'TEG-002', 'TEG', false, 'Affordable T style from the TEG series.'),
  ('electric_guitar', 'Aria', '615-Frontier', 'Frontier', false, 'T style with vintage styling and alder body.'),
  ('electric_guitar', 'Aria', '714-Fullerton', 'Fullerton', false, 'S style with vintage tremolo and versatile pickups.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
