begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('electric_guitar', 'LTD', 'EC-10', 'EC', false, 'Entry level singlecut with basswood body and ESP designed humbuckers.'),
  ('electric_guitar', 'LTD', 'EC-50', 'EC', false, 'Discontinued entry singlecut with bolt-on neck construction.'),
  ('electric_guitar', 'LTD', 'EC-100QM', 'EC', false, 'Early 2000s singlecut with quilted maple top.'),
  ('electric_guitar', 'LTD', 'EC-200QM', 'EC', false, 'Discontinued singlecut with quilted maple top and dual humbuckers.'),
  ('electric_guitar', 'LTD', 'EC-201', 'EC', false, 'Stripped down singlecut with a single bridge humbucker.'),
  ('electric_guitar', 'LTD', 'EC-257', 'EC', false, 'Seven string version of the mid tier EC singlecut.'),
  ('electric_guitar', 'LTD', 'EC-400', 'EC', false, 'Set neck singlecut with active EMG pickups.'),
  ('electric_guitar', 'LTD', 'EC-401', 'EC', false, 'Set neck singlecut with EMG 81 and 60 active pickups.'),
  ('electric_guitar', 'LTD', 'EC-407', 'EC', false, 'Seven string EC with active EMG pickups.'),
  ('electric_guitar', 'LTD', 'EC-1000FR', 'EC', false, 'Deluxe series EC with Floyd Rose double locking tremolo.'),
  ('electric_guitar', 'LTD', 'EC-1000 EverTune', 'EC', true, 'Deluxe EC with EverTune constant tension bridge.'),
  ('electric_guitar', 'LTD', 'EC-1000T CTM', 'EC', false, 'Traditional body thickness EC with set-thru neck construction.'),
  ('electric_guitar', 'LTD', 'EC-1007 EverTune', 'EC', false, 'Seven string Deluxe EC with EverTune bridge.'),
  ('electric_guitar', 'LTD', 'EC Black Metal', 'EC', false, 'Blacked out EC with a single active EMG 81 pickup.'),
  ('electric_guitar', 'LTD', 'EC Arctic Metal', 'EC', false, 'Snow white satin EC with black hardware and one EMG 81.'),
  ('electric_guitar', 'LTD', 'Eclipse ''87', 'Eclipse', false, 'Reissue of the late eighties Eclipse with Floyd Rose tremolo.'),
  ('electric_guitar', 'LTD', 'MH-100QM', 'MH', false, 'Bolt-on superstrat with quilted maple top from the 2000s lineup.'),
  ('electric_guitar', 'LTD', 'MH-103QM', 'MH', false, 'Quilted top superstrat with licensed Floyd Rose tremolo.'),
  ('electric_guitar', 'LTD', 'MH-200', 'MH', false, 'Affordable superstrat with double locking tremolo.'),
  ('electric_guitar', 'LTD', 'MH-203QM', 'MH', false, 'Quilted maple superstrat with Floyd Rose special tremolo.'),
  ('electric_guitar', 'LTD', 'MH-207', 'MH', false, 'Discontinued seven string bolt-on superstrat.'),
  ('electric_guitar', 'LTD', 'MH-300', 'MH', false, 'Discontinued mid tier superstrat with dual humbuckers.'),
  ('electric_guitar', 'LTD', 'MH-350FR', 'MH', false, 'Mid tier superstrat with Floyd Rose and active pickups.'),
  ('electric_guitar', 'LTD', 'MH-400', 'MH', false, 'Neck-thru superstrat with EMG 81 and 85 pickups.'),
  ('electric_guitar', 'LTD', 'MH-401', 'MH', false, 'Superstrat with active EMG pickups and Floyd Rose option.'),
  ('electric_guitar', 'LTD', 'MH-417', 'MH', false, 'Seven string superstrat with active EMG pickups.'),
  ('electric_guitar', 'LTD', 'MH-1000 EverTune', 'MH', true, 'Deluxe superstrat with EverTune constant tension bridge.'),
  ('electric_guitar', 'LTD', 'MH-1007 EverTune', 'MH', false, 'Seven string Deluxe superstrat with EverTune bridge.'),
  ('electric_guitar', 'LTD', 'M-10', 'M', false, 'Entry level superstrat with basswood body.'),
  ('electric_guitar', 'LTD', 'M-50', 'M', false, 'Discontinued entry superstrat with agathis body.'),
  ('electric_guitar', 'LTD', 'M-100FM', 'M', false, 'Flamed maple top superstrat with licensed Floyd Rose.'),
  ('electric_guitar', 'LTD', 'M-200FM', 'M', false, 'Flamed top superstrat with double locking tremolo.'),
  ('electric_guitar', 'LTD', 'M-400', 'M', false, 'Mid tier superstrat with EMG pickups and Floyd Rose.'),
  ('electric_guitar', 'LTD', 'M-1001', 'M', true, 'Deluxe neck-thru superstrat with Floyd Rose tremolo.'),
  ('electric_guitar', 'LTD', 'M-1007', 'M', false, 'Seven string Deluxe superstrat with active pickups.'),
  ('electric_guitar', 'LTD', 'Mirage Deluxe ''87', 'Mirage', false, 'Reissue of the 1987 Mirage with pastel finishes and Floyd Rose.'),
  ('electric_guitar', 'LTD', 'M-1 Custom ''87', 'M', false, 'Eighties style superstrat with single humbucker and Floyd Rose.'),
  ('electric_guitar', 'LTD', 'H-101FM', 'H', false, 'Affordable arched top superstrat with flamed maple veneer.'),
  ('electric_guitar', 'LTD', 'H-1001', 'H', false, 'Deluxe set-thru superstrat with EMG pickups.'),
  ('electric_guitar', 'LTD', 'H3-1000', 'H', true, 'Modern H series with sculpted body and Fishman Fluence pickups.'),
  ('electric_guitar', 'LTD', 'H3-1007', 'H', false, 'Seven string version of the modern H3 platform.'),
  ('electric_guitar', 'LTD', 'KH-202', 'KH', true, 'Affordable Kirk Hammett signature with skull and bones inlays.'),
  ('electric_guitar', 'LTD', 'KH-602', 'KH', true, 'Kirk Hammett signature with neck-thru build and EMG Bone Breaker set.'),
  ('electric_guitar', 'LTD', 'KH-V', 'KH', false, 'Kirk Hammett signature V in red sparkle finish.'),
  ('electric_guitar', 'LTD', 'KH-WZ', 'KH', false, 'Kirk Hammett signature with White Zombie graphic finish.'),
  ('electric_guitar', 'LTD', 'KH-3 Spider', 'KH', false, 'Kirk Hammett singlecut with spider graphic finish.'),
  ('electric_guitar', 'LTD', 'Alexi-200', 'Alexi', false, 'Affordable Alexi Laiho signature V with bolt-on neck.'),
  ('electric_guitar', 'LTD', 'Alexi-600', 'Alexi', true, 'Alexi Laiho signature V with sawtooth inlays and Floyd Rose.'),
  ('electric_guitar', 'LTD', 'Alexi Ripped', 'Alexi', false, 'Alexi Laiho tribute V with ripped pinstripe graphic.'),
  ('electric_guitar', 'LTD', 'Alexi Hexed', 'Alexi', false, 'Alexi Laiho signature V with hexed graphic and scythe inlays.'),
  ('electric_guitar', 'LTD', 'Alexi Greeny', 'Alexi', false, 'Alexi Laiho tribute V in green burst with pinstripes.'),
  ('electric_guitar', 'LTD', 'TE-200', 'TE', false, 'Bolt-on T style body with dual humbuckers.'),
  ('electric_guitar', 'LTD', 'TE-401', 'TE', false, 'T style body with active EMG pickups.'),
  ('electric_guitar', 'LTD', 'TE-1000', 'TE', true, 'Deluxe T style with premium appointments and active pickups.'),
  ('electric_guitar', 'LTD', 'SC-20', 'SC', false, 'Stephen Carpenter signature T style with EMG pickups.'),
  ('electric_guitar', 'LTD', 'SC-607B', 'SC', false, 'Stephen Carpenter seven string baritone with EMG pickups.'),
  ('electric_guitar', 'LTD', 'SN-200HT', 'SN', false, 'Modern S style with hardtail bridge.'),
  ('electric_guitar', 'LTD', 'SN-1000FR', 'SN', false, 'Deluxe S style with Floyd Rose and Fishman Fluence pickups.'),
  ('electric_guitar', 'LTD', 'SN-1000W', 'SN', false, 'Deluxe modern S style with hardtail bridge.'),
  ('electric_guitar', 'LTD', 'Viper-10', 'Viper', false, 'Entry level offset double-cutaway with ESP designed pickups.'),
  ('electric_guitar', 'LTD', 'Viper-201B', 'Viper', false, 'Baritone version of the offset double-cutaway Viper.'),
  ('electric_guitar', 'LTD', 'Viper-256', 'Viper', false, 'Mid tier Viper with dual humbuckers and set neck.'),
  ('electric_guitar', 'LTD', 'Viper-400', 'Viper', false, 'Discontinued Viper with active EMG pickups.'),
  ('electric_guitar', 'LTD', 'Viper-1000', 'Viper', true, 'Deluxe set-thru Viper with active pickups.'),
  ('electric_guitar', 'LTD', 'Viper Black Metal', 'Viper', false, 'Blacked out Viper with single EMG 81 and satin finish.'),
  ('electric_guitar', 'LTD', 'BB-600 Baritone', 'BB', false, 'Ben Burnley signature baritone based on the Viper shape.'),
  ('electric_guitar', 'LTD', 'EX-360', 'EX', false, 'Angular EX body with active EMG pickups.'),
  ('electric_guitar', 'LTD', 'EX-401', 'EX', false, 'Set neck EX with active EMG pickups and black finish.'),
  ('electric_guitar', 'LTD', 'F-10', 'F', false, 'Entry level aggressive F body shape with bolt-on neck.'),
  ('electric_guitar', 'LTD', 'F-50', 'F', false, 'Affordable F series with pointed body styling.'),
  ('electric_guitar', 'LTD', 'F-100FM', 'F', false, 'F series with flamed maple top and dual humbuckers.'),
  ('electric_guitar', 'LTD', 'F-250', 'F', false, 'Mid tier F series with sharp body bevels.'),
  ('electric_guitar', 'LTD', 'F-400FM', 'F', false, 'Discontinued upper tier F series with flamed top.'),
  ('electric_guitar', 'LTD', 'Arrow-200', 'Arrow', false, 'Affordable arrow shaped body with dual humbuckers.'),
  ('electric_guitar', 'LTD', 'Arrow-401', 'Arrow', false, 'Arrow body with EMG pickups and Floyd Rose.'),
  ('electric_guitar', 'LTD', 'Arrow-1000', 'Arrow', false, 'Deluxe arrow shape with neck-thru build and Floyd Rose.'),
  ('electric_guitar', 'LTD', 'Arrow Black Metal', 'Arrow', false, 'Blacked out arrow shape with single EMG 81.'),
  ('electric_guitar', 'LTD', 'Phoenix-200', 'Phoenix', false, 'Affordable offset singlecut with dual humbuckers.'),
  ('electric_guitar', 'LTD', 'Phoenix-401', 'Phoenix', false, 'Offset singlecut Phoenix with active EMG pickups.'),
  ('electric_guitar', 'LTD', 'Phoenix-1000', 'Phoenix', false, 'Deluxe Phoenix with set-thru neck and Fishman pickups.'),
  ('electric_guitar', 'LTD', 'Phoenix Black Metal', 'Phoenix', false, 'Blacked out Phoenix with single EMG and satin finish.'),
  ('electric_guitar', 'LTD', 'Snakebyte', 'Snakebyte', true, 'James Hetfield signature with EMG JH pickup set.'),
  ('electric_guitar', 'LTD', 'Iron Cross', 'Iron Cross', true, 'James Hetfield signature singlecut with iron cross graphic.'),
  ('electric_guitar', 'LTD', 'Vulture', 'Vulture', true, 'James Hetfield signature V with active EMG JH pickups.'),
  ('electric_guitar', 'LTD', 'GH-600', 'GH', false, 'Gary Holt signature EC with Floyd Rose and EMG pickups.'),
  ('electric_guitar', 'LTD', 'JH-600', 'JH', false, 'Jeff Hanneman signature superstrat with Floyd Rose.'),
  ('electric_guitar', 'LTD', 'WA-200', 'WA', false, 'Will Adler signature with warbird graphic finish.'),
  ('electric_guitar', 'LTD', 'Sparrowhawk', 'Sparrowhawk', false, 'Bill Kelliher signature singlecut with offset styling.'),
  ('electric_guitar', 'ESP', 'E-II Horizon FR', 'E-II', true, 'Japan made Horizon with Floyd Rose and EMG pickups.'),
  ('electric_guitar', 'ESP', 'E-II Horizon NT-II', 'E-II', false, 'Japan made neck-thru Horizon with flamed maple top.'),
  ('electric_guitar', 'ESP', 'E-II Horizon NT-7B', 'E-II', false, 'Japan made seven string baritone Horizon with Hipshot bridge.'),
  ('electric_guitar', 'ESP', 'E-II M-I Thru NT', 'E-II', false, 'Japan made M-I with neck-thru build and single EMG pickup.'),
  ('electric_guitar', 'ESP', 'E-II Arrow', 'E-II', false, 'Japan made arrow shape with Floyd Rose and EMG pickups.'),
  ('electric_guitar', 'ESP', 'E-II ST-1', 'E-II', false, 'Japan made double-cutaway S style with premium build.'),
  ('electric_guitar', 'ESP', 'E-II ST-2', 'E-II', false, 'Japan made S style with dual single coils and bridge humbucker.'),
  ('electric_guitar', 'ESP', 'E-II Mystique', 'E-II', false, 'Japan made offset body with flamed maple top.'),
  ('electric_guitar', 'ESP', 'E-II FRX', 'E-II', false, 'Japan made aggressive FRX shape with active EMG pickups.'),
  ('electric_guitar', 'ESP', 'E-II Viper', 'E-II', false, 'Japan made offset double-cutaway with EMG pickups.'),
  ('electric_guitar', 'ESP', 'E-II Eclipse DB', 'E-II', false, 'Japan made singlecut Eclipse variant with premium appointments.'),
  ('electric_guitar', 'ESP', 'E-II Vintage Plus', 'E-II', false, 'Japan made vintage style S type with modern electronics.'),
  ('electric_guitar', 'ESP', 'Eclipse-II', 'Eclipse', true, 'Japan made singlecut with set neck and EMG pickups.'),
  ('electric_guitar', 'ESP', 'Horizon-III', 'Horizon', true, 'Japan made Horizon with neck-thru build and reverse headstock.'),
  ('electric_guitar', 'ESP', 'Snapper', 'Snapper', true, 'Japan made S style with sculpted heel and versatile pickups.'),
  ('electric_guitar', 'ESP', 'Snapper-CTM', 'Snapper', false, 'Custom tier Snapper with bound body and premium woods.'),
  ('electric_guitar', 'ESP', 'Forest-GT', 'Forest', false, 'Japan made original body shape with carved flamed top.'),
  ('electric_guitar', 'ESP', 'Phoenix', 'Phoenix', false, 'Japan made offset singlecut with set-thru neck.'),
  ('electric_guitar', 'ESP', 'Arrow', 'Arrow', false, 'Japan made arrow shape with premium construction.'),
  ('electric_guitar', 'ESP', 'Random Star', 'Random Star', false, 'Eighties original star shaped body from ESP in Japan.'),
  ('electric_guitar', 'ESP', 'Kamikaze-1', 'Kamikaze', true, 'George Lynch signature with kamikaze graphic finish.'),
  ('electric_guitar', 'ESP', 'KH-2', 'KH', true, 'Kirk Hammett signature superstrat with EMG pickups.'),
  ('electric_guitar', 'ESP', 'KH-2 Vintage', 'KH', false, 'Aged Kirk Hammett signature modeled on his main touring guitar.'),
  ('electric_guitar', 'ESP', 'Snakebyte', 'Snakebyte', true, 'James Hetfield signature with active EMG JH set.'),
  ('electric_guitar', 'ESP', 'Iron Cross', 'Iron Cross', false, 'James Hetfield signature singlecut with cross graphic over white finish.'),
  ('electric_guitar', 'ESP', 'Vulture', 'Vulture', false, 'James Hetfield signature V with satin black finish.'),
  ('electric_guitar', 'ESP', 'Viper', 'Viper', false, 'Japan made offset double-cutaway with set-thru neck.'),
  ('electric_guitar', 'ESP', 'Mirage Deluxe', 'Mirage', false, 'Late eighties superstrat with Floyd Rose tremolo.'),
  ('electric_guitar', 'Schecter', 'C-1 Classic', 'C-1', false, 'Set neck double-cutaway with vine of life inlay.'),
  ('electric_guitar', 'Schecter', 'C-1 Plus', 'C-1', false, 'Double-cutaway with flamed maple top over mahogany body.'),
  ('electric_guitar', 'Schecter', 'C-1 Custom', 'C-1', false, 'Upscale C-1 with bound flamed top and abalone accents.'),
  ('electric_guitar', 'Schecter', 'C-1 E/A', 'C-1', false, 'Semi hollow version of the C-1 double-cutaway.'),
  ('electric_guitar', 'Schecter', 'C-1 Apocalypse', 'C-1', true, 'Aggressive C-1 with swamp ash body and Schecter Apocalypse pickups.'),
  ('electric_guitar', 'Schecter', 'C-1 FR-S Apocalypse', 'C-1', false, 'Apocalypse C-1 with Floyd Rose and Sustainiac system.'),
  ('electric_guitar', 'Schecter', 'C-1 SLS Elite', 'C-1', true, 'Slim line C-1 with ultra thin neck and Fishman Fluence pickups.'),
  ('electric_guitar', 'Schecter', 'C-1 SLS Elite Evil Twin', 'C-1', false, 'Blacked out SLS Elite variant with active pickups.'),
  ('electric_guitar', 'Schecter', 'C-1 Silver Mountain', 'C-1', true, 'Dark themed C-1 with EverTune and Sustainiac options.'),
  ('electric_guitar', 'Schecter', 'C-1 Blackjack', 'C-1', false, 'Workhorse C-1 voiced for high gain styles.'),
  ('electric_guitar', 'Schecter', 'C-1 Blackjack ATX', 'C-1', false, 'Blackjack variant with active pickups and aged white binding.'),
  ('electric_guitar', 'Schecter', 'C-1 Hellraiser Hybrid', 'C-1', false, 'Combines Hellraiser build with SLS style appointments.'),
  ('electric_guitar', 'Schecter', 'C-6 Plus', 'C-6', false, 'Affordable double-cutaway with figured maple top.'),
  ('electric_guitar', 'Schecter', 'C-6 Deluxe', 'C-6', false, 'Budget friendly C shape with dual humbuckers.'),
  ('electric_guitar', 'Schecter', 'C-7 Deluxe', 'C-7', false, 'Budget friendly seven string with dual humbuckers.'),
  ('electric_guitar', 'Schecter', 'C-7 Hellraiser', 'C-7', false, 'Seven string Hellraiser with active EMG pickups.'),
  ('electric_guitar', 'Schecter', 'C-7 Apocalypse', 'C-7', false, 'Seven string Apocalypse with aggressive styling.'),
  ('electric_guitar', 'Schecter', 'C-7 SLS Elite', 'C-7', false, 'Seven string SLS Elite with Fishman Fluence pickups.'),
  ('electric_guitar', 'Schecter', 'C-8 Deluxe', 'C-8', false, 'Affordable eight string with dual humbuckers.'),
  ('electric_guitar', 'Schecter', 'Omen-6', 'Omen', true, 'Popular entry level double-cutaway with Schecter Diamond pickups.'),
  ('electric_guitar', 'Schecter', 'Omen-7', 'Omen', false, 'Entry level seven string version of the Omen.'),
  ('electric_guitar', 'Schecter', 'Omen-8', 'Omen', false, 'Entry level eight string version of the Omen.'),
  ('electric_guitar', 'Schecter', 'Omen Extreme-7', 'Omen', false, 'Seven string Omen Extreme with quilted maple top.'),
  ('electric_guitar', 'Schecter', 'Omen Extreme-6 FR', 'Omen', false, 'Omen Extreme with licensed Floyd Rose tremolo.'),
  ('electric_guitar', 'Schecter', 'Omen Elite-6', 'Omen', false, 'Updated Omen line with figured poplar top.'),
  ('electric_guitar', 'Schecter', 'Omen Elite-6 FR', 'Omen', false, 'Omen Elite with Floyd Rose special tremolo.'),
  ('electric_guitar', 'Schecter', 'Damien-6', 'Damien', false, 'Metal focused double-cutaway with gothic cross inlays.'),
  ('electric_guitar', 'Schecter', 'Damien-7', 'Damien', false, 'Seven string version of the Damien.'),
  ('electric_guitar', 'Schecter', 'Damien Platinum-6', 'Damien', false, 'Damien Platinum with EMG 81 and 85 active pickups.'),
  ('electric_guitar', 'Schecter', 'Damien Elite-6', 'Damien', false, 'Discontinued Damien tier with quilted maple top.'),
  ('electric_guitar', 'Schecter', 'Reaper-6', 'Reaper', true, 'Modern double-cutaway with swamp ash burl top.'),
  ('electric_guitar', 'Schecter', 'Reaper-6 Custom', 'Reaper', false, 'Upscale Reaper with ebony board and stainless frets.'),
  ('electric_guitar', 'Schecter', 'Reaper-7', 'Reaper', false, 'Seven string Reaper with burl maple top.'),
  ('electric_guitar', 'Schecter', 'Reaper-7 Multiscale', 'Reaper', false, 'Fanned fret seven string Reaper.'),
  ('electric_guitar', 'Schecter', 'Sun Valley Super Shredder FR', 'Sun Valley', false, 'Super Shredder with Floyd Rose 1500 series tremolo.'),
  ('electric_guitar', 'Schecter', 'Banshee-6 Extreme', 'Banshee', false, 'Fast playing Banshee with figured extreme top.'),
  ('electric_guitar', 'Schecter', 'Banshee Elite-6', 'Banshee', false, 'Premium Banshee with ebony fingerboard.'),
  ('electric_guitar', 'Schecter', 'Banshee Elite-7', 'Banshee', false, 'Seven string premium Banshee.'),
  ('electric_guitar', 'Schecter', 'Banshee Mach-6', 'Banshee', true, 'Modern Banshee with sculpted bevels and reverse headstock.'),
  ('electric_guitar', 'Schecter', 'Banshee Mach-7', 'Banshee', false, 'Seven string Banshee Mach with EverTune option.'),
  ('electric_guitar', 'Schecter', 'PT', 'PT', true, 'Classic double bound T style singlecut design.'),
  ('electric_guitar', 'Schecter', 'PT Fastback', 'PT', false, 'Retro styled PT with dual humbuckers.'),
  ('electric_guitar', 'Schecter', 'PT Fastback II B', 'PT', false, 'Baritone PT Fastback with vintage styling.'),
  ('electric_guitar', 'Schecter', 'PT Special', 'PT', false, 'PT with vintage style appointments.'),
  ('electric_guitar', 'Schecter', 'Nick Johnston Traditional', 'Nick Johnston', true, 'Nick Johnston signature S style in atomic finish colors.'),
  ('electric_guitar', 'Schecter', 'Nick Johnston Traditional HSS', 'Nick Johnston', false, 'HSS version of the Nick Johnston signature.'),
  ('electric_guitar', 'Schecter', 'KM-6', 'Keith Merrow', false, 'Original Keith Merrow signature double-cutaway.'),
  ('electric_guitar', 'Schecter', 'KM-6 MK-III', 'Keith Merrow', true, 'Third generation Keith Merrow model with Fishman pickups.'),
  ('electric_guitar', 'Schecter', 'KM-7 MK-III', 'Keith Merrow', false, 'Seven string Keith Merrow MK-III.'),
  ('electric_guitar', 'Schecter', 'Jerry Horton Tempest', 'Tempest', false, 'Jerry Horton signature version of the Tempest.'),
  ('electric_guitar', 'Schecter', 'Solo-II Special', 'Solo-II', false, 'Singlecut Solo-II with swamp ash body.'),
  ('electric_guitar', 'Schecter', 'Solo-II Supreme', 'Solo-II', false, 'Upscale Solo-II with figured top and premium hardware.'),
  ('electric_guitar', 'Schecter', 'Corsair', 'Corsair', false, 'Semi hollow double-cutaway with retro styling.'),
  ('electric_guitar', 'Schecter', 'Coupe', 'Coupe', false, 'Full hollowbody archtop with dual humbuckers.'),
  ('electric_guitar', 'Schecter', 'Synyster Standard', 'Synyster', false, 'Synyster Gates signature with pinstripe graphics.'),
  ('electric_guitar', 'Schecter', 'Synyster Custom-S', 'Synyster', true, 'Synyster Gates signature with Sustainiac and Floyd Rose.'),
  ('electric_guitar', 'Schecter', 'Zacky Vengeance 6661', 'Zacky Vengeance', false, 'Zacky Vengeance signature singlecut with custom graphics.'),
  ('electric_guitar', 'Schecter', 'Demon-7', 'Demon', false, 'Seven string Demon with satin finish.'),
  ('electric_guitar', 'Schecter', 'Demon-8', 'Demon', false, 'Eight string version of the Demon.'),
  ('electric_guitar', 'Schecter', 'Ultra', 'Ultra', false, 'Retro styled offset solidbody.'),
  ('electric_guitar', 'Schecter', 'Tempest Custom', 'Tempest', false, 'Set neck Tempest with flamed maple top.'),
  ('electric_guitar', 'Schecter', 'E-1 Custom', 'E-1', false, 'Angular set neck E-1 with figured maple top.'),
  ('electric_guitar', 'Schecter', 'V-1 Custom', 'V-1', false, 'Set neck V shape with flamed maple top.'),
  ('electric_guitar', 'Schecter', 'V-1 Platinum', 'V-1', false, 'V shape with satin finish and active pickups.'),
  ('electric_guitar', 'Schecter', 'UltraCure', 'UltraCure', false, 'Robert Smith signature with elongated horns and chrome accents.'),
  ('electric_guitar', 'Dean', 'ML 79', 'ML', true, 'Classic ML shape with mahogany body and string-thru bridge.'),
  ('electric_guitar', 'Dean', 'MLX', 'ML', false, 'Affordable X series version of the ML shape.'),
  ('electric_guitar', 'Dean', 'Baby ML', 'ML', false, 'Downsized ML body from the eighties lineup.'),
  ('electric_guitar', 'Dean', 'Dean From Hell CFH', 'Dimebag', true, 'Dimebag Darrell signature ML with lightning storm graphic.'),
  ('electric_guitar', 'Dean', 'Dime O Flame', 'Dimebag', false, 'Dimebag Darrell ML with flame graphic finish.'),
  ('electric_guitar', 'Dean', 'Dime Slime', 'Dimebag', false, 'Dimebag Darrell ML in slime green burst.'),
  ('electric_guitar', 'Dean', 'Razorback V', 'Dimebag', false, 'Dimebag Darrell V with razor styled body edges.'),
  ('electric_guitar', 'Dean', 'VX', 'V', false, 'Affordable X series version of the V shape.'),
  ('electric_guitar', 'Dean', 'Dave Mustaine VMNT', 'V', true, 'Dave Mustaine signature V with set neck construction.'),
  ('electric_guitar', 'Dean', 'Kerry King V', 'V', false, 'Kerry King signature V voiced for thrash metal.'),
  ('electric_guitar', 'Dean', 'Z 79', 'Z', true, 'Classic Z shape with mahogany body and string-thru bridge.'),
  ('electric_guitar', 'Dean', 'ZX', 'Z', false, 'Affordable X series version of the Z shape.'),
  ('electric_guitar', 'Dean', 'Z Select', 'Z', false, 'Mid tier Z with flamed maple top.'),
  ('electric_guitar', 'Dean', 'Cadillac 1980', 'Cadillac', true, 'Reissue style Cadillac with mahogany body and set neck.'),
  ('electric_guitar', 'Dean', 'Cadillac Select', 'Cadillac', false, 'Mid tier Cadillac with figured maple top.'),
  ('electric_guitar', 'Dean', 'Cadillac X', 'Cadillac', false, 'Affordable X series version of the Cadillac.'),
  ('electric_guitar', 'Dean', 'Thoroughbred Select', 'Thoroughbred', false, 'Singlecut Thoroughbred with flamed maple top.'),
  ('electric_guitar', 'Dean', 'Thoroughbred X', 'Thoroughbred', false, 'Affordable X series singlecut Thoroughbred.'),
  ('electric_guitar', 'Dean', 'Thoroughbred Deluxe', 'Thoroughbred', false, 'Upscale Thoroughbred with bound body and inlays.'),
  ('electric_guitar', 'Dean', 'Vendetta XM', 'Vendetta', false, 'Entry level double-cutaway with satin natural finish.'),
  ('electric_guitar', 'Dean', 'Vendetta 1.0', 'Vendetta', false, 'Discontinued double-cutaway from the Vendetta line.'),
  ('electric_guitar', 'Dean', 'Exile Select', 'Exile', false, 'Modern carved top double-cutaway with figured finish.'),
  ('electric_guitar', 'Dean', 'MD24', 'MD24', true, 'Modern superstrat with roasted maple neck and locking tuners.'),
  ('electric_guitar', 'Dean', 'MD24 Floyd', 'MD24', false, 'MD24 variant with Floyd Rose tremolo.'),
  ('electric_guitar', 'Dean', 'Icon', 'Icon', false, 'Flat top singlecut with set neck design.'),
  ('electric_guitar', 'Dean', 'Icon X', 'Icon', false, 'Affordable X series version of the Icon singlecut.'),
  ('electric_guitar', 'Dean', 'EVO', 'EVO', false, 'Compact singlecut with dual humbuckers.'),
  ('electric_guitar', 'Dean', 'EVO XM', 'EVO', false, 'Entry level satin finish version of the EVO.'),
  ('electric_guitar', 'Dean', 'Custom Zone', 'Custom', false, 'Nineties style solidbody in fluorescent finishes.'),
  ('electric_guitar', 'Dean', 'Custom 350', 'Custom', false, 'Double-cutaway with flamed top and licensed tremolo.'),
  ('electric_guitar', 'Dean', 'Splittail', 'Splittail', false, 'Offset body with split tail lower bout.'),
  ('electric_guitar', 'Dean', 'Hardtail', 'Hardtail', false, 'Double-cutaway with fixed bridge and carved top.'),
  ('electric_guitar', 'Dean', 'Michael Schenker Standard', 'Michael Schenker', false, 'Michael Schenker signature V with black and white finish.'),
  ('electric_guitar', 'B.C. Rich', 'Warlock MK3', 'Warlock', false, 'Aggressive Warlock shape with dual humbuckers.'),
  ('electric_guitar', 'B.C. Rich', 'Warlock MK5', 'Warlock', false, 'Warlock with Floyd Rose and upgraded electronics.'),
  ('electric_guitar', 'B.C. Rich', 'Warlock Extreme', 'Warlock', true, 'Modern Warlock with neck-thru build and Fishman pickups.'),
  ('electric_guitar', 'B.C. Rich', 'Kerry King Wartribe', 'Warlock', true, 'Kerry King signature Warlock with tribal graphic.'),
  ('electric_guitar', 'B.C. Rich', 'Mockingbird ST', 'Mockingbird', true, 'Classic Mockingbird with set neck and dual humbuckers.'),
  ('electric_guitar', 'B.C. Rich', 'Mockingbird MK3', 'Mockingbird', false, 'Affordable Mockingbird with quilted top veneer.'),
  ('electric_guitar', 'B.C. Rich', 'Mockingbird Extreme', 'Mockingbird', false, 'Modern Mockingbird with premium woods and electronics.'),
  ('electric_guitar', 'B.C. Rich', 'Ironbird', 'Ironbird', true, 'Radical pointed body shape from the eighties.'),
  ('electric_guitar', 'B.C. Rich', 'Ironbird Extreme', 'Ironbird', false, 'Modern Ironbird with neck-thru construction and Floyd Rose option.'),
  ('electric_guitar', 'B.C. Rich', 'Bich', 'Bich', true, 'Iconic angular double-cutaway from the seventies.'),
  ('electric_guitar', 'B.C. Rich', 'Bich 10', 'Bich', false, 'Ten string version of the Bich with four drone strings.'),
  ('electric_guitar', 'B.C. Rich', 'Stealth', 'Stealth', true, 'Minimalist angular shape linked to Chuck Schuldiner.'),
  ('electric_guitar', 'B.C. Rich', 'Villain Deluxe', 'Villain', false, 'Pointed offset shape from the Villain series.'),
  ('electric_guitar', 'B.C. Rich', 'Shredzilla Extreme', 'Shredzilla', false, 'Shred focused superstrat with deep cutaways.'),
  ('electric_guitar', 'B.C. Rich', 'Shredzilla Prophecy Exotic Archtop', 'Shredzilla', false, 'Arched exotic top Shredzilla with Floyd Rose.'),
  ('electric_guitar', 'B.C. Rich', 'Gunslinger Retro', 'Gunslinger', false, 'Eighties style superstrat with single bridge humbucker.'),
  ('electric_guitar', 'B.C. Rich', 'Eagle', 'Eagle', false, 'Carved top classic with neck-thru construction.'),
  ('electric_guitar', 'B.C. Rich', 'Seagull', 'Seagull', false, 'Seventies original with curved horns and carved body.'),
  ('electric_guitar', 'B.C. Rich', 'Draco', 'Draco', false, 'Extreme pointed V shape with angular bevels.'),
  ('electric_guitar', 'B.C. Rich', 'Beast', 'Beast', false, 'Aggressive double-cutaway with clawed styling.'),
  ('electric_guitar', 'B.C. Rich', 'Jr. V Extreme', 'Jr. V', false, 'Compact V with modern Extreme series appointments.'),
  ('electric_guitar', 'B.C. Rich', 'Assassin', 'Assassin', false, 'Fast playing double-cutaway from the early nineties.'),
  ('electric_guitar', 'B.C. Rich', 'Warbeast', 'Warbeast', false, 'Hybrid V shape with aggressive points.'),
  ('electric_guitar', 'B.C. Rich', 'Warbeast Extreme', 'Warbeast', false, 'Modern Warbeast with premium construction.'),
  ('electric_guitar', 'Solar', 'A2.6', 'A', true, 'Set neck superstrat with Duncan Solar pickups.'),
  ('electric_guitar', 'Solar', 'A2.7', 'A', false, 'Seven string version of the A2 superstrat.'),
  ('electric_guitar', 'Solar', 'A2.6C', 'A', false, 'Matte carbon black superstrat with Duncan Solar pickups.'),
  ('electric_guitar', 'Solar', 'E1.6', 'E', true, 'Angular E type body with neck-thru construction.'),
  ('electric_guitar', 'Solar', 'E2.6', 'E', false, 'Set neck E type with matte finish.'),
  ('electric_guitar', 'Solar', 'S2.6', 'S', false, 'Singlecut S type with set neck and dual humbuckers.'),
  ('electric_guitar', 'Solar', 'V1.6', 'V', false, 'Neck-thru V type with matte black finish.'),
  ('electric_guitar', 'Solar', 'V2.6', 'V', false, 'Set neck V type with Duncan Solar pickups.'),
  ('electric_guitar', 'Solar', 'GC1.6', 'GC', true, 'Double-cutaway GC type with neck-thru construction.'),
  ('electric_guitar', 'Solar', 'GC2.6', 'GC', false, 'Set neck GC type with matte finish.'),
  ('electric_guitar', 'Solar', 'GF1.6', 'GF', false, 'Offset GF type with modern appointments.'),
  ('electric_guitar', 'Solar', 'T1.6', 'T', false, 'T style single cutaway with dual humbuckers.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
