begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('bass_guitar', 'Fender', 'Player II Precision Bass', 'Player II', true, 'Mexico built Player II P Bass with split single-coil punch.'),
  ('bass_guitar', 'Fender', 'Player II Jazz Bass', 'Player II', true, 'Mexico built Player II Jazz Bass with dual single-coils.'),
  ('bass_guitar', 'Fender', 'Player II Jazz Bass V', 'Player II', false, '5-string Player II Jazz Bass.'),
  ('bass_guitar', 'Fender', 'Player II Precision Bass Left-Hand', 'Player II', false, 'Left-handed Player II Precision Bass.'),
  ('bass_guitar', 'Fender', 'American Professional II Precision Bass', 'American Professional II', true, 'USA Precision Bass with V-Mod II split single-coil.'),
  ('bass_guitar', 'Fender', 'American Professional II Precision Bass Left-Hand', 'American Professional II', false, 'Left-handed USA Precision Bass with V-Mod II pickup.'),
  ('bass_guitar', 'Fender', 'American Professional II Jazz Bass', 'American Professional II', true, 'USA Jazz Bass with V-Mod II single-coils and HiMass bridge.'),
  ('bass_guitar', 'Fender', 'American Professional II Jazz Bass V', 'American Professional II', false, '5-string USA Jazz Bass with V-Mod II pickups.'),
  ('bass_guitar', 'Fender', 'American Professional II Jazz Bass Left-Hand', 'American Professional II', false, 'Left-handed USA Jazz Bass with V-Mod II pickups.'),
  ('bass_guitar', 'Fender', 'American Ultra Precision Bass', 'American Ultra', true, 'USA Ultra Precision Bass with Ultra Noiseless pickup and Modern D neck.'),
  ('bass_guitar', 'Fender', 'American Ultra Jazz Bass', 'American Ultra', true, 'USA Ultra Jazz Bass with Ultra Noiseless pickups and active preamp.'),
  ('bass_guitar', 'Fender', 'American Ultra Jazz Bass V', 'American Ultra', false, '5-string USA Ultra Jazz Bass with active preamp.'),
  ('bass_guitar', 'Fender', 'American Ultra II Precision Bass', 'American Ultra II', false, 'Second gen Ultra Precision Bass with refined pickups.'),
  ('bass_guitar', 'Fender', 'American Ultra II Jazz Bass', 'American Ultra II', false, 'Second gen Ultra Jazz Bass with updated preamp.'),
  ('bass_guitar', 'Fender', 'American Ultra II Jazz Bass V', 'American Ultra II', false, 'Second gen 5-string Ultra Jazz Bass.'),
  ('bass_guitar', 'Fender', 'American Vintage II 1954 Precision Bass', 'American Vintage II', false, '1954 spec USA P Bass reissue with pure vintage single-coil.'),
  ('bass_guitar', 'Fender', 'American Vintage II 1960 Precision Bass', 'American Vintage II', false, '1960 spec USA P Bass reissue with split single-coil.'),
  ('bass_guitar', 'Fender', 'American Vintage II 1966 Jazz Bass', 'American Vintage II', false, '1966 spec USA Jazz Bass reissue with pure vintage pickups.'),
  ('bass_guitar', 'Fender', 'American Performer Precision Bass', 'American Performer', false, 'USA Performer Precision Bass with Yosemite split single-coil.'),
  ('bass_guitar', 'Fender', 'American Performer Jazz Bass', 'American Performer', false, 'USA Performer Jazz Bass with Yosemite single-coils.'),
  ('bass_guitar', 'Fender', 'American Performer Mustang Bass', 'American Performer', false, 'USA Performer short scale Mustang Bass.'),
  ('bass_guitar', 'Fender', 'Vintera 50s Precision Bass', 'Vintera', false, 'Vintera 50s P Bass with vintage voiced single-coil.'),
  ('bass_guitar', 'Fender', 'Vintera 60s Precision Bass', 'Vintera', false, 'Vintera 60s P Bass with split single-coil.'),
  ('bass_guitar', 'Fender', 'Vintera 60s Jazz Bass', 'Vintera', false, 'Vintera 60s Jazz Bass with vintage voiced pickups.'),
  ('bass_guitar', 'Fender', 'Vintera 70s Jazz Bass', 'Vintera', false, 'Vintera 70s Jazz Bass with block inlays and hot pickups.'),
  ('bass_guitar', 'Fender', 'Vintera II 50s Precision Bass', 'Vintera II', false, 'Vintera II 50s Precision Bass with refined vintage feel.'),
  ('bass_guitar', 'Fender', 'Vintera II 60s Jazz Bass', 'Vintera II', false, 'Vintera II 60s Jazz Bass with vintage voiced pickups.'),
  ('bass_guitar', 'Fender', 'Vintera II 70s Jazz Bass', 'Vintera II', false, 'Vintera II 70s Jazz Bass with block inlays.'),
  ('bass_guitar', 'Fender', 'Vintera II 70s Mustang Bass', 'Vintera II', false, 'Vintera II 70s short scale Mustang Bass.'),
  ('bass_guitar', 'Fender', 'Vintera II 60s Precision Bass', 'Vintera II', false, 'Vintera II 60s Precision Bass with split single-coil.'),
  ('bass_guitar', 'Fender', 'Player Mustang Bass PJ', 'Player', true, 'Player short scale Mustang Bass with PJ pickup layout.'),
  ('bass_guitar', 'Fender', 'Player Jaguar Bass', 'Player', false, 'Player Jaguar Bass with PJ pickups.'),
  ('bass_guitar', 'Fender', 'Aerodyne Special Precision Bass', 'Aerodyne Special', false, 'Aerodyne Special P Bass with sculpted heel and Noiseless pickup.'),
  ('bass_guitar', 'Fender', 'Aerodyne Special Jazz Bass', 'Aerodyne Special', false, 'Aerodyne Special Jazz Bass with sculpted heel.'),
  ('bass_guitar', 'Fender', 'Meteora Bass', 'Meteora', false, 'Offset body Meteora Bass with dual humbuckers.'),
  ('bass_guitar', 'Fender', 'Duff McKagan Deluxe Precision Bass', 'Artist', false, 'Duff McKagan signature Deluxe P Bass with PJ pickups.'),
  ('bass_guitar', 'Fender', 'Geddy Lee Jazz Bass', 'Artist', true, 'Geddy Lee signature Jazz Bass with vintage single-coils and thin neck.'),
  ('bass_guitar', 'Fender', 'Flea Jazz Bass', 'Artist', false, 'Flea signature Jazz Bass with active preamp and Noiseless pickups.'),
  ('bass_guitar', 'Fender', 'Jaco Pastorius Jazz Bass', 'Artist', false, 'Jaco Pastorius signature fretless Jazz Bass.'),
  ('bass_guitar', 'Fender', 'Steve Harris Precision Bass', 'Artist', false, 'Steve Harris signature P Bass with hot pickup and mirror pickguard.'),
  ('bass_guitar', 'Fender', 'Nate Mendel Precision Bass', 'Artist', false, 'Nate Mendel signature Precision Bass with Seymour Duncan Basslines pickup.'),
  ('bass_guitar', 'Fender', 'Player Plus Precision Bass', 'Player Plus', false, 'Player Plus P Bass with Noiseless pickup and active preamp.'),
  ('bass_guitar', 'Fender', 'Player Plus Jazz Bass', 'Player Plus', true, 'Player Plus Jazz Bass with Noiseless pickups and active preamp.'),
  ('bass_guitar', 'Fender', 'Player Plus Jazz Bass V', 'Player Plus', false, '5-string Player Plus Jazz Bass with active preamp.'),
  ('bass_guitar', 'Fender', 'Player Plus Active Meteora Bass', 'Player Plus', false, 'Player Plus Meteora Bass with active humbuckers.'),
  ('bass_guitar', 'Squier', 'Classic Vibe 50s Precision Bass', 'Classic Vibe', true, 'Classic Vibe 50s P Bass with Alnico single-coil.'),
  ('bass_guitar', 'Squier', 'Classic Vibe 60s Precision Bass', 'Classic Vibe', true, 'Classic Vibe 60s P Bass with Alnico split single-coil.'),
  ('bass_guitar', 'Squier', 'Classic Vibe 60s Jazz Bass', 'Classic Vibe', true, 'Classic Vibe 60s Jazz Bass with Alnico single-coils.'),
  ('bass_guitar', 'Squier', 'Classic Vibe 70s Jazz Bass', 'Classic Vibe', true, 'Classic Vibe 70s Jazz Bass with block inlays.'),
  ('bass_guitar', 'Squier', 'Classic Vibe 70s Jazz Bass V', 'Classic Vibe', false, '5-string Classic Vibe 70s Jazz Bass.'),
  ('bass_guitar', 'Squier', 'Classic Vibe 60s Mustang Bass', 'Classic Vibe', false, 'Classic Vibe 60s short scale Mustang Bass.'),
  ('bass_guitar', 'Squier', 'Classic Vibe Starcaster Bass', 'Classic Vibe', false, 'Classic Vibe semi hollow Starcaster Bass.'),
  ('bass_guitar', 'Squier', 'Affinity Precision Bass PJ', 'Affinity', true, 'Affinity Precision Bass with PJ pickup layout.'),
  ('bass_guitar', 'Squier', 'Affinity Jazz Bass', 'Affinity', true, 'Affinity Jazz Bass with dual single-coils.'),
  ('bass_guitar', 'Squier', 'Affinity Jazz Bass V', 'Affinity', false, '5-string Affinity Jazz Bass.'),
  ('bass_guitar', 'Squier', 'Sonic Precision Bass', 'Sonic', false, 'Entry level Sonic Precision Bass with ceramic split single-coil.'),
  ('bass_guitar', 'Squier', 'Sonic Bronco Bass', 'Sonic', false, 'Short scale Sonic Bronco Bass for beginners.'),
  ('bass_guitar', 'Squier', 'Sonic Mustang Bass PJ', 'Sonic', false, 'Sonic short scale Mustang Bass with PJ pickups.'),
  ('bass_guitar', 'Squier', 'Contemporary Active Jazz Bass HH', 'Contemporary', false, 'Contemporary Jazz Bass with dual active humbuckers.'),
  ('bass_guitar', 'Squier', 'Contemporary Active Jazz Bass HH V', 'Contemporary', false, 'Contemporary 5-string Jazz Bass with dual active humbuckers.'),
  ('bass_guitar', 'Squier', 'Contemporary Active Precision Bass PH', 'Contemporary', false, 'Contemporary Precision Bass with PH pickup layout and active preamp.'),
  ('bass_guitar', 'Squier', 'Paranormal Rascal Bass HH', 'Paranormal', false, 'Paranormal Rascal short scale Bass with dual humbuckers.'),
  ('bass_guitar', 'Squier', 'Paranormal Jazz Bass 32', 'Paranormal', false, 'Paranormal 32 inch scale Jazz Bass.'),
  ('bass_guitar', 'Ibanez', 'SR300E', 'SR', true, 'SR300E with dual Powerspan Neo humbuckers and 3-band EQ.'),
  ('bass_guitar', 'Ibanez', 'SR305E', 'SR', true, '5-string SR305E with active pickups and 3-band EQ.'),
  ('bass_guitar', 'Ibanez', 'SR500E', 'SR', true, 'SR500E with Bartolini BH2 pickups and 3-band EQ.'),
  ('bass_guitar', 'Ibanez', 'SR505E', 'SR', true, '5-string SR505E with Bartolini pickups and 3-band EQ.'),
  ('bass_guitar', 'Ibanez', 'SR506E', 'SR', false, '6-string SR506E with Bartolini pickups.'),
  ('bass_guitar', 'Ibanez', 'SR605E', 'SR Premium', false, 'Premium SR605 5-string with Nordstrand Big Split pickups.'),
  ('bass_guitar', 'Ibanez', 'SR1100B Premium', 'SR Premium', false, 'Premium SR1100 with Aguilar pickups and 3-band EQ.'),
  ('bass_guitar', 'Ibanez', 'SR1200E Premium', 'SR Premium', false, 'Premium SR1200 with Bartolini BH2 pickups.'),
  ('bass_guitar', 'Ibanez', 'SR1305B Premium', 'SR Premium', false, 'Premium SR1305 5-string with Nordstrand pickups.'),
  ('bass_guitar', 'Ibanez', 'SR2600 Premium', 'SR Premium', false, 'Premium SR2600 with Nordstrand Big Split pickups.'),
  ('bass_guitar', 'Ibanez', 'SR5005 Prestige', 'SR Prestige', false, 'Prestige SR5005 5-string with Bartolini pickups.'),
  ('bass_guitar', 'Ibanez', 'SRMD200 Mezzo', 'SR Mezzo', false, '32 inch scale SR Mezzo with dual PowerSpan Neo pickups.'),
  ('bass_guitar', 'Ibanez', 'SRMD201', 'SR Mezzo', false, '32 inch scale SR Mezzo with dual passive humbuckers.'),
  ('bass_guitar', 'Ibanez', 'SR30TH4II Anniversary', 'SR', false, 'SR Anniversary edition 4-string.'),
  ('bass_guitar', 'Ibanez', 'BTB605MS', 'BTB Multi-Scale', false, 'BTB605 5-string multi-scale with Bartolini pickups.'),
  ('bass_guitar', 'Ibanez', 'BTB745', 'BTB', false, 'BTB745 5-string with Bartolini BH2 pickups.'),
  ('bass_guitar', 'Ibanez', 'BTB846', 'BTB', false, '6-string BTB846 with Bartolini pickups.'),
  ('bass_guitar', 'Ibanez', 'TMB100', 'Talman Bass', true, 'Talman TMB100 with PJ pickup layout.'),
  ('bass_guitar', 'Ibanez', 'TMB110', 'Talman Bass', false, 'Talman TMB110 with active preamp.'),
  ('bass_guitar', 'Ibanez', 'TMB600', 'Talman Bass', false, 'Talman TMB600 with active preamp and premium finish.'),
  ('bass_guitar', 'Ibanez', 'GSR200', 'Gio', true, 'Beginner Gio GSR200 with PJ pickups and Phat II EQ.'),
  ('bass_guitar', 'Ibanez', 'GSR205', 'Gio', false, '5-string Gio GSR205 with PJ pickups.'),
  ('bass_guitar', 'Ibanez', 'GSRM20 miKro', 'Gio miKro', false, 'Short scale Gio miKro Bass for smaller players.'),
  ('bass_guitar', 'Ibanez', 'EHB1005SMS', 'EHB', true, 'Ergonomic Headless Bass 5-string multi-scale.'),
  ('bass_guitar', 'Ibanez', 'EHB1005MS', 'EHB', false, 'Ergonomic Headless Bass 5-string multi-scale with Bartolini pickups.'),
  ('bass_guitar', 'Ibanez', 'EHB1505MS', 'EHB', false, 'Premium Ergonomic Headless Bass 5-string multi-scale.'),
  ('bass_guitar', 'Ibanez', 'EHB1000S', 'EHB', false, 'Ergonomic Headless Bass 4-string with Bartolini pickups.'),
  ('bass_guitar', 'Ibanez', 'Gary Willis GWB35', 'Signature', false, 'Gary Willis GWB35 5-string fretless with Bartolini pickup.'),
  ('bass_guitar', 'Ibanez', 'Adam Nitti ANB306E', 'Signature', false, 'Adam Nitti ANB306E 6-string signature bass.'),
  ('bass_guitar', 'Yamaha', 'TRBX174', 'TRBX', true, 'Entry level TRBX174 with PJ pickup layout.'),
  ('bass_guitar', 'Yamaha', 'TRBX174EW', 'TRBX', false, 'TRBX174 with exotic wood top.'),
  ('bass_guitar', 'Yamaha', 'TRBX304', 'TRBX', true, 'TRBX304 with dual humbuckers and active EQ.'),
  ('bass_guitar', 'Yamaha', 'TRBX305', 'TRBX', true, '5-string TRBX305 with active EQ.'),
  ('bass_guitar', 'Yamaha', 'TRBX504', 'TRBX', true, 'TRBX504 with alder body and D-DECK preamp.'),
  ('bass_guitar', 'Yamaha', 'TRBX505', 'TRBX', false, '5-string TRBX505 with D-DECK preamp.'),
  ('bass_guitar', 'Yamaha', 'TRBX604FM', 'TRBX', false, 'TRBX604 with flamed maple top and dual humbuckers.'),
  ('bass_guitar', 'Yamaha', 'TRBX605FM', 'TRBX', false, '5-string TRBX605 with flamed maple top.'),
  ('bass_guitar', 'Yamaha', 'BB234', 'BB', true, 'BB234 with PJ pickup layout and passive electronics.'),
  ('bass_guitar', 'Yamaha', 'BB235', 'BB', false, '5-string BB235 with PJ pickups.'),
  ('bass_guitar', 'Yamaha', 'BB434', 'BB', true, 'BB434 with vintage plus modern PJ pickups.'),
  ('bass_guitar', 'Yamaha', 'BB435', 'BB', false, '5-string BB435 with PJ pickup layout.'),
  ('bass_guitar', 'Yamaha', 'BB734A', 'BB', false, 'BB734A with active/passive electronics and PJ pickups.'),
  ('bass_guitar', 'Yamaha', 'BB735A', 'BB', false, '5-string BB735A with active/passive electronics.'),
  ('bass_guitar', 'Yamaha', 'BBP34', 'BB Pro', false, 'BB Pro 34 with vintage BB style and premium pickups.'),
  ('bass_guitar', 'Yamaha', 'BBP35', 'BB Pro', false, '5-string BB Pro 35 with premium construction.'),
  ('bass_guitar', 'Yamaha', 'Billy Sheehan Attitude Limited 3', 'Attitude', false, 'Billy Sheehan Attitude Limited 3 signature bass.'),
  ('bass_guitar', 'Music Man', 'StingRay Special 4 HH', 'StingRay Special', true, 'StingRay Special 4-string with dual Neodymium humbuckers.'),
  ('bass_guitar', 'Music Man', 'StingRay Special 5 H', 'StingRay Special', true, '5-string StingRay Special with single Neodymium humbucker.'),
  ('bass_guitar', 'Music Man', 'StingRay Special 5 HH', 'StingRay Special', false, '5-string StingRay Special with dual humbuckers.'),
  ('bass_guitar', 'Music Man', 'Bongo 4 H', 'Bongo', false, '4-string Bongo with single humbucker and 3-band EQ.'),
  ('bass_guitar', 'Music Man', 'Bongo 4 HH', 'Bongo', false, '4-string Bongo with dual humbuckers.'),
  ('bass_guitar', 'Music Man', 'Bongo 5 H', 'Bongo', false, '5-string Bongo with single humbucker.'),
  ('bass_guitar', 'Music Man', 'Bongo 5 HH', 'Bongo', false, '5-string Bongo with dual humbuckers.'),
  ('bass_guitar', 'Music Man', 'Sterling 4 H', 'Sterling', false, 'Sterling 4-string with single humbucker and smaller body.'),
  ('bass_guitar', 'Music Man', 'Sterling 5 HH', 'Sterling', false, '5-string Sterling with dual humbuckers.'),
  ('bass_guitar', 'Music Man', 'Joe Dart Artist Series I', 'Artist', false, 'Joe Dart signature bass with single humbucker.'),
  ('bass_guitar', 'Music Man', 'Joe Dart Artist Series II', 'Artist', false, 'Joe Dart Artist Series II signature bass.'),
  ('bass_guitar', 'Music Man', 'DarkRay 4', 'DarkRay', false, 'DarkRay collaboration with Darkglass featuring built in distortion circuit.'),
  ('bass_guitar', 'Music Man', 'DarkRay 5', 'DarkRay', false, '5-string DarkRay with built in Darkglass distortion.'),
  ('bass_guitar', 'Sterling by Music Man', 'Ray4', 'Ray', true, 'Sterling by MM Ray4 with single humbucker.'),
  ('bass_guitar', 'Sterling by Music Man', 'Ray4 HH', 'Ray', false, 'Sterling by MM Ray4 with dual humbuckers.'),
  ('bass_guitar', 'Sterling by Music Man', 'Ray5', 'Ray', true, '5-string Sterling by MM Ray5 with single humbucker.'),
  ('bass_guitar', 'Sterling by Music Man', 'Ray24CA', 'Ray', false, 'Sterling by MM Ray24 Classic Active with 2-band EQ.'),
  ('bass_guitar', 'Sterling by Music Man', 'Ray34', 'Ray', true, 'Sterling by MM Ray34 with active 3-band EQ.'),
  ('bass_guitar', 'Sterling by Music Man', 'Ray34 HH', 'Ray', false, 'Sterling by MM Ray34 with dual humbuckers.'),
  ('bass_guitar', 'Sterling by Music Man', 'Ray35', 'Ray', false, '5-string Sterling by MM Ray35 with active EQ.'),
  ('bass_guitar', 'Sterling by Music Man', 'StingRay Short Scale RaySS4', 'Ray', false, 'Sterling short scale StingRay 4-string.'),
  ('bass_guitar', 'Sterling by Music Man', 'SUB Series Ray4', 'SUB', false, 'Entry level SUB Series Ray4.'),
  ('bass_guitar', 'Sterling by Music Man', 'SUB Series Ray5', 'SUB', false, 'Entry level 5-string SUB Series Ray5.'),
  ('bass_guitar', 'ESP LTD', 'B-204SM', 'B', false, 'B-204 with spalted maple top and Bartolini pickups.'),
  ('bass_guitar', 'ESP LTD', 'B-205SM', 'B', false, '5-string B-205 with spalted maple top.'),
  ('bass_guitar', 'ESP LTD', 'B-4E', 'B', false, 'B-4E with EMG humbuckers and ash body.'),
  ('bass_guitar', 'ESP LTD', 'B-1004SE', 'B', false, 'B-1004 5-string with active pickups.'),
  ('bass_guitar', 'ESP LTD', 'AP-204', 'AP', false, 'AP-204 P Bass style with EMG pickups.'),
  ('bass_guitar', 'ESP LTD', 'AP-4', 'AP', false, 'AP-4 P Bass style with passive pickups.'),
  ('bass_guitar', 'ESP LTD', 'Frank Bello FB-4', 'Signature', false, 'Frank Bello signature FB-4 with EMG pickups.'),
  ('bass_guitar', 'ESP LTD', 'Surveyor 87', 'Surveyor', false, 'Reissued 87 spec Surveyor Bass with EMG pickups.'),
  ('bass_guitar', 'Schecter', 'Stiletto Extreme-4', 'Stiletto', false, 'Stiletto Extreme 4-string with EMG-HZ pickups.'),
  ('bass_guitar', 'Schecter', 'Stiletto Extreme-5', 'Stiletto', false, '5-string Stiletto Extreme with EMG-HZ pickups.'),
  ('bass_guitar', 'Schecter', 'Stiletto Studio-4', 'Stiletto', false, 'Stiletto Studio 4-string with EMG-HZ pickups.'),
  ('bass_guitar', 'Schecter', 'Stiletto Studio-5', 'Stiletto', false, '5-string Stiletto Studio.'),
  ('bass_guitar', 'Schecter', 'Stiletto Custom-4', 'Stiletto', false, 'Stiletto Custom 4-string with premium appointments.'),
  ('bass_guitar', 'Schecter', 'Stiletto Custom-5', 'Stiletto', false, '5-string Stiletto Custom with premium appointments.'),
  ('bass_guitar', 'Schecter', 'Omen-4', 'Omen', true, 'Omen 4-string with dual Schecter humbuckers.'),
  ('bass_guitar', 'Schecter', 'Omen-5', 'Omen', false, '5-string Omen with dual humbuckers.'),
  ('bass_guitar', 'Schecter', 'Model-T Session-4', 'Model-T', false, 'Model-T Session 4-string with P Bass style and Fishman Fluence pickups.'),
  ('bass_guitar', 'Schecter', 'Model-T Session-5', 'Model-T', false, '5-string Model-T Session.'),
  ('bass_guitar', 'Schecter', 'Riot-4', 'Riot', false, 'Riot 4-string with Diamond Custom pickups.'),
  ('bass_guitar', 'Schecter', 'C-4 GT', 'C', false, 'C-4 GT with EMG 35DC pickups and modern feel.'),
  ('bass_guitar', 'Schecter', 'C-5 GT', 'C', false, '5-string C-5 GT with EMG pickups.'),
  ('bass_guitar', 'Schecter', 'dUg Pinnick DP-12', 'Signature', false, 'dUg Pinnick DP-12 12-string signature bass.'),
  ('bass_guitar', 'Schecter', 'Michael Anthony MA-4', 'Signature', false, 'Michael Anthony MA-4 signature bass.'),
  ('bass_guitar', 'Warwick', 'RockBass Corvette Basic 4', 'RockBass Corvette', true, 'RockBass Corvette 4-string with dual MEC humbuckers.'),
  ('bass_guitar', 'Warwick', 'RockBass Corvette Basic 5', 'RockBass Corvette', false, '5-string RockBass Corvette Basic.'),
  ('bass_guitar', 'Warwick', 'RockBass Corvette $$', 'RockBass Corvette', false, 'RockBass Corvette Double Buck with dual MEC humbuckers.'),
  ('bass_guitar', 'Warwick', 'RockBass Corvette $$ 5', 'RockBass Corvette', false, '5-string RockBass Corvette Double Buck.'),
  ('bass_guitar', 'Warwick', 'RockBass Streamer LX 4', 'RockBass Streamer', false, 'RockBass Streamer LX 4-string with MEC pickups.'),
  ('bass_guitar', 'Warwick', 'RockBass Streamer LX 5', 'RockBass Streamer', false, '5-string RockBass Streamer LX.'),
  ('bass_guitar', 'Warwick', 'RockBass Thumb BO 4', 'RockBass Thumb', false, 'RockBass Thumb bolt-on 4-string with MEC pickups.'),
  ('bass_guitar', 'Warwick', 'RockBass Thumb BO 5', 'RockBass Thumb', false, '5-string RockBass Thumb bolt-on.'),
  ('bass_guitar', 'Warwick', 'German Pro Series Corvette Standard', 'Pro Series', false, 'German made Pro Series Corvette Standard.'),
  ('bass_guitar', 'Warwick', 'German Pro Series Thumb BO 4', 'Pro Series', false, 'German made Pro Series Thumb bolt-on 4-string.'),
  ('bass_guitar', 'Warwick', 'German Pro Series Streamer LX 4', 'Pro Series', false, 'German made Pro Series Streamer LX 4-string.'),
  ('bass_guitar', 'Spector', 'NS Ethos 4', 'NS Ethos', true, 'NS Ethos 4-string with EMG pickups and Darkglass Tone Capsule.'),
  ('bass_guitar', 'Spector', 'NS Ethos 5', 'NS Ethos', false, '5-string NS Ethos with active preamp.'),
  ('bass_guitar', 'Spector', 'NS Dimension 4', 'NS Dimension', false, 'NS Dimension 4-string with EMG pickups.'),
  ('bass_guitar', 'Spector', 'NS Dimension 5', 'NS Dimension', false, '5-string NS Dimension.'),
  ('bass_guitar', 'Spector', 'Euro 4 LT', 'Euro', false, 'Euro 4 LT with EMG pickups and Darkglass Tone Capsule.'),
  ('bass_guitar', 'Spector', 'Euro 5 LT', 'Euro', false, '5-string Euro LT with EMG pickups.'),
  ('bass_guitar', 'Spector', 'Legend 4 Standard', 'Legend', false, 'Legend 4 Standard with EMG-HZ pickups.'),
  ('bass_guitar', 'Spector', 'Legend 5 Standard', 'Legend', false, '5-string Legend Standard.'),
  ('bass_guitar', 'Spector', 'Performer 4', 'Performer', false, 'Performer 4-string with Spector active preamp.'),
  ('bass_guitar', 'Spector', 'Performer 5', 'Performer', false, '5-string Performer with active preamp.'),
  ('bass_guitar', 'Spector', 'Bantam 4', 'Bantam', false, 'Bantam short scale 4-string.'),
  ('bass_guitar', 'Sandberg', 'California II TT 4', 'California', false, 'California II TT 4-string with dual single-coils.'),
  ('bass_guitar', 'Sandberg', 'California II TT 5', 'California', false, '5-string California II TT.'),
  ('bass_guitar', 'Sandberg', 'California II VM 4', 'California', false, 'California II VM 4-string with vintage voiced pickups.'),
  ('bass_guitar', 'Sandberg', 'California II VS 4', 'California', false, 'California II VS 4-string with split single-coil.'),
  ('bass_guitar', 'Sandberg', 'Electra II TT', 'Electra', false, 'Electra II TT with modern features and Sandberg preamp.'),
  ('bass_guitar', 'Dingwall', 'NG-2 4', 'NG', true, 'Nolly Getgood NG-2 4-string multi-scale with Dingwall pickups.'),
  ('bass_guitar', 'Dingwall', 'NG-2 5', 'NG', false, '5-string NG-2 multi-scale.'),
  ('bass_guitar', 'Dingwall', 'NG-3 4', 'NG', false, 'NG-3 4-string multi-scale with three FD3n pickups.'),
  ('bass_guitar', 'Dingwall', 'NG-3 5', 'NG', false, '5-string NG-3 multi-scale.'),
  ('bass_guitar', 'Dingwall', 'NG-3 6', 'NG', false, '6-string NG-3 multi-scale.'),
  ('bass_guitar', 'Dingwall', 'Combustion 4', 'Combustion', false, 'Combustion 4-string multi-scale with FD3n pickups.'),
  ('bass_guitar', 'Dingwall', 'Combustion 5', 'Combustion', false, '5-string Combustion multi-scale.'),
  ('bass_guitar', 'Dingwall', 'D-Roc Standard 4', 'D-Roc', false, 'D-Roc Standard 4-string multi-scale.'),
  ('bass_guitar', 'Dingwall', 'D-Roc Standard 5', 'D-Roc', false, '5-string D-Roc Standard multi-scale.'),
  ('bass_guitar', 'Lakland', 'Skyline 44-01', 'Skyline', false, 'Skyline 44-01 with Hanson pickups and MB-2 electronics.'),
  ('bass_guitar', 'Lakland', 'Skyline 44-02', 'Skyline', false, 'Skyline 44-02 with LH-3 pickups.'),
  ('bass_guitar', 'Lakland', 'Skyline 44-64 Custom', 'Skyline', false, 'Skyline 44-64 P-style with Hanson split coil pickup.'),
  ('bass_guitar', 'Lakland', 'Skyline 55-01', 'Skyline', false, '5-string Skyline 55-01 with Hanson pickups.'),
  ('bass_guitar', 'Lakland', 'Skyline 55-02', 'Skyline', false, '5-string Skyline 55-02 with LH-3 pickups.'),
  ('bass_guitar', 'Lakland', 'Skyline Darryl Jones DJ4', 'Skyline Signature', false, 'Darryl Jones signature 4-string Skyline.'),
  ('bass_guitar', 'Lakland', 'Skyline Darryl Jones DJ5', 'Skyline Signature', false, '5-string Darryl Jones signature Skyline.'),
  ('bass_guitar', 'Lakland', 'Skyline Duck Dunn', 'Skyline Signature', false, 'Donald Duck Dunn signature Skyline.'),
  ('bass_guitar', 'G&L', 'Tribute L-2000', 'Tribute', true, 'Tribute L-2000 with dual MFD humbuckers and active/passive switching.'),
  ('bass_guitar', 'G&L', 'Tribute L-2500', 'Tribute', false, '5-string Tribute L-2500.'),
  ('bass_guitar', 'G&L', 'Tribute JB', 'Tribute', false, 'Tribute JB Jazz Bass style with dual single-coils.'),
  ('bass_guitar', 'G&L', 'Tribute LB-100', 'Tribute', false, 'Tribute LB-100 Precision Bass style.'),
  ('bass_guitar', 'G&L', 'Tribute Kiloton', 'Tribute', false, 'Tribute Kiloton with single MFD humbucker.'),
  ('bass_guitar', 'G&L', 'Tribute Fallout Bass', 'Tribute', false, 'Tribute Fallout short scale Bass.'),
  ('bass_guitar', 'G&L', 'Fullerton Deluxe L-2000', 'Fullerton Deluxe', false, 'USA Fullerton Deluxe L-2000 with premium construction.'),
  ('bass_guitar', 'G&L', 'Fullerton Deluxe JB', 'Fullerton Deluxe', false, 'USA Fullerton Deluxe JB Jazz style.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V3 4', 'V', true, 'Marcus Miller V3 4-string with Sire Marcus Heritage pickups.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V3 5', 'V', true, '5-string Marcus Miller V3.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V5 4', 'V', false, 'Marcus Miller V5 4-string with active preamp.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V5 5', 'V', false, '5-string Marcus Miller V5.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V7 4', 'V', true, 'Marcus Miller V7 4-string with premium Marcus Heritage pickups.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V7 5', 'V', false, '5-string Marcus Miller V7.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V7 Vintage 4', 'V', false, 'Marcus Miller V7 Vintage with vintage voiced pickups.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V7 Vintage 5', 'V', false, '5-string Marcus Miller V7 Vintage.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V8 4', 'V', false, 'Marcus Miller V8 4-string with premium construction.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V8 5', 'V', false, '5-string Marcus Miller V8.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V10 4', 'V', false, 'Marcus Miller V10 flagship 4-string.'),
  ('bass_guitar', 'Sire', 'Marcus Miller V10 5', 'V', false, '5-string Marcus Miller V10 flagship.'),
  ('bass_guitar', 'Sire', 'Marcus Miller M2 4', 'M', false, 'Marcus Miller M2 4-string with soapbar humbuckers.'),
  ('bass_guitar', 'Sire', 'Marcus Miller M2 5', 'M', false, '5-string Marcus Miller M2.'),
  ('bass_guitar', 'Sire', 'Marcus Miller M5 4', 'M', false, 'Marcus Miller M5 4-string with premium soapbar pickups.'),
  ('bass_guitar', 'Sire', 'Marcus Miller M5 5', 'M', false, '5-string Marcus Miller M5.'),
  ('bass_guitar', 'Sire', 'Marcus Miller M7 4', 'M', true, 'Marcus Miller M7 4-string with premium construction.'),
  ('bass_guitar', 'Sire', 'Marcus Miller M7 5', 'M', false, '5-string Marcus Miller M7.'),
  ('bass_guitar', 'Sire', 'Marcus Miller P5 4', 'P', false, 'Marcus Miller P5 4-string P Bass style.'),
  ('bass_guitar', 'Sire', 'Marcus Miller P5 5', 'P', false, '5-string Marcus Miller P5.'),
  ('bass_guitar', 'Sire', 'Marcus Miller P7 4', 'P', false, 'Marcus Miller P7 4-string P Bass with active preamp.'),
  ('bass_guitar', 'Sire', 'Marcus Miller P7 5', 'P', false, '5-string Marcus Miller P7.'),
  ('bass_guitar', 'Sire', 'Marcus Miller D5 4', 'D', false, 'Marcus Miller D5 4-string with fretless option.'),
  ('bass_guitar', 'Sire', 'Marcus Miller U5 4', 'U', false, 'Marcus Miller U5 4-string ukulele bass.'),
  ('bass_guitar', 'Sire', 'Marcus Miller Z3 4', 'Z', false, 'Marcus Miller Z3 4-string with soapbar humbuckers.'),
  ('bass_guitar', 'Sire', 'Marcus Miller Z7 4', 'Z', false, 'Marcus Miller Z7 flagship 4-string.'),
  ('bass_guitar', 'Cort', 'A4 Plus Artisan', 'Artisan', false, 'A4 Plus Artisan 4-string with Bartolini MK1 pickups.'),
  ('bass_guitar', 'Cort', 'A5 Plus Artisan', 'Artisan', false, '5-string A5 Plus Artisan.'),
  ('bass_guitar', 'Cort', 'A6 Plus Artisan', 'Artisan', false, '6-string A6 Plus Artisan.'),
  ('bass_guitar', 'Cort', 'B4 Plus', 'B', false, 'B4 Plus with Bartolini MK1 pickups.'),
  ('bass_guitar', 'Cort', 'B5 Plus', 'B', false, '5-string B5 Plus.'),
  ('bass_guitar', 'Cort', 'GB74JJ', 'GB', false, 'GB74JJ Jazz Bass style 4-string.'),
  ('bass_guitar', 'Cort', 'GB75JJ', 'GB', false, '5-string GB75JJ Jazz Bass style.'),
  ('bass_guitar', 'Cort', 'Action Bass Plus', 'Action', false, 'Action Bass Plus with PJ pickup layout.'),
  ('bass_guitar', 'Cort', 'Action PJ', 'Action', false, 'Action PJ 4-string.'),
  ('bass_guitar', 'Jackson', 'Spectra JS3', 'Spectra', false, 'JS Series Spectra with dual humbuckers.'),
  ('bass_guitar', 'Jackson', 'Spectra JS3V', 'Spectra', false, '5-string JS Series Spectra.'),
  ('bass_guitar', 'Jackson', 'Concert Bass JS2', 'Concert', false, 'JS2 Concert Bass with PJ pickups.'),
  ('bass_guitar', 'Jackson', 'Concert Bass JS3', 'Concert', false, 'JS3 Concert Bass with premium features.'),
  ('bass_guitar', 'Jackson', 'X Series Spectra IV', 'X Series', false, 'X Series Spectra 4-string with dual humbuckers.'),
  ('bass_guitar', 'Gretsch', 'G2220 Electromatic Junior Jet Bass II', 'Electromatic', false, 'Electromatic short scale Jr Jet Bass with dual humbuckers.'),
  ('bass_guitar', 'Gretsch', 'G5440LSB Electromatic', 'Electromatic', false, 'Electromatic Long Scale Bass with dual humbuckers.'),
  ('bass_guitar', 'Rickenbacker', '4003', '4000', true, 'Iconic Rickenbacker 4003 bass with dual single-coils and neck through construction.'),
  ('bass_guitar', 'Rickenbacker', '4003S', '4000', false, '4003S with dot fingerboard inlays.'),
  ('bass_guitar', 'Rickenbacker', '4003W', '4000', false, '4003W with walnut body.'),
  ('bass_guitar', 'Hofner', 'Violin Bass Ignition SE', 'Violin Bass', true, 'Beginner Violin Bass Ignition Special Edition.'),
  ('bass_guitar', 'Hofner', 'Violin Bass Ignition Pro', 'Violin Bass', false, 'Ignition Pro Violin Bass with upgraded appointments.'),
  ('bass_guitar', 'Hofner', 'Violin Bass Contemporary HCT-500', 'Violin Bass', true, 'Contemporary HCT-500 Violin Bass with vintage voiced pickups.'),
  ('bass_guitar', 'Hofner', 'German 500/1 V62 Vintage', 'Violin Bass', false, 'German made 500/1 V62 Vintage Violin Bass.'),
  ('bass_guitar', 'Hofner', 'Club Bass Ignition', 'Club Bass', false, 'Ignition Club Bass with Beatle-era body shape.'),
  ('bass_guitar', 'Epiphone', 'Thunderbird 64', 'Thunderbird', true, 'Thunderbird 64 reissue with vintage voiced pickups.'),
  ('bass_guitar', 'Epiphone', 'Embassy', 'Embassy', false, 'Embassy Bass with dual ProBucker humbuckers.'),
  ('bass_guitar', 'Epiphone', 'Newport', 'Newport', false, 'Newport short scale Bass with mini humbucker.'),
  ('bass_guitar', 'Epiphone', 'EB-0', 'EB', false, 'EB-0 short scale with neck humbucker.'),
  ('bass_guitar', 'Epiphone', 'EB-3', 'EB', false, 'EB-3 SG-style Bass with dual humbuckers.'),
  ('bass_guitar', 'Epiphone', 'Viola Bass', 'Viola Bass', false, 'Beatle style Viola Bass with dual humbuckers.'),
  ('bass_guitar', 'Gibson', 'Thunderbird', 'Thunderbird', true, 'USA Thunderbird with dual T-Bird humbuckers and neck through construction.'),
  ('bass_guitar', 'Gibson', 'SG Standard Bass', 'SG', false, 'USA SG Standard Bass with T-Bird humbuckers.'),
  ('bass_guitar', 'Gibson', 'Les Paul Junior Tribute DC Bass', 'Les Paul', false, 'USA Les Paul Junior Tribute Bass with dogear P-90.'),
  ('bass_guitar', 'Gibson', 'Non-Reverse Thunderbird', 'Thunderbird', false, 'USA Non-Reverse Thunderbird with mini humbuckers.'),
  ('bass_guitar', 'Harley Benton', 'PB-20', 'PB', true, 'Beginner PB-20 P Bass style.'),
  ('bass_guitar', 'Harley Benton', 'JB-20', 'JB', true, 'Beginner JB-20 Jazz Bass style.'),
  ('bass_guitar', 'Harley Benton', 'PB-50', 'PB', false, 'PB-50 vintage voiced P Bass style.'),
  ('bass_guitar', 'Harley Benton', 'JB-75', 'JB', false, 'JB-75 70s spec Jazz Bass style with block inlays.'),
  ('bass_guitar', 'Harley Benton', 'MB-4', 'MB', false, 'MB-4 modern 4-string with dual humbuckers.'),
  ('bass_guitar', 'Harley Benton', 'B-450', 'B', false, 'B-450 with active preamp and dual pickups.'),
  ('bass_guitar', 'Harley Benton', 'B-550', 'B', false, '5-string B-550 with active preamp.'),
  ('bass_guitar', 'Harley Benton', 'JB-40', 'JB', false, 'JB-40 short scale Jazz Bass style.'),
  ('bass_guitar', 'Harley Benton', 'MP-4', 'MP', false, 'MP-4 with P and Jazz pickup layout.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
