-- Phase 86: US southern/blues-rock revival + worship completions + 2010s US-teen canon.

with target(artist_name, artist_slug, song_title, song_slug, album, release_year) as (
  values
    ('Tedeschi Trucks Band','tedeschi-trucks-band','Midnight in Harlem','midnight-in-harlem','Revelator',2011),
    ('The Allman Brothers Band','the-allman-brothers-band','Soulshine','soulshine','Where It All Begins',1994),
    ('Blackberry Smoke','blackberry-smoke','One Horse Town','one-horse-town','The Whippoorwill',2012),
    ('Whiskey Myers','whiskey-myers','Broken Window Serenade','broken-window-serenade','Firewater',2011),
    ('Larkin Poe','larkin-poe','She''s a Self Made Man','shes-a-self-made-man','Self Made Man',2020),
    ('Marcus King','marcus-king','The Well','the-well','El Dorado',2020),
    ('Christone "Kingfish" Ingram','christone-kingfish-ingram','Fresh Out','fresh-out','Kingfish',2019),
    ('Samantha Fish','samantha-fish','Bulletproof','bulletproof','Kill or Be Kind',2019),
    ('Sinach','sinach','Way Maker','way-maker','Way Maker',2015),
    ('Pat Barrett','pat-barrett','Build My Life','build-my-life','Pat Barrett',2018),
    ('Phil Wickham','phil-wickham','House of the Lord','house-of-the-lord','Hymn of Heaven',2021),
    ('Matt Redman','matt-redman','10,000 Reasons (Bless the Lord)','10000-reasons','10,000 Reasons',2011),
    ('Hillsong Worship','hillsong-worship','Cornerstone','cornerstone','Cornerstone',2012),
    ('All Sons & Daughters','all-sons-and-daughters','Great Are You Lord','great-are-you-lord','All Sons & Daughters',2013),
    ('5 Seconds of Summer','5-seconds-of-summer','She Looks So Perfect','she-looks-so-perfect','5 Seconds of Summer',2014),
    ('5 Seconds of Summer','5-seconds-of-summer','Amnesia','amnesia','5 Seconds of Summer',2014),
    ('Jonas Brothers','jonas-brothers','Sucker','sucker','Happiness Begins',2019),
    ('Young the Giant','young-the-giant','Cough Syrup','cough-syrup','Young the Giant',2010),
    ('Young the Giant','young-the-giant','My Body','my-body','Young the Giant',2010),
    ('Bleachers','bleachers','I Wanna Get Better','i-wanna-get-better','Strange Desire',2014),
    ('The Neighbourhood','the-neighbourhood','Daddy Issues','daddy-issues','Wiped Out!',2015),
    ('Cavetown','cavetown','This Is Home','this-is-home','Cavetown',2015),
    ('Surf Curse','surf-curse','Freaks','freaks','Buds',2013),
    ('Turnover','turnover','Dizzy on the Comedown','dizzy-on-the-comedown','Peripheral Vision',2015),
    ('Movements','movements-band','Daylily','daylily','Feel Something',2017)
),
ins_artists as (
  insert into public.artists (name, slug, search_text, is_active)
  select distinct artist_name, artist_slug, artist_name, true from target
  on conflict (slug) do update set name = excluded.name, is_active = true
  returning id, slug
)
insert into public.songs (artist_id, title, slug, album, release_year, search_text, is_active)
select a.id, t.song_title, t.song_slug, t.album, t.release_year,
       concat_ws(' ', t.song_title, t.artist_name, t.album), true
from target t join ins_artists a on a.slug = t.artist_slug
on conflict (artist_id, slug) do update set
  title = excluded.title, album = excluded.album, release_year = excluded.release_year,
  is_active = true, updated_at = now();

delete from public.tone_profile_effects e where e.profile_id in (
  select p.id from public.song_tone_profiles p
  join public.songs s on s.id = p.song_id join public.artists a on a.id = s.artist_id
  join (values
    ('tedeschi-trucks-band','midnight-in-harlem'),('the-allman-brothers-band','soulshine'),
    ('blackberry-smoke','one-horse-town'),('whiskey-myers','broken-window-serenade'),
    ('larkin-poe','shes-a-self-made-man'),('marcus-king','the-well'),('christone-kingfish-ingram','fresh-out'),
    ('samantha-fish','bulletproof'),('sinach','way-maker'),('pat-barrett','build-my-life'),
    ('phil-wickham','house-of-the-lord'),('matt-redman','10000-reasons'),('hillsong-worship','cornerstone'),
    ('all-sons-and-daughters','great-are-you-lord'),('5-seconds-of-summer','she-looks-so-perfect'),
    ('5-seconds-of-summer','amnesia'),('jonas-brothers','sucker'),('young-the-giant','cough-syrup'),
    ('young-the-giant','my-body'),('bleachers','i-wanna-get-better'),('the-neighbourhood','daddy-issues'),
    ('cavetown','this-is-home'),('surf-curse','freaks'),('turnover','dizzy-on-the-comedown'),
    ('movements-band','daylily')
  ) as t(artist_slug, song_slug) on t.artist_slug = a.slug and t.song_slug = s.slug
  where p.mode = 'guitar'
);
delete from public.tone_profile_sources src where src.profile_id in (
  select p.id from public.song_tone_profiles p
  join public.songs s on s.id = p.song_id join public.artists a on a.id = s.artist_id
  join (values
    ('tedeschi-trucks-band','midnight-in-harlem'),('the-allman-brothers-band','soulshine'),
    ('blackberry-smoke','one-horse-town'),('whiskey-myers','broken-window-serenade'),
    ('larkin-poe','shes-a-self-made-man'),('marcus-king','the-well'),('christone-kingfish-ingram','fresh-out'),
    ('samantha-fish','bulletproof'),('sinach','way-maker'),('pat-barrett','build-my-life'),
    ('phil-wickham','house-of-the-lord'),('matt-redman','10000-reasons'),('hillsong-worship','cornerstone'),
    ('all-sons-and-daughters','great-are-you-lord'),('5-seconds-of-summer','she-looks-so-perfect'),
    ('5-seconds-of-summer','amnesia'),('jonas-brothers','sucker'),('young-the-giant','cough-syrup'),
    ('young-the-giant','my-body'),('bleachers','i-wanna-get-better'),('the-neighbourhood','daddy-issues'),
    ('cavetown','this-is-home'),('surf-curse','freaks'),('turnover','dizzy-on-the-comedown'),
    ('movements-band','daylily')
  ) as t(artist_slug, song_slug) on t.artist_slug = a.slug and t.song_slug = s.slug
  where p.mode = 'guitar'
);
delete from public.song_tone_profiles p where p.mode = 'guitar' and p.id in (
  select p2.id from public.song_tone_profiles p2
  join public.songs s on s.id = p2.song_id join public.artists a on a.id = s.artist_id
  join (values
    ('tedeschi-trucks-band','midnight-in-harlem'),('the-allman-brothers-band','soulshine'),
    ('blackberry-smoke','one-horse-town'),('whiskey-myers','broken-window-serenade'),
    ('larkin-poe','shes-a-self-made-man'),('marcus-king','the-well'),('christone-kingfish-ingram','fresh-out'),
    ('samantha-fish','bulletproof'),('sinach','way-maker'),('pat-barrett','build-my-life'),
    ('phil-wickham','house-of-the-lord'),('matt-redman','10000-reasons'),('hillsong-worship','cornerstone'),
    ('all-sons-and-daughters','great-are-you-lord'),('5-seconds-of-summer','she-looks-so-perfect'),
    ('5-seconds-of-summer','amnesia'),('jonas-brothers','sucker'),('young-the-giant','cough-syrup'),
    ('young-the-giant','my-body'),('bleachers','i-wanna-get-better'),('the-neighbourhood','daddy-issues'),
    ('cavetown','this-is-home'),('surf-curse','freaks'),('turnover','dizzy-on-the-comedown'),
    ('movements-band','daylily')
  ) as t(artist_slug, song_slug) on t.artist_slug = a.slug and t.song_slug = s.slug
);

insert into public.song_tone_profiles (
  song_id, song_title, artist_name, mode, part_type, part_label, tone_type,
  genre, tone_category, difficulty,
  original_guitar, original_amp, original_cab, original_pickup,
  original_effects, original_settings, adaptation_notes, playing_notes,
  source_summary, confidence, verification_status, search_text, is_public
)
select
  s.id, s.title, a.name, c.mode, c.part_type, c.part_label, c.tone_type,
  c.genre, c.tone_category, c.difficulty,
  c.original_guitar, c.original_amp, c.original_cab, c.original_pickup,
  c.original_effects, c.original_settings, c.adaptation_notes, c.playing_notes,
  c.source_summary, c.confidence, 'admin_verified',
  concat_ws(' ', s.title, a.name, c.part_label, c.tone_type, c.original_guitar, c.original_amp, 'researched verified tone'),
  true
from (
  values
    ('midnight-in-harlem','tedeschi-trucks-band','guitar','solo','slide ballad + solo','clean','blues rock','lead','advanced',
     'Gibson SG with slide (Derek Trucks)','Fender Super Reverb, warm clean','Fender 4x10 cab','neck pickup',
     '[]'::jsonb,'{"gain":3,"bass":5,"mids":6,"treble":5,"presence":4,"reverb":3,"delay":0,"master":7}'::jsonb,
     array['Derek''s open-E slide sermon — the modern era''s most beautiful solo, no pick, no pedals.','Warm clean Super Reverb; the slide sings sarod-like phrases.'],
     array['Open E tuning, fingers only, slide on the ring finger.','The solo builds like a sunrise over the bridge.'],
     'Studio recording, 2011. Derek''s open-E slide sermon.',79),
    ('soulshine','the-allman-brothers-band','guitar','riff','soul ballad + solo','clean','southern rock','lead','intermediate',
     'Gibson Les Paul (Warren Haynes)','Tube amp, warm soul-blues','Closed-back cab','neck pickup',
     '[]'::jsonb,'{"gain":4,"bass":5,"mids":6,"treble":5,"presence":4,"reverb":3,"delay":0,"master":7}'::jsonb,
     array['Haynes'' better-than-sunshine hymn — warm soul-blues comping and a testifying solo (gain 6).','Round singing warmth; it''s better than sunshine, it''s better than moonshine.'],
     array['Comp the gospel changes warmly.','The solo testifies — long tones, wide vibrato.'],
     'Studio recording, 1994. Haynes'' soulshine hymn.',78),
    ('one-horse-town','blackberry-smoke','guitar','riff','southern strums + leads','crunch','southern rock','rhythm','beginner',
     'Gibson Les Paul (Charlie Starr)','Tube amp, warm southern crunch','Closed-back cab','bridge humbucker',
     '[]'::jsonb,'{"gain":4,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":2,"delay":0,"master":7}'::jsonb,
     array['The small-town lament — warm southern crunch with Skynyrd bones and a lump in its throat.','Loose warm drive; I could''ve been born in a bigger town.'],
     array['Strum the story; fill with southern curls.','Play it like the city limits sign hurts.'],
     'Studio recording, 2012. The small-town lament.',75),
    ('broken-window-serenade','whiskey-myers','guitar','main','red-dirt ballad','acoustic','southern rock','rhythm','beginner',
     'Acoustic + electric (Cody Cannon band)','Acoustic with weeping electric','Open-back combo cab','neck pickup',
     '[]'::jsonb,'{"gain":0,"bass":5,"mids":5,"treble":6,"presence":5,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['The red-dirt tearjerker — bare acoustic with crying electric fills for the girl gone wrong.','Warm plain acoustic; hey little darling won''t you come home.'],
     array['Strum the verses honestly.','The electric fills mourn (gain 4, neck pickup).'],
     'Studio recording, 2011. The red-dirt tearjerker.',75),
    ('shes-a-self-made-man','larkin-poe','guitar','riff','slide-stomp riff','crunch','blues rock','rhythm','intermediate',
     'Electric + lap steel (Rebecca & Megan Lovell)','Tube amp, stomping slide crunch','Closed-back cab','bridge pickup',
     '[]'::jsonb,'{"gain":5,"bass":6,"mids":6,"treble":6,"presence":5,"reverb":2,"delay":0,"master":8}'::jsonb,
     array['The sister-slide stomp — Rebecca''s riff and Megan''s screaming lap steel.','Gritty stomping drive; the slide answers everything.'],
     array['Stomp the riff on the low strings.','Lap steel or slide answers — high and mean.'],
     'Studio recording, 2020. The sister-slide stomp.',75),
    ('the-well','marcus-king','guitar','riff','soul-rock riff + solo','crunch','blues rock','lead','intermediate',
     'Gibson ES-345 (Marcus King)','Tube amp, greasy soul-rock','Closed-back cab','neck pickup',
     '[]'::jsonb,'{"gain":5,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":2,"delay":0,"master":8}'::jsonb,
     array['The Dan Auerbach-produced burner — King''s greasy hollow-body stomp.','Warm gritty drive; the young king testifying.'],
     array['The riff grinds on the low strings.','The solo screams churchy — bend from the wrist.'],
     'Studio recording, 2020. The young king''s burner.',75),
    ('fresh-out','christone-kingfish-ingram','guitar','riff','modern blues + solo','clean','blues','lead','intermediate',
     'Fender Telecaster (Christone "Kingfish" Ingram)','Fender tube amp, biting clean','Fender combo cab','bridge pickup',
     '[]'::jsonb,'{"gain":4,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":3,"delay":0,"master":7}'::jsonb,
     array['The Clarksdale heir — Kingfish''s biting Delta-modern phrasing (with Buddy Guy guesting).','Bright pushed clean; the future of the blues, certified.'],
     array['The slow-burn phrases speak — space between them.','Bend like Buddy''s watching. He was.'],
     'Studio recording, 2019. The Clarksdale heir''s calling card.',75),
    ('bulletproof','samantha-fish','guitar','riff','cigar-box stomp','fuzz','blues rock','rhythm','intermediate',
     'Cigar-box guitar + electric (Samantha Fish)','Tube amp with fuzz stomp','Closed-back cab','bridge pickup',
     '[{"effect_type":"fuzz","effect_name":"gnarly fuzz","placement":"front","settings":{"gain":7,"tone":5,"level":6}}]'::jsonb,
     '{"gain":6,"bass":6,"mids":6,"treble":6,"presence":5,"reverb":2,"delay":0,"master":8}'::jsonb,
     array['The cigar-box gospel — Fish''s fuzzed four-string stomp riff.','Spitting fuzz drive; keep me bulletproof.'],
     array['The riff stomps on open tuning.','Play it mean; sing it meaner.'],
     'Studio recording, 2019. The cigar-box gospel stomp.',74),
    ('way-maker','sinach','guitar','main','worship swell','clean','worship','rhythm','beginner',
     'Clean electric (worship arrangement)','Clean amp with ambient swell','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"ambient shimmer","placement":"post_gain","settings":{"mix":5,"decay":7}},{"effect_type":"delay","effect_name":"dotted-eighth delay","placement":"post_gain","settings":{"time":4,"mix":3,"feedback":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":5,"presence":4,"reverb":5,"delay":3,"master":6}'::jsonb,
     array['The global declaration — the Nigerian-born anthem every US church now sings.','Wet worship swell; miracle worker, promise keeper.'],
     array['Pad the verses; build the bridge.','Even when I don''t see it — keep the swell working.'],
     'Studio recording, 2015. The global declaration.',74),
    ('build-my-life','pat-barrett','guitar','main','worship build','clean','worship','rhythm','beginner',
     'Acoustic + clean electric (Pat Barrett)','Clean amp with ambience','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"ambient reverb","placement":"post_gain","settings":{"mix":4,"decay":6}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":4,"delay":2,"master":6}'::jsonb,
     array['The foundation-builder — patient worship build to the surrender bridge.','Warm ambient clean; and I will build my life upon Your love.'],
     array['Simple progression, huge patience.','The bridge is the whole point — arrive there honestly.'],
     'Studio recording, 2018. The foundation-builder.',74),
    ('house-of-the-lord','phil-wickham','guitar','main','celebration strums','clean','worship','rhythm','beginner',
     'Acoustic + clean electric (Phil Wickham)','Clean amp, bright celebration','Open-back combo cab','bridge pickup',
     '[{"effect_type":"delay","effect_name":"dotted-eighth delay","placement":"post_gain","settings":{"time":4,"mix":3,"feedback":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":6,"presence":5,"reverb":3,"delay":3,"master":7}'::jsonb,
     array['The Sunday celebration — bright driving worship-pop with the shout-of-joy hook.','Crisp bright clean; there''s joy in the house of the Lord.'],
     array['Drive the strums with lift.','We shout out Your praise — literally, at the hook.'],
     'Studio recording, 2021. The Sunday celebration.',74),
    ('10000-reasons','matt-redman','guitar','main','hymn strums','acoustic','worship','rhythm','beginner',
     'Acoustic guitar (Matt Redman)','Acoustic — mic''d','No cab (acoustic)','n/a (acoustic)',
     '[]'::jsonb,'{"gain":0,"bass":5,"mids":5,"treble":6,"presence":5,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['The modern doxology — gentle acoustic under bless-the-Lord-oh-my-soul.','Warm open acoustic; sing like never before.'],
     array['Simple strums in worship time.','The sun comes up — so does the dynamic.'],
     'Studio recording, 2011. The modern doxology.',75),
    ('cornerstone','hillsong-worship','guitar','main','hymn build','clean','worship','rhythm','beginner',
     'Clean electric + acoustic (Hillsong)','Clean amp with ambience','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"ambient reverb","placement":"post_gain","settings":{"mix":4,"decay":6}},{"effect_type":"delay","effect_name":"dotted-eighth","placement":"post_gain","settings":{"time":4,"mix":3,"feedback":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":5,"presence":4,"reverb":4,"delay":3,"master":6}'::jsonb,
     array['The hymn reborn — My Hope Is Built recast as an ambient worship build.','Wet patient clean; Christ alone, cornerstone.'],
     array['Pad the hymn verses; lift the chorus.','Weak made strong — the dynamic arc is the sermon.'],
     'Studio recording, 2012. The hymn reborn.',74),
    ('great-are-you-lord','all-sons-and-daughters','guitar','main','folk-worship strums','acoustic','worship','rhythm','beginner',
     'Acoustic guitar (Leslie Jordan / David Leonard)','Acoustic — mic''d, folk intimacy','No cab (acoustic)','n/a (acoustic)',
     '[]'::jsonb,'{"gain":0,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['The it''s-Your-breath hymn — folk-duo warmth turned congregation standard.','Soft warm acoustic; we pour out our praise.'],
     array['Gentle strums in 6/8.','The bridge repeats until the room lifts — let it.'],
     'Studio recording, 2013. The folk-worship standard.',74),
    ('she-looks-so-perfect','5-seconds-of-summer','guitar','riff','main riff','distorted','pop punk','rhythm','beginner',
     'Gibson/Fender electric (Michael Clifford / Luke Hemmings)','Tube amp, arena pop-punk','Closed-back 4x12 cab','bridge humbucker',
     '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":1,"delay":0,"master":8}'::jsonb,
     array['The American Apparel anthem — arena pop-punk wall for the Tumblr generation.','Bright polished saturation; hey hey!'],
     array['Drive the chords; punch the heys.','Made pop-punk stadium-sized again.'],
     'Studio recording, 2014. The Tumblr-era anthem.',74),
    ('amnesia','5-seconds-of-summer','guitar','main','ballad strums','acoustic','pop punk','rhythm','beginner',
     'Acoustic guitar (5SOS)','Acoustic — mic''d with band swell','No cab (acoustic)','n/a (acoustic)',
     '[]'::jsonb,'{"gain":0,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['The wish-I-could-wake-up ballad — soft strums for every 2014 heartbreak.','Warm gentle acoustic; I wish that I could wake up with amnesia.'],
     array['Arpeggiate the verses; strum the chorus swell.','The bridge cracks — let your dynamics crack with it.'],
     'Studio recording, 2014. The amnesia ballad.',73),
    ('sucker','jonas-brothers','guitar','riff','funk-pop riff','clean','pop','rhythm','beginner',
     'Electric guitar (Nick Jonas / session)','Clean amp, funk-pop snap','Studio direct','bridge pickup',
     '[{"effect_type":"compressor","effect_name":"studio compression","placement":"front","settings":{"sustain":5,"level":5}}]'::jsonb,
     '{"gain":2,"bass":4,"mids":5,"treble":7,"presence":6,"reverb":1,"delay":0,"master":6}'::jsonb,
     array['The comeback smash — snapping funk-pop chips and the whistle hook.','Dry bright funk clean; I''m a sucker for you.'],
     array['Chip the funk pattern tight.','The groove does the courting.'],
     'Studio recording, 2019. The comeback funk-pop smash.',73),
    ('cough-syrup','young-the-giant','guitar','riff','main riff','clean','indie rock','rhythm','beginner',
     'Fender electric (Jacob Tilley / Eric Cannata)','Clean amp, liquid indie shimmer','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":3}},{"effect_type":"compressor","effect_name":"light compression","placement":"front","settings":{"sustain":4,"level":5}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":6,"presence":5,"reverb":3,"delay":1,"master":6}'::jsonb,
     array['The life''s-too-short shimmer (Glee re-immortalized it) — liquid clean figures under the ache.','Soft glassy clean; and so I run now to the things they said could restore me.'],
     array['The picked figure rolls liquid.','Down, down, down — but the tone floats.'],
     'Studio recording, 2010. The cough-syrup shimmer.',75),
    ('my-body','young-the-giant','guitar','riff','main riff','crunch','indie rock','rhythm','beginner',
     'Fender electric (Jacob Tilley)','Tube amp, driving indie crunch','Closed-back cab','bridge pickup',
     '[]'::jsonb,'{"gain":5,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":2,"delay":0,"master":8}'::jsonb,
     array['The tells-me-to-go anthem — driving festival crunch.','Bright punchy drive; my body tells me no, but I won''t quit.'],
     array['Drive the riff relentlessly.','''Cause I want more — so does the chorus.'],
     'Studio recording, 2010. The won''t-quit anthem.',74),
    ('i-wanna-get-better','bleachers','guitar','riff','maximalist riff','crunch','indie pop','rhythm','beginner',
     'Fender electric (Jack Antonoff)','Driven amp, maximalist pop','Studio direct','bridge pickup',
     '[{"effect_type":"compressor","effect_name":"pumping compression","placement":"front","settings":{"sustain":6,"level":6}}]'::jsonb,
     '{"gain":5,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":2,"delay":0,"master":8}'::jsonb,
     array['Antonoff''s therapy shout — pumping maximalist crunch under the piano hammer.','Compressed bright drive; I didn''t know I was lonely till I saw your face.'],
     array['Slam the chords with the piano loop.','I wanna get better — shout it, strum it.'],
     'Studio recording, 2014. Antonoff''s therapy shout.',74),
    ('daddy-issues','the-neighbourhood','guitar','riff','moody clean riff','clean','indie pop','rhythm','beginner',
     'Fender electric (Zach Abels)','Clean amp, midnight haze','Studio direct','neck pickup',
     '[{"effect_type":"reverb","effect_name":"dark reverb","placement":"post_gain","settings":{"mix":4}},{"effect_type":"chorus","effect_name":"soft chorus","placement":"post_gain","settings":{"rate":3,"depth":3,"mix":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":5,"presence":4,"reverb":4,"delay":1,"master":6}'::jsonb,
     array['The Wiped Out! slow-burn TikTok resurrected — hazy midnight clean.','Dark soft clean; go ahead and cry, little girl.'],
     array['The riff drifts on the beat.','Keep it 2 a.m. quiet.'],
     'Studio recording, 2015. The midnight slow-burn.',74),
    ('this-is-home','cavetown','guitar','main','bedroom fingerpicking','clean','bedroom pop','rhythm','beginner',
     'Electric guitar (Robin Skinner)','Clean DI, bedroom intimacy','Studio direct','neck pickup',
     '[{"effect_type":"compressor","effect_name":"soft compression","placement":"front","settings":{"sustain":4,"level":5}}]'::jsonb,
     '{"gain":1,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":2,"delay":0,"master":5}'::jsonb,
     array['The bedroom-pop hymn of belonging — soft picked clean recorded at desk distance.','Dry gentle clean; turn off your porcelain face.'],
     array['Pick the pattern small and close.','Often I am upset — the guitar isn''t.'],
     'Studio recording, 2015. The bedroom belonging hymn.',73),
    ('freaks','surf-curse','guitar','riff','surf-punk riff','crunch','surf indie','rhythm','beginner',
     'Fender Jazzmaster (Jacob Rubeck / Nick Rattigan)','Tube amp, wet surf-punk','Open-back cab','bridge pickup',
     '[{"effect_type":"reverb","effect_name":"drippy spring reverb","placement":"post_gain","settings":{"mix":5}}]'::jsonb,
     '{"gain":5,"bass":4,"mids":6,"treble":7,"presence":6,"reverb":5,"delay":0,"master":8}'::jsonb,
     array['The TikTok surf-punk anthem — wet driving riff for every outsider edit.','Reverb-soaked crunch; I am just a freak.'],
     array['Drive the riff with surf tremolo energy.','The scream section earns itself.'],
     'Studio recording, 2013. The outsider surf-punk anthem.',74),
    ('dizzy-on-the-comedown','turnover','guitar','riff','dream-emo shimmer','clean','dream pop','rhythm','beginner',
     'Fender Jazzmaster (Austin Getz / Eric Soucy)','Clean amp with chorus shimmer','Open-back combo cab','neck pickup',
     '[{"effect_type":"chorus","effect_name":"dream chorus","placement":"post_gain","settings":{"rate":3,"depth":4,"mix":5}},{"effect_type":"reverb","effect_name":"soft reverb","placement":"post_gain","settings":{"mix":4}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":4,"delay":1,"master":6}'::jsonb,
     array['The Peripheral Vision jewel — chorused dream-emo shimmer that launched a thousand Jazzmasters.','Glassy chorused clean; try not to think about it.'],
     array['The riff glides on the chorus wobble.','Soft attack; let the shimmer breathe.'],
     'Studio recording, 2015. The dream-emo jewel.',75),
    ('daylily','movements-band','guitar','riff','post-hardcore shimmer','clean','post-hardcore','rhythm','beginner',
     'Fender electric (Ira George)','Clean amp with bright shimmer','Closed-back cab','bridge pickup',
     '[{"effect_type":"reverb","effect_name":"bright reverb","placement":"post_gain","settings":{"mix":4}},{"effect_type":"delay","effect_name":"subtle delay","placement":"post_gain","settings":{"time":3,"mix":2,"feedback":2}}]'::jsonb,
     '{"gain":3,"bass":5,"mids":5,"treble":7,"presence":6,"reverb":4,"delay":2,"master":7}'::jsonb,
     array['The hope-song — bright shimmering figures under the spoken comfort.','Sparkling wet clean; it won''t always be this dark.'],
     array['The lead figure glimmers over the strums.','You will bloom again — so does the chorus.'],
     'Studio recording, 2017. The hope-song shimmer.',73)
) as c(
  song_slug, artist_slug, mode, part_type, part_label, tone_type, genre, tone_category, difficulty,
  original_guitar, original_amp, original_cab, original_pickup,
  original_effects, original_settings, adaptation_notes, playing_notes, source_summary, confidence
)
join public.artists a on a.slug = c.artist_slug
join public.songs s on s.artist_id = a.id and s.slug = c.song_slug;
