begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('electric_guitar', 'Ibanez', 'RG550', 'RG', true, 'Reissue of the original RG with Wizard neck and Edge tremolo.'),
  ('electric_guitar', 'Ibanez', 'RG565', 'RG', false, 'RG565 Genesis Collection reissue with HSH pickup layout and Edge trem.'),
  ('electric_guitar', 'Ibanez', 'RG370AHMZ', 'RG', false, 'RG370 with ash mahogany body and Edge Zero II tremolo.'),
  ('electric_guitar', 'Ibanez', 'RG421', 'RG', true, 'Hardtail RG with Quantum humbuckers and Wizard III neck.'),
  ('electric_guitar', 'Ibanez', 'RG421EX', 'RG', false, 'RG421 with EX finish options and Quantum humbuckers.'),
  ('electric_guitar', 'Ibanez', 'RG421MSP', 'RG', false, 'RG421 with multi sparkle painted finish.'),
  ('electric_guitar', 'Ibanez', 'RG450DX', 'RG', false, 'RG450DX with HSH pickups and Edge Zero II tremolo.'),
  ('electric_guitar', 'Ibanez', 'RG470AHM', 'RG', false, 'RG470 with ash mahogany body construction.'),
  ('electric_guitar', 'Ibanez', 'RG470DX', 'RG', false, 'RG470DX with V7 and V8 humbuckers and single-coil middle.'),
  ('electric_guitar', 'Ibanez', 'RG550XH', 'RG', false, 'Extended run 30 fret RG550 for extreme upper register playing.'),
  ('electric_guitar', 'Ibanez', 'RG652AHM Prestige', 'RG Prestige', true, 'Prestige RG652 with ash mahogany body and DiMarzio Fusion Edge pickups.'),
  ('electric_guitar', 'Ibanez', 'RG752AHM Prestige', 'RG Prestige', false, '7-string Prestige RG752 with ash mahogany body.'),
  ('electric_guitar', 'Ibanez', 'RG5170B Prestige', 'RG Prestige', false, 'Prestige RG5170 with mahogany body and DiMarzio Air Norton and Tone Zone.'),
  ('electric_guitar', 'Ibanez', 'RG5320C Prestige', 'RG Prestige', false, 'Prestige RG5320 with roasted maple neck and Fishman Fluence Modern pickups.'),
  ('electric_guitar', 'Ibanez', 'RGA42FM', 'RGA', false, 'RGA42 with flamed maple top and arched body.'),
  ('electric_guitar', 'Ibanez', 'RGA61AL Axion Label', 'RGA Axion Label', false, 'Axion Label RGA with ash body and Bare Knuckle Aftermath pickups.'),
  ('electric_guitar', 'Ibanez', 'RGD61AL Axion Label', 'RGD Axion Label', false, 'Axion Label RGD with 26.5 baritone scale and Fishman Fluence pickups.'),
  ('electric_guitar', 'Ibanez', 'RGD71ALMS Axion Label', 'RGD Axion Label', false, 'Axion Label RGD 7-string multi-scale with Fishman Fluence Modern pickups.'),
  ('electric_guitar', 'Ibanez', 'RGD3127 Prestige', 'RGD Prestige', false, 'Prestige RGD 7-string with 26.5 scale length and DiMarzio pickups.'),
  ('electric_guitar', 'Ibanez', 'RG7421', 'RG', false, '7-string RG with Quantum humbuckers and hardtail bridge.'),
  ('electric_guitar', 'Ibanez', 'RG8', 'RG', false, '8-string RG with fixed bridge and long 27 scale.'),
  ('electric_guitar', 'Ibanez', 'RGA8', 'RGA', false, '8-string RGA with arched body and fixed bridge.'),
  ('electric_guitar', 'Ibanez', 'S521', 'S', false, 'S series with slim mahogany body and Quantum humbuckers.'),
  ('electric_guitar', 'Ibanez', 'S561', 'S', false, 'S series with mahogany body and Quantum humbuckers.'),
  ('electric_guitar', 'Ibanez', 'S670QM', 'S', false, 'S670 with quilted maple top and Sat Pro II tremolo.'),
  ('electric_guitar', 'Ibanez', 'S1070PBZ Premium', 'S Premium', false, 'Premium S1070 with poplar burl top and DiMarzio Fusion Edge pickups.'),
  ('electric_guitar', 'Ibanez', 'S5470F Prestige', 'S Prestige', false, 'Prestige S5470 with figured maple top and Edge Zero tremolo.'),
  ('electric_guitar', 'Ibanez', 'SA260FM', 'SA', false, 'SA style with figured maple top and HSS pickups.'),
  ('electric_guitar', 'Ibanez', 'AZ2204', 'AZ Prestige', true, 'Prestige AZ2204 with Seymour Duncan Hyperion pickups.'),
  ('electric_guitar', 'Ibanez', 'AZ2402', 'AZ Prestige', true, 'Prestige AZ2402 with dual Hyperion humbuckers.'),
  ('electric_guitar', 'Ibanez', 'AZ2407F', 'AZ Prestige', false, 'Prestige AZ 7-string with figured top.'),
  ('electric_guitar', 'Ibanez', 'AZ242PBG Premium', 'AZ Premium', false, 'Premium AZ242 with poplar burl top and Seymour Duncan pickups.'),
  ('electric_guitar', 'Ibanez', 'AZ2204N', 'AZ Prestige', false, 'Prestige AZ2204 with natural finish and HSS pickups.'),
  ('electric_guitar', 'Ibanez', 'AZS2200', 'AZS Prestige', false, 'Prestige AZS with hardtail bridge and SSS pickup layout.'),
  ('electric_guitar', 'Ibanez', 'AZS2209', 'AZS Prestige', false, 'Prestige AZS with HSS pickup layout.'),
  ('electric_guitar', 'Ibanez', 'AZES40', 'AZ Standard', true, 'AZ Essentials with roasted maple neck and Essential pickups.'),
  ('electric_guitar', 'Ibanez', 'AZES31', 'AZ Standard', false, 'AZ Essentials 31 with dyna-MIX9 switching system.'),
  ('electric_guitar', 'Ibanez', 'AZ226PB Premium', 'AZ Premium', false, 'Premium AZ226 with poplar burl top.'),
  ('electric_guitar', 'Ibanez', 'GRX40', 'GIO', false, 'Beginner GIO GRX40 with HSS pickup layout.'),
  ('electric_guitar', 'Ibanez', 'GRG121DX', 'GIO', false, 'Beginner GIO GRG121 with dual humbuckers.'),
  ('electric_guitar', 'Ibanez', 'GRG170DX', 'GIO', true, 'Beginner GIO GRG170 with HSH pickup layout.'),
  ('electric_guitar', 'Ibanez', 'GRGM21 miKro', 'GIO miKro', false, '3/4 scale GIO miKro for smaller players.'),
  ('electric_guitar', 'Ibanez', 'GRX70QA', 'GIO', false, 'Beginner GIO GRX70 with quilted art top.'),
  ('electric_guitar', 'Ibanez', 'GRGA120', 'GIO', false, 'Beginner GIO GRGA with dual humbuckers and arched top.'),
  ('electric_guitar', 'Ibanez', 'JEM7V', 'JEM', true, 'Steve Vai JEM7V signature with DiMarzio Evolution pickups and monkey grip.'),
  ('electric_guitar', 'Ibanez', 'JEM77', 'JEM', false, 'Steve Vai JEM77 signature with distinct floral pattern finish.'),
  ('electric_guitar', 'Ibanez', 'JEM77P', 'JEM', false, 'Premium JEM77P Steve Vai model with DiMarzio pickups.'),
  ('electric_guitar', 'Ibanez', 'JEMJR', 'JEM', true, 'Affordable JEM Junior signature Steve Vai model.'),
  ('electric_guitar', 'Ibanez', 'PIA3761', 'PIA', true, 'Steve Vai PIA (Paradise In Art) signature with DiMarzio UtoPIA pickups.'),
  ('electric_guitar', 'Ibanez', 'PIA3761C', 'PIA', false, 'PIA3761C custom color Vai signature.'),
  ('electric_guitar', 'Ibanez', 'JS240PS', 'JS', false, 'Joe Satriani JS240 with sparkle finish.'),
  ('electric_guitar', 'Ibanez', 'JS1000', 'JS', false, 'Joe Satriani JS1000 with DiMarzio pickups and Edge Pro tremolo.'),
  ('electric_guitar', 'Ibanez', 'JS2450', 'JS', false, 'Joe Satriani JS2450 with muscle car finish and Sustainiac pickup.'),
  ('electric_guitar', 'Ibanez', 'JS3CR', 'JS', false, 'Joe Satriani JS3CR chrome finish signature.'),
  ('electric_guitar', 'Ibanez', 'JS100', 'JS', false, 'Entry level Joe Satriani JS100 signature.'),
  ('electric_guitar', 'Ibanez', 'JS140M', 'JS', false, 'Joe Satriani JS140M with matte finish.'),
  ('electric_guitar', 'Ibanez', 'Q54', 'Q', false, 'Q Series headless Q54 with Fishman Fluence pickups.'),
  ('electric_guitar', 'Ibanez', 'Q52', 'Q', false, 'Q Series headless Q52 with dual humbuckers.'),
  ('electric_guitar', 'Ibanez', 'Q547', 'Q', false, 'Q Series headless 7-string Q547.'),
  ('electric_guitar', 'Ibanez', 'QX527PB', 'QX Premium', false, 'Premium QX 7-string with poplar burl top.'),
  ('electric_guitar', 'Ibanez', 'QX52', 'QX', false, 'QX Series with H-S-H style pickups and headless design.'),
  ('electric_guitar', 'Ibanez', 'AF75', 'Artcore', true, 'Artcore AF75 hollowbody with dual humbuckers.'),
  ('electric_guitar', 'Ibanez', 'AF95', 'Artcore', false, 'Artcore Expressionist AF95 with figured maple body.'),
  ('electric_guitar', 'Ibanez', 'AS53', 'Artcore', true, 'Artcore AS53 semi hollow with dual Infinity R humbuckers.'),
  ('electric_guitar', 'Ibanez', 'AS73', 'Artcore', true, 'Artcore AS73 semi hollow with dual Classic Elite humbuckers.'),
  ('electric_guitar', 'Ibanez', 'AS93FM', 'Artcore Expressionist', false, 'Artcore Expressionist AS93 with figured maple top.'),
  ('electric_guitar', 'Ibanez', 'AG75G', 'Artcore', false, 'Artcore AG75 grand size hollowbody with dual humbuckers.'),
  ('electric_guitar', 'Ibanez', 'AF200LTD', 'Artcore', false, 'Limited Artcore AF200 with premium appointments.'),
  ('electric_guitar', 'Ibanez', 'ARZ400', 'ARZ', false, 'ARZ400 single cutaway with dual humbuckers.'),
  ('electric_guitar', 'Ibanez', 'AR420', 'AR', false, 'AR420 single cutaway with mahogany body and Super 58 pickups.'),
  ('electric_guitar', 'Ibanez', 'PS120 Paul Stanley', 'Iceman Signature', false, 'Paul Stanley PS120 Iceman signature.'),
  ('electric_guitar', 'Ibanez', 'FR400', 'FR', false, 'FR400 with hardtail bridge and dual humbuckers.'),
  ('electric_guitar', 'Ibanez', 'FR2020', 'FR Prestige', false, 'Prestige FR2020 with mahogany body.'),
  ('electric_guitar', 'Ibanez', 'TM302', 'Talman', false, 'Talman TM302 offset with dual humbuckers.'),
  ('electric_guitar', 'Ibanez', 'TM303', 'Talman', false, 'Talman TM303 with HSS pickup layout.'),
  ('electric_guitar', 'Jackson', 'JS22 Dinky', 'JS Series', true, 'Beginner JS22 Dinky with dual high output humbuckers.'),
  ('electric_guitar', 'Jackson', 'JS22-7 Dinky', 'JS Series', false, '7-string JS22 Dinky with dual humbuckers.'),
  ('electric_guitar', 'Jackson', 'JS32 Dinky', 'JS Series', true, 'JS32 Dinky with compound radius fretboard and Floyd Rose special.'),
  ('electric_guitar', 'Jackson', 'JS32 Dinky Arch Top', 'JS Series', false, 'JS32 Dinky with arched top body.'),
  ('electric_guitar', 'Jackson', 'JS32-7 Dinky', 'JS Series', false, '7-string JS32 Dinky with dual humbuckers.'),
  ('electric_guitar', 'Jackson', 'JS32 Rhoads', 'JS Series', false, 'JS32 Rhoads V shape with dual humbuckers.'),
  ('electric_guitar', 'Jackson', 'JS32 King V', 'JS Series', false, 'JS32 King V with dual humbuckers.'),
  ('electric_guitar', 'Jackson', 'JS32 Kelly', 'JS Series', false, 'JS32 Kelly with dual humbuckers.'),
  ('electric_guitar', 'Jackson', 'JS32 Warrior', 'JS Series', false, 'JS32 Warrior with unique body shape and humbuckers.'),
  ('electric_guitar', 'Jackson', 'JS32Q Dinky', 'JS Series', false, 'JS32 Dinky with quilted maple top.'),
  ('electric_guitar', 'Jackson', 'X Series Soloist SLX DX', 'X Series', true, 'X Series Soloist SLX DX with Duncan Designed pickups and Floyd Rose.'),
  ('electric_guitar', 'Jackson', 'X Series Soloist SL3X DX', 'X Series', false, 'X Series Soloist SL3X DX with reverse headstock.'),
  ('electric_guitar', 'Jackson', 'X Series Dinky DK2X', 'X Series', false, 'X Series Dinky DK2X with Duncan Designed pickups.'),
  ('electric_guitar', 'Jackson', 'X Series Dinky DK3XR HSS', 'X Series', false, 'X Series Dinky DK3XR with HSS pickup layout.'),
  ('electric_guitar', 'Jackson', 'X Series Rhoads RRX24', 'X Series', true, 'X Series Rhoads RRX24 with Duncan Designed pickups and Floyd Rose.'),
  ('electric_guitar', 'Jackson', 'X Series Rhoads RRX24-7', 'X Series', false, '7-string X Series Rhoads RRX24.'),
  ('electric_guitar', 'Jackson', 'X Series Kelly KEX', 'X Series', false, 'X Series Kelly KEX with Duncan Designed humbuckers.'),
  ('electric_guitar', 'Jackson', 'X Series King V KVX', 'X Series', false, 'X Series King V KVX with Duncan Designed humbuckers.'),
  ('electric_guitar', 'Jackson', 'X Series Warrior WRX24', 'X Series', false, 'X Series Warrior WRX24 with Duncan Designed pickups.'),
  ('electric_guitar', 'Jackson', 'Pro Series Soloist SL2', 'Pro Series', true, 'Pro Series Soloist SL2 with Seymour Duncan JB TB4 and Jazz SH2N.'),
  ('electric_guitar', 'Jackson', 'Pro Series Soloist SL3', 'Pro Series', false, 'Pro Series Soloist SL3 with HSS pickup layout.'),
  ('electric_guitar', 'Jackson', 'Pro Series Dinky DK2', 'Pro Series', true, 'Pro Series Dinky DK2 with Seymour Duncan pickups.'),
  ('electric_guitar', 'Jackson', 'Pro Series Dinky DK Modern', 'Pro Series', false, 'Pro Series Dinky Modern with Fishman Fluence Modern pickups.'),
  ('electric_guitar', 'Jackson', 'Pro Series Rhoads RR24', 'Pro Series', false, 'Pro Series Rhoads RR24 with Seymour Duncan pickups.'),
  ('electric_guitar', 'Jackson', 'Pro Series King V KV', 'Pro Series', false, 'Pro Series King V with Seymour Duncan pickups.'),
  ('electric_guitar', 'Jackson', 'Pro Plus Series Soloist SLA3', 'Pro Plus', false, 'Pro Plus Soloist SLA3 with Seymour Duncan pickups and roasted maple neck.'),
  ('electric_guitar', 'Jackson', 'Pro Plus Series Dinky MDK HT7', 'Pro Plus', false, 'Pro Plus Dinky 7-string hardtail with Seymour Duncan pickups.'),
  ('electric_guitar', 'Jackson', 'Pro Plus Series Soloist SLA3Q', 'Pro Plus', false, 'Pro Plus Soloist SLA3 with quilted maple top.'),
  ('electric_guitar', 'Jackson', 'MJ Series Dinky DKR', 'MJ Series', false, 'Made in Japan MJ Series Dinky with premium appointments.'),
  ('electric_guitar', 'Jackson', 'MJ Series Rhoads RR24MG', 'MJ Series', false, 'Made in Japan MJ Series Rhoads with glow finish.'),
  ('electric_guitar', 'Jackson', 'MJ Series Soloist SL2', 'MJ Series', false, 'Made in Japan MJ Series Soloist SL2.'),
  ('electric_guitar', 'Jackson', 'American Series Soloist SL3', 'American Series', false, 'American Series USA Soloist SL3 with Seymour Duncan pickups.'),
  ('electric_guitar', 'Jackson', 'American Series Virtuoso', 'American Series', false, 'American Series Virtuoso USA with premium appointments.'),
  ('electric_guitar', 'Jackson', 'USA Signature Misha Mansoor Juggernaut HT6', 'USA Signature', false, 'Misha Mansoor USA Juggernaut HT6 with Bare Knuckle Juggernaut pickups.'),
  ('electric_guitar', 'Jackson', 'USA Signature Misha Mansoor Juggernaut HT7', 'USA Signature', false, 'Misha Mansoor USA Juggernaut HT7 7-string.'),
  ('electric_guitar', 'Jackson', 'Pro Series Signature Misha Mansoor Juggernaut HT6FM', 'Pro Series Signature', false, 'Pro Series Misha Mansoor Juggernaut HT6 with figured maple top.'),
  ('electric_guitar', 'Jackson', 'Pro Series Signature Misha Mansoor Juggernaut HT7FM', 'Pro Series Signature', false, 'Pro Series Misha Mansoor Juggernaut HT7 7-string.'),
  ('electric_guitar', 'Jackson', 'X Series Signature Marty Friedman MF-1', 'X Series Signature', false, 'Marty Friedman MF-1 X Series signature with Kelly style body.'),
  ('electric_guitar', 'Jackson', 'X Series Signature Phil Collen PC1', 'X Series Signature', false, 'Phil Collen PC1 X Series with dual humbuckers and single-coil middle.'),
  ('electric_guitar', 'Jackson', 'USA Signature Phil Collen PC1', 'USA Signature', false, 'Phil Collen USA PC1 signature with Sustainer system.'),
  ('electric_guitar', 'Jackson', 'X Series Signature Corey Beaulieu KV6', 'X Series Signature', false, 'Corey Beaulieu KV6 X Series King V signature.'),
  ('electric_guitar', 'Jackson', 'X Series Signature Corey Beaulieu KV7', 'X Series Signature', false, 'Corey Beaulieu KV7 X Series 7-string King V.'),
  ('electric_guitar', 'Jackson', 'Pro Series Signature Jeff Loomis Soloist SL7', 'Pro Series Signature', false, 'Jeff Loomis Pro Series 7-string Soloist.'),
  ('electric_guitar', 'Jackson', 'USA Signature Jeff Loomis Soloist SL7', 'USA Signature', false, 'Jeff Loomis USA Signature 7-string Soloist.'),
  ('electric_guitar', 'Jackson', 'X Series Signature Chris Broderick Soloist 6', 'X Series Signature', false, 'Chris Broderick 6-string Soloist X Series signature.'),
  ('electric_guitar', 'Jackson', 'X Series Signature Chris Broderick Soloist 7', 'X Series Signature', false, 'Chris Broderick 7-string Soloist X Series signature.'),
  ('electric_guitar', 'Jackson', 'Pro Series Signature Chris Broderick Soloist 6', 'Pro Series Signature', false, 'Chris Broderick Pro Series 6-string Soloist.'),
  ('electric_guitar', 'Jackson', 'Pro Series Signature Chris Broderick Soloist 7', 'Pro Series Signature', false, 'Chris Broderick Pro Series 7-string Soloist.'),
  ('electric_guitar', 'Jackson', 'Pro Series Signature Andreas Kisser Soloist', 'Pro Series Signature', false, 'Andreas Kisser Pro Series Soloist signature.'),
  ('electric_guitar', 'Jackson', 'X Series Signature Brandon Ellis Kelly KEXQ', 'X Series Signature', false, 'Brandon Ellis Kelly X Series signature with quilted maple top.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK22 SSS 2PT', 'Pro-Mod DK', true, 'Pro-Mod DK22 Strat style with three Seymour Duncan single-coils.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK24 HH FR M', 'Pro-Mod DK', true, 'Pro-Mod DK24 with dual Seymour Duncan humbuckers and Floyd Rose.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK24 HH HT E', 'Pro-Mod DK', false, 'Pro-Mod DK24 with dual humbuckers, hardtail and ebony board.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK24 HH FR E', 'Pro-Mod DK', false, 'Pro-Mod DK24 with dual humbuckers, Floyd Rose and ebony board.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK24 HSH 2PT', 'Pro-Mod DK', false, 'Pro-Mod DK24 with HSH pickup layout and 2-point tremolo.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK24 HSH FR', 'Pro-Mod DK', false, 'Pro-Mod DK24 with HSH pickups and Floyd Rose tremolo.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK24 HSS 2PT M', 'Pro-Mod DK', false, 'Pro-Mod DK24 with HSS pickup layout and maple board.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK24 HSS 2PT E', 'Pro-Mod DK', false, 'Pro-Mod DK24 with HSS pickup layout and ebony board.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK24-7 HH 2PT', 'Pro-Mod DK', false, '7-string Pro-Mod DK24 with dual humbuckers.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK Ash', 'Pro-Mod DK', false, 'Pro-Mod DK with swamp ash body and Duncan pickups.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod San Dimas Style 1 HH FR', 'Pro-Mod San Dimas', true, 'Pro-Mod San Dimas Style 1 with dual humbuckers and Floyd Rose.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod San Dimas Style 1 HH HT', 'Pro-Mod San Dimas', false, 'Pro-Mod San Dimas Style 1 with dual humbuckers and hardtail bridge.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod San Dimas Style 1 HSS FR', 'Pro-Mod San Dimas', false, 'Pro-Mod San Dimas Style 1 with HSS pickups and Floyd Rose.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod San Dimas Style 1 HSS HT', 'Pro-Mod San Dimas', false, 'Pro-Mod San Dimas Style 1 with HSS pickups and hardtail.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod San Dimas Style 1 HH E', 'Pro-Mod San Dimas', false, 'Pro-Mod San Dimas Style 1 with dual humbuckers and ebony board.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod San Dimas Style 2 HH FR', 'Pro-Mod San Dimas', false, 'Pro-Mod San Dimas Style 2 Tele style with dual humbuckers.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod So-Cal Style 1 HH FR', 'Pro-Mod So-Cal', true, 'Pro-Mod So-Cal Style 1 with dual humbuckers and Floyd Rose.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod So-Cal Style 1 HSS FR M', 'Pro-Mod So-Cal', false, 'Pro-Mod So-Cal Style 1 with HSS pickups, Floyd Rose and maple board.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod So-Cal Style 1 HSS FR E', 'Pro-Mod So-Cal', false, 'Pro-Mod So-Cal Style 1 with HSS pickups, Floyd Rose and ebony board.'),
  ('electric_guitar', 'Charvel', 'MJ San Dimas SD24 CM', 'MJ Series', true, 'Made in Japan MJ San Dimas with caramelized maple neck.'),
  ('electric_guitar', 'Charvel', 'MJ San Dimas SD24 HT', 'MJ Series', false, 'Made in Japan MJ San Dimas with hardtail bridge.'),
  ('electric_guitar', 'Charvel', 'MJ DK24 HSH 2PT', 'MJ Series', false, 'Made in Japan MJ DK24 with HSH pickup layout.'),
  ('electric_guitar', 'Charvel', 'MJ DK24 HH 2PT', 'MJ Series', false, 'Made in Japan MJ DK24 with dual humbuckers.'),
  ('electric_guitar', 'Charvel', 'USA Select DK24 HH 2PT', 'USA Select', false, 'USA Select DK24 with premium USA construction and Duncan pickups.'),
  ('electric_guitar', 'Charvel', 'USA Select San Dimas Style 1 HSS FR', 'USA Select', false, 'USA Select San Dimas Style 1 with premium construction.'),
  ('electric_guitar', 'Charvel', 'USA Signature Guthrie Govan HSH Caramelized Ash', 'USA Signature', false, 'Guthrie Govan USA signature with caramelized ash body.'),
  ('electric_guitar', 'Charvel', 'USA Signature Guthrie Govan HSH Flame Maple', 'USA Signature', false, 'Guthrie Govan USA signature with flamed maple top.'),
  ('electric_guitar', 'Charvel', 'MJ San Dimas SD24 CM Guthrie Govan Signature', 'MJ Signature', false, 'Made in Japan MJ Guthrie Govan signature with caramelized maple neck.'),
  ('electric_guitar', 'Charvel', 'USA Signature Warren DeMartini San Dimas', 'USA Signature', false, 'Warren DeMartini USA San Dimas signature.'),
  ('electric_guitar', 'Charvel', 'USA Signature Joe Duplantier San Dimas Style 2', 'USA Signature', false, 'Joe Duplantier USA San Dimas Style 2 signature with EMG pickups.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK24-7 Angel Vivaldi', 'Pro-Mod Signature', false, 'Angel Vivaldi Pro-Mod DK24-7 signature with Fishman Fluence pickups.'),
  ('electric_guitar', 'Charvel', 'Henrik Danhage Signature Pro-Mod Limited Edition', 'Pro-Mod Signature', false, 'Henrik Danhage limited edition Pro-Mod signature.'),
  ('electric_guitar', 'Charvel', 'Marco Sfogli Signature Pro-Mod So-Cal Style 1', 'Pro-Mod Signature', false, 'Marco Sfogli Pro-Mod So-Cal signature.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
