begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('guitar_amp', 'Fender', 'Champion 20', 'Champion', true, 'Compact 20 watt modeling combo with 17 amp voices and built in effects.'),
  ('guitar_amp', 'Fender', 'Champion 40', 'Champion', true, '40 watt modeling combo with dual channels and built in effects.'),
  ('guitar_amp', 'Fender', 'Champion 50XL', 'Champion', false, '50 watt modeling combo with 12 amp models and effects.'),
  ('guitar_amp', 'Fender', 'Champion 100', 'Champion', false, '100 watt modeling combo with dual 12 inch speakers.'),
  ('guitar_amp', 'Fender', 'Mustang LT25', 'Mustang LT', true, 'Modeling combo with 30 preset amps and USB recording.'),
  ('guitar_amp', 'Fender', 'Mustang LT40S', 'Mustang LT', false, '40 watt Mustang LT with speaker sim output.'),
  ('guitar_amp', 'Fender', 'Mustang GTX50', 'Mustang GTX', true, '50 watt WiFi enabled modeling combo with tone cloud.'),
  ('guitar_amp', 'Fender', 'Mustang GTX100', 'Mustang GTX', false, '100 watt WiFi enabled Mustang GTX combo.'),
  ('guitar_amp', 'Fender', 'Mustang Micro', 'Mustang Micro', true, 'Portable headphone amp with amp models and effects.'),
  ('guitar_amp', 'Fender', 'Mustang Micro Plus', 'Mustang Micro', false, 'Updated Mustang Micro Plus with expanded features.'),
  ('guitar_amp', 'Fender', 'Tone Master Twin Reverb', 'Tone Master', true, 'Digital recreation of the 65 Twin Reverb with attenuator outputs.'),
  ('guitar_amp', 'Fender', 'Tone Master Princeton Reverb', 'Tone Master', true, 'Digital recreation of the 65 Princeton Reverb.'),
  ('guitar_amp', 'Fender', 'Tone Master Super Reverb', 'Tone Master', false, 'Digital recreation of the Super Reverb with 4x10 speaker configuration.'),
  ('guitar_amp', 'Fender', 'Tone Master Pro', 'Tone Master', false, 'Flagship modeling floor unit with Tone Master processing.'),
  ('guitar_amp', 'Fender', '65 Twin Reverb', '65 Series', true, 'Vintage voiced 65 Twin Reverb tube combo with dual 12 inch speakers.'),
  ('guitar_amp', 'Fender', '65 Deluxe Reverb', '65 Series', true, 'Vintage voiced 65 Deluxe Reverb 22 watt tube combo.'),
  ('guitar_amp', 'Fender', '65 Princeton Reverb', '65 Series', true, 'Vintage voiced 65 Princeton Reverb 12 watt tube combo.'),
  ('guitar_amp', 'Fender', '64 Custom Deluxe Reverb', '64 Custom', false, 'Custom Shop 64 Deluxe Reverb with hand wired construction.'),
  ('guitar_amp', 'Fender', '64 Custom Princeton Reverb', '64 Custom', false, 'Custom Shop 64 Princeton Reverb.'),
  ('guitar_amp', 'Fender', '68 Custom Deluxe Reverb', '68 Custom', false, '68 Custom Deluxe Reverb with modified vibrato circuit.'),
  ('guitar_amp', 'Fender', '68 Custom Princeton Reverb', '68 Custom', false, '68 Custom Princeton Reverb with silverface style.'),
  ('guitar_amp', 'Fender', '68 Custom Twin Reverb', '68 Custom', false, '68 Custom Twin Reverb with silverface style circuit.'),
  ('guitar_amp', 'Fender', '68 Custom Vibro Champ Reverb', '68 Custom', false, '68 Custom Vibro Champ Reverb 5 watt combo.'),
  ('guitar_amp', 'Fender', '57 Custom Champ', '57 Custom', false, 'Custom Shop 57 Champ with hand wired construction.'),
  ('guitar_amp', 'Fender', '57 Custom Deluxe', '57 Custom', false, 'Custom Shop 57 tweed Deluxe with hand wired construction.'),
  ('guitar_amp', 'Fender', '57 Custom Twin-Amp', '57 Custom', false, 'Custom Shop 57 tweed Twin-Amp with hand wired construction.'),
  ('guitar_amp', 'Fender', 'Blues Junior IV', 'Blues Junior', true, 'Compact 15 watt tube combo with warm midrange and spring reverb.'),
  ('guitar_amp', 'Fender', 'Blues Deluxe Reissue', 'Blues', false, '40 watt tweed style tube combo with spring reverb.'),
  ('guitar_amp', 'Fender', 'Hot Rod Deluxe IV', 'Hot Rod', true, '40 watt three channel tube combo with spring reverb.'),
  ('guitar_amp', 'Fender', 'Hot Rod DeVille 212 IV', 'Hot Rod', false, '60 watt three channel tube combo with dual 12 inch speakers.'),
  ('guitar_amp', 'Fender', 'Pro Junior IV', 'Pro Junior', false, '15 watt single channel tube combo.'),
  ('guitar_amp', 'Fender', 'Super-Sonic 22', 'Super-Sonic', false, '22 watt hand wired combo with clean and burn channels.'),
  ('guitar_amp', 'Fender', 'Bassbreaker 15', 'Bassbreaker', false, '15 watt tube combo with vintage voicing.'),
  ('guitar_amp', 'Fender', 'Bassbreaker 30R', 'Bassbreaker', false, '30 watt Bassbreaker with reverb.'),
  ('guitar_amp', 'Fender', 'Bassbreaker 007', 'Bassbreaker', false, '7 watt tube combo for bedroom volume tones.'),
  ('guitar_amp', 'Fender', 'Acoustasonic 40', 'Acoustasonic', false, '40 watt acoustic amp with dual channels.'),
  ('guitar_amp', 'Fender', 'Acoustasonic 90', 'Acoustasonic', false, '90 watt acoustic amp with feedback control.'),
  ('guitar_amp', 'Fender', 'Frontman 10G', 'Frontman', false, 'Entry level 10 watt practice amp with clean and drive.'),
  ('guitar_amp', 'Fender', 'Frontman 20G', 'Frontman', false, '20 watt Frontman practice amp with dual channels.'),
  ('guitar_amp', 'Fender', 'Vibro-King', 'Vibro-King', false, 'Custom Shop 60 watt tube combo with tremolo and reverb.'),
  ('guitar_amp', 'Marshall', 'DSL1CR', 'DSL', false, '1 watt DSL combo with power scaling and reverb.'),
  ('guitar_amp', 'Marshall', 'DSL1HR', 'DSL', false, '1 watt DSL head with power scaling.'),
  ('guitar_amp', 'Marshall', 'DSL5CR', 'DSL', false, '5 watt DSL combo with power scaling and reverb.'),
  ('guitar_amp', 'Marshall', 'DSL20CR', 'DSL', true, '20 watt DSL combo with two channels and reverb.'),
  ('guitar_amp', 'Marshall', 'DSL20HR', 'DSL', false, '20 watt DSL head with two channels.'),
  ('guitar_amp', 'Marshall', 'DSL100HR', 'DSL', false, '100 watt DSL head with two channels and effects loop.'),
  ('guitar_amp', 'Marshall', 'JVM205C', 'JVM', false, '50 watt JVM 2-channel combo.'),
  ('guitar_amp', 'Marshall', 'JVM205H', 'JVM', false, '50 watt JVM 2-channel head.'),
  ('guitar_amp', 'Marshall', 'JVM210C', 'JVM', false, '100 watt JVM 2-channel combo.'),
  ('guitar_amp', 'Marshall', 'JVM210H', 'JVM', false, '100 watt JVM 2-channel head.'),
  ('guitar_amp', 'Marshall', 'JVM410C', 'JVM', false, '100 watt 4-channel JVM combo.'),
  ('guitar_amp', 'Marshall', 'Origin 20C', 'Origin', true, '20 watt Origin combo with Tilt and Boost controls.'),
  ('guitar_amp', 'Marshall', 'Origin 20H', 'Origin', false, '20 watt Origin head with Tilt and Boost controls.'),
  ('guitar_amp', 'Marshall', 'Origin 50C', 'Origin', false, '50 watt Origin combo with EL34 tubes.'),
  ('guitar_amp', 'Marshall', 'Origin 50H', 'Origin', false, '50 watt Origin head.'),
  ('guitar_amp', 'Marshall', 'SV20C Studio Vintage', 'Studio', false, 'Studio Vintage 20 watt combo based on the 1959SLP.'),
  ('guitar_amp', 'Marshall', 'SV20H Studio Vintage', 'Studio', true, 'Studio Vintage 20 watt head based on the 1959SLP Plexi.'),
  ('guitar_amp', 'Marshall', 'SC20C Studio Classic', 'Studio', false, 'Studio Classic 20 watt combo based on the JCM800 2203.'),
  ('guitar_amp', 'Marshall', 'SC20H Studio Classic', 'Studio', true, 'Studio Classic 20 watt head based on the JCM800.'),
  ('guitar_amp', 'Marshall', 'ST20C Studio JTM', 'Studio', false, 'Studio JTM 20 watt combo based on the JTM45.'),
  ('guitar_amp', 'Marshall', 'ST20H Studio JTM', 'Studio', false, 'Studio JTM 20 watt head based on the JTM45.'),
  ('guitar_amp', 'Marshall', '2525C Mini Jubilee', 'Mini Silver Jubilee', false, 'Mini Silver Jubilee 20 watt combo.'),
  ('guitar_amp', 'Marshall', '2525H Mini Jubilee', 'Mini Silver Jubilee', false, 'Mini Silver Jubilee 20 watt head.'),
  ('guitar_amp', 'Marshall', 'MG10', 'MG', false, 'Entry level 10 watt practice amp.'),
  ('guitar_amp', 'Marshall', 'MG15', 'MG', false, '15 watt MG practice combo.'),
  ('guitar_amp', 'Marshall', 'MG15GFX', 'MG', false, '15 watt MG with built in effects.'),
  ('guitar_amp', 'Marshall', 'MG30GFX', 'MG', false, '30 watt MG with built in effects.'),
  ('guitar_amp', 'Marshall', 'MG50GFX', 'MG', false, '50 watt MG combo with effects.'),
  ('guitar_amp', 'Marshall', 'MG102GFX', 'MG', false, '100 watt MG combo with 2x12 speakers.'),
  ('guitar_amp', 'Marshall', 'Code 25', 'Code', false, '25 watt modeling combo with Bluetooth and mobile app.'),
  ('guitar_amp', 'Marshall', 'Code 50', 'Code', false, '50 watt Code modeling combo.'),
  ('guitar_amp', 'Marshall', 'Code 100', 'Code', false, '100 watt Code modeling combo or head.'),
  ('guitar_amp', 'Marshall', 'JCM900 4100', 'JCM', false, 'Classic JCM900 4100 100 watt head.'),
  ('guitar_amp', 'Marshall', '1959HW', 'Plexi', false, 'Hand wired 100 watt Plexi head reissue.'),
  ('guitar_amp', 'Marshall', '1987X', 'Plexi', false, '50 watt Plexi head with vintage voicing.'),
  ('guitar_amp', 'Marshall', 'JTM45 2245', 'JTM', false, 'JTM45 30 watt combo based on the original 1962 amp.'),
  ('guitar_amp', 'Marshall', '2555X Silver Jubilee', 'Silver Jubilee', true, 'Silver Jubilee 100 watt reissue head.'),
  ('guitar_amp', 'Marshall', 'AS50D', 'Acoustic', false, '50 watt acoustic amp with 2 channels and reverb.'),
  ('guitar_amp', 'Vox', 'AC4C1-12', 'AC', false, '4 watt tube combo with 12 inch speaker.'),
  ('guitar_amp', 'Vox', 'AC10C1', 'AC', false, '10 watt tube combo with 10 inch speaker.'),
  ('guitar_amp', 'Vox', 'AC15C1', 'AC', true, '15 watt AC15 combo with Top Boost circuit.'),
  ('guitar_amp', 'Vox', 'AC15C2', 'AC', false, '15 watt AC15 with dual 12 inch speakers.'),
  ('guitar_amp', 'Vox', 'AC15HW1', 'AC', false, 'Hand wired AC15 combo with vintage voicing.'),
  ('guitar_amp', 'Vox', 'AC30C2', 'AC', true, '30 watt AC30 combo with dual 12 inch speakers.'),
  ('guitar_amp', 'Vox', 'AC30C2X', 'AC', false, 'AC30 combo with Celestion Alnico Blue speakers.'),
  ('guitar_amp', 'Vox', 'AC30S1', 'AC', false, 'Single channel AC30 combo.'),
  ('guitar_amp', 'Vox', 'AC30HW2', 'AC', false, 'Hand wired AC30 combo.'),
  ('guitar_amp', 'Vox', 'MV50 Clean', 'MV50', false, 'Compact 50 watt Nutube head with clean voicing.'),
  ('guitar_amp', 'Vox', 'MV50 AC', 'MV50', true, 'Compact 50 watt Nutube head with AC30 voicing.'),
  ('guitar_amp', 'Vox', 'MV50 Rock', 'MV50', false, 'Compact 50 watt Nutube head with rock voicing.'),
  ('guitar_amp', 'Vox', 'MV50 Boutique', 'MV50', false, 'Compact 50 watt Nutube head with boutique voicing.'),
  ('guitar_amp', 'Vox', 'MV50 High Gain', 'MV50', false, 'Compact 50 watt Nutube head with high gain voicing.'),
  ('guitar_amp', 'Vox', 'Cambridge50', 'Cambridge', false, '50 watt modeling combo with tube preamp.'),
  ('guitar_amp', 'Vox', 'Pathfinder 10', 'Pathfinder', false, '10 watt practice amp with clean and overdrive.'),
  ('guitar_amp', 'Vox', 'Valvetronix VT20X', 'Valvetronix', true, '20 watt Valvetronix modeling combo with tube preamp.'),
  ('guitar_amp', 'Vox', 'Valvetronix VT40X', 'Valvetronix', true, '40 watt Valvetronix modeling combo with 10 inch speaker.'),
  ('guitar_amp', 'Vox', 'Valvetronix VT100X', 'Valvetronix', false, '100 watt Valvetronix modeling combo with 12 inch speaker.'),
  ('guitar_amp', 'Vox', 'adio Air GT', 'adio', false, 'Portable Bluetooth modeling amp with amp models.'),
  ('guitar_amp', 'Vox', 'Mini Superbeetle', 'Superbeetle', false, 'Miniature stack amp with 25 watt Nutube power section.'),
  ('guitar_amp', 'Orange', 'Crush 12', 'Crush', true, '12 watt practice combo with 3 band EQ and overdrive.'),
  ('guitar_amp', 'Orange', 'Crush 20', 'Crush', true, '20 watt practice combo with dual channels.'),
  ('guitar_amp', 'Orange', 'Crush 20RT', 'Crush', false, '20 watt Crush with reverb and tuner.'),
  ('guitar_amp', 'Orange', 'Crush 35RT', 'Crush', false, '35 watt Crush combo with reverb and tuner.'),
  ('guitar_amp', 'Orange', 'Crush Pro CR60C', 'Crush Pro', false, '60 watt Crush Pro combo with dual channels.'),
  ('guitar_amp', 'Orange', 'Crush Pro CR120C', 'Crush Pro', false, '120 watt Crush Pro combo.'),
  ('guitar_amp', 'Orange', 'Crush Pro CR120H', 'Crush Pro', false, '120 watt Crush Pro head.'),
  ('guitar_amp', 'Orange', 'Super Crush 100 Combo', 'Super Crush', false, '100 watt Super Crush combo with vintage voicing.'),
  ('guitar_amp', 'Orange', 'Super Crush 100 Head', 'Super Crush', false, '100 watt Super Crush head.'),
  ('guitar_amp', 'Orange', 'Rocker 15', 'Rocker', true, '15 watt tube combo with EL84 power tubes.'),
  ('guitar_amp', 'Orange', 'Rocker 15 Terror', 'Rocker Terror', false, '15 watt Rocker Terror lunchbox head.'),
  ('guitar_amp', 'Orange', 'Rocker 32', 'Rocker', false, '30 watt stereo Rocker combo.'),
  ('guitar_amp', 'Orange', 'Rockerverb 50 MkIII Combo', 'Rockerverb', false, '50 watt Rockerverb MkIII combo with reverb.'),
  ('guitar_amp', 'Orange', 'Rockerverb 50 MkIII Head', 'Rockerverb', true, '50 watt Rockerverb MkIII head.'),
  ('guitar_amp', 'Orange', 'Rockerverb 100 MkIII Head', 'Rockerverb', false, '100 watt Rockerverb MkIII head.'),
  ('guitar_amp', 'Orange', 'TremLord 30', 'TremLord', false, '30 watt tube combo with tremolo and reverb.'),
  ('guitar_amp', 'Orange', 'OR15H', 'OR', false, '15 watt Orange OR15 head with vintage voicing.'),
  ('guitar_amp', 'Orange', 'Dual Terror', 'Terror', false, '30 watt Dual Terror lunchbox head.'),
  ('guitar_amp', 'Orange', 'Micro Terror', 'Terror', true, '20 watt Micro Terror with tube preamp and solid-state power.'),
  ('guitar_amp', 'Orange', 'Micro Dark', 'Terror', true, '20 watt Micro Dark with tube preamp and high gain voicing.'),
  ('guitar_amp', 'Orange', 'Terror Stamp', 'Terror', false, '20 watt Terror Stamp pedal amp with tube preamp.'),
  ('guitar_amp', 'Orange', 'Pedal Baby 100', 'Pedal Baby', false, '100 watt Class AB power amp for pedalboards.'),
  ('guitar_amp', 'Orange', 'AD30HTC', 'AD', false, '30 watt hand wired AD30 head with dual channels.'),
  ('guitar_amp', 'Supro', 'Delta King 8', 'Delta King', false, '1 watt Delta King 8 inch practice amp with reverb.'),
  ('guitar_amp', 'Supro', 'Delta King 10', 'Delta King', false, '5 watt Delta King 10 inch tube combo.'),
  ('guitar_amp', 'Supro', 'Delta King 12', 'Delta King', false, '15 watt Delta King 12 inch tube combo.'),
  ('guitar_amp', 'Supro', 'Blues King 8', 'Blues King', false, '1 watt Blues King 8 inch practice combo.'),
  ('guitar_amp', 'Supro', 'Blues King 10', 'Blues King', false, '5 watt Blues King 10 inch combo.'),
  ('guitar_amp', 'Supro', 'Blues King 12', 'Blues King', false, '15 watt Blues King 12 inch combo.'),
  ('guitar_amp', 'Supro', 'Amulet', 'Amulet', false, '15 watt Amulet 1x10 combo with reverb.'),
  ('guitar_amp', 'Supro', 'Delegate', 'Delegate', false, '25 watt Delegate 1x12 combo with vintage voicing.'),
  ('guitar_amp', 'Magnatone', 'Twilighter 112', 'Twilighter', false, '22 watt Twilighter 1x12 combo with FM vibrato.'),
  ('guitar_amp', 'Magnatone', 'Panoramic Stereo 212', 'Panoramic', false, '2x22 watt stereo combo with FM vibrato.'),
  ('guitar_amp', 'Magnatone', 'Super Fifteen', 'Super Fifteen', false, '15 watt Super Fifteen tube combo.'),
  ('guitar_amp', 'Magnatone', 'Super Fifty-Nine M-80', 'Super Fifty-Nine', false, '45 watt Super Fifty-Nine M-80 tube combo.'),
  ('guitar_amp', 'Magnatone', 'Starlite', 'Starlite', false, '5 watt Starlite tube combo.'),
  ('guitar_amp', 'Tone King', 'Imperial MkII', 'Imperial', false, '20 watt Imperial MkII combo with two channels and attenuator.'),
  ('guitar_amp', 'Tone King', 'Falcon Grande', 'Falcon', false, '20 watt Falcon Grande combo with reverb.'),
  ('guitar_amp', 'Tone King', 'Gremlin', 'Gremlin', false, '5 watt Gremlin 1x12 combo with attenuator.'),
  ('guitar_amp', 'Tone King', 'Royalist MkIII', 'Royalist', false, '40 watt Royalist MkIII combo with 3 channels.'),
  ('guitar_amp', 'Bad Cat', 'Black Cat 1x12', 'Black Cat', false, '30 watt Black Cat 1x12 tube combo.'),
  ('guitar_amp', 'Bad Cat', 'Hot Cat 1x12', 'Hot Cat', false, '30 watt Hot Cat 1x12 tube combo with EL34 tubes.'),
  ('guitar_amp', 'Bad Cat', 'Cub 1x12', 'Cub', false, '15 watt Cub 1x12 hand wired combo.'),
  ('guitar_amp', 'Bad Cat', 'Lynx Head', 'Lynx', false, '40 watt Lynx head with two channels.'),
  ('guitar_amp', 'Matchless', 'DC-30', 'DC', false, '30 watt DC-30 hand wired combo with two channels.'),
  ('guitar_amp', 'Matchless', 'HC-30', 'HC', false, '30 watt HC-30 head with two channels.'),
  ('guitar_amp', 'Matchless', 'Laurel Canyon 1x12', 'Laurel Canyon', false, '20 watt Laurel Canyon 1x12 combo.'),
  ('guitar_amp', 'Matchless', 'Spitfire 1x12', 'Spitfire', false, '15 watt Spitfire hand wired 1x12 combo.'),
  ('guitar_amp', 'Dr. Z', 'Maz 18 Jr', 'Maz', false, '18 watt Maz Jr hand wired combo.'),
  ('guitar_amp', 'Dr. Z', 'Z-28 MkII', 'Z-28', false, '32 watt Z-28 MkII combo.'),
  ('guitar_amp', 'Dr. Z', 'Carmen Ghia', 'Carmen Ghia', false, '18 watt Carmen Ghia hand wired combo.'),
  ('guitar_amp', 'Two-Rock', 'Studio Signature', 'Studio Signature', false, '35 watt Studio Signature hand wired combo.'),
  ('guitar_amp', 'Two-Rock', 'Classic Reverb Signature', 'Classic Reverb Signature', false, '50 watt Classic Reverb Signature hand wired combo.'),
  ('guitar_amp', 'Two-Rock', 'Vintage Deluxe', 'Vintage Deluxe', false, '35 watt Vintage Deluxe hand wired combo.'),
  ('guitar_amp', 'Morgan', 'AC20 Deluxe', 'AC', false, '20 watt AC20 Deluxe combo with British voicing.'),
  ('guitar_amp', 'Carr', 'Rambler', 'Rambler', false, 'Multi wattage tube combo with variable power.'),
  ('guitar_amp', 'Carr', 'Sportsman', 'Sportsman', false, 'Low wattage tube combo with vintage voicing.'),
  ('guitar_amp', 'Carr', 'Mercury V', 'Mercury', false, 'Variable wattage Mercury V tube combo.'),
  ('guitar_amp', 'Carr', 'Telstar', 'Telstar', false, 'Two channel Telstar tube combo.'),
  ('guitar_amp', 'Roland', 'JC-22', 'Jazz Chorus', false, '30 watt JC-22 Jazz Chorus 1x10 combo with stereo chorus.'),
  ('guitar_amp', 'Roland', 'JC-40', 'Jazz Chorus', true, '40 watt JC-40 Jazz Chorus 2x10 combo with stereo chorus and reverb.'),
  ('guitar_amp', 'Roland', 'JC-120', 'Jazz Chorus', true, 'Iconic 120 watt Jazz Chorus 2x12 stereo combo.'),
  ('guitar_amp', 'Roland', 'Blues Cube Hot', 'Blues Cube', false, '30 watt Blues Cube Hot 1x12 combo.'),
  ('guitar_amp', 'Roland', 'Blues Cube Stage', 'Blues Cube', false, '60 watt Blues Cube Stage 1x12 combo.'),
  ('guitar_amp', 'Roland', 'Blues Cube Artist', 'Blues Cube', false, '80 watt Blues Cube Artist 1x12 combo.'),
  ('guitar_amp', 'Roland', 'Cube Street EX', 'Cube Street', false, 'Portable battery powered Cube Street EX with stereo speakers.'),
  ('guitar_amp', 'Roland', 'Cube Street II', 'Cube Street', false, 'Second gen Cube Street II battery powered practice amp.'),
  ('guitar_amp', 'Roland', 'Micro Cube GX', 'Micro Cube', false, '3 watt battery powered Micro Cube GX with 8 amp models.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
