-- Phase 47: viral / TikTok-era guitar songs (bedroom pop, modern prog, dream pop), verified per-part tone data.

with target(artist_name, artist_slug, song_title, song_slug, album, release_year) as (
  values
    ('Polyphia','polyphia','Ego Death','ego-death','Remember That You Will Die',2022),
    ('Polyphia','polyphia','ABC','abc','Remember That You Will Die',2022),
    ('Steve Lacy','steve-lacy','Dark Red','dark-red','Steve Lacy''s Demo',2017),
    ('d4vd','d4vd','Romantic Homicide','romantic-homicide','Petals to Thorns',2022),
    ('The Marias','the-marias','No One Noticed','no-one-noticed','Submarine',2024),
    ('wave to earth','wave-to-earth','seasons','seasons','summer flows 0.02',2020),
    ('Men I Trust','men-i-trust','Show Me How','show-me-how','Oncle Jazz',2019),
    ('Mitski','mitski','My Love Mine All Mine','my-love-mine-all-mine','The Land Is Inhospitable and So Are We',2023),
    ('Clairo','clairo','Sofia','sofia','Immunity',2019),
    ('Clairo','clairo','Bags','bags','Immunity',2019),
    ('girl in red','girl-in-red','we fell in love in october','we-fell-in-love-in-october','chapter 2',2018),
    ('Peach Pit','peach-pit','Alrighty Aphrodite','alrighty-aphrodite','Being So Normal',2018),
    ('The Backseat Lovers','the-backseat-lovers','Kilby Girl','kilby-girl','When We Were Friends',2019),
    ('Mac DeMarco','mac-demarco','Ode to Viceroy','ode-to-viceroy','2',2012),
    ('Mac DeMarco','mac-demarco','Freaking Out the Neighborhood','freaking-out-the-neighborhood','2',2012),
    ('TV Girl','tv-girl','Lovers Rock','lovers-rock','French Exit',2014),
    ('Cigarettes After Sex','cigarettes-after-sex','Apocalypse','apocalypse','Cigarettes After Sex',2017),
    ('Title Fight','title-fight','Head in the Ceiling Fan','head-in-the-ceiling-fan','Floral Green',2012),
    ('Beach Fossils','beach-fossils','Sleep Apnea','sleep-apnea','Clash the Truth',2013),
    ('Current Joys','current-joys','Blondie','blondie','A Different Age',2018),
    ('Frank Ocean','frank-ocean','Ivy','ivy','Blonde',2016),
    ('Laufey','laufey','From the Start','from-the-start','Bewitched',2023),
    ('Stephen Sanchez','stephen-sanchez','Until I Found You','until-i-found-you','Angel Face',2021),
    ('The Neighbourhood','the-neighbourhood','Sweater Weather','sweater-weather','I Love You.',2013),
    ('Ricky Montgomery','ricky-montgomery','Line Without a Hook','line-without-a-hook','Montgomery Ricky',2016)
),
ins_artists as (
  insert into public.artists (name, slug, search_text, is_active)
  select distinct artist_name, artist_slug, artist_name, true from target
  on conflict (slug) do update set name = excluded.name, is_active = true
  returning id, slug
)
insert into public.songs (artist_id, title, slug, album, release_year, search_text, is_active)
select a.id, t.song_title, t.song_slug, t.album, t.release_year,
       concat_ws(' ', t.song_title, t.artist_name, t.album), true
from target t join ins_artists a on a.slug = t.artist_slug
on conflict (artist_id, slug) do update set
  title = excluded.title, album = excluded.album, release_year = excluded.release_year,
  is_active = true, updated_at = now();

delete from public.tone_profile_effects e where e.profile_id in (
  select p.id from public.song_tone_profiles p
  join public.songs s on s.id = p.song_id join public.artists a on a.id = s.artist_id
  join (values
    ('polyphia','ego-death'),('polyphia','abc'),('steve-lacy','dark-red'),('d4vd','romantic-homicide'),
    ('the-marias','no-one-noticed'),('wave-to-earth','seasons'),('men-i-trust','show-me-how'),
    ('mitski','my-love-mine-all-mine'),('clairo','sofia'),('clairo','bags'),('girl-in-red','we-fell-in-love-in-october'),
    ('peach-pit','alrighty-aphrodite'),('the-backseat-lovers','kilby-girl'),('mac-demarco','ode-to-viceroy'),
    ('mac-demarco','freaking-out-the-neighborhood'),('tv-girl','lovers-rock'),('cigarettes-after-sex','apocalypse'),
    ('title-fight','head-in-the-ceiling-fan'),('beach-fossils','sleep-apnea'),('current-joys','blondie'),
    ('frank-ocean','ivy'),('laufey','from-the-start'),('stephen-sanchez','until-i-found-you'),
    ('the-neighbourhood','sweater-weather'),('ricky-montgomery','line-without-a-hook')
  ) as t(artist_slug, song_slug) on t.artist_slug = a.slug and t.song_slug = s.slug
);
delete from public.tone_profile_sources src where src.profile_id in (
  select p.id from public.song_tone_profiles p
  join public.songs s on s.id = p.song_id join public.artists a on a.id = s.artist_id
  join (values
    ('polyphia','ego-death'),('polyphia','abc'),('steve-lacy','dark-red'),('d4vd','romantic-homicide'),
    ('the-marias','no-one-noticed'),('wave-to-earth','seasons'),('men-i-trust','show-me-how'),
    ('mitski','my-love-mine-all-mine'),('clairo','sofia'),('clairo','bags'),('girl-in-red','we-fell-in-love-in-october'),
    ('peach-pit','alrighty-aphrodite'),('the-backseat-lovers','kilby-girl'),('mac-demarco','ode-to-viceroy'),
    ('mac-demarco','freaking-out-the-neighborhood'),('tv-girl','lovers-rock'),('cigarettes-after-sex','apocalypse'),
    ('title-fight','head-in-the-ceiling-fan'),('beach-fossils','sleep-apnea'),('current-joys','blondie'),
    ('frank-ocean','ivy'),('laufey','from-the-start'),('stephen-sanchez','until-i-found-you'),
    ('the-neighbourhood','sweater-weather'),('ricky-montgomery','line-without-a-hook')
  ) as t(artist_slug, song_slug) on t.artist_slug = a.slug and t.song_slug = s.slug
);
delete from public.song_tone_profiles p where p.id in (
  select p2.id from public.song_tone_profiles p2
  join public.songs s on s.id = p2.song_id join public.artists a on a.id = s.artist_id
  join (values
    ('polyphia','ego-death'),('polyphia','abc'),('steve-lacy','dark-red'),('d4vd','romantic-homicide'),
    ('the-marias','no-one-noticed'),('wave-to-earth','seasons'),('men-i-trust','show-me-how'),
    ('mitski','my-love-mine-all-mine'),('clairo','sofia'),('clairo','bags'),('girl-in-red','we-fell-in-love-in-october'),
    ('peach-pit','alrighty-aphrodite'),('the-backseat-lovers','kilby-girl'),('mac-demarco','ode-to-viceroy'),
    ('mac-demarco','freaking-out-the-neighborhood'),('tv-girl','lovers-rock'),('cigarettes-after-sex','apocalypse'),
    ('title-fight','head-in-the-ceiling-fan'),('beach-fossils','sleep-apnea'),('current-joys','blondie'),
    ('frank-ocean','ivy'),('laufey','from-the-start'),('stephen-sanchez','until-i-found-you'),
    ('the-neighbourhood','sweater-weather'),('ricky-montgomery','line-without-a-hook')
  ) as t(artist_slug, song_slug) on t.artist_slug = a.slug and t.song_slug = s.slug
);

insert into public.song_tone_profiles (
  song_id, song_title, artist_name, mode, part_type, part_label, tone_type,
  genre, tone_category, difficulty,
  original_guitar, original_amp, original_cab, original_pickup,
  original_effects, original_settings, adaptation_notes, playing_notes,
  source_summary, confidence, verification_status, search_text, is_public
)
select
  s.id, s.title, a.name, c.mode, c.part_type, c.part_label, c.tone_type,
  c.genre, c.tone_category, c.difficulty,
  c.original_guitar, c.original_amp, c.original_cab, c.original_pickup,
  c.original_effects, c.original_settings, c.adaptation_notes, c.playing_notes,
  c.source_summary, c.confidence, 'admin_verified',
  concat_ws(' ', s.title, a.name, c.part_label, c.tone_type, c.original_guitar, c.original_amp, 'researched verified tone'),
  true
from (
  values
    -- ============ POLYPHIA (Tim Henson: Ibanez signature, DI into amp sims) ============
    ('ego-death','polyphia','guitar','riff','main theme','clean','instrumental prog','lead','expert',
     'Ibanez TOD10/THBB10 (Tim Henson)','Direct — Neural DSP-style amp sim, clean compressed','Studio direct (IR cab)','bridge + neck blend',
     '[{"effect_type":"compressor","effect_name":"studio compressor","placement":"front","settings":{"sustain":6,"level":6}},{"effect_type":"reverb","effect_name":"ambient plate reverb","placement":"post_gain","settings":{"mix":3,"decay":4}},{"effect_type":"delay","effect_name":"subtle digital delay","placement":"post_gain","settings":{"time":3,"mix":2,"feedback":2}}]'::jsonb,
     '{"gain":3,"bass":4,"mids":6,"treble":7,"presence":6,"reverb":3,"delay":2,"master":6}'::jsonb,
     array['Recorded direct through amp sims — pristine compressed clean with ambient sheen; the heavy section under the Steve Vai solo pushes into drive.','Going direct with a modeler is the authentic path here, not an amp.'],
     array['Hybrid picking, tapped harmonics, and percussive dead notes.','Slow every phrase down first — the parts are dense.'],
     'Studio recording, 2022. Direct amp-sim clean — the modern Polyphia production sound.',80),
    ('abc','polyphia','guitar','riff','main theme','clean','instrumental prog','lead','expert',
     'Ibanez TOD10 (Tim Henson)','Direct — Neural DSP-style amp sim, clean compressed','Studio direct (IR cab)','bridge + neck blend',
     '[{"effect_type":"compressor","effect_name":"studio compressor","placement":"front","settings":{"sustain":6,"level":6}},{"effect_type":"reverb","effect_name":"ambient plate reverb","placement":"post_gain","settings":{"mix":3,"decay":4}}]'::jsonb,
     '{"gain":2,"bass":4,"mids":6,"treble":7,"presence":6,"reverb":3,"delay":1,"master":6}'::jsonb,
     array['Bouncy percussive clean — thumping muted lines with glassy top.','Direct/modeler clean with heavy compression; treble sparkle is the identity.'],
     array['The thumb-slap and percussive muting drive the groove.','Ghost notes matter as much as the pitched notes.'],
     'Studio recording, 2022. Percussive compressed direct clean.',79),

    -- ============ BEDROOM POP / VIRAL ============
    ('dark-red','steve-lacy','guitar','riff','main riff','crunch','bedroom pop','rhythm','beginner',
     'Solid-body electric (Steve Lacy)','Direct/lo-fi driven recording chain','Studio direct','bridge pickup',
     '[{"effect_type":"compressor","effect_name":"lo-fi limiting","placement":"post_gain","settings":{"sustain":7,"level":6}}]'::jsonb,
     '{"gain":4,"bass":6,"mids":6,"treble":5,"presence":4,"reverb":1,"delay":0,"master":6}'::jsonb,
     array['Lo-fi warm grit — recorded direct with heavy limiting, famously from a bedroom setup.','Slightly driven, dark, and squashed; hi-fi polish is wrong.'],
     array['The bouncing riff doubles the bass line.','Loose feel, quantized-sounding repetition.'],
     'Studio recording, 2017. Lo-fi direct bedroom grit from Steve Lacy''s Demo.',74),
    ('romantic-homicide','d4vd','guitar','riff','main loop','clean','bedroom pop','rhythm','beginner',
     'Solid-body electric','Clean amp/plugin with heavy reverb','Studio direct','neck pickup',
     '[{"effect_type":"reverb","effect_name":"large hall reverb","placement":"post_gain","settings":{"mix":6,"decay":7}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":5,"presence":4,"reverb":6,"delay":1,"master":6}'::jsonb,
     array['Washy melancholy clean loop drowned in reverb — bedroom production (famously made in a closet with free software).','Clean with huge reverb; the mix darkness is part of the mood.'],
     array['A simple looping arpeggio figure carries the song.','Play it soft and let the reverb do the emotion.'],
     'Studio recording, 2022. Reverb-drowned bedroom clean loop.',73),
    ('no-one-noticed','the-marias','guitar','riff','main riff','clean','indie pop','rhythm','intermediate',
     'Semi-hollow electric (Josh Conway / Jesse Perlman)','Warm clean tube amp','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"plate reverb","placement":"post_gain","settings":{"mix":4,"decay":5}},{"effect_type":"compressor","effect_name":"light compression","placement":"front","settings":{"sustain":4,"level":5}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":6,"treble":5,"presence":4,"reverb":4,"delay":1,"master":6}'::jsonb,
     array['Smoky, jazzy clean — warm neck-pickup lines in soft plate reverb.','Dark clean; roll the tone knob back if it bites.'],
     array['Slinky melodic fills answer the vocal.','Soft attack — brush the strings, don''t pick hard.'],
     'Studio recording, 2024. Smoky jazz-tinged dream pop clean from Submarine.',73),
    ('seasons','wave-to-earth','guitar','riff','main riff','clean','indie pop','rhythm','intermediate',
     'Semi-hollow electric (Daniel Kim)','Warm clean amp','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":3,"decay":4}},{"effect_type":"compressor","effect_name":"soft compression","placement":"front","settings":{"sustain":4,"level":5}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":6,"treble":5,"presence":4,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['Warm jazzy lo-fi clean — soft, rounded, intimate.','Neck pickup, low treble, gentle compression; keep everything soft.'],
     array['The jazzy chord voicings use add9 and maj7 colors.','Fingerstyle or soft-pick for the intimate feel.'],
     'Studio recording, 2020. Warm jazzy Korean indie clean.',73),
    ('show-me-how','men-i-trust','guitar','riff','main riff','clean','indie pop','rhythm','intermediate',
     'Solid-body electric (Jessy Caron)','Clean amp with soft modulation','Open-back combo cab','neck pickup',
     '[{"effect_type":"chorus","effect_name":"soft chorus/flanger","placement":"post_gain","settings":{"rate":3,"depth":4,"mix":4}},{"effect_type":"compressor","effect_name":"heavy soft compression","placement":"front","settings":{"sustain":6,"level":5}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":4,"presence":3,"reverb":3,"delay":0,"master":5}'::jsonb,
     array['Underwater dreamy clean — dark, compressed, gently modulated.','Roll treble way down; the tone is deliberately muffled and soft.'],
     array['Muted, liquid single-note lines.','Dynamics stay flat and dreamy — no accents.'],
     'Studio recording, 2019. Muffled dreamy modulated clean.',74),
    ('my-love-mine-all-mine','mitski','guitar','riff','main riff','clean','indie pop','rhythm','beginner',
     'Hollow-body electric','Warm clean amp with tremolo','Open-back combo cab','neck pickup',
     '[{"effect_type":"tremolo","effect_name":"slow amp tremolo","placement":"post_gain","settings":{"rate":3,"depth":4}},{"effect_type":"reverb","effect_name":"spring reverb","placement":"post_gain","settings":{"mix":4}}]'::jsonb,
     '{"gain":1,"bass":5,"mids":6,"treble":4,"presence":3,"reverb":4,"delay":0,"master":5}'::jsonb,
     array['Moonlit waltz clean — warm, dark, with gentle tremolo shimmer.','Barely-there clean; tremolo and spring reverb create the sway.'],
     array['Slow 3/4 sway — let each chord breathe.','Play behind the beat, dreamy and unhurried.'],
     'Studio recording, 2023. Warm tremolo waltz clean from Mitski''s viral hit.',73),
    ('sofia','clairo','guitar','riff','main riff','crunch','bedroom pop','rhythm','beginner',
     'Solid-body electric (Clairo / Rostam)','Driven amp with chorus wobble','Open-back combo cab','bridge pickup',
     '[{"effect_type":"chorus","effect_name":"warbly chorus","placement":"post_gain","settings":{"rate":4,"depth":5,"mix":5}}]'::jsonb,
     '{"gain":5,"bass":5,"mids":6,"treble":5,"presence":4,"reverb":2,"delay":0,"master":6}'::jsonb,
     array['Fuzzy warbling indie-pop drive — The Strokes filtered through bedroom pop.','Medium crunch with prominent chorus wobble; lo-fi charm over precision.'],
     array['Driving eighth-note strums push the chorus.','Keep it loose — the warble is the personality.'],
     'Studio recording, 2019. Warbly driven bedroom-pop banger from Immunity.',74),
    ('bags','clairo','guitar','riff','main riff','clean','bedroom pop','rhythm','beginner',
     'Solid-body electric (Clairo / Rostam)','Warm clean amp','Open-back combo cab','neck pickup',
     '[{"effect_type":"compressor","effect_name":"soft compression","placement":"front","settings":{"sustain":4,"level":5}},{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":6,"treble":5,"presence":4,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['Soft circling clean arpeggio under layered production.','Warm clean; the drive layers that enter later are overdubs.'],
     array['The same gentle figure loops and builds.','Consistency and patience over flash.'],
     'Studio recording, 2019. Soft looping clean from Immunity.',74),
    ('we-fell-in-love-in-october','girl-in-red','guitar','riff','main riff','clean','bedroom pop','rhythm','beginner',
     'Solid-body electric (Marie Ulven)','Clean amp with reverb','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":4,"decay":4}},{"effect_type":"chorus","effect_name":"light chorus","placement":"post_gain","settings":{"rate":3,"depth":3,"mix":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":4,"delay":0,"master":6}'::jsonb,
     array['Jangly lo-fi bedroom clean with soft reverb halo.','Bright but soft clean; slight chorus sheen.'],
     array['Gentle arpeggios and soft strums throughout.','The lead fills are simple octave melodies.'],
     'Studio recording, 2018. Jangly bedroom-pop clean, a girl in red signature.',73),
    ('alrighty-aphrodite','peach-pit','guitar','riff','main riff + lead','clean','indie rock','lead','intermediate',
     'Hollow-body electric (Neil Smith / Christopher Vanderkooy)','Clean tube amp, edge of breakup','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"spring reverb","placement":"post_gain","settings":{"mix":3}}]'::jsonb,
     '{"gain":3,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['Slinky bendy indie lead over jangly clean strums.','Just-clean with spring bounce; the lead bends are vocal-like.'],
     array['Vanderkooy''s lead lines slide and bend constantly.','Two guitars: jangly rhythm + slippery lead.'],
     'Studio recording, 2018. Slinky bendy "chewed bubblegum pop" leads.',73),
    ('kilby-girl','the-backseat-lovers','guitar','riff','verse clean + chorus drive','crunch','indie rock','rhythm','intermediate',
     'Solid-body electric (Josh Harmon / Jonas Swanson)','Tube combo, clean to driven','Open-back combo cab','bridge pickup',
     '[]'::jsonb,'{"gain":4,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":2,"delay":0,"master":6}'::jsonb,
     array['Dynamic build from muted clean verse to soaring driven chorus (push gain to 6 for the payoff).','Program clean and crunch settings; the dynamic contrast is the song.'],
     array['Palm-muted verse groove, wide-open chorus strums.','The bridge builds patiently — resist rushing it.'],
     'Studio recording, 2019. Quiet-loud indie dynamics behind the viral hit.',73),
    ('ode-to-viceroy','mac-demarco','guitar','riff','main riff','clean','indie rock','rhythm','intermediate',
     'Cheap offset electric (Mac DeMarco)','Fender-style clean amp with vibrato warble','Open-back combo cab','neck pickup',
     '[{"effect_type":"chorus","effect_name":"vibrato/chorus warble","placement":"post_gain","settings":{"rate":4,"depth":5,"mix":5}},{"effect_type":"reverb","effect_name":"spring reverb","placement":"post_gain","settings":{"mix":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":6,"presence":5,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['The signature jizz-jazz warble — cheap-guitar clean with seasick vibrato.','Clean with constant pitch warble; Mac''s tone is deliberately woozy.'],
     array['Lazy, behind-the-beat jangle strums.','The lead breaks are simple and slippery.'],
     'Studio recording, 2012. Mac''s woozy warbled clean from 2.',75),
    ('freaking-out-the-neighborhood','mac-demarco','guitar','riff','main riff','clean','indie rock','rhythm','beginner',
     'Cheap offset electric (Mac DeMarco)','Fender-style clean amp with vibrato warble','Open-back combo cab','neck pickup',
     '[{"effect_type":"chorus","effect_name":"vibrato/chorus warble","placement":"post_gain","settings":{"rate":4,"depth":4,"mix":5}},{"effect_type":"reverb","effect_name":"spring reverb","placement":"post_gain","settings":{"mix":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['Bouncy warbled clean riff — sunny and slightly seasick.','Same woozy vibrato-clean recipe; keep it bright but soft.'],
     array['The main riff bounces between bass notes and chord stabs.','Swing it gently.'],
     'Studio recording, 2012. Sunny woozy clean riff.',75),
    ('lovers-rock','tv-girl','guitar','riff','main riff','clean','indie pop','rhythm','beginner',
     'Solid-body electric','Clean amp, lo-fi sampled texture','Studio direct','neck pickup',
     '[{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":4}},{"effect_type":"compressor","effect_name":"lo-fi limiting","placement":"post_gain","settings":{"sustain":6,"level":5}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":6,"treble":5,"presence":4,"reverb":4,"delay":0,"master":6}'::jsonb,
     array['Hazy sample-flavored jangle — warm, squashed, and nostalgic.','Soft clean with lo-fi compression; sounds like an old record on purpose.'],
     array['Simple looping chord figure under the vocal.','Feel matters more than precision.'],
     'Studio recording, 2014. Hazy lo-fi jangle from French Exit.',72),
    ('apocalypse','cigarettes-after-sex','guitar','riff','main riff','clean','dream pop','rhythm','beginner',
     'Solid-body electric (Greg Gonzalez)','Clean amp drowned in reverb and delay','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"huge hall reverb","placement":"post_gain","settings":{"mix":7,"decay":8}},{"effect_type":"delay","effect_name":"ambient delay","placement":"post_gain","settings":{"time":5,"mix":4,"feedback":4}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":5,"presence":4,"reverb":7,"delay":4,"master":6}'::jsonb,
     array['Slow-motion dream pop — clean guitar dissolved in cathedral reverb.','Max ambience: huge reverb plus delay; the notes should blur together.'],
     array['Slow arpeggios and swells — every note sustains forever.','Play half as many notes as you think you need.'],
     'Studio recording, 2017. Cathedral-reverb dream pop clean.',75),
    ('head-in-the-ceiling-fan','title-fight','guitar','riff','main riff','crunch','shoegaze','rhythm','intermediate',
     'Solid-body electric (Shane Moran / Ned Russin)','Driven amp with washy reverb','Closed-back cab','bridge pickup',
     '[{"effect_type":"reverb","effect_name":"large reverb wash","placement":"post_gain","settings":{"mix":5,"decay":6}}]'::jsonb,
     '{"gain":5,"bass":5,"mids":5,"treble":5,"presence":4,"reverb":5,"delay":0,"master":6}'::jsonb,
     array['Melancholy shoegaze-punk wash — driven chords smeared with reverb.','Medium gain washed in reverb; heaviness through blur, not tightness.'],
     array['Let ringing open strings drone through the chord changes.','The repeating figure builds by layering, not speed.'],
     'Studio recording, 2012. Shoegaze-punk reverb wash from Floral Green.',73),
    ('sleep-apnea','beach-fossils','guitar','riff','main riff','clean','indie rock','rhythm','beginner',
     'Solid-body electric (Dustin Payseur)','Bright clean amp with reverb','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":4,"decay":4}},{"effect_type":"chorus","effect_name":"light chorus","placement":"post_gain","settings":{"rate":3,"depth":3,"mix":3}}]'::jsonb,
     '{"gain":2,"bass":4,"mids":5,"treble":7,"presence":5,"reverb":4,"delay":0,"master":6}'::jsonb,
     array['Drifting jangle — bright interlocking clean melody lines.','Trebly clean with soft reverb; the melody line is the hook.'],
     array['Guitar and bass weave counter-melodies.','Even, hypnotic picking throughout.'],
     'Studio recording, 2013. Drifting jangle-clean melody lines.',73),
    ('blondie','current-joys','guitar','riff','main riff','crunch','indie rock','rhythm','beginner',
     'Solid-body electric (Nick Rattigan)','Driven amp, lo-fi and raw','Open-back combo cab','bridge pickup',
     '[{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":4}}]'::jsonb,
     '{"gain":5,"bass":5,"mids":5,"treble":5,"presence":4,"reverb":4,"delay":0,"master":6}'::jsonb,
     array['Raw emotional lo-fi strums — driven but hazy.','Medium gain, lo-fi room sound; imperfection is the aesthetic.'],
     array['Big emotional downstrokes on the chord progression.','Dynamics swell with the vocal intensity.'],
     'Studio recording, 2018. Raw emotional lo-fi drive.',71),
    ('ivy','frank-ocean','guitar','riff','main riff','clean','indie pop','rhythm','intermediate',
     'Solid-body electric (session — Alex G associated)','Clean amp with chorus shimmer','Studio direct','neck pickup',
     '[{"effect_type":"chorus","effect_name":"watery chorus","placement":"post_gain","settings":{"rate":4,"depth":4,"mix":5}},{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['Watery chorused clean — intimate and slightly detuned-feeling.','Clean with prominent chorus; warm, not bright.'],
     array['Gentle arpeggiated figures under the vocal.','The wobble is the emotion — don''t fight it.'],
     'Studio recording, 2016. Watery chorused clean from Blonde.',72),
    ('from-the-start','laufey','guitar','riff','main riff','clean','jazz pop','rhythm','intermediate',
     'Hollow-body archtop (Laufey)','Warm jazz clean amp','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":2}}]'::jsonb,
     '{"gain":1,"bass":5,"mids":6,"treble":4,"presence":3,"reverb":2,"delay":0,"master":5}'::jsonb,
     array['Bossa-nova jazz clean — warm archtop comping.','Dark round jazz tone: neck pickup, treble rolled off, nearly dry.'],
     array['Bossa comping pattern with jazz chord extensions.','Fingerstyle or soft pick; keep it buoyant.'],
     'Studio recording, 2023. Warm bossa jazz-pop clean from Bewitched.',75),
    ('until-i-found-you','stephen-sanchez','guitar','riff','main riff','clean','indie pop','rhythm','beginner',
     'Hollow-body electric (Stephen Sanchez)','Vintage-voiced clean amp with spring reverb','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"spring reverb","placement":"post_gain","settings":{"mix":4}},{"effect_type":"tremolo","effect_name":"light tremolo","placement":"post_gain","settings":{"rate":3,"depth":3}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":5,"presence":4,"reverb":4,"delay":0,"master":6}'::jsonb,
     array['50s-throwback romantic clean — warm hollow-body with spring splash.','Vintage doo-wop voicing: clean, springy, softly tremolo''d.'],
     array['Slow 6/8 arpeggios in the verse.','Channel the 1950s slow-dance feel.'],
     'Studio recording, 2021. 50s-styled romantic clean behind the viral hit.',74),
    ('sweater-weather','the-neighbourhood','guitar','riff','main riff','clean','indie pop','rhythm','intermediate',
     'Solid-body electric (Zach Abels / Jeremy Freedman)','Bright clean amp, tight and produced','Studio direct','bridge pickup',
     '[{"effect_type":"compressor","effect_name":"studio compression","placement":"front","settings":{"sustain":5,"level":5}},{"effect_type":"reverb","effect_name":"short room reverb","placement":"post_gain","settings":{"mix":2}}]'::jsonb,
     '{"gain":2,"bass":4,"mids":5,"treble":7,"presence":5,"reverb":2,"delay":1,"master":6}'::jsonb,
     array['Glassy produced clean — the intro hook is bright, compressed, and dry-ish.','Tight modern pop-production clean; crisp attack, short ambience.'],
     array['The intro arpeggio hook must be metronome-tight.','Muted verse chugs support the beat-driven production.'],
     'Studio recording, 2013. Glassy produced clean hook.',74),
    ('line-without-a-hook','ricky-montgomery','guitar','riff','main riff','clean','indie pop','rhythm','beginner',
     'Solid-body electric (Ricky Montgomery)','Clean amp with light reverb','Open-back combo cab','neck pickup',
     '[{"effect_type":"reverb","effect_name":"room reverb","placement":"post_gain","settings":{"mix":3}},{"effect_type":"compressor","effect_name":"light compression","placement":"front","settings":{"sustain":4,"level":5}}]'::jsonb,
     '{"gain":2,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":3,"delay":0,"master":6}'::jsonb,
     array['Bouncy indie-pop clean strums with a soft sheen.','Bright-but-warm clean; the energy comes from the strumming.'],
     array['Driving muted strum pattern in the verse.','Open up the chorus with full strums.'],
     'Studio recording, 2016. Bouncy clean strums behind the TikTok revival hit.',72)
) as c(
  song_slug, artist_slug, mode, part_type, part_label, tone_type, genre, tone_category, difficulty,
  original_guitar, original_amp, original_cab, original_pickup,
  original_effects, original_settings, adaptation_notes, playing_notes, source_summary, confidence
)
join public.artists a on a.slug = c.artist_slug
join public.songs s on s.artist_id = a.id and s.slug = c.song_slug;
