begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('guitar_amp', 'Marshall', 'JCM800 2204', 'JCM800', false, '50 watt JCM800 2204 master volume head.'),
  ('guitar_amp', 'Marshall', 'JCM900 4500', 'JCM900', false, '50 watt JCM900 4500 Hi-Gain Dual Reverb head.'),
  ('guitar_amp', 'Marshall', 'TSL60', 'JCM2000', false, '60 watt JCM2000 TSL60 triple channel head.'),
  ('guitar_amp', 'Marshall', 'TSL100', 'JCM2000', false, '100 watt JCM2000 TSL100 triple channel head.'),
  ('guitar_amp', 'Marshall', 'DSL401', 'JCM2000', false, '40 watt JCM2000 DSL401 1x12 combo.'),
  ('guitar_amp', 'Marshall', 'Valvestate VS100', 'Valvestate', false, '100 watt Valvestate VS100 hybrid combo.'),
  ('guitar_amp', 'Marshall', 'Valvestate 8080', 'Valvestate', false, '80 watt Valvestate 8080 hybrid combo.'),
  ('guitar_amp', 'Marshall', 'Astoria Classic', 'Astoria', false, '30 watt hand wired Astoria Classic combo.'),
  ('guitar_amp', 'Marshall', 'Astoria Custom', 'Astoria', false, '30 watt hand wired Astoria Custom with gain channel.'),
  ('guitar_amp', 'Marshall', '1974X', 'Handwired', false, '18 watt hand wired 1974X combo reissue with tremolo.'),
  ('guitar_amp', 'Marshall', 'MS-2', 'Micro', false, '1 watt MS-2 micro stack practice amp.'),
  ('guitar_amp', 'Marshall', 'MS-4', 'Micro', false, '1 watt MS-4 full micro stack practice amp.'),
  ('guitar_amp', 'Fender', 'Champion 600', 'Champion', false, '5 watt Champion 600 reissue with vintage styling.'),
  ('guitar_amp', 'Fender', 'Super Champ X2', 'Super Champ', false, '15 watt Super Champ X2 hybrid combo with amp voicings.'),
  ('guitar_amp', 'Fender', 'Super Champ XD', 'Super Champ', false, '15 watt Super Champ XD hybrid combo.'),
  ('guitar_amp', 'Fender', 'Pawn Shop Greta', 'Pawn Shop', false, '2 watt Greta tabletop tube amp with retro styling.'),
  ('guitar_amp', 'Fender', 'Pawn Shop Excelsior', 'Pawn Shop', false, '13 watt Excelsior tube combo with 15 inch speaker.'),
  ('guitar_amp', 'Fender', '59 Bassman LTD', 'Bassman', false, '45 watt 59 Bassman LTD 4x10 tweed reissue.'),
  ('guitar_amp', 'Fender', '68 Custom Vibrolux Reverb', '68 Custom', false, '35 watt 68 Custom Vibrolux Reverb 2x10 combo.'),
  ('guitar_amp', 'Fender', 'Mustang GT 40', 'Mustang GT', false, '40 watt WiFi enabled Mustang GT modeling combo.'),
  ('guitar_amp', 'Fender', 'Mustang GT 100', 'Mustang GT', false, '100 watt Mustang GT modeling combo.'),
  ('guitar_amp', 'Fender', 'Mustang GT 200', 'Mustang GT', false, '200 watt Mustang GT stereo modeling combo.'),
  ('guitar_amp', 'Fender', 'Bronco 40', 'Bronco', false, '40 watt Bronco 40 bass practice combo with modeling.'),
  ('guitar_amp', 'Vox', 'AC15C1X', 'AC', false, 'AC15 combo with Celestion Alnico Blue speaker.'),
  ('guitar_amp', 'Vox', 'AC4TV', 'AC', false, '4 watt AC4TV with built in attenuator and TV front styling.'),
  ('guitar_amp', 'Vox', 'Night Train NT15H G2', 'Night Train', false, '15 watt Night Train G2 lunchbox head.'),
  ('guitar_amp', 'Vox', 'Lil Night Train NT2H', 'Night Train', false, '2 watt Lil Night Train micro head.'),
  ('guitar_amp', 'Vox', 'Pathfinder 15R', 'Pathfinder', false, '15 watt Pathfinder 15R combo with reverb and tremolo.'),
  ('guitar_amp', 'Vox', 'AC30VR', 'AC', false, '30 watt AC30VR Valve Reactor hybrid combo.'),
  ('guitar_amp', 'Roland', 'Cube 10GX', 'Cube', false, '10 watt Cube 10GX practice combo with COSM amp models.'),
  ('guitar_amp', 'Roland', 'Cube 40GX', 'Cube', false, '40 watt Cube 40GX combo with COSM modeling.'),
  ('guitar_amp', 'Roland', 'Cube 80GX', 'Cube', false, '80 watt Cube 80GX combo with COSM modeling.'),
  ('guitar_amp', 'Mesa Boogie', 'Mark IV', 'Mark', false, 'Classic Mark IV head with three channels and graphic EQ.'),
  ('guitar_amp', 'Mesa Boogie', 'Express 5:25 Plus', 'Express', false, '25 watt Express Plus combo with multi-watt switching.'),
  ('guitar_amp', 'Mesa Boogie', 'Express 5:50 Plus', 'Express', false, '50 watt Express Plus combo.'),
  ('guitar_amp', 'Mesa Boogie', 'Roadster', 'Rectifier', false, '100 watt Roadster Dual Rectifier head with four channels.'),
  ('guitar_amp', 'Mesa Boogie', 'Stiletto Ace', 'Stiletto', false, '50 watt Stiletto Ace head with EL34 British voicing.'),
  ('guitar_amp', 'Mesa Boogie', 'Triple Crown TC-100', 'Triple Crown', false, '100 watt Triple Crown TC-100 head with three channels.'),
  ('guitar_amp', 'Mesa Boogie', 'Electra Dyne', 'Electra Dyne', false, '90 watt Electra Dyne head with vintage American and British modes.'),
  ('guitar_amp', 'PRS', 'Archon 100', 'Archon', false, '100 watt Archon head with high gain voicing.'),
  ('guitar_amp', 'PRS', 'Sonzera 20', 'Sonzera', false, '20 watt Sonzera combo with two channels and reverb.'),
  ('guitar_amp', 'PRS', 'Sonzera 50', 'Sonzera', false, '50 watt Sonzera combo with two channels.'),
  ('guitar_amp', 'PRS', 'HDRX 20', 'HDRX', false, '20 watt HDRX head with Hendrix era touring amp circuit.'),
  ('guitar_amp', 'PRS', 'HDRX 50', 'HDRX', false, '50 watt HDRX head.'),
  ('guitar_amp', 'PRS', 'HDRX 100', 'HDRX', false, '100 watt HDRX flagship head.'),
  ('guitar_amp', 'Boss', 'Acoustic Singer Live', 'Acoustic Singer', false, '60 watt Acoustic Singer Live acoustic amp with vocal harmony.'),
  ('guitar_amp', 'Boss', 'Acoustic Singer Pro', 'Acoustic Singer', false, '120 watt Acoustic Singer Pro acoustic amp.'),
  ('guitar_amp', 'Boss', 'Acoustic Singer Live LT', 'Acoustic Singer', false, '60 watt Acoustic Singer Live LT with streamlined controls.'),
  ('guitar_amp', 'Blackstar', 'Artist 15', 'Artist', false, '15 watt Artist 15 tube combo with 6L6 tubes.'),
  ('guitar_amp', 'Blackstar', 'Artist 30', 'Artist', false, '30 watt Artist 30 2x12 tube combo.'),
  ('guitar_amp', 'Blackstar', 'Artisan 15', 'Artisan', false, '15 watt hand wired Artisan 15 combo.'),
  ('guitar_amp', 'Blackstar', 'Artisan 30', 'Artisan', false, '30 watt hand wired Artisan 30 2x12 combo.'),
  ('guitar_amp', 'Laney', 'GH50L', 'GH', false, '50 watt GH50L tube head with British voicing.'),
  ('guitar_amp', 'Laney', 'GH100L', 'GH', false, '100 watt GH100L tube head.'),
  ('guitar_amp', 'Laney', 'VC30-112', 'VC', false, '30 watt VC30 1x12 class A tube combo.'),
  ('guitar_amp', 'Hiwatt', 'Custom 100 DR103', 'Custom', false, '100 watt Custom 100 DR103 hand wired head.'),
  ('guitar_amp', 'Hiwatt', 'Custom 50 DR504', 'Custom', false, '50 watt Custom 50 DR504 hand wired head.'),
  ('guitar_amp', 'Hiwatt', 'Custom 20 Combo', 'Custom', false, '20 watt Custom 20 1x12 combo.'),
  ('guitar_amp', 'Hiwatt', 'Custom 20 Head', 'Custom', false, '20 watt Custom 20 head.'),
  ('guitar_amp', 'Egnater', 'Rebel-20', 'Rebel', false, '20 watt Rebel-20 head with tube mix control.'),
  ('guitar_amp', 'Egnater', 'Rebel-30', 'Rebel', false, '30 watt Rebel-30 head with two channels.'),
  ('guitar_amp', 'Egnater', 'Tweaker 15', 'Tweaker', false, '15 watt Tweaker head with voicing switches.'),
  ('guitar_amp', 'Egnater', 'Tweaker 40', 'Tweaker', false, '40 watt Tweaker 40 head.'),
  ('guitar_amp', 'Egnater', 'Renegade 65', 'Renegade', false, '65 watt Renegade head with tube mixing.'),
  ('guitar_amp', 'Jet City', 'JCA20H', 'JCA', false, '20 watt JCA20H head designed with Soldano voicing.'),
  ('guitar_amp', 'Jet City', 'JCA22H', 'JCA', false, '20 watt JCA22H two channel head.'),
  ('guitar_amp', 'Jet City', 'JCA50H', 'JCA', false, '50 watt JCA50H head.'),
  ('guitar_amp', 'Jet City', 'JCA2112RC', 'JCA', false, '20 watt JCA2112RC 1x12 combo.'),
  ('guitar_amp', 'ZT', 'Lunchbox', 'Lunchbox', false, '200 watt ultra compact Lunchbox combo.'),
  ('guitar_amp', 'ZT', 'Lunchbox Junior', 'Lunchbox', false, '35 watt Lunchbox Junior micro combo.'),
  ('guitar_amp', 'DV Mark', 'Little Jazz', 'Jazz', false, '45 watt Little Jazz compact combo for archtop players.'),
  ('guitar_amp', 'DV Mark', 'DV Jazz 12', 'Jazz', false, '45 watt Jazz 12 combo with warm clean voicing.'),
  ('guitar_amp', 'DV Mark', 'Micro 50 II', 'Micro', false, '50 watt Micro 50 II compact head.'),
  ('guitar_amp', 'Koch', 'Studiotone XL', 'Studiotone', false, '40 watt Studiotone XL combo with built in attenuator.'),
  ('guitar_amp', 'Suhr', 'Badger 18', 'Badger', false, '18 watt Badger head with power scaling.'),
  ('guitar_amp', 'Suhr', 'Badger 30', 'Badger', false, '30 watt Badger 30 head.'),
  ('guitar_amp', 'Suhr', 'Bella', 'Bella', false, '44 watt Bella head with American clean voicing.'),
  ('guitar_amp', 'Suhr', 'Hombre', 'Hombre', false, '18 watt Hombre combo with tweed voicing.'),
  ('guitar_amp', 'Suhr', 'SL68', 'SL68', false, '100 watt SL68 head with Plexi style circuit.'),
  ('guitar_amp', 'Krank', 'Krankenstein', 'Krankenstein', false, '100 watt Krankenstein head with high gain voicing.'),
  ('guitar_amp', 'Ibanez', 'TSA15', 'TSA', false, '15 watt Tube Screamer Amp combo with built in TS circuit.'),
  ('guitar_amp', 'Ibanez', 'TSA30', 'TSA', false, '30 watt Tube Screamer Amp combo.'),
  ('guitar_amp', 'Sound City', 'SC30', 'SC', false, '30 watt SC30 hand wired combo.'),
  ('guitar_amp', 'Monoprice', 'Stage Right 15W 1x12', 'Stage Right', false, '15 watt Stage Right tube combo with Celestion speaker.'),
  ('guitar_amp', 'Kustom', 'Defender V5', 'Defender', false, '5 watt Defender V5 tube head.'),
  ('guitar_amp', 'Orange', 'O-Tone 40', 'O-Tone', false, '40 watt O-Tone 40 solid-state combo.'),
  ('guitar_amp', 'Bugera', 'Trirec Infinium', 'Trirec', false, '100 watt Trirec Infinium head with three channels.'),
  ('guitar_amp', 'Bugera', 'G20 Infinium', 'G', false, '20 watt G20 Infinium head.'),
  ('guitar_amp', 'Randall', 'NB King 100', 'Signature', false, 'Nuno Bettencourt NB King 100 signature head.'),
  ('guitar_amp', 'Randall', 'RG1003H', 'RG', false, '100 watt RG1003H solid-state head.'),
  ('guitar_amp', 'Peavey', 'Envoy 110', 'TransTube', false, '40 watt Envoy 110 TransTube combo.'),
  ('guitar_amp', 'Peavey', 'Studio Pro 112', 'TransTube', false, '65 watt Studio Pro 112 TransTube combo.'),
  ('bass_amp', 'SWR', 'Workingman''s 12', 'Workingman', false, '100 watt Workingmans 12 bass combo.'),
  ('bass_amp', 'SWR', 'Super Redhead', 'Redhead', false, '350 watt Super Redhead 2x10 bass combo.'),
  ('bass_amp', 'SWR', 'SM-500', 'SM', false, '500 watt SM-500 rack style bass head.'),
  ('bass_amp', 'Genz Benz', 'Shuttle 6.0', 'Shuttle', false, '600 watt Shuttle 6.0 ultra light bass head.'),
  ('bass_amp', 'Genz Benz', 'Shuttle 9.0', 'Shuttle', false, '900 watt Shuttle 9.0 ultra light bass head.'),
  ('bass_amp', 'Genz Benz', 'Streamliner 900', 'Streamliner', false, '900 watt Streamliner 900 bass head with tube preamp.'),
  ('bass_amp', 'Gallien Krueger', '700RB-II', 'RB', false, '480 watt 700RB-II bass head.'),
  ('bass_amp', 'Gallien Krueger', '1001RB-II', 'RB', false, '700 watt 1001RB-II bass head.'),
  ('bass_amp', 'Gallien Krueger', 'MB Fusion 500', 'MB Fusion', false, '500 watt MB Fusion 500 with tube preamp.'),
  ('bass_amp', 'Gallien Krueger', 'MB Fusion 800', 'MB Fusion', false, '800 watt MB Fusion 800 with tube preamp.'),
  ('bass_amp', 'Gallien Krueger', 'Backline 600', 'Backline', false, '300 watt Backline 600 bass head.'),
  ('bass_amp', 'Ampeg', 'B2RE', 'B', false, '450 watt B2RE rack mount bass head.'),
  ('bass_amp', 'Ampeg', 'SVT-6PRO', 'SVT', false, '1100 watt SVT-6PRO hybrid bass head.'),
  ('bass_amp', 'Aguilar', 'AG 500', 'AG', false, '500 watt AG 500 bass head.'),
  ('bass_amp', 'Aguilar', 'DB 750', 'DB', false, '750 watt DB 750 hybrid bass head.'),
  ('bass_amp', 'Fender', 'Super Bassman', 'Bassman Pro', false, '300 watt Super Bassman all tube head.'),
  ('bass_amp', 'Fender', 'Bassman 500', 'Bassman Pro', false, '500 watt Bassman 500 hybrid head.'),
  ('bass_amp', 'Fender', 'Bassman 800', 'Bassman Pro', false, '800 watt Bassman 800 hybrid head.'),
  ('bass_amp', 'Orange', 'AD200B MK3', 'AD200B', false, '200 watt AD200B MK3 all tube bass head.'),
  ('bass_amp', 'Mesa Boogie', 'Walkabout', 'Walkabout', false, '300 watt Walkabout compact bass head with tube preamp.'),
  ('bass_amp', 'Mesa Boogie', 'Big Block 750', 'Big Block', false, '750 watt Big Block 750 bass head.'),
  ('bass_amp', 'Trace Elliot', 'AH350SMX', 'AH', false, '350 watt AH350SMX bass head with 12 band EQ.'),
  ('bass_amp', 'Ibanez', 'Promethean P3110', 'Promethean', false, '300 watt Promethean P3110 1x10 bass combo.'),
  ('bass_amp', 'Behringer', 'Ultrabass BXD3000H', 'Ultrabass', false, '300 watt Ultrabass BXD3000H bass head.'),
  ('bass_amp', 'Hartke', 'LH1000', 'LH', false, '1000 watt LH1000 bass head with tube preamp.'),
  ('bass_amp', 'Hartke', 'HA5500', 'HA', false, '500 watt HA5500 bass head with hybrid preamp.'),
  ('bass_amp', 'Markbass', 'Little Mark 250 Black Line', 'Little Mark', false, '250 watt Little Mark 250 Black Line head.'),
  ('bass_amp', 'Eden', 'WT550 Traveler', 'Traveler', false, '550 watt WT550 Traveler bass head.'),
  ('bass_amp', 'Ashdown', 'Little Bastard LB-30', 'Little Bastard', false, '30 watt Little Bastard all tube bass head.'),
  ('bass_amp', 'Peavey', 'TKO 115', 'TKO', false, '400 watt TKO 115 bass combo.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
