begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('guitar_amp', 'Boss', 'Katana-50 Gen 3', 'Katana', true, 'Third generation Katana 50 combo with new Pushed clean voicing.'),
  ('guitar_amp', 'Boss', 'Katana-100 Gen 3', 'Katana', true, 'Third generation Katana 100 combo with 12 inch speaker.'),
  ('guitar_amp', 'Boss', 'Katana-100/212 Gen 3', 'Katana', false, 'Third generation Katana 100 with dual 12 inch speakers.'),
  ('guitar_amp', 'Boss', 'Katana Artist Gen 3', 'Katana', false, 'Third generation Katana Artist 100 with premium components.'),
  ('guitar_amp', 'Boss', 'Katana Head MkII', 'Katana', false, '100 watt Katana MkII head format.'),
  ('guitar_amp', 'Boss', 'Katana-50 MkII EX', 'Katana', false, 'Extended feature Katana 50 MkII EX combo.'),
  ('guitar_amp', 'Boss', 'Katana-Air', 'Katana', false, 'Battery powered wireless Katana Air combo.'),
  ('guitar_amp', 'Boss', 'Katana-Air EX', 'Katana', false, 'Extended feature Katana Air EX with expanded amp models.'),
  ('guitar_amp', 'Boss', 'Katana-Mini', 'Katana', true, 'Portable battery powered Katana Mini practice amp.'),
  ('guitar_amp', 'Boss', 'Katana-Mini X', 'Katana', false, 'Katana Mini X with Bluetooth and effects.'),
  ('guitar_amp', 'Boss', 'Nextone Special', 'Nextone', false, '80 watt Nextone Special combo with Tube Logic circuit.'),
  ('guitar_amp', 'Boss', 'Nextone Stage', 'Nextone', false, '40 watt Nextone Stage combo.'),
  ('guitar_amp', 'Boss', 'Nextone Artist', 'Nextone', false, '80 watt Nextone Artist premium combo.'),
  ('guitar_amp', 'Boss', 'Cube Street II', 'Cube Street', false, 'Second gen Cube Street II battery powered busker amp.'),
  ('guitar_amp', 'Boss', 'Dual Cube LX', 'Dual Cube', false, 'Portable Dual Cube LX with stereo speakers.'),
  ('guitar_amp', 'Boss', 'Waza Amp Head', 'Waza', false, 'Premium Waza amp head with hand crafted circuitry.'),
  ('guitar_amp', 'Line 6', 'Catalyst 60', 'Catalyst', true, '60 watt Catalyst 1x12 modeling combo with HX amp models.'),
  ('guitar_amp', 'Line 6', 'Catalyst 100', 'Catalyst', true, '100 watt Catalyst 1x12 modeling combo.'),
  ('guitar_amp', 'Line 6', 'Catalyst 200', 'Catalyst', false, '200 watt Catalyst 2x12 combo.'),
  ('guitar_amp', 'Line 6', 'Catalyst CX 60', 'Catalyst CX', false, 'Second gen Catalyst CX 60 with expanded features.'),
  ('guitar_amp', 'Line 6', 'Catalyst CX 100', 'Catalyst CX', false, 'Second gen Catalyst CX 100.'),
  ('guitar_amp', 'Line 6', 'Catalyst CX 200', 'Catalyst CX', false, 'Second gen Catalyst CX 200 2x12.'),
  ('guitar_amp', 'Line 6', 'Spider V 20 MkII', 'Spider V', false, '20 watt Spider V MkII practice combo with modeling.'),
  ('guitar_amp', 'Line 6', 'Spider V 30 MkII', 'Spider V', false, '30 watt Spider V MkII combo.'),
  ('guitar_amp', 'Line 6', 'Spider V 60 MkII', 'Spider V', false, '60 watt Spider V MkII combo.'),
  ('guitar_amp', 'Line 6', 'Spider V 120 MkII', 'Spider V', false, '120 watt Spider V MkII combo.'),
  ('guitar_amp', 'Line 6', 'Spider V 240 MkII', 'Spider V', false, '240 watt Spider V MkII 2x12 combo.'),
  ('guitar_amp', 'Line 6', 'Powercab 112', 'Powercab', false, '250 watt active FRFR Powercab 112 with speaker models.'),
  ('guitar_amp', 'Line 6', 'Powercab 112 Plus', 'Powercab', false, '250 watt Powercab 112 Plus with IR loading.'),
  ('guitar_amp', 'Positive Grid', 'Spark 40', 'Spark', true, '40 watt Spark smart amp with app based tone matching.'),
  ('guitar_amp', 'Positive Grid', 'Spark GO', 'Spark', false, '5 watt portable Spark GO with Bluetooth.'),
  ('guitar_amp', 'Positive Grid', 'Spark MINI', 'Spark', true, '10 watt Spark MINI portable Bluetooth combo.'),
  ('guitar_amp', 'Positive Grid', 'Spark LIVE', 'Spark', false, '150 watt Spark LIVE with 4 speakers.'),
  ('guitar_amp', 'Positive Grid', 'Spark 2', 'Spark', true, 'Second gen Spark with improved DSP and jam features.'),
  ('guitar_amp', 'Positive Grid', 'Spark NEO', 'Spark', false, 'Compact Spark NEO with headphone monitoring.'),
  ('guitar_amp', 'Yamaha', 'THR5', 'THR', false, '5 watt battery powered THR5 desktop combo.'),
  ('guitar_amp', 'Yamaha', 'THR5A', 'THR', false, 'THR5A acoustic version with acoustic guitar voicings.'),
  ('guitar_amp', 'Yamaha', 'THR10II', 'THR', true, '20 watt THR10II desktop combo with Bluetooth.'),
  ('guitar_amp', 'Yamaha', 'THR10II Wireless', 'THR', false, 'THR10II Wireless with G10T wireless receiver.'),
  ('guitar_amp', 'Yamaha', 'THR30II Wireless', 'THR', true, '30 watt THR30II Wireless with expanded features.'),
  ('guitar_amp', 'Yamaha', 'THR30IIA Wireless', 'THR', false, 'THR30IIA Wireless acoustic version.'),
  ('guitar_amp', 'Blackstar', 'Debut 10E', 'Debut', false, '10 watt Debut practice amp with delay and MP3 input.'),
  ('guitar_amp', 'Blackstar', 'Debut 15E', 'Debut', false, '15 watt Debut with tape delay and reverb.'),
  ('guitar_amp', 'Blackstar', 'Debut 50R', 'Debut', false, '50 watt Debut combo with reverb.'),
  ('guitar_amp', 'Blackstar', 'Fly 3', 'Fly', true, 'Compact 3 watt battery powered Fly practice amp.'),
  ('guitar_amp', 'Blackstar', 'ID:Core 10 V3', 'ID:Core', false, '10 watt ID:Core V3 modeling combo with 6 amp voices.'),
  ('guitar_amp', 'Blackstar', 'ID:Core 20 V3', 'ID:Core', false, '20 watt ID:Core V3 modeling combo.'),
  ('guitar_amp', 'Blackstar', 'ID:Core 40 V3', 'ID:Core', false, '40 watt ID:Core V3 modeling combo.'),
  ('guitar_amp', 'Blackstar', 'Silverline Special', 'Silverline', false, 'Digital Silverline Special combo with True Valve Power.'),
  ('guitar_amp', 'Blackstar', 'Silverline Deluxe', 'Silverline', false, 'Digital Silverline Deluxe 100 watt combo.'),
  ('guitar_amp', 'Blackstar', 'Silverline Stage', 'Silverline', false, 'Digital Silverline Stage 100 watt 1x12 combo.'),
  ('guitar_amp', 'Blackstar', 'Sonnet 60', 'Sonnet', false, '60 watt Sonnet acoustic amp with dual channels.'),
  ('guitar_amp', 'Blackstar', 'Sonnet 120', 'Sonnet', false, '120 watt Sonnet acoustic amp with feedback control.'),
  ('guitar_amp', 'Blackstar', 'HT-1R MkII', 'HT', false, '1 watt HT-1R MkII tube practice combo with reverb.'),
  ('guitar_amp', 'Blackstar', 'HT-5R MkII', 'HT', false, '5 watt HT-5R MkII tube combo with reverb.'),
  ('guitar_amp', 'Blackstar', 'HT-20R MkII', 'HT', false, '20 watt HT-20R MkII tube combo with reverb.'),
  ('guitar_amp', 'Blackstar', 'HT Club 40 MkII', 'HT Club', false, '40 watt HT Club MkII tube combo with reverb.'),
  ('guitar_amp', 'Blackstar', 'HT Stage 60 212 MkII', 'HT Stage', false, '60 watt HT Stage MkII with dual 12 inch speakers.'),
  ('guitar_amp', 'Blackstar', 'St. James 50 6L6 Combo', 'St. James', false, '50 watt St. James lightweight tube combo with 6L6 tubes.'),
  ('guitar_amp', 'Blackstar', 'St. James 50 6L6 Head', 'St. James', false, '50 watt St. James lightweight tube head with 6L6 tubes.'),
  ('guitar_amp', 'Blackstar', 'St. James 50 EL34 Head', 'St. James', false, '50 watt St. James head with EL34 tubes.'),
  ('guitar_amp', 'Blackstar', 'Dept.10 AMPED 1', 'Dept.10', false, '100 watt AMPED 1 pedal amp with tube preamp.'),
  ('guitar_amp', 'Blackstar', 'Dept.10 AMPED 2', 'Dept.10', false, '100 watt AMPED 2 with British voicing.'),
  ('guitar_amp', 'Blackstar', 'Dept.10 AMPED 3', 'Dept.10', false, '100 watt AMPED 3 with modern high gain voicing.'),
  ('guitar_amp', 'Peavey', '6505 II Head', '6505', true, 'Updated 6505 II head with 6L6 tubes and modern refinements.'),
  ('guitar_amp', 'Peavey', '6505 MH Mini Head', '6505', true, '20 watt 6505 MH lunchbox head.'),
  ('guitar_amp', 'Peavey', '6505+ 112 Combo', '6505', false, '60 watt 6505+ 1x12 combo.'),
  ('guitar_amp', 'Peavey', 'Invective MH', 'Invective', false, '20 watt Invective MH lunchbox head co-designed with Misha Mansoor.'),
  ('guitar_amp', 'Peavey', 'Invective.120', 'Invective', false, '120 watt Invective head with three channels.'),
  ('guitar_amp', 'Peavey', 'Classic 30 112', 'Classic', true, '30 watt Classic 30 1x12 tube combo.'),
  ('guitar_amp', 'Peavey', 'Classic 50 212', 'Classic', false, '50 watt Classic 50 2x12 tube combo.'),
  ('guitar_amp', 'Peavey', 'Delta Blues 210 II', 'Delta Blues', false, '30 watt Delta Blues II combo with 2x10 speakers.'),
  ('guitar_amp', 'Peavey', 'Bandit 112', 'Bandit', true, '80 watt Bandit 1x12 combo with TransTube technology.'),
  ('guitar_amp', 'Peavey', 'Vypyr X1', 'Vypyr', false, '20 watt Vypyr X1 modeling combo.'),
  ('guitar_amp', 'Peavey', 'Vypyr X2', 'Vypyr', false, '40 watt Vypyr X2 modeling combo.'),
  ('guitar_amp', 'Peavey', 'Vypyr X3', 'Vypyr', false, '100 watt Vypyr X3 modeling combo.'),
  ('guitar_amp', 'Peavey', 'ValveKing II 20 Micro Head', 'ValveKing', false, '20 watt ValveKing II lunchbox head.'),
  ('guitar_amp', 'Mesa Boogie', 'Mark VII', 'Mark', true, 'Mark VII head with three channels and updated Boogie voicing.'),
  ('guitar_amp', 'Mesa Boogie', 'Mark Five 25', 'Mark Five', false, '25 watt Mark Five combo with multiple modes.'),
  ('guitar_amp', 'Mesa Boogie', 'Mark Five 35', 'Mark Five', false, '35 watt Mark Five combo.'),
  ('guitar_amp', 'Mesa Boogie', 'Mark Five 90', 'Mark Five', false, '90 watt Mark Five head with 9 amp modes.'),
  ('guitar_amp', 'Mesa Boogie', 'JP-2C', 'Signature', false, 'John Petrucci JP-2C signature head based on the Mark IIC+.'),
  ('guitar_amp', 'Mesa Boogie', 'Badlander 25', 'Badlander', true, '25 watt Badlander head with modern high gain voicing.'),
  ('guitar_amp', 'Mesa Boogie', 'Badlander 50', 'Badlander', false, '50 watt Badlander head or combo.'),
  ('guitar_amp', 'Mesa Boogie', 'Badlander 100', 'Badlander', false, '100 watt Badlander flagship head.'),
  ('guitar_amp', 'Mesa Boogie', 'California Tweed 6V6 2:20', 'California Tweed', false, '20 watt California Tweed combo with 6V6 tubes.'),
  ('guitar_amp', 'Mesa Boogie', 'California Tweed 6V6 4:40', 'California Tweed', false, '40 watt California Tweed 4x6V6 combo.'),
  ('guitar_amp', 'Mesa Boogie', 'Fillmore 25', 'Fillmore', false, '25 watt Fillmore combo with vintage voicing.'),
  ('guitar_amp', 'Mesa Boogie', 'Fillmore 50', 'Fillmore', false, '50 watt Fillmore head or combo.'),
  ('guitar_amp', 'Mesa Boogie', 'Fillmore 100', 'Fillmore', false, '100 watt Fillmore head with three channels.'),
  ('guitar_amp', 'Mesa Boogie', 'Lone Star Special', 'Lone Star', false, '30 watt Lone Star Special combo.'),
  ('guitar_amp', 'Mesa Boogie', 'TC-50 Triple Crown', 'Triple Crown', false, '50 watt Triple Crown TC-50 head.'),
  ('guitar_amp', 'Mesa Boogie', 'Rectoverb 25', 'Rectoverb', false, '25 watt Rectoverb combo with Rectifier voicing and reverb.'),
  ('guitar_amp', 'EVH', '5150III 50W 6L6 Head', '5150III', true, '50 watt 5150III head with 6L6 tubes and three channels.'),
  ('guitar_amp', 'EVH', '5150III 50W 6L6 Combo', '5150III', false, '50 watt 5150III 1x12 combo with 6L6 tubes.'),
  ('guitar_amp', 'EVH', '5150III 50W EL34 Head', '5150III', false, '50 watt 5150III head with EL34 tubes.'),
  ('guitar_amp', 'EVH', '5150III 100W Head', '5150III', false, '100 watt 5150III head with three channels.'),
  ('guitar_amp', 'EVH', '5150 Iconic 15W 1x10', '5150 Iconic', true, '15 watt 5150 Iconic 1x10 combo.'),
  ('guitar_amp', 'EVH', '5150 Iconic 40W 1x12', '5150 Iconic', false, '40 watt 5150 Iconic 1x12 combo.'),
  ('guitar_amp', 'EVH', '5150 Iconic 60W Head', '5150 Iconic', false, '60 watt 5150 Iconic head.'),
  ('guitar_amp', 'EVH', '5150III LBX', '5150III', false, '15 watt 5150III LBX lunchbox head.'),
  ('guitar_amp', 'EVH', '5150III LBXII', '5150III', false, '15 watt 5150III LBXII lunchbox head.'),
  ('guitar_amp', 'Hughes & Kettner', 'TubeMeister Deluxe 20', 'TubeMeister', false, '20 watt TubeMeister Deluxe head with Red Box DI.'),
  ('guitar_amp', 'Hughes & Kettner', 'TubeMeister Deluxe 40', 'TubeMeister', false, '40 watt TubeMeister Deluxe head.'),
  ('guitar_amp', 'Hughes & Kettner', 'GrandMeister Deluxe 40', 'GrandMeister', false, '40 watt GrandMeister Deluxe with MIDI and effects.'),
  ('guitar_amp', 'Hughes & Kettner', 'Black Spirit 200 Head', 'Black Spirit', true, '200 watt Black Spirit 200 head with Spirit Tone Generator.'),
  ('guitar_amp', 'Hughes & Kettner', 'Black Spirit 200 Combo', 'Black Spirit', false, '200 watt Black Spirit 200 combo.'),
  ('guitar_amp', 'Hughes & Kettner', 'Black Spirit 200 Floor', 'Black Spirit', false, '200 watt Black Spirit 200 Floor pedalboard format.'),
  ('guitar_amp', 'Hughes & Kettner', 'Spirit of Rock Nano', 'Spirit', false, '50 watt Spirit of Rock Nano head with British voicing.'),
  ('guitar_amp', 'Hughes & Kettner', 'Spirit of Metal Nano', 'Spirit', false, '50 watt Spirit of Metal Nano head with high gain voicing.'),
  ('guitar_amp', 'Hughes & Kettner', 'Spirit of Vintage Nano', 'Spirit', false, '50 watt Spirit of Vintage Nano head with clean/crunch voicing.'),
  ('guitar_amp', 'Hughes & Kettner', 'AmpMan Classic', 'AmpMan', false, 'Pedalboard format 50 watt AmpMan Classic amp.'),
  ('guitar_amp', 'Hughes & Kettner', 'AmpMan Modern', 'AmpMan', false, 'Pedalboard format 50 watt AmpMan Modern amp.'),
  ('guitar_amp', 'Laney', 'IRT Studio', 'Ironheart', false, '15 watt IRT Studio all tube head with USB recording.'),
  ('guitar_amp', 'Laney', 'Ironheart IRT60H', 'Ironheart', false, '60 watt Ironheart IRT60H head with three channels.'),
  ('guitar_amp', 'Laney', 'Ironheart IRT120H', 'Ironheart', false, '120 watt Ironheart flagship head.'),
  ('guitar_amp', 'Laney', 'Lionheart L5T-112', 'Lionheart', false, '5 watt Lionheart L5T 1x12 hand wired combo.'),
  ('guitar_amp', 'Laney', 'Lionheart L20T-212', 'Lionheart', false, '20 watt Lionheart L20T 2x12 hand wired combo.'),
  ('guitar_amp', 'Laney', 'Lionheart L20H', 'Lionheart', false, '20 watt Lionheart L20H hand wired head.'),
  ('guitar_amp', 'Laney', 'Cub Super 10', 'Cub', false, '10 watt Cub Super combo with 10 inch speaker.'),
  ('guitar_amp', 'Laney', 'Cub Super 12R', 'Cub', false, '15 watt Cub Super combo with reverb.'),
  ('guitar_amp', 'Laney', 'LX65R', 'LX', false, '65 watt LX65R solid-state combo with reverb.'),
  ('guitar_amp', 'Bugera', 'V5 Infinium', 'V', false, '5 watt V5 Infinium tube combo with attenuator.'),
  ('guitar_amp', 'Bugera', 'V22 Infinium', 'V', false, '22 watt V22 Infinium 1x12 tube combo.'),
  ('guitar_amp', 'Bugera', 'V55 Infinium', 'V', false, '55 watt V55 Infinium 1x12 tube combo.'),
  ('guitar_amp', 'Bugera', '6262 Infinium', '6262', false, '120 watt 6262 Infinium head with dual channels.'),
  ('guitar_amp', 'Bugera', '333XL Infinium', '333', false, '120 watt 333XL Infinium head with three channels.'),
  ('guitar_amp', 'Bugera', 'T50 Infinium', 'T', false, '50 watt T50 Infinium head with tube monitoring.'),
  ('guitar_amp', 'Randall', 'Diavlo RD5H', 'Diavlo', false, '5 watt Diavlo RD5 tube lunchbox head.'),
  ('guitar_amp', 'Randall', 'Diavlo RD20H', 'Diavlo', false, '20 watt Diavlo RD20 tube head.'),
  ('guitar_amp', 'Randall', 'Diavlo RD45H', 'Diavlo', false, '45 watt Diavlo RD45 tube head.'),
  ('guitar_amp', 'Randall', 'RG80', 'RG', false, '80 watt RG80 solid-state combo.'),
  ('guitar_amp', 'Randall', 'Satan 50', 'Satan', false, 'Ola Englund signature Satan 50 head.'),
  ('guitar_amp', 'Randall', 'Thrasher 120', 'Thrasher', false, '120 watt Thrasher head with high gain voicing.'),
  ('guitar_amp', 'Engl', 'Fireball 25', 'Fireball', false, '25 watt Fireball head with modern high gain voicing.'),
  ('guitar_amp', 'Engl', 'Fireball 60', 'Fireball', false, '60 watt Fireball head with two channels.'),
  ('guitar_amp', 'Engl', 'Fireball 100', 'Fireball', false, '100 watt Fireball head.'),
  ('guitar_amp', 'Engl', 'Powerball II', 'Powerball', false, '100 watt Powerball II with 4 channels.'),
  ('guitar_amp', 'Engl', 'Savage 120 MkII', 'Savage', false, '120 watt Savage MkII head with 4 channels.'),
  ('guitar_amp', 'Engl', 'Ironball SE 20', 'Ironball', false, '20 watt Ironball Special Edition lunchbox head.'),
  ('guitar_amp', 'Diezel', 'VH4', 'VH', true, '100 watt VH4 flagship head with four channels.'),
  ('guitar_amp', 'Diezel', 'Herbert MkIII', 'Herbert', false, '180 watt Herbert MkIII flagship head with three channels.'),
  ('guitar_amp', 'Diezel', 'Hagen', 'Hagen', false, '100 watt Hagen head with four channels.'),
  ('guitar_amp', 'Diezel', 'Paul', 'Paul', false, '45 watt Paul head with two channels and lightweight design.'),
  ('guitar_amp', 'Diezel', 'D-Moll', 'D-Moll', false, '100 watt D-Moll head with three channels.'),
  ('guitar_amp', 'Diezel', 'VHX', 'VHX', false, '100 watt VHX programmable head with MIDI.'),
  ('guitar_amp', 'Friedman', 'BE-50 Deluxe', 'BE', false, '50 watt BE-50 Deluxe head with three channels.'),
  ('guitar_amp', 'Friedman', 'BE-Mini', 'BE', false, '30 watt BE-Mini head with two channels.'),
  ('guitar_amp', 'Friedman', 'Smallbox 50 Head', 'Smallbox', false, '50 watt Smallbox 50 head with two channels.'),
  ('guitar_amp', 'Friedman', 'Dirty Shirley 40 Head', 'Dirty Shirley', false, '40 watt Dirty Shirley head.'),
  ('guitar_amp', 'Friedman', 'Dirty Shirley Combo', 'Dirty Shirley', false, '40 watt Dirty Shirley 1x12 combo.'),
  ('guitar_amp', 'Friedman', 'JJ-100 Jerry Cantrell', 'Signature', false, 'Jerry Cantrell signature JJ-100 head.'),
  ('guitar_amp', 'Friedman', 'Runt-20 Head', 'Runt', false, '20 watt Runt lunchbox head.'),
  ('guitar_amp', 'Friedman', 'Runt-50 Head', 'Runt', false, '50 watt Runt head with two channels.'),
  ('guitar_amp', 'Friedman', 'PT-20 Pink Taco', 'Pink Taco', false, '20 watt Pink Taco PT-20 head.'),
  ('guitar_amp', 'Bogner', 'Shiva 20th Anniversary', 'Shiva', false, '80 watt Shiva 20th Anniversary head.'),
  ('guitar_amp', 'Bogner', 'Uberschall Revision Blue', 'Uberschall', false, '150 watt Uberschall Revision Blue head with high gain voicing.'),
  ('guitar_amp', 'Bogner', 'Helios 50', 'Helios', false, '50 watt Helios head based on the Uberkab loaded 100 watt.'),
  ('guitar_amp', 'Bogner', 'Helios 100', 'Helios', false, '100 watt Helios head with hot rodded Plexi voicing.'),
  ('guitar_amp', 'Bogner', 'Atma Head', 'Atma', false, '18 watt Atma multi-power hand wired head.'),
  ('guitar_amp', 'Bogner', 'Goldfinger 45', 'Goldfinger', false, '45 watt Goldfinger head with two channels.'),
  ('guitar_amp', 'Soldano', 'SLO-100 Classic', 'SLO', true, 'Reissue of the classic 100 watt SLO with high gain voicing.'),
  ('guitar_amp', 'Soldano', 'SLO-30 Head', 'SLO', false, '30 watt SLO-30 head with SLO circuit.'),
  ('guitar_amp', 'Soldano', 'SLO-30 1x12 Combo', 'SLO', false, '30 watt SLO-30 1x12 combo.'),
  ('guitar_amp', 'Soldano', 'Astro-20', 'Astro', false, '20 watt Astro-20 lunchbox head with three channels.'),
  ('guitar_amp', 'Revv', 'Generator 120 MkIII', 'Generator', false, '120 watt Generator 120 MkIII head with four channels.'),
  ('guitar_amp', 'Revv', 'Generator 100R MkII', 'Generator', false, '100 watt Generator 100R MkII head with reverb.'),
  ('guitar_amp', 'Revv', 'Generator 100P MkII', 'Generator', false, '100 watt Generator 100P MkII head.'),
  ('guitar_amp', 'Revv', 'D20', 'D', false, '20 watt D20 lunchbox head with Two Notes cab sim.'),
  ('guitar_amp', 'Revv', 'G20', 'G', false, '20 watt G20 lunchbox head with cab sim.'),
  ('guitar_amp', 'Victory', 'V40 The Duchess Deluxe Head', 'V40', false, '40 watt V40 The Duchess Deluxe head.'),
  ('guitar_amp', 'Victory', 'V40 The Duchess Deluxe Combo', 'V40', false, '40 watt V40 Duchess Deluxe 1x12 combo.'),
  ('guitar_amp', 'Victory', 'VC35 The Copper Deluxe Head', 'VC35', false, '35 watt VC35 Copper Deluxe head.'),
  ('guitar_amp', 'Victory', 'RK50 Richie Kotzen Head', 'Signature', false, '50 watt Richie Kotzen RK50 signature head.'),
  ('guitar_amp', 'Victory', 'The Sheriff 44', 'Sheriff', false, '44 watt Sheriff 44 head with two channels.'),
  ('guitar_amp', 'Victory', 'V4 The Jack Guitar Amp', 'V4', false, '180 watt V4 Jack pedalboard amp with British voicing.'),
  ('guitar_amp', 'Victory', 'V4 The Duchess Guitar Amp', 'V4', false, '180 watt V4 Duchess pedalboard amp with American voicing.'),
  ('guitar_amp', 'Victory', 'V4 The Kraken Guitar Amp', 'V4', false, '180 watt V4 Kraken pedalboard amp with high gain voicing.'),
  ('guitar_amp', 'Victory', 'V4 The Sheriff Guitar Amp', 'V4', false, '180 watt V4 Sheriff pedalboard amp with Marshall style voicing.'),
  ('guitar_amp', 'NUX', 'Mighty 8BT MkII', 'Mighty', false, '8 watt Mighty 8BT MkII with Bluetooth.'),
  ('guitar_amp', 'NUX', 'Mighty 20BT', 'Mighty', false, '20 watt Mighty 20BT modeling combo.'),
  ('guitar_amp', 'NUX', 'Mighty 40BT', 'Mighty', false, '40 watt Mighty 40BT modeling combo.'),
  ('guitar_amp', 'NUX', 'Mighty Space', 'Mighty', false, '30 watt Mighty Space wireless modeling combo.'),
  ('guitar_amp', 'NUX', 'Mighty Lite BT MkII', 'Mighty', false, 'Compact Mighty Lite BT MkII with Bluetooth.'),
  ('guitar_amp', 'Joyo', 'BanTamP JackMan JMA-10', 'BanTamP', false, 'Compact JackMan lunchbox head with British voicing.'),
  ('guitar_amp', 'Joyo', 'BanTamP Meteor MET-8', 'BanTamP', false, 'Compact Meteor lunchbox head with modern high gain.'),
  ('guitar_amp', 'Joyo', 'BanTamP Zombie ZOM-6', 'BanTamP', false, 'Compact Zombie lunchbox head with high gain voicing.'),
  ('guitar_amp', 'Joyo', 'BanTamP Vivo VIV-3', 'BanTamP', false, 'Compact Vivo lunchbox head with vintage voicing.'),
  ('guitar_amp', 'Joyo', 'BanTamP Bluejay BLJ-5', 'BanTamP', false, 'Compact Bluejay lunchbox head with blues voicing.'),
  ('guitar_amp', 'Joyo', 'BanTamP Atomic ATM-7', 'BanTamP', false, 'Compact Atomic lunchbox head with modern voicing.'),
  ('guitar_amp', 'Mooer', 'Hornet 15i', 'Hornet', false, '15 watt Hornet 15i modeling combo with iOS connectivity.'),
  ('guitar_amp', 'Mooer', 'Hornet White', 'Hornet', false, 'Hornet White 15 watt modeling combo.'),
  ('guitar_amp', 'Mooer', 'SD30', 'SD', false, '30 watt SD30 modeling combo with GNR Audio Interface.'),
  ('guitar_amp', 'Mooer', 'SD75', 'SD', false, '75 watt SD75 modeling combo.'),
  ('guitar_amp', 'Harley Benton', 'TUBE5 Celestion', 'TUBE', false, '5 watt TUBE5 Celestion tube combo.'),
  ('guitar_amp', 'Harley Benton', 'TUBE15 Head', 'TUBE', false, '15 watt TUBE15 tube head.'),
  ('guitar_amp', 'Harley Benton', 'HB-20R', 'HB', false, '20 watt HB-20R practice combo with reverb.'),
  ('guitar_amp', 'Harley Benton', 'TUBE30C', 'TUBE', false, '30 watt TUBE30C tube combo.'),
  ('guitar_amp', 'Quilter', 'SuperBlock US', 'SuperBlock', false, '25 watt SuperBlock US pedalboard head with American voicing.'),
  ('guitar_amp', 'Quilter', 'SuperBlock UK', 'SuperBlock', false, '25 watt SuperBlock UK pedalboard head with British voicing.'),
  ('guitar_amp', 'Quilter', 'OverDrive 202', 'OverDrive', false, '200 watt OverDrive 202 head with dual channels.'),
  ('guitar_amp', 'Quilter', 'Aviator Cub', 'Aviator', false, '50 watt Aviator Cub 1x12 combo.'),
  ('guitar_amp', 'Quilter', '101 Reverb Head', '101', false, '50 watt 101 Reverb pedalboard head.'),
  ('guitar_amp', 'Hotone', 'Nano Legacy British Invasion', 'Nano Legacy', false, '5 watt Nano Legacy British Invasion mini head.'),
  ('guitar_amp', 'Hotone', 'Nano Legacy Purple Wind', 'Nano Legacy', false, '5 watt Nano Legacy Purple Wind mini head with high gain voicing.'),
  ('guitar_amp', 'Hotone', 'Nano Legacy Mojo Diamond', 'Nano Legacy', false, '5 watt Nano Legacy Mojo Diamond mini head.'),
  ('guitar_amp', 'Hotone', 'Nano Legacy Heart Attack', 'Nano Legacy', false, '5 watt Nano Legacy Heart Attack mini head.'),
  ('guitar_amp', 'Hotone', 'Pulze Luna', 'Pulze', false, 'Pulze Luna compact modeling amp.'),
  ('guitar_amp', 'Fishman', 'Loudbox Mini', 'Loudbox', true, '60 watt Loudbox Mini acoustic amp with dual channels.'),
  ('guitar_amp', 'Fishman', 'Loudbox Mini Charge', 'Loudbox', false, '60 watt Loudbox Mini Charge battery powered acoustic amp.'),
  ('guitar_amp', 'Fishman', 'Loudbox Artist', 'Loudbox', false, '120 watt Loudbox Artist acoustic amp.'),
  ('guitar_amp', 'Fishman', 'Loudbox Performer', 'Loudbox', false, '180 watt Loudbox Performer acoustic amp.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
