-- Phase 95 (partial): 80s rock tier-2 verification: researched verified tone profiles (generated 2026-08-06).
-- Assembled from per-artist research fragments; rigs sourced from
-- Equipboard/GroundGuitar/manufacturer interviews per song.
begin;

create temp table phase_targets(
  artist_name text, artist_slug text, song_title text, song_slug text,
  album text, release_year int
) on commit drop;

insert into phase_targets(artist_name, artist_slug, song_title, song_slug, album, release_year) values
('Blue Oyster Cult','blue-oyster-cult','Astronomy','astronomy','Secret Treaties',1974),
('Blue Oyster Cult','blue-oyster-cult','Burnin'' for You','burnin-for-you','Fire of Unknown Origin',1981),
('Blue Oyster Cult','blue-oyster-cult','Godzilla','godzilla','Spectres',1977),
('Blue Oyster Cult','blue-oyster-cult','Cities on Flame with Rock and Roll','cities-on-flame-with-rock-and-roll','Blue Oyster Cult',1972),
('Blue Oyster Cult','blue-oyster-cult','Flaming Telepaths','flaming-telepaths','Secret Treaties',1974),
('Blue Oyster Cult','blue-oyster-cult','Buck''s Boogie','bucks-boogie','On Your Feet or on Your Knees',1975),
('Blue Oyster Cult','blue-oyster-cult','Tattoo Vampire','tattoo-vampire','Agents of Fortune',1976),
('Blue Oyster Cult','blue-oyster-cult','E.T.I. (Extra Terrestrial Intelligence)','eti-extra-terrestrial-intelligence','Agents of Fortune',1976),
('Blue Oyster Cult','blue-oyster-cult','The Last Days of May','the-last-days-of-may','Blue Oyster Cult',1972),
('Bryan Adams','bryan-adams','Run to You','run-to-you','Reckless',1984),
('Bryan Adams','bryan-adams','Heaven','heaven','Reckless',1984),
('Bryan Adams','bryan-adams','Cuts Like a Knife','cuts-like-a-knife','Cuts Like a Knife',1983),
('Bryan Adams','bryan-adams','Somebody','somebody','Reckless',1984),
('Bryan Adams','bryan-adams','(Everything I Do) I Do It for You','everything-i-do-i-do-it-for-you','Waking Up the Neighbours',1991),
('Bryan Adams','bryan-adams','It''s Only Love','its-only-love','Reckless',1984),
('Bryan Adams','bryan-adams','Kids Wanna Rock','kids-wanna-rock','Reckless',1984),
('Bryan Adams','bryan-adams','Straight from the Heart','straight-from-the-heart','Cuts Like a Knife',1983),
('Bryan Adams','bryan-adams','Can''t Stop This Thing We Started','cant-stop-this-thing-we-started','Waking Up the Neighbours',1991),
('Bryan Adams','bryan-adams','Please Forgive Me','please-forgive-me','So Far So Good',1993),
('Bryan Adams','bryan-adams','18 Til I Die','18-til-i-die','18 til I Die',1996),
('Bon Jovi','bon-jovi','Bad Medicine','bad-medicine','New Jersey',1988),
('Bon Jovi','bon-jovi','It''s My Life','its-my-life','Crush',2000),
('Bon Jovi','bon-jovi','Blaze of Glory','blaze-of-glory','Blaze of Glory',1990),
('Bon Jovi','bon-jovi','Keep the Faith','keep-the-faith','Keep the Faith',1992),
('Bon Jovi','bon-jovi','In These Arms','in-these-arms','Keep the Faith',1992),
('Bon Jovi','bon-jovi','Born to Be My Baby','born-to-be-my-baby','New Jersey',1988),
('Bon Jovi','bon-jovi','Lay Your Hands on Me','lay-your-hands-on-me','New Jersey',1988),
('Bon Jovi','bon-jovi','Have a Nice Day','have-a-nice-day','Have a Nice Day',2005),
('Bon Jovi','bon-jovi','I''ll Be There for You','ill-be-there-for-you','New Jersey',1988),
('Def Leppard','def-leppard','Animal','animal','Hysteria',1987),
('Def Leppard','def-leppard','Love Bites','love-bites','Hysteria',1987),
('Def Leppard','def-leppard','Foolin''','foolin','Pyromania',1983),
('Def Leppard','def-leppard','Bringin'' On the Heartbreak','bringin-on-the-heartbreak','High ''n'' Dry',1981),
('Def Leppard','def-leppard','Hysteria','hysteria','Hysteria',1987),
('Def Leppard','def-leppard','Armageddon It','armageddon-it','Hysteria',1987),
('Def Leppard','def-leppard','Let''s Get Rocked','lets-get-rocked','Adrenalize',1992),
('Def Leppard','def-leppard','Rocket','rocket','Hysteria',1987),
('Scorpions','scorpions','No One Like You','no-one-like-you','Blackout',1982),
('Scorpions','scorpions','Blackout','blackout','Blackout',1982),
('Scorpions','scorpions','The Zoo','the-zoo','Animal Magnetism',1980),
('Scorpions','scorpions','Send Me an Angel','send-me-an-angel','Crazy World',1990),
('Scorpions','scorpions','Big City Nights','big-city-nights','Love at First Sting',1984),
('Scorpions','scorpions','Coast to Coast','coast-to-coast','Lovedrive',1979),
('Scorpions','scorpions','Holiday','holiday','Lovedrive',1979),
('Scorpions','scorpions','Bad Boys Running Wild','bad-boys-running-wild','Love at First Sting',1984),
('Scorpions','scorpions','Dynamite','dynamite','Blackout',1982),
('Duran Duran','duran-duran','Hungry Like the Wolf','hungry-like-the-wolf','Rio',1982),
('Duran Duran','duran-duran','Girls on Film','girls-on-film','Duran Duran',1981),
('Duran Duran','duran-duran','Save a Prayer','save-a-prayer','Rio',1982),
('Duran Duran','duran-duran','The Reflex','the-reflex','Seven and the Ragged Tiger',1983),
('Duran Duran','duran-duran','Notorious','notorious','Notorious',1986),
('Duran Duran','duran-duran','Wild Boys','wild-boys','Arena',1984),
('Duran Duran','duran-duran','Skin Trade','skin-trade','Notorious',1986);

insert into public.artists (name, slug, search_text, is_active)
select distinct artist_name, artist_slug, artist_name, true from phase_targets
on conflict (slug) do update set name = excluded.name, is_active = true;

insert into public.songs (artist_id, title, slug, album, release_year, search_text, is_active)
select a.id, t.song_title, t.song_slug, t.album, t.release_year,
       concat_ws(' ', t.song_title, t.artist_name, t.album), true
from phase_targets t join public.artists a on a.slug = t.artist_slug
on conflict (artist_id, slug) do update set
  title = excluded.title, album = excluded.album, release_year = excluded.release_year,
  is_active = true, updated_at = now();

-- Hide pre-existing duplicate songs (same artist+title, different slug)
update public.song_tone_profiles p
set is_public = false
from public.songs s, public.artists a, phase_targets t
where p.song_id = s.id and s.artist_id = a.id and a.slug = t.artist_slug
  and lower(s.title) = lower(t.song_title) and s.slug <> t.song_slug;

update public.songs s
set is_active = false
from public.artists a, phase_targets t
where s.artist_id = a.id and a.slug = t.artist_slug
  and lower(s.title) = lower(t.song_title) and s.slug <> t.song_slug;

-- Replace existing guitar profiles for target songs
delete from public.tone_profile_effects e where e.profile_id in (
  select p.id from public.song_tone_profiles p
  join public.songs s on s.id = p.song_id join public.artists a on a.id = s.artist_id
  join phase_targets t on t.artist_slug = a.slug and t.song_slug = s.slug
  where p.mode = 'guitar'
);
delete from public.tone_profile_sources src where src.profile_id in (
  select p.id from public.song_tone_profiles p
  join public.songs s on s.id = p.song_id join public.artists a on a.id = s.artist_id
  join phase_targets t on t.artist_slug = a.slug and t.song_slug = s.slug
  where p.mode = 'guitar'
);
delete from public.song_tone_profiles p where p.mode = 'guitar' and p.id in (
  select p2.id from public.song_tone_profiles p2
  join public.songs s on s.id = p2.song_id join public.artists a on a.id = s.artist_id
  join phase_targets t on t.artist_slug = a.slug and t.song_slug = s.slug
);

insert into public.song_tone_profiles (
  song_id, song_title, artist_name, mode, part_type, part_label, tone_type,
  genre, tone_category, difficulty,
  original_guitar, original_amp, original_cab, original_pickup,
  original_effects, original_settings, adaptation_notes, playing_notes,
  source_summary, confidence, verification_status, search_text, is_public
)
select
  s.id, s.title, a.name, c.mode, c.part_type, c.part_label, c.tone_type,
  c.genre, c.tone_category, c.difficulty,
  c.original_guitar, c.original_amp, c.original_cab, c.original_pickup,
  c.original_effects, c.original_settings, c.adaptation_notes, c.playing_notes,
  c.source_summary, c.confidence, 'admin_verified',
  concat_ws(' ', s.title, a.name, c.part_label, c.tone_type, c.original_guitar, c.original_amp, 'researched verified tone'),
  true
from (
  values
('astronomy','blue-oyster-cult','guitar','solo','extended lead section','distorted','hard rock','lead','advanced',
 'Gibson SG Standard (Buck Dharma)','Marshall Super Lead 100','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":3,"delay":2,"master":7}'::jsonb,
 array['Buck''s smooth sustained vocal-like lead tone comes from a cranked Marshall, not pedal fuzz','The song builds from moody clean picking to a soaring saturated climax, so ride the guitar volume knob'],
 array['Use legato slides and long held bends to sing through the climactic lead lines','Follow the slow-burn dynamics: hold back in the verses so the outro lead explodes'],
 'Guitar World and Equipboard document Buck Dharma''s white 1969 Gibson SG into Marshall full stacks as his core 1970s Blue Oyster Cult rig.',72),
('burnin-for-you','blue-oyster-cult','guitar','riff','main riff and hook','crunch','hard rock','rhythm','beginner',
 'Gibson SG Standard (Buck Dharma)','Marshall JMP 100','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":3,"delay":1,"master":7}'::jsonb,
 array['A polished 1981 crunch: enough gain to sustain but clean enough that the melodic hook stays articulate','Buck favors strong treble with controlled bass, so the SG bridge humbucker never gets muddy'],
 array['Let the ringing open-position riff chords bleed into each other for the drone effect','Keep downstrokes even and relaxed; the song grooves at a mid-tempo lope, not a sprint'],
 'Guitar Chalk''s Buck Dharma amp-settings breakdown and Equipboard document his SG-into-Marshall tone with strong treble and moderate mids for the Fire of Unknown Origin era.',74),
('godzilla','blue-oyster-cult','guitar','riff','main riff','distorted','hard rock','distortion','beginner',
 'Gibson SG Standard (Buck Dharma)','Marshall Super Lead 100','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":6,"mids":6,"treble":6,"presence":5,"reverb":2,"delay":0,"master":8}'::jsonb,
 array['The stomping monster riff is a mid-heavy Marshall roar, fat but still tight on the low strings','Keep some string separation so the chromatic walk-up in the riff stays distinct'],
 array['Palm-mute the opening chugs slightly then open up on the full chords for maximum stomp','Lock rigidly to the drums; the riff''s power is in its relentless repetition'],
 'Equipboard and Guitar World interviews document Buck Dharma''s Gibson SG through Marshall stacks as the core Spectres-era Blue Oyster Cult rig.',76),
('cities-on-flame-with-rock-and-roll','blue-oyster-cult','guitar','riff','main riff','distorted','hard rock','distortion','beginner',
 'Gibson SG Standard (Buck Dharma)','Marshall Super Lead 100','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":6,"mids":7,"treble":5,"presence":5,"reverb":2,"delay":0,"master":8}'::jsonb,
 array['A Black Sabbath-inspired doom riff, so favor thick midrange over modern scooped gain','Early 1970s Marshall breakup is raw and woolly, not compressed high-gain'],
 array['Dig in hard with downstrokes and let the slow riff hang behind the beat','Bend the bluesy riff endings slightly sharp for that heavy early-70s attitude'],
 'Wikipedia documents the riff as Black Sabbath-inspired, and period live footage plus Equipboard show Buck Dharma''s white Gibson SG into walls of Marshall amps in the early 1970s.',73),
('flaming-telepaths','blue-oyster-cult','guitar','solo','guitar solo','distorted','hard rock','lead','advanced',
 'Gibson SG Standard (Buck Dharma)','Marshall Super Lead 100','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":3,"delay":1,"master":7}'::jsonb,
 array['Buck''s solo cuts over the piano-driven arrangement with a singing sustained Marshall lead tone','Bridge humbucker with strong treble keeps the fast runs articulate against the dense mix'],
 array['Alternate-pick the fast climbing sequences cleanly before releasing into held bends','Land the solo phrases on chord tones; the changes move under you throughout'],
 'Equipboard and Guitar World document the Gibson SG plus Marshall stack rig Buck Dharma used throughout the Secret Treaties era.',68),
('bucks-boogie','blue-oyster-cult','guitar','lead','instrumental boogie lead','crunch','hard rock','lead','advanced',
 'Gibson SG Standard (Buck Dharma)','Marshall Super Lead 100','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":2,"delay":0,"master":7}'::jsonb,
 array['A fast instrumental showcase: moderate crunch keeps every note of the boogie lines defined','Buck''s clean articulate picking does the work; too much gain smears the shuffle runs'],
 array['Master the alternate-picked boogie shuffle pattern slowly before pushing the tempo','Mix double-stops and single-note runs; the piece is a workout in right-hand endurance'],
 'The live staple is documented on On Your Feet or on Your Knees, with Equipboard and period footage showing Buck Dharma''s Gibson SG into Marshall stacks.',68),
('tattoo-vampire','blue-oyster-cult','guitar','riff','main riff','distorted','hard rock','distortion','intermediate',
 'Gibson SG Standard (Buck Dharma)','Marshall Super Lead 100','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":2,"delay":0,"master":8}'::jsonb,
 array['One of the band''s most aggressive riffs: bright biting Marshall distortion with fast attack','The slashing chord stabs need presence and treble to cut through the dense Agents of Fortune mix'],
 array['Attack the syncopated riff stabs with sharp aggressive downstrokes','Mute quickly between stabs; the rests are as important as the hits'],
 'Equipboard documents Buck Dharma''s SG-and-Marshall rig through the Agents of Fortune era, and the track is noted as among the album''s hardest rockers.',68),
('eti-extra-terrestrial-intelligence','blue-oyster-cult','guitar','riff','main riff','distorted','hard rock','rhythm','intermediate',
 'Gibson SG Standard (Buck Dharma)','Marshall Super Lead 100','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":3,"delay":1,"master":7}'::jsonb,
 array['A hypnotic circular riff with moderate Marshall gain, eerie rather than aggressive','Keep the tone slightly restrained so the riff''s odd descending figure sounds mysterious'],
 array['Loop the descending riff evenly and resist rushing its hypnotic cycle','Use light palm-muting on the verses and open up for the chorus swells'],
 'Equipboard and Guitar World interviews document the Gibson SG into Marshall stacks Buck Dharma used across Agents of Fortune.',72),
('the-last-days-of-may','blue-oyster-cult','guitar','solo','outro solo','crunch','hard rock','lead','advanced',
 'Gibson SG Standard (Buck Dharma)','Marshall Super Lead 100','4x12','humbucker neck',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":5,"presence":5,"reverb":4,"delay":1,"master":7}'::jsonb,
 array['The mellow ballad erupts into one of Buck''s most lyrical extended solos, warm and vocal on the neck pickup','Moderate gain with generous sustain: the notes cry rather than scream'],
 array['Phrase the solo like a singer, leaving space between the long bent notes','Build intensity gradually across the outro; the final passes should peak, not the first'],
 'The debut-album ballad and its extended solo are documented on Blue Oyster Cult (1972), with Equipboard placing Buck Dharma''s Gibson SG and Marshall amps in that era.',70),
('run-to-you','bryan-adams','guitar','riff','intro riff','crunch','rock','rhythm','intermediate',
 'Fender Stratocaster (Keith Scott)','Marshall JCM800','4x12','single-coil bridge',
 '[]'::jsonb,'{"gain":5,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":3,"delay":2,"master":7}'::jsonb,
 array['The chiming intro arpeggio riff sits between clean and crunch: edge-of-breakup with sparkle','Keith Scott''s modded Hiwatt/JCM800-style gain adds bite when the power chords hit the chorus'],
 array['Fret the F#m-based arpeggio riff cleanly and let all strings ring together','Switch from fingertip arpeggio picking to firm downstroke power chords for the chorus lift'],
 'Premier Guitar''s Bryan Adams Rig Rundown and Kemper forum documentation describe Keith Scott''s Strat into modded Hiwatts with JCM800-level gain for the Reckless-era recordings.',76),
('heaven','bryan-adams','guitar','solo','guitar solo','distorted','rock','lead','intermediate',
 'Gibson Les Paul (Keith Scott)','Marshall JCM800','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":4,"delay":2,"master":7}'::jsonb,
 array['A classic 80s power-ballad lead: smooth Marshall-style sustain with a wash of studio reverb','Keep gain moderate so the melodic bends stay sweet rather than fizzy'],
 array['Sing the melody-based solo with wide vibrato on every held bend','Play clean arpeggiated chords with a soft touch in the verses before the lead break'],
 'Premier Guitar''s Rig Rundown documents Keith Scott''s 1954 Gibson Les Paul and Marshall/Hiwatt amp setups used across the Reckless era.',72),
('cuts-like-a-knife','bryan-adams','guitar','riff','main riff','crunch','rock','rhythm','beginner',
 'Fender Stratocaster (Keith Scott)','Marshall JCM800','4x12','single-coil bridge',
 '[]'::jsonb,'{"gain":5,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":3,"delay":1,"master":7}'::jsonb,
 array['A punchy open-chord crunch riff with Strat clarity; the muted D-riff groove drives the whole song','Edge-of-breakup gain keeps the stop-start dynamics tight and percussive'],
 array['Alternate between palm-muted chugs and open ringing chords to nail the riff''s bounce','Leave the rests empty; the silence between hits is the hook'],
 'Premier Guitar and Equipboard document Keith Scott''s Stratocaster and Marshall-voiced amp rig from the Cuts Like a Knife sessions onward.',74),
('somebody','bryan-adams','guitar','riff','main riff','crunch','rock','rhythm','beginner',
 'Fender Stratocaster (Keith Scott)','Marshall JCM800','4x12','single-coil bridge',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":3,"delay":1,"master":7}'::jsonb,
 array['Arena-rock crunch with Strat snap: the riff alternates ringing suspended chords and driving eighths','Mutt-era Adams records keep guitars bright and punchy, never saturated'],
 array['Accent the sus4 hammer-ons inside the chord riff for the signature lift','Drive the chorus with steady eighth-note downstrokes locked to the kick'],
 'Premier Guitar''s Rig Rundown and Kemper forum threads document Keith Scott''s Strat into modded Hiwatt/JCM800-style amps for the Reckless sessions.',72),
('everything-i-do-i-do-it-for-you','bryan-adams','guitar','solo','guitar solo','distorted','rock','lead','intermediate',
 'Gibson Les Paul (Keith Scott)','Marshall JCM800','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":5,"presence":5,"reverb":5,"delay":2,"master":6}'::jsonb,
 array['A piano-led ballad, so the guitar''s moment is the warm singing solo; this profile covers that lead voice','Round Les Paul sustain with big hall reverb matches the Mutt Lange production sheen'],
 array['Follow the vocal melody closely in the solo and milk each bend with slow vibrato','Stay dynamically soft under the verses if you comp; the guitar is a supporting voice until the solo'],
 'Premier Guitar''s Rig Rundown documents Keith Scott''s vintage Les Paul and Marshall-family amps in the Waking Up the Neighbours era; the song itself is piano-led, so this targets the solo.',66),
('its-only-love','bryan-adams','guitar','riff','main riff','distorted','rock','rhythm','intermediate',
 'Gibson Les Paul (Keith Scott)','Marshall JCM800','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":3,"delay":1,"master":8}'::jsonb,
 array['The heaviest Reckless cut: aggressive Marshall crunch trading punches with Tina Turner''s vocal','Bridge humbucker grind with tight bass keeps the stabbing riff mean and punchy'],
 array['Hit the riff stabs hard and choke them quickly for maximum aggression','Answer the vocal phrases with the bluesy fills exactly in the gaps'],
 'Premier Guitar''s Rig Rundown documents Keith Scott''s Les Paul and JCM800-level modded Hiwatt gain used across the Reckless sessions.',72),
('kids-wanna-rock','bryan-adams','guitar','riff','main riff','distorted','rock','distortion','intermediate',
 'Fender Stratocaster (Keith Scott)','Marshall JCM800','4x12','single-coil bridge',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":2,"delay":1,"master":8}'::jsonb,
 array['The fastest, loudest Adams cut: cranked Marshall-style drive with whammy-bar squeals in the fills','Strat bridge pickup keeps the frantic riff cutting and wiry rather than thick'],
 array['Drive the riff with relentless fast downstrokes at full commitment','Grab dive-bomb and flutter accents with the bar between riff cycles'],
 'Premier Guitar''s Rig Rundown documents Keith Scott''s Strat-and-Marshall-voiced rig; the track is documented as Reckless''s all-out rocker showcase.',71),
('straight-from-the-heart','bryan-adams','guitar','rhythm','clean verse rhythm','clean','rock','clean','beginner',
 'Fender Stratocaster (Keith Scott)','Fender Twin Reverb','2x12','single-coil neck',
 '[]'::jsonb,'{"gain":3,"bass":5,"mids":5,"treble":6,"presence":5,"reverb":5,"delay":2,"master":6}'::jsonb,
 array['A warm sparkling clean ballad tone with generous plate-style reverb behind the piano','Neck-position Strat softness keeps the arpeggios round and supportive'],
 array['Arpeggiate the open chords gently with a light pick or fingers','Swell into the chorus strums without adding grit; dynamics come from the wrist'],
 'Premier Guitar and Equipboard document Keith Scott''s Stratocaster-based rig from the Cuts Like a Knife sessions; the ballad rides clean arpeggios under piano.',68),
('cant-stop-this-thing-we-started','bryan-adams','guitar','riff','main riff','crunch','rock','rhythm','beginner',
 'Fender Stratocaster (Keith Scott)','Marshall JCM800','4x12','single-coil bridge',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":3,"delay":1,"master":7}'::jsonb,
 array['Driving Mutt Lange rock-radio crunch: bright, compressed, and relentlessly rhythmic','Layered rhythm tracks on the record mean one tight crunch tone with strong treble works best'],
 array['Keep the fast chord riff bouncing with a straight-wrist strumming motion','Palm-mute the verse pattern and release fully on the chorus chords'],
 'Premier Guitar''s Rig Rundown documents Keith Scott''s Strat and Marshall-family amps through the Waking Up the Neighbours era.',71),
('please-forgive-me','bryan-adams','guitar','rhythm','clean arpeggio rhythm','clean','rock','clean','beginner',
 'Fender Stratocaster (Keith Scott)','Fender Twin Reverb','2x12','single-coil neck',
 '[]'::jsonb,'{"gain":3,"bass":5,"mids":5,"treble":6,"presence":5,"reverb":5,"delay":3,"master":6}'::jsonb,
 array['Glassy clean arpeggios with lush reverb and a touch of delay carry the ballad''s verses','The tone stays pristine until the soaring Les Paul-style solo lifts the final chorus'],
 array['Roll dynamics with your picking hand: whisper the first verse, lean in by the bridge','Let each arpeggiated chord ring its full length under the vocal'],
 'Premier Guitar''s Rig Rundown documents Keith Scott''s Strat and vintage Fender-style cleans in the early-90s Adams ballad productions.',68),
('18-til-i-die','bryan-adams','guitar','riff','main riff','distorted','rock','distortion','intermediate',
 'Gibson Les Paul (Keith Scott)','Marshall JCM800','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":2,"delay":0,"master":8}'::jsonb,
 array['A swaggering mid-90s rock riff: thick Les Paul grind with tight low end','Punchier and more saturated than the 80s records but still Marshall-bright'],
 array['Snap the syncopated riff accents against the backbeat','Choke the chords sharply on the stops so the vocal punches land alone'],
 'Premier Guitar''s Rig Rundown documents Keith Scott''s Les Paul and Marshall-family rig continuing through the 18 til I Die sessions.',70),
('bad-medicine','bon-jovi','guitar','riff','main riff','distorted','hard rock','rhythm','beginner',
 'Kramer Jersey Star (Richie Sambora)','Marshall JCM800','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":3,"delay":1,"master":8}'::jsonb,
 array['Classic New Jersey-era superstrat crunch: bright, compressed 80s Marshall grind','The record doubles rhythm guitars hard left and right, so keep the tone tight and consistent'],
 array['Drive the main riff with confident downstrokes and mute crisply between phrases','Nail the pick-slide and the stop-time hits; the riff is all about swagger'],
 'Equipboard and Uberproaudio document Richie Sambora''s Kramer superstrats into Marshall heads as the core New Jersey-era rig.',75),
('its-my-life','bon-jovi','guitar','intro','talk box intro riff','distorted','hard rock','rhythm','intermediate',
 'Fender Stratocaster Double-Neck era superstrat (Richie Sambora)','Marshall JCM2000 DSL100','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":7,"treble":6,"presence":5,"reverb":2,"delay":1,"master":8}'::jsonb,
 array['The famous intro note is a talk box: distorted guitar shaped by mouth vowels, mids pushed hard to mimic it without one','Crush-era Sambora ran a JCM2000 Dual Super Lead doubled with a Mesa Rectifier for the rhythm wall'],
 array['With a talk box, sustain the intro note and mouth the wah-oh vowels; without one, use a wah rocked slowly','Chug the dropped-feel verse riff tight and palm-muted before the wide chorus chords'],
 'Sambora is documented using a custom Framptone talk box on It''s My Life, and describes his Crush-era tone as a Les Paul or superstrat doubled through a Marshall JCM2000 and Mesa Rectifier.',76),
('blaze-of-glory','bon-jovi','guitar','solo','guitar solo','distorted','hard rock','lead','advanced',
 'Fender Stratocaster Plus (Jeff Beck)','Marshall Plexi-style rented head','4x12','single-coil bridge',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":4,"delay":2,"master":7}'::jsonb,
 array['The album leads are Jeff Beck on a Lace Sensor-loaded Strat Plus straight into a rented amp with no pedals','Expressive fingerstyle attack and whammy inflections do the talking over the western-flavored backing'],
 array['Play the solo fingerstyle and control dynamics from your picking hand like Beck','Use the bar for gentle scoops and cries at phrase ends rather than dive-bombs'],
 'Guitar World and Guitar Player document Jeff Beck cutting the Blaze of Glory album solos on his Surf Green Strat Plus through a rented amp with no pedals at A&M Studios.',72),
('keep-the-faith','bon-jovi','guitar','riff','muted funk-rock riff','crunch','hard rock','rhythm','intermediate',
 'Gibson Les Paul (Richie Sambora)','Marshall JCM800','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":5,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":2,"delay":1,"master":7}'::jsonb,
 array['A leaner 90s sound: tight palm-muted sixteenth groove riding the driving bass line','Moderate crunch keeps the percussive muted pattern articulate and funky'],
 array['Lock the muted sixteenth-note pattern to the bass riff like a metronome','Open into full chords only at the chorus; the verse tension is the point'],
 'Equipboard and Vintage Guitar interviews document Sambora shifting toward vintage Les Pauls and Marshall heads for the Keep the Faith sessions.',72),
('in-these-arms','bon-jovi','guitar','solo','guitar solo','distorted','hard rock','lead','intermediate',
 'Gibson Les Paul (Richie Sambora)','Marshall JCM800','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":4,"delay":3,"master":7}'::jsonb,
 array['Big 90s power-ballad lead: saturated Marshall sustain with wide reverb and echo repeats','Chorused clean layers fill the verses, then the solo soars with singing bends'],
 array['Milk the melodic bends with slow wide vibrato through the solo','Comp the verses with clean shimmering arpeggios before kicking to the lead sound'],
 'Equipboard and Vintage Guitar document Sambora''s Les Paul-and-Marshall setup with layered chorus cleans throughout the Keep the Faith era.',68),
('born-to-be-my-baby','bon-jovi','guitar','riff','main riff','distorted','hard rock','rhythm','beginner',
 'Kramer Jersey Star (Richie Sambora)','Marshall JCM800','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":3,"delay":1,"master":8}'::jsonb,
 array['Double-tracked 80s Marshall crunch with the polish of the Fairbairn-produced New Jersey sessions','Keep the gain saturated but the low end tight so the driving chord riff stays punchy'],
 array['Drive steady eighth-note chords under the verse and accent the riff pushes','Land the na-na-na chorus hits exactly with the band stops'],
 'Equipboard and Uberproaudio document Sambora''s Kramer superstrat and Marshall rig across the New Jersey album sessions.',72),
('lay-your-hands-on-me','bon-jovi','guitar','riff','main riff','distorted','hard rock','distortion','intermediate',
 'Kramer Jersey Star (Richie Sambora)','Marshall JCM800','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":6,"mids":6,"treble":6,"presence":6,"reverb":4,"delay":1,"master":8}'::jsonb,
 array['The slow-building arena intro wants a huge saturated stack sound with long hall reverb','Fat low-string riffing carries the gospel-rock stomp once the groove lands'],
 array['Let the intro chords swell and sustain over the drum build','Dig into the low-string riff with heavy strokes locked to the half-time backbeat'],
 'Equipboard and Uberproaudio document the Kramer-into-Marshall stack rig Sambora used throughout the New Jersey tour and sessions.',71),
('have-a-nice-day','bon-jovi','guitar','riff','main riff','distorted','hard rock','distortion','intermediate',
 'Gibson Les Paul (Richie Sambora)','Marshall JCM2000 DSL100','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":8,"bass":6,"mids":5,"treble":6,"presence":6,"reverb":2,"delay":1,"master":8}'::jsonb,
 array['Modern-rock era Bon Jovi: heavier scooped-edge gain from the JCM2000/Rectifier doubled rig','The dropped-feel riff should sound massive but still track the vocal rhythm tightly'],
 array['Attack the opening riff with tight palm-muted aggression before the open chorus chords','Match the riff accents to the drum pattern; it is groove metal-lite, not shred'],
 'Sambora describes his 2000s tone as a Les Paul doubled through a Marshall JCM2000 Dual Super Lead and Mesa Rectifier, per Equipboard-collected interviews.',71),
('ill-be-there-for-you','bon-jovi','guitar','solo','guitar solo','distorted','hard rock','lead','intermediate',
 'Gibson Les Paul (Richie Sambora)','Marshall JCM800','4x12','humbucker bridge',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":4,"delay":2,"master":7}'::jsonb,
 array['A bluesy power-ballad lead: warm Les Paul sustain with soulful over-the-top bends','The verses ride clean 12-string-style strums, so the solo contrast is the emotional payoff'],
 array['Phrase the solo vocally with big rakes into the high bends','Slow your vibrato down; the solo cries rather than shreds'],
 'Equipboard and Vintage Guitar document Sambora''s Les Paul and Marshall stack setup from the New Jersey sessions where the ballad''s bluesy lead was cut.',72),
('animal','def-leppard','guitar','main','Layered chorus crunch','crunch','hard rock','crunch','intermediate',
 'Jackson Soloist (Cracklejack) / 1978 Fender Strat w/ DiMarzio bridge','Scholz Rockman (Scholz-modded units)','Recorded direct (no cab)','Bridge humbucker',
 '[]'::jsonb,'{"gain":5,"bass":5,"mids":4,"treble":6,"presence":6,"reverb":3,"delay":2,"master":7}'::jsonb,
 array['Hysteria guitars are dozens of Rockman layers, so keep single-track gain moderate and let compression do the sustain','Collen''s small Gallien-Krueger demo amp even survives on part of this track — the tone is polished, not raw'],
 array['Track rhythm parts twice and pan hard to fake the Mutt Lange wall of layers','Palm-mute the verse chords lightly so the chorus open chords bloom'],
 'Guitar.com and Guitar World Hysteria retrospectives: Collen/Clark cut the album on Scholz-modded Rockman units instead of Marshalls, using Collen''s Jackson Soloist and DiMarzio-loaded Strat.',78),
('love-bites','def-leppard','guitar','main','Ballad clean layers','clean','hard rock','clean','intermediate',
 '1978 Fender Strat w/ DiMarzio bridge humbucker','Gallien-Krueger small combo / Rockman','Recorded direct (no cab)','Bridge humbucker',
 '[]'::jsonb,'{"gain":2,"bass":5,"mids":4,"treble":6,"presence":5,"reverb":4,"delay":3,"master":6}'::jsonb,
 array['Collen has said the Gallien-Krueger demo take of this ballad made it onto the finished record','Glassy compressed cleans with chorus-like sheen from stacked Rockman layers, never fully dry'],
 array['Use a light pick attack and let arpeggiated chords ring into each other','Add a subtle slow delay to fill space under the vocal instead of strumming harder'],
 'Guitar World interview with Phil Collen on making Hysteria: the Love Bites demo tracked through a small Gallien-Krueger amp was kept, with Rockman layers around it.',76),
('foolin','def-leppard','guitar','main','Arpeggio-to-anthem rhythm','distorted','hard rock','rhythm','intermediate',
 'Gibson Les Paul Standard','Marshall JMP 100w','Marshall 4x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":5,"treble":6,"presence":6,"reverb":3,"delay":1,"master":7}'::jsonb,
 array['Pyromania-era Leppard is still a Marshall record — tighter and more produced than High ''n'' Dry but not yet Rockman-sterile','Clean picked intro arpeggios jump-cut into big multitracked power chords at the chorus'],
 array['Roll your guitar volume down for the intro arpeggios instead of switching channels','Keep chorus power chords short and stabbed — the size comes from layering, not sustain'],
 'Equipboard and Guitar World Pyromania coverage: Clark''s Les Paul and Marshall stacks under Mutt Lange''s layered production define the album''s rhythm sound.',72),
('bringin-on-the-heartbreak','def-leppard','guitar','intro','Arpeggiated intro and crunch verses','crunch','hard rock','crunch','intermediate',
 'Gibson Les Paul Standard','Marshall JMP 2x12 combo','Marshall 2x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":5,"bass":5,"mids":6,"treble":6,"presence":5,"reverb":3,"delay":1,"master":7}'::jsonb,
 array['Steve Clark''s signature piece: minor-key arpeggios on a Les Paul into a cranked Marshall, gain from the amp not pedals','High ''n'' Dry is the rawest Mutt Lange Leppard record — crunch, not the later Rockman gloss'],
 array['Let each intro arpeggio note overlap the next by holding chord shapes','Dig in harder for the verse chords — the same tone covers both parts via pick attack'],
 'steveclarkguitar.com gear history and Guitar World: Clark played Les Pauls into Marshall combos/stacks on High ''n'' Dry under Mutt Lange.',77),
('hysteria','def-leppard','guitar','main','Clean layered arpeggios','clean','hard rock','clean','intermediate',
 '1978 Fender Strat w/ DiMarzio bridge humbucker','Scholz Rockman (Scholz-modded units)','Recorded direct (no cab)','Bridge humbucker',
 '[]'::jsonb,'{"gain":2,"bass":4,"mids":4,"treble":6,"presence":5,"reverb":4,"delay":4,"master":6}'::jsonb,
 array['The title track is the purest example of the Rockman clean stack — chorused, compressed arpeggios woven into a bed','Multiple interlocking clean parts share the space; no single guitar plays the whole hook'],
 array['Practice the arpeggio pattern with a compressor and chorus to approximate the Rockman voicing','Mute unused strings carefully — the clean tone exposes every stray noise'],
 'Guitar.com Hysteria gear feature: the album''s clean beds were built from Scholz-modded Rockman units tracked direct, layered dozens of times.',78),
('armageddon-it','def-leppard','guitar','riff','Strutting mid-gain riff','crunch','hard rock','crunch','intermediate',
 'Jackson Soloist (Cracklejack)','Scholz Rockman (Scholz-modded units)','Recorded direct (no cab)','Bridge humbucker',
 '[]'::jsonb,'{"gain":5,"bass":5,"mids":5,"treble":6,"presence":6,"reverb":3,"delay":2,"master":7}'::jsonb,
 array['The main riff sits at Rockman half-gain — springy and compressed rather than saturated','Clean chordal accents answer the crunch riff, both printed with the same processed sheen'],
 array['Swing the riff slightly behind the beat for the strut feel','Use a light palm mute so the compression pumps evenly across strings'],
 'Guitar.com and Jackson blog Hysteria retrospectives: Collen''s Jackson Soloist into modded Rockman units, layered per Mutt Lange''s production method.',76),
('lets-get-rocked','def-leppard','guitar','riff','Stadium crunch riff','crunch','hard rock','crunch','intermediate',
 'Jackson PC1','Scholz Rockman rack','Recorded direct (no cab)','Bridge humbucker',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":4,"treble":6,"presence":6,"reverb":3,"delay":2,"master":7}'::jsonb,
 array['Adrenalize carried the Hysteria Rockman method forward with Collen''s Jackson PC1 as the main guitar','Stop-start riff hits are gated-tight with big processed chords between vocal lines'],
 array['Choke each riff stab dead with your fretting hand for the stop-start effect','Layer a second take an octave up on the chorus if recording'],
 'Jackson Guitars blog and Equipboard: Collen''s PC1 signature and continued Rockman-based layering defined the Adrenalize sessions after Clark''s death.',72),
('rocket','def-leppard','guitar','riff','Tribal groove riff','crunch','hard rock','crunch','intermediate',
 'Jackson Soloist (Cracklejack)','Scholz Rockman (Scholz-modded units)','Recorded direct (no cab)','Bridge humbucker',
 '[]'::jsonb,'{"gain":5,"bass":6,"mids":4,"treble":5,"presence":5,"reverb":4,"delay":3,"master":7}'::jsonb,
 array['The riff rides a drum-machine tribal groove, so the guitars are more texture than lead engine','Reversed and effected guitar snippets float around the compressed Rockman core parts'],
 array['Lock the riff to the kick pattern rather than strumming through it','Keep the gain moderate — the part should chug, not saturate'],
 'Guitar.com Hysteria gear feature: Rocket''s guitar beds came from the same Scholz-modded Rockman direct rig used across the album.',74),
('no-one-like-you','scorpions','guitar','main','Clean intro into anthem riff','distorted','hard rock','rhythm','intermediate',
 'Gibson Flying V','Marshall JMP 50w Super Lead','Marshall 4x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":3,"delay":1,"master":8}'::jsonb,
 array['Schenker''s Flying V into a cranked 50-watt Marshall — all power-tube drive, no pedals in front','Clean arpeggiated intro hands off to a mid-forward chording riff with Jabs'' melodic leads on top'],
 array['Play the intro arpeggios with the neck pickup and guitar volume rolled down','Hit the riff''s accents with full downstrokes to push the amp into singing sustain'],
 'Equipboard, Vintage Guitar and Marshall forum documentation: Blackout-era Scorpions ran Flying V and Explorer into non-master Marshall Super Leads, drive from the power tubes.',77),
('blackout','scorpions','guitar','riff','Full-throttle title riff','distorted','heavy metal','distortion','intermediate',
 'Gibson Flying V','Marshall JMP 100w Super Lead','Marshall 4x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":7,"presence":7,"reverb":2,"delay":0,"master":8}'::jsonb,
 array['A cranked plexi-style Marshall at full tilt — aggressive but still dynamic, cleaning up with pick attack','Jabs'' Blackout-era leads used his black Strat "trouble guitar" with Floyd Rose for the whammy moments'],
 array['Drive the riff with strict alternate down-up picking to keep the sixteenth energy','Leave the low E slightly loose-muted so the riff breathes between accents'],
 'Vintage Guitar and My Les Paul forum era breakdowns: the Blackout album is Flying V/Explorer into cranked 50/100w Marshall Super Leads with no front-end boxes.',75),
('the-zoo','scorpions','guitar','riff','Mid-paced groove riff','distorted','hard rock','rhythm','intermediate',
 'Gibson Flying V','Marshall JMP 50w Super Lead','Marshall 4x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":6,"bass":6,"mids":6,"treble":5,"presence":5,"reverb":3,"delay":1,"master":8}'::jsonb,
 array['Schenker''s slow, heavy chord riff carries the song; Jabs'' famous solo runs through a talk box','The groove is deliberate and behind the beat — Marshall power-tube crunch with the tone knob warm'],
 array['Play the riff slower than feels natural and lean on the low-string slides','If you have a talk box, vowel-shape the solo phrases; otherwise a wah rocked slowly gets close'],
 'Wikipedia and Guitar World: The Zoo (Animal Magnetism, 1980) is Schenker''s Flying V/Marshall rhythm groove with Matthias Jabs'' documented talk-box lead.',78),
('send-me-an-angel','scorpions','guitar','main','Clean ballad with singing lead','clean','hard rock','clean','beginner',
 'Gibson Explorer 90','Marshall JCM800','Marshall 4x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":2,"bass":5,"mids":5,"treble":6,"presence":5,"reverb":5,"delay":3,"master":6}'::jsonb,
 array['Warm chorused clean arpeggios under the verses, with Jabs'' sustaining Marshall lead for the melody spots','Crazy World-era Jabs favored his downsized Explorer 90 he designed with Gibson in ''87'],
 array['Arpeggiate the chords softly and let the reverb carry the space','For the lead lines, use slow wide vibrato — the melody is vocal, not flashy'],
 'Equipboard and Vintage Guitar interviews: Jabs'' Explorer 90 and Marshall backline covered the Crazy World ballads, clean verses with amp-drive leads.',70),
('big-city-nights','scorpions','guitar','riff','Arena-rock chord riff','distorted','hard rock','rhythm','intermediate',
 'Gibson Flying V','Marshall JCM800 2203','Marshall 4x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":6,"treble":6,"presence":6,"reverb":3,"delay":1,"master":8}'::jsonb,
 array['Love at First Sting sits on JCM800-era Marshall crunch — tighter and brighter than the earlier plexi records','The riff is open-chord arena rock: big downstroke hits with space for the vocal'],
 array['Strum the chord stabs with confident full downstrokes and immediate mutes','Keep gain moderate so each chord''s notes stay separated in the mix'],
 'Equipboard and Marshall forum documentation: Schenker''s Flying V and JCM800 2203/JMP heads powered the Love at First Sting rhythm sound.',74),
('coast-to-coast','scorpions','guitar','main','Instrumental melody riff','distorted','hard rock','lead','intermediate',
 'Gibson Flying V (black/white)','Marshall 50w plexi','Marshall 4x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":6,"bass":5,"mids":7,"treble":6,"presence":6,"reverb":3,"delay":1,"master":8}'::jsonb,
 array['Michael Schenker composed and played lead on this Lovedrive instrumental — his half-black Flying V into a cranked 50w Marshall','Mid-heavy, vocal-sounding drive; Schenker often used a wah parked partway as a midrange filter'],
 array['Phrase the melody like a singer with slides into the target notes','Try a wah pedal fixed around halfway to nail the honky Schenker midrange'],
 'Wikipedia and Michael Schenker interviews confirm he played lead on Coast to Coast; guitargangsters.net documents the Flying V/50w Marshall/parked-wah recipe.',76),
('holiday','scorpions','guitar','intro','Acoustic-style clean arpeggios','clean','hard rock','clean','beginner',
 'Gibson Flying V (neck pickup, clean)','Marshall 50w plexi (low volume)','Marshall 4x12','Neck humbucker',
 '[]'::jsonb,'{"gain":1,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":5,"delay":2,"master":5}'::jsonb,
 array['The original intro is fingerpicked acoustic guitar — this is an electric clean adaptation, so expect a rounder tone than the record','Michael Schenker has said he wrote the song''s opening section during the Lovedrive sessions'],
 array['Fingerpick the arpeggios with thumb-and-fingers rather than a flat pick','Roll the tone knob back slightly to soften the attack toward an acoustic feel'],
 'Lovedrive documentation (Wikipedia, Schenker interviews) confirms the acoustic ballad arrangement; settings here adapt the fingerpicked acoustic intro to a clean electric rig.',63),
('bad-boys-running-wild','scorpions','guitar','riff','Driving opener riff','distorted','heavy metal','distortion','intermediate',
 'Gibson Flying V','Marshall JCM800 2203','Marshall 4x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":7,"presence":6,"reverb":2,"delay":0,"master":8}'::jsonb,
 array['The Love at First Sting opener rides a tight palm-muted JCM800 gallop with stabbed chord accents','Jabs adds Floyd-equipped Strat-style lead flash over Schenker''s locked V rhythm'],
 array['Palm-mute the low-string drive hard and release only on the chord accents','Count the syncopated stabs carefully — the riff pushes ahead of the backbeat'],
 'Equipboard and era interviews: Schenker''s Flying V into JCM800-series Marshalls, drive from the amp, defined the 1984 album''s rhythm attack.',73),
('dynamite','scorpions','guitar','riff','Fast heavy gallop riff','distorted','heavy metal','distortion','advanced',
 'Gibson Flying V','Marshall JMP 100w Super Lead','Marshall 4x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":7,"bass":5,"mids":6,"treble":7,"presence":7,"reverb":2,"delay":0,"master":8}'::jsonb,
 array['One of the band''s heaviest cuts — a cranked non-master Marshall pushed to the edge of its natural saturation','Fast downpicked gallop with pentatonic fills; the tone stays raw and mid-forward, never scooped'],
 array['Build downpicking stamina at slower tempos before attempting full speed','Accent the first note of each gallop cluster to keep the riff from blurring'],
 'Vintage Guitar and Marshall forum Blackout-era documentation: Flying V into cranked Marshall Super Leads with no pedals — the album''s fastest, heaviest application of that rig.',73),
('hungry-like-the-wolf','duran-duran','guitar','riff','New-wave crunch riff','crunch','new wave','crunch','beginner',
 'Gibson Les Paul','Marshall JCM800','Marshall 4x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":5,"bass":4,"mids":5,"treble":7,"presence":6,"reverb":3,"delay":2,"master":6}'::jsonb,
 array['Andy Taylor''s bright chugging riff cuts through the synth bed — a Marshall JCM800 kept at edge-of-breakup crunch','The part is rhythmic and clipped, closer to power-pop than hard rock despite the Marshall rig'],
 array['Keep the riff tightly palm-muted and staccato so it interlocks with the sequencer','Favor the bridge pickup with treble up to slice through keyboard pads'],
 'duranduran.com gear Q&As and MusicPlayers.com interview: Taylor used Les Paul/Telecaster into Marshall JCM800 on the Rio album.',74),
('girls-on-film','duran-duran','guitar','riff','Funk-rock scratch riff','crunch','new wave','crunch','intermediate',
 'Fender Telecaster','Marshall JCM800','Marshall 4x12','Bridge single-coil',
 '[]'::jsonb,'{"gain":4,"bass":4,"mids":5,"treble":7,"presence":6,"reverb":2,"delay":1,"master":6}'::jsonb,
 array['A funk scratch rhythm dressed in light Marshall crunch — Taylor''s disco-meets-rock hybrid on the debut album','The verse is muted 16th-note scratching; the chorus opens into ringing chord hits'],
 array['Practice the muted 16th-note strumming with a loose wrist and constant motion','Ghost-strum through the muted beats so the groove never stops'],
 'duranduran.com gear pages and MusicPlayers.com: Taylor''s Telecaster/Les Paul into Marshall JCM800 covered the debut-album funk-rock rhythm parts.',72),
('save-a-prayer','duran-duran','guitar','main','Clean arpeggio adaptation','clean','new wave','clean','beginner',
 'Gibson ES-335','Vox AC30','Vox 2x12','Neck humbucker',
 '[]'::jsonb,'{"gain":1,"bass":5,"mids":5,"treble":6,"presence":4,"reverb":5,"delay":4,"master":5}'::jsonb,
 array['The famous hook is a synthesizer arpeggio, not guitar — this profile adapts it to clean electric arpeggios','Taylor''s actual guitar role on the record is sparse atmospheric color under the synth bed'],
 array['Arpeggiate the chord shapes evenly to mimic the synth pattern''s clockwork feel','Add generous delay and reverb to approximate the synth pad wash'],
 'Rio-era documentation shows the lead hook is Nick Rhodes'' synth arpeggio; this is an honest guitar adaptation using Taylor-style clean gear.',62),
('the-reflex','duran-duran','guitar','rhythm','Funk scratch accents','clean','new wave','clean','intermediate',
 'Fender Telecaster','Vox AC30','Vox 2x12','Bridge single-coil',
 '[]'::jsonb,'{"gain":2,"bass":4,"mids":5,"treble":7,"presence":6,"reverb":3,"delay":2,"master":6}'::jsonb,
 array['Taylor moved toward Vox AC30 tones for Seven and the Ragged Tiger — chimey clean scratch stabs between synth lines','The Nile Rodgers remix pushed the rhythmic elements forward; the guitar plays percussive chips, not chords held long'],
 array['Chip at the strings with short up-and-down 16th strokes, mostly muted','Place the guitar stabs in the gaps the vocal leaves — less is the whole point'],
 'MusicPlayers.com Andy Taylor interview: Vox AC30 alongside Marshalls for the Seven and the Ragged Tiger era; the single''s Rodgers remix foregrounds the funk rhythm parts.',68),
('notorious','duran-duran','guitar','riff','Chic-style funk scratch','clean','funk','clean','intermediate',
 'Fender Stratocaster','Fender twin-style clean combo','Fender 2x12','Neck-middle single-coil combination',
 '[]'::jsonb,'{"gain":1,"bass":4,"mids":5,"treble":7,"presence":6,"reverb":2,"delay":0,"master":6}'::jsonb,
 array['Producer Nile Rodgers'' Chic-style chucking drives the track — a hardtail Strat into a clean Fender-style amp','Dry, bright and percussive: the in-between pickup position with almost no reverb is the sound'],
 array['Master the left-hand mute-and-release so only chosen 16th chips sound','Keep strict 16th-note wrist motion even through the rests'],
 'Wikipedia and Notorious album documentation: Nile Rodgers produced and played his signature funk scratch guitar on the title track after Andy Taylor''s departure.',75),
('wild-boys','duran-duran','guitar','chorus','Power-chord accents','crunch','new wave','crunch','beginner',
 'Gibson Les Paul','Marshall JCM800','Marshall 4x12','Bridge humbucker',
 '[]'::jsonb,'{"gain":5,"bass":5,"mids":5,"treble":6,"presence":6,"reverb":3,"delay":2,"master":6}'::jsonb,
 array['Taylor''s guitar punches big sustained power chords into a dense synth-and-drum production','The tone is compressed mid-gain crunch, mixed as an accent layer rather than the lead voice'],
 array['Hit the chorus power chords hard and let them sustain their full length','Stay out of the verses — the arrangement wants silence from the guitar there'],
 'duranduran.com gear pages and era interviews: Taylor''s Les Paul/JCM800 rig supplied the rock accents on the Nile Rodgers-produced 1984 single.',68),
('skin-trade','duran-duran','guitar','rhythm','Smooth funk chords','clean','funk','clean','intermediate',
 'Fender Stratocaster','Fender twin-style clean combo','Fender 2x12','Neck single-coil',
 '[]'::jsonb,'{"gain":1,"bass":5,"mids":5,"treble":6,"presence":5,"reverb":3,"delay":1,"master":6}'::jsonb,
 array['A Chic-influenced slow-funk groove from the Notorious sessions — soft 9th-chord chucks and sustained partial chords','Warmer and rounder than the Notorious title track; neck pickup with the treble slightly tamed'],
 array['Use 9th and minor-7th chord voicings on the top four strings','Alternate between muted chips and let-ring chord swells across the bar'],
 'Notorious album documentation: the post-Andy Taylor sessions leaned on Nile Rodgers-style funk rhythm guitar (Rodgers and Warren Cuccurullo contributing), adapted here to a clean Strat rig.',66)
) as c(song_slug, artist_slug, mode, part_type, part_label, tone_type, genre, tone_category, difficulty,
       original_guitar, original_amp, original_cab, original_pickup,
       original_effects, original_settings, adaptation_notes, playing_notes, source_summary, confidence)
join public.artists a on a.slug = c.artist_slug
join public.songs s on s.artist_id = a.id and s.slug = c.song_slug;

do $$
declare
  expected int;
  actual int;
begin
  select count(*) into expected from phase_targets;
  select count(*) into actual
  from public.song_tone_profiles p
  join public.songs s on s.id = p.song_id
  join public.artists a on a.id = s.artist_id
  join phase_targets t on t.artist_slug = a.slug and t.song_slug = s.slug
  where p.mode = 'guitar' and p.verification_status = 'admin_verified';
  if actual < expected then
    raise exception 'POST-CONDITION FAILED: % verified guitar profiles for % targets — slug mismatch between fragments', actual, expected;
  end if;
end $$;

commit;
