begin;

-- Correction: the Fender-era John Mayer signature was the John Mayer Stratocaster;
-- Silver Sky is a PRS model. Remove the incorrect row (the PRS Silver Sky already
-- exists separately under brand PRS).
delete from public.equipment
where equipment_type = 'electric_guitar'
  and brand = 'Fender'
  and model = 'John Mayer Silver Sky';

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('electric_guitar', 'Fender', 'John Mayer Stratocaster', 'Artist', false, 'John Mayer signature Stratocaster with Big Dipper pickups.'),
  ('electric_guitar', 'Fender', 'Nile Rodgers Hitmaker Stratocaster', 'Artist', false, 'Nile Rodgers Hitmaker Strat with hardtail bridge and slim body.'),
  ('electric_guitar', 'Fender', 'Steve Lacy People Pleaser Stratocaster', 'Artist', false, 'Steve Lacy People Pleaser Strat with custom wiring.'),
  ('electric_guitar', 'Fender', 'Chrissie Hynde Telecaster', 'Artist', false, 'Chrissie Hynde signature Telecaster with faded finish.'),
  ('electric_guitar', 'Fender', 'Jason Isbell Custom Telecaster', 'Artist', false, 'Jason Isbell Custom Telecaster with road worn treatment.'),
  ('electric_guitar', 'Fender', 'Gold Foil Jazzmaster', 'Gold Foil', false, 'Limited Gold Foil Jazzmaster with gold foil pickups.'),
  ('electric_guitar', 'Strandberg', 'Boden Standard NX 6', 'Boden', true, 'Headless Boden Standard NX 6 with ergonomic EndurNeck.'),
  ('electric_guitar', 'Strandberg', 'Boden Standard NX 7', 'Boden', false, '7-string headless Boden Standard NX.'),
  ('electric_guitar', 'Strandberg', 'Boden Original NX 6', 'Boden', false, 'Boden Original NX 6 with chambered body.'),
  ('electric_guitar', 'Strandberg', 'Boden Original NX 7', 'Boden', false, '7-string Boden Original NX.'),
  ('electric_guitar', 'Strandberg', 'Boden Prog NX 6', 'Boden', false, 'Boden Prog NX 6 with HSS Fishman Fluence pickups.'),
  ('electric_guitar', 'Strandberg', 'Boden Metal NX 6', 'Boden', false, 'Boden Metal NX 6 with Fishman Fluence Modern pickups.'),
  ('electric_guitar', 'Strandberg', 'Boden Metal NX 7', 'Boden', false, '7-string Boden Metal NX.'),
  ('electric_guitar', 'Strandberg', 'Boden Essential 6', 'Boden', false, 'Accessible Boden Essential 6 headless guitar.'),
  ('electric_guitar', 'Mayones', 'Regius 6', 'Regius', false, 'Regius 6 neck through with premium tonewoods.'),
  ('electric_guitar', 'Mayones', 'Regius 7', 'Regius', false, '7-string Regius neck through.'),
  ('electric_guitar', 'Mayones', 'Duvell Elite 6', 'Duvell', false, 'Duvell Elite 6 with modern metal voicing.'),
  ('electric_guitar', 'Mayones', 'Duvell Elite 7', 'Duvell', false, '7-string Duvell Elite.'),
  ('electric_guitar', 'Mayones', 'Setius 6', 'Setius', false, 'Setius 6 set neck with mahogany body.'),
  ('electric_guitar', 'Ormsby', 'Hype GTR 6', 'Hype', false, 'Hype GTR 6 multiscale with Ormsby pickups.'),
  ('electric_guitar', 'Ormsby', 'Hype GTR 7', 'Hype', false, '7-string Hype GTR multiscale.'),
  ('electric_guitar', 'Ormsby', 'TX GTR 6', 'TX', false, 'TX GTR 6 with aggressive modern styling.'),
  ('electric_guitar', 'Ormsby', 'Goliath GTR 6', 'Goliath', false, 'Goliath GTR 6 superstrat with multiscale option.'),
  ('electric_guitar', 'Balaguer', 'Espada Standard', 'Espada', false, 'Espada Standard with offset modern body.'),
  ('electric_guitar', 'Balaguer', 'Growler Standard', 'Growler', false, 'Growler Standard with compact double cut body.'),
  ('electric_guitar', 'Eastwood', 'Airline 59 2P', 'Airline', false, 'Retro Airline 59 2P reissue with vintage styling.'),
  ('electric_guitar', 'Eastwood', 'Sidejack Baritone DLX', 'Sidejack', false, 'Sidejack Baritone DLX with surf era styling.'),
  ('electric_guitar', 'Eastwood', 'Classic 6', 'Classic', false, 'Classic 6 semi hollow with retro appointments.'),
  ('electric_guitar', 'Peavey', 'HP2', 'HP', false, 'USA made HP2 with dual humbuckers and Floyd Rose.'),
  ('electric_guitar', 'Peavey', 'Raptor Plus', 'Raptor', false, 'Affordable Raptor Plus with SSS pickups.'),
  ('electric_guitar', 'Danelectro', 'Stock 59', '59', false, 'Stock 59 reissue with lipstick pickups and vintage vibe.'),
  ('electric_guitar', 'Reverend', 'Jetstream 390', 'Jetstream', false, 'Jetstream 390 with three P-90 style pickups.'),
  ('electric_guitar', 'Reverend', 'Charger 290', 'Charger', false, 'Charger 290 with dual P-90 pickups.'),
  ('electric_guitar', 'Reverend', 'Double Agent OG', 'Double Agent', false, 'Double Agent OG with humbucker and P-90 combination.'),
  ('electric_guitar', 'Reverend', 'Six Gun', 'Six Gun', false, 'Six Gun with three single-coils and bass contour control.'),
  ('electric_guitar', 'Reverend', 'Sensei RA', 'Sensei', false, 'Sensei RA with dual humbuckers and set neck.'),
  ('electric_guitar', 'Reverend', 'Contender RB', 'Contender', false, 'Contender RB with railhammer pickups.'),
  ('electric_guitar', 'Reverend', 'Greg Koch Gristlemaster', 'Signature', false, 'Greg Koch Gristlemaster with Fishman Fluence Greg Koch pickups.'),
  ('electric_guitar', 'Guild', 'Starfire I DC', 'Starfire', false, 'Starfire I DC semi hollow with LB-1 humbuckers.'),
  ('electric_guitar', 'Guild', 'Starfire IV ST', 'Starfire', false, 'Starfire IV ST semi hollow with center block.'),
  ('electric_guitar', 'Guild', 'Surfliner', 'Surfliner', false, 'Surfliner offset with three pickup layout.'),
  ('electric_guitar', 'Guild', 'Surfliner Deluxe', 'Surfliner', false, 'Surfliner Deluxe with tremolo and upgraded pickups.'),
  ('electric_guitar', 'Guild', 'S-100 Polara', 'Polara', false, 'S-100 Polara solid body with dual humbuckers.'),
  ('electric_guitar', 'Guild', 'Polara Kim Thayil', 'Signature', false, 'Kim Thayil signature Polara.'),
  ('electric_guitar', 'Godin', 'Session HT', 'Session', false, 'Session HT with HSS pickups and hardtail bridge.'),
  ('electric_guitar', 'Godin', 'Stadium HT', 'Stadium', false, 'Stadium HT with Tele style layout.'),
  ('electric_guitar', 'Godin', 'Summit Classic HT', 'Summit', false, 'Summit Classic HT single cut with humbuckers.'),
  ('electric_guitar', 'Godin', 'xtSA', 'xtSA', false, 'xtSA with electric, acoustic and synth access outputs.'),
  ('electric_guitar', 'Godin', '5th Avenue Kingpin', '5th Avenue', false, '5th Avenue Kingpin archtop with P-90.'),
  ('electric_guitar', 'Godin', 'Radiator', 'Radiator', false, 'Radiator with retro styling and dual pickups.'),
  ('electric_guitar', 'D''Angelico', 'Premier DC', 'Premier', false, 'Premier DC semi hollow with stairstep tailpiece.'),
  ('electric_guitar', 'D''Angelico', 'Premier SS', 'Premier', false, 'Premier SS single cut semi hollow.'),
  ('electric_guitar', 'D''Angelico', 'Premier Mini DC', 'Premier', false, 'Compact Premier Mini DC semi hollow.'),
  ('electric_guitar', 'D''Angelico', 'Deluxe Atlantic', 'Deluxe', false, 'Deluxe Atlantic solid body single cut.'),
  ('electric_guitar', 'Gretsch', 'G2215-P90 Streamliner Junior Jet Club', 'Streamliner', false, 'Streamliner Junior Jet Club with P-90 pickups.'),
  ('electric_guitar', 'Gretsch', 'G2622T Streamliner Center Block', 'Streamliner', false, 'Streamliner Center Block with Bigsby.'),
  ('electric_guitar', 'Gretsch', 'G5222 Electromatic Double Jet', 'Electromatic', false, 'Electromatic Double Jet with FT-5E Filtertron pickups.'),
  ('electric_guitar', 'Gretsch', 'G5230T Electromatic Jet FT', 'Electromatic', false, 'Electromatic Jet FT with Bigsby tailpiece.'),
  ('electric_guitar', 'Gretsch', 'G6659T Players Edition Broadkaster Jr', 'Professional', false, 'Players Edition Broadkaster Jr with Full-Tron pickups.'),
  ('electric_guitar', 'PRS', 'SE CE 24 Standard Satin', 'SE', false, 'SE CE 24 Standard Satin with bolt on maple neck.'),
  ('electric_guitar', 'PRS', 'SE Paul''s Guitar', 'SE', false, 'SE Pauls Guitar with TCI S pickups and mini toggles.'),
  ('electric_guitar', 'PRS', 'SE 277 Baritone', 'SE', false, 'SE 277 baritone with 27.7 inch scale.'),
  ('electric_guitar', 'PRS', 'SE Hollowbody Standard', 'SE', false, 'SE Hollowbody Standard with 58/15 S pickups.'),
  ('electric_guitar', 'PRS', 'SE Swamp Ash Special', 'SE', false, 'SE Swamp Ash Special with three pickup layout.'),
  ('electric_guitar', 'PRS', 'S2 Vela Semi-Hollow', 'S2', false, 'S2 Vela Semi-Hollow with offset body.'),
  ('electric_guitar', 'PRS', 'CE 24 Semi-Hollow', 'CE', false, 'CE 24 Semi-Hollow with bolt on neck and f-hole.'),
  ('electric_guitar', 'Schecter', 'C-6 Plus', 'C', false, 'Affordable C-6 Plus with Diamond Plus pickups.'),
  ('electric_guitar', 'Schecter', 'C-6 Pro', 'C', false, 'C-6 Pro with active style humbuckers.'),
  ('electric_guitar', 'Schecter', 'Omen Elite-6', 'Omen', false, 'Omen Elite-6 with heavy metal styling.'),
  ('electric_guitar', 'Schecter', 'Omen Elite-6 FR', 'Omen', false, 'Omen Elite-6 with Floyd Rose tremolo.'),
  ('electric_guitar', 'Schecter', 'Hellraiser C-7', 'Hellraiser', false, '7-string Hellraiser C-7 with EMG active pickups.'),
  ('electric_guitar', 'Schecter', 'C-1 SLS Elite FR', 'SLS Elite', false, 'C-1 SLS Elite with Floyd Rose and Fishman Fluence pickups.'),
  ('electric_guitar', 'Schecter', 'KM-7 MK-III Standard', 'Signature', false, 'Keith Merrow KM-7 MK-III Standard 7-string.'),
  ('electric_guitar', 'Schecter', 'Reaper-6', 'Reaper', false, 'Reaper-6 with swamp ash burl top.'),
  ('electric_guitar', 'Schecter', 'PT Fastback II B', 'PT', false, 'PT Fastback II B with Bigsby tailpiece.'),
  ('electric_guitar', 'LTD', 'EC-201', 'EC', false, 'EC-201 single cut with single bridge humbucker.'),
  ('electric_guitar', 'LTD', 'EC-256FM', 'EC', false, 'EC-256 with flamed maple top.'),
  ('electric_guitar', 'LTD', 'EC-401', 'EC', false, 'EC-401 with EMG 81/60 active pickups.'),
  ('electric_guitar', 'LTD', 'MH-203QM', 'MH', false, 'MH-203 with quilted maple top.'),
  ('electric_guitar', 'LTD', 'MH-400NT', 'MH', false, 'MH-400NT neck through with EMG pickups.'),
  ('electric_guitar', 'LTD', 'M-400', 'M', false, 'M-400 with Floyd Rose and EMG pickups.'),
  ('electric_guitar', 'LTD', 'Viper-256', 'Viper', false, 'Viper-256 SG style double cutaway.'),
  ('electric_guitar', 'LTD', 'Viper-1000', 'Viper', false, 'Viper-1000 with EMG active pickups.'),
  ('electric_guitar', 'LTD', 'Phoenix-1000', 'Phoenix', false, 'Phoenix-1000 with reverse Firebird styling.'),
  ('electric_guitar', 'LTD', 'TE-200', 'TE', false, 'TE-200 Tele style with dual humbuckers.'),
  ('electric_guitar', 'Ibanez', 'RG421AHM', 'RG', false, 'RG421 with ash body and Quantum pickups.'),
  ('electric_guitar', 'Ibanez', 'S621QM', 'S', false, 'S621 with quilted maple top.'),
  ('electric_guitar', 'Ibanez', 'RGA42EX', 'RGA', false, 'RGA42EX with arched top and high output pickups.'),
  ('electric_guitar', 'Ibanez', 'AS113', 'Artcore Expressionist', false, 'Artcore Expressionist AS113 semi hollow.'),
  ('electric_guitar', 'Ibanez', 'AM53', 'Artcore', false, 'Compact Artcore AM53 semi hollow.'),
  ('electric_guitar', 'Ibanez', 'AM93QM', 'Artcore Expressionist', false, 'Artcore Expressionist AM93 with quilted maple.'),
  ('electric_guitar', 'Ibanez', 'RGAIX6FM Iron Label', 'Iron Label', false, 'Iron Label RGAIX6 with flamed maple and Fishman pickups.'),
  ('electric_guitar', 'Ibanez', 'RGIB6 Iron Label Baritone', 'Iron Label', false, 'Iron Label RGIB6 baritone with 28 inch scale.'),
  ('electric_guitar', 'Epiphone', 'Casino Worn', 'Casino', false, 'Casino Worn hollowbody with aged satin finish.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Muse', 'Muse', false, 'Lightweight Les Paul Muse with chambered body.'),
  ('electric_guitar', 'Epiphone', 'SG Muse', 'Muse', false, 'Lightweight SG Muse with metallic finishes.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Prophecy', 'Prophecy', false, 'Les Paul Prophecy with Fishman Fluence pickups.'),
  ('electric_guitar', 'Epiphone', 'SG Prophecy', 'Prophecy', false, 'SG Prophecy with Fishman Fluence pickups.'),
  ('electric_guitar', 'Epiphone', 'Extura Prophecy', 'Prophecy', false, 'Extura Prophecy with modern angular body.'),
  ('electric_guitar', 'Epiphone', 'Flying V Prophecy', 'Prophecy', false, 'Flying V Prophecy with Fishman Fluence pickups.'),
  ('electric_guitar', 'Kramer', 'NightSwan', 'NightSwan', false, 'Reissued NightSwan with Seymour Duncan pickups.'),
  ('electric_guitar', 'Kramer', 'SM-1 Figured', 'SM', false, 'SM-1 Figured with maple top and Floyd Rose.'),
  ('electric_guitar', 'EVH', 'SA-126 Special', 'SA-126', false, 'SA-126 Special semi hollow designed by Eddie Van Halen team.'),
  ('electric_guitar', 'Music Man', 'Kaizen 6', 'Kaizen', false, 'Tosin Abasi designed Kaizen 6 with multiscale option.'),
  ('electric_guitar', 'Music Man', 'Kaizen 7', 'Kaizen', false, '7-string Kaizen designed with Tosin Abasi.'),
  ('electric_guitar', 'Sterling by Music Man', 'Cutlass CT50 HSS', 'Cutlass', false, 'Cutlass CT50 with HSS pickups and vintage tremolo.'),
  ('electric_guitar', 'Sterling by Music Man', 'Axis AX3S', 'Axis', false, 'Axis AX3S with flame maple top and dual humbuckers.'),
  ('electric_guitar', 'Harley Benton', 'Fusion-II HH FR', 'Fusion', false, 'Fusion-II HH with Floyd Rose and roasted maple neck.'),
  ('electric_guitar', 'Harley Benton', 'TE-70 Black Paisley', 'TE', false, 'TE-70 Black Paisley with vintage style pickups.'),
  ('electric_guitar', 'Cort', 'KX507MS', 'KX', false, '7-string KX507 multiscale with Fishman Fluence pickups.'),
  ('electric_guitar', 'Cort', 'X700 Mutility', 'X', false, 'X700 Mutility with Fishman Fluence and multiscale design.'),
  ('electric_guitar', 'Sire', 'Larry Carlton H7', 'H', false, 'Larry Carlton H7 semi hollow with LC humbuckers.'),
  ('electric_guitar', 'Sire', 'Larry Carlton T7', 'T', false, 'Larry Carlton T7 Tele style with rolled edges.'),
  ('electric_guitar', 'Solar', 'E1.6', 'E', false, 'E1.6 with Evertune bridge and Duncan Solar pickups.'),
  ('electric_guitar', 'Solar', 'V1.6', 'V', false, 'V1.6 V shape with aggressive metal styling.'),
  ('electric_guitar', 'Solar', 'GC1.6', 'GC', false, 'GC1.6 single cut with modern metal appointments.'),
  ('electric_guitar', 'Yamaha', 'Pacifica Standard Plus', 'Pacifica', false, 'Pacifica Standard Plus with Reflectone pickups.'),
  ('electric_guitar', 'Yamaha', 'Pacifica Professional', 'Pacifica', false, 'Japan made Pacifica Professional with Reflectone pickups.'),
  ('electric_guitar', 'Rickenbacker', '620', '600', false, '620 solid body with dual high gain pickups.'),
  ('electric_guitar', 'Rickenbacker', '660', '600', false, '660 with vintage style toaster pickups.'),
  ('electric_guitar', 'Suhr', 'Classic S', 'Classic', false, 'Classic S with SSS or HSS options and 60s styling.'),
  ('electric_guitar', 'Suhr', 'Classic T', 'Classic', false, 'Classic T with Tele styling and Thornbucker option.'),
  ('electric_guitar', 'Squier', 'Classic Vibe Bass VI', 'Classic Vibe', false, 'Classic Vibe Bass VI six string bass guitar hybrid.'),
  ('electric_guitar', 'Squier', 'Mini Stratocaster', 'Mini', false, '3/4 scale Mini Strat for young players.'),
  ('electric_guitar', 'Squier', 'Mini Jazzmaster HH', 'Mini', false, '3/4 scale Mini Jazzmaster with dual humbuckers.'),
  ('bass_guitar', 'Danelectro', 'Longhorn Bass', 'Longhorn', true, 'Iconic Longhorn Bass with lipstick pickups and short scale.'),
  ('bass_guitar', 'Danelectro', '59DC Long Scale Bass', '59', false, '59DC Long Scale Bass with lipstick pickups.'),
  ('bass_guitar', 'Sadowsky', 'MetroExpress Vintage J/J 4', 'MetroExpress', false, 'MetroExpress Vintage Jazz style 4-string with Sadowsky preamp.'),
  ('bass_guitar', 'Sadowsky', 'MetroExpress Vintage J/J 5', 'MetroExpress', false, '5-string MetroExpress Vintage Jazz style.'),
  ('bass_guitar', 'Sadowsky', 'MetroExpress Vintage P/J 4', 'MetroExpress', false, 'MetroExpress Vintage P/J 4-string.'),
  ('bass_guitar', 'Sadowsky', 'MetroLine Vintage J/J 4', 'MetroLine', false, 'German made MetroLine Vintage Jazz style 4-string.'),
  ('bass_guitar', 'MTD', 'Kingston Z4', 'Kingston', false, 'Kingston Z4 with dual soapbar pickups.'),
  ('bass_guitar', 'MTD', 'Kingston Heir 4', 'Kingston', false, 'Kingston Heir 4 with single humbucker.'),
  ('bass_guitar', 'Ibanez', 'SR370E', 'SR', false, 'SR370E with PowerSpan dual coil pickups.'),
  ('bass_guitar', 'Ibanez', 'SR405EQM', 'SR', false, '5-string SR405E with quilted maple top.'),
  ('bass_guitar', 'Fender', 'Player Precision Bass', 'Player', true, 'Mexico built Player P Bass with Alnico split single-coil.'),
  ('bass_guitar', 'Fender', 'Player Jazz Bass', 'Player', true, 'Mexico built Player Jazz Bass with dual Alnico single-coils.'),
  ('bass_guitar', 'Fender', 'Player Jazz Bass V', 'Player', false, '5-string Player Jazz Bass.'),
  ('bass_guitar', 'ESP LTD', 'D-4', 'D', false, 'D-4 with neck through construction and active EQ.'),
  ('bass_guitar', 'ESP LTD', 'D-5', 'D', false, '5-string D-5 neck through.'),
  ('bass_guitar', 'ESP LTD', 'B-1005SE', 'B', false, 'B-1005SE 5-string with premium tonewoods.'),
  ('bass_guitar', 'Spector', 'Euro 4 LX', 'Euro', false, 'Euro 4 LX with EMG pickups and Tonepump preamp.'),
  ('bass_guitar', 'Spector', 'NS-2', 'NS', false, 'USA NS-2 with EMG pickups and curved body.'),
  ('bass_guitar', 'Warwick', 'German Pro Series Streamer Stage I', 'Pro Series', false, 'German made Streamer Stage I with active MEC pickups.'),
  ('bass_guitar', 'Peavey', 'Milestone', 'Milestone', false, 'Affordable Milestone 4-string with split coil pickup.'),
  ('bass_guitar', 'Dean', 'Edge 09', 'Edge', false, 'Edge 09 with single soapbar pickup.'),
  ('bass_guitar', 'Guild', 'Starfire Bass II', 'Starfire', false, 'Semi hollow Starfire Bass II with Bisonic pickups.'),
  ('bass_guitar', 'Music Man', 'StingRay Special 4 H', 'StingRay Special', false, 'StingRay Special 4-string with single Neodymium humbucker.'),
  ('bass_guitar', 'Cort', 'GB Modern 4', 'GB', false, 'GB Modern 4 with roasted maple neck and active EQ.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
