begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('electric_guitar', 'Gibson', 'Les Paul Standard 50s P-90', 'Les Paul Standard', false, 'USA Les Paul Standard with dual P-90 soapbar pickups and vintage 50s neck.'),
  ('electric_guitar', 'Gibson', 'Les Paul Standard 50s Faded', 'Les Paul Standard', false, 'Satin faded finish Les Paul Standard with Burstbucker 1 and 2 pickups.'),
  ('electric_guitar', 'Gibson', 'Les Paul Standard 50s Figured Top', 'Les Paul Standard', false, 'Les Paul Standard 50s with AA figured maple top and vintage 50s neck profile.'),
  ('electric_guitar', 'Gibson', 'Les Paul Standard 60s Faded', 'Les Paul Standard', false, 'Satin faded burst Les Paul Standard with slim taper 60s neck.'),
  ('electric_guitar', 'Gibson', 'Les Paul Standard 60s Figured Top', 'Les Paul Standard', false, 'Les Paul Standard 60s with AA figured maple top and Burstbucker 61 pickups.'),
  ('electric_guitar', 'Gibson', 'Les Paul Standard HP', 'Les Paul Standard', false, 'High Performance Les Paul with fast access heel and titanium saddles.'),
  ('electric_guitar', 'Gibson', 'Les Paul Modern Lite', 'Les Paul', false, 'Lightweight chambered Les Paul with slim taper neck and satin finish.'),
  ('electric_guitar', 'Gibson', 'Les Paul Modern Figured', 'Les Paul', false, 'Les Paul Modern with figured maple top, ebony board and coil tapping.'),
  ('electric_guitar', 'Gibson', 'Les Paul Modern Studio', 'Les Paul', false, 'Studio take on the Modern platform with contoured heel and push pull pots.'),
  ('electric_guitar', 'Gibson', 'Les Paul Tribute', 'Les Paul', true, 'Affordable USA Les Paul with satin finish and 490R and 490T humbuckers.'),
  ('electric_guitar', 'Gibson', 'Les Paul Studio Session', 'Les Paul', false, 'Les Paul Studio with AA figured top, push pull coil taps and no binding.'),
  ('electric_guitar', 'Gibson', 'Les Paul Studio Lite', 'Les Paul', false, 'Chambered 90s era Les Paul Studio with lightweight balanced body.'),
  ('electric_guitar', 'Gibson', 'Les Paul Studio Faded', 'Les Paul', false, 'Stripped down Les Paul Studio with thin satin faded finish.'),
  ('electric_guitar', 'Gibson', 'Les Paul Traditional', 'Les Paul', false, 'Non weight relieved Les Paul with vintage spec construction and 57 Classics.'),
  ('electric_guitar', 'Gibson', 'Les Paul Traditional Pro V', 'Les Paul', false, 'Guitar Center exclusive Traditional with coil tapping and asymmetrical neck.'),
  ('electric_guitar', 'Gibson', 'Les Paul Special Tribute Humbucker', 'Les Paul', false, 'Slab body Les Paul Special with dual humbuckers and satin finish.'),
  ('electric_guitar', 'Gibson', 'Les Paul Special Tribute P-90', 'Les Paul', false, 'Slab body Les Paul Special with raw sounding P-90 pickups.'),
  ('electric_guitar', 'Gibson', 'Les Paul Special Double Cut', 'Les Paul', false, 'Double cutaway Special with two P-90 pickups and wraparound bridge.'),
  ('electric_guitar', 'Gibson', 'Les Paul Junior Tribute DC', 'Les Paul', false, 'Double cutaway Junior with single doghouse P-90 and satin finish.'),
  ('electric_guitar', 'Gibson', 'Les Paul Supreme', 'Les Paul', false, 'Flagship Les Paul with AAA figured top, ebony board and split block inlays.'),
  ('electric_guitar', 'Gibson', 'Les Paul Axcess Standard', 'Les Paul Axcess', false, 'Contoured heel Les Paul with Floyd Rose option and thinner body.'),
  ('electric_guitar', 'Gibson', 'Les Paul Axcess Custom', 'Les Paul Axcess', false, 'Custom appointed Axcess with carved heel and ebony fingerboard.'),
  ('electric_guitar', 'Gibson', 'Les Paul 70s Deluxe', 'Les Paul', false, 'Reissue of the 70s Deluxe with mini humbuckers and bold neck profile.'),
  ('electric_guitar', 'Gibson', 'Les Paul Deluxe', 'Les Paul', false, 'Classic mini humbucker Les Paul introduced in 1969.'),
  ('electric_guitar', 'Gibson', 'Les Paul Classic Custom', 'Les Paul', false, 'Classic platform with Custom style binding and ebony fingerboard.'),
  ('electric_guitar', 'Gibson', 'Les Paul BFG', 'Les Paul', false, 'Raw unbound Les Paul with P-90 neck and Burstbucker 3 bridge pickups.'),
  ('electric_guitar', 'Gibson', 'Les Paul Gothic', 'Les Paul', false, 'Flat black Les Paul with ebony board and blacked out hardware.'),
  ('electric_guitar', 'Gibson', 'Les Paul Recording', 'Les Paul', false, 'Low impedance studio Les Paul from the early 70s with phase switching.'),
  ('electric_guitar', 'Gibson', 'Slash Les Paul Standard', 'Les Paul', true, 'Slash signature Les Paul with C shaped neck and custom Burstbucker Alnico II pickups.'),
  ('electric_guitar', 'Gibson', 'Slash Jessica Les Paul Standard', 'Les Paul', false, 'Recreation of the honey burst Les Paul Slash calls Jessica.'),
  ('electric_guitar', 'Gibson', 'Slash Victoria Les Paul Standard Goldtop', 'Les Paul', false, 'Goldtop Slash signature based on his guitar named Victoria.'),
  ('electric_guitar', 'Gibson', 'Kirk Hammett Greeny Les Paul Standard', 'Les Paul', true, 'Recreation of the 1959 burst once owned by Peter Green and Gary Moore.'),
  ('electric_guitar', 'Gibson', 'Adam Jones Les Paul Standard', 'Les Paul', false, 'Antique Silverburst signature with reversed Seymour Duncan Distortion in the neck.'),
  ('electric_guitar', 'Gibson', 'Jimmy Page Signature Les Paul', 'Les Paul', true, 'Nineties USA signature modeled on the Led Zeppelin Number Two Les Paul.'),
  ('electric_guitar', 'Gibson', 'Peter Frampton Phenix Les Paul Custom', 'Les Paul', false, 'Three pickup black Custom recreating the famous Frampton Phenix.'),
  ('electric_guitar', 'Gibson', 'Billie Joe Armstrong Les Paul Junior', 'Les Paul', false, 'Green Day signature Junior with single H-90 style P-90 pickup.'),
  ('electric_guitar', 'Gibson', 'Rick Beato Les Paul Special Double Cut', 'Les Paul', false, 'Signature double cut Special in Sparkling Burgundy with P-90 pickups.'),
  ('electric_guitar', 'Gibson', 'SG Standard ''61', 'SG', true, 'Vintage spec SG with small pickguard, slim taper neck and Burstbucker 61 pickups.'),
  ('electric_guitar', 'Gibson', 'SG Standard ''61 Maestro Vibrola', 'SG', false, 'SG Standard 61 fitted with the long Maestro Vibrola tailpiece.'),
  ('electric_guitar', 'Gibson', 'SG Standard ''61 Sideways Vibrola', 'SG', false, 'SG Standard 61 with the period correct sideways action vibrola.'),
  ('electric_guitar', 'Gibson', 'SG Standard ''61 Faded Maestro Vibrola', 'SG', false, 'Faded satin SG Standard 61 with Maestro Vibrola tailpiece.'),
  ('electric_guitar', 'Gibson', 'SG Standard HP', 'SG', false, 'High Performance SG with fast access neck joint and locking tuners.'),
  ('electric_guitar', 'Gibson', 'SG Modern', 'SG', false, 'Modern SG with AA figured top, ebony board and 24 fret access.'),
  ('electric_guitar', 'Gibson', 'SG Tribute', 'SG', false, 'Affordable USA SG with satin finish and 490 humbucker pair.'),
  ('electric_guitar', 'Gibson', 'SG Junior', 'SG', false, 'Single P-90 SG with wraparound bridge and stripped down controls.'),
  ('electric_guitar', 'Gibson', 'SG Classic', 'SG', false, 'SG with dual P-90 soapbars and vintage style appointments.'),
  ('electric_guitar', 'Gibson', 'SG Supreme', 'SG', false, 'Upscale SG with figured maple top and split diamond styling.'),
  ('electric_guitar', 'Gibson', 'SG Special Faded', 'SG', false, 'Worn finish SG Special with 490 humbuckers and rosewood board.'),
  ('electric_guitar', 'Gibson', 'SG Gothic', 'SG', false, 'Matte black SG with ebony fingerboard and minimal appointments.'),
  ('electric_guitar', 'Gibson', 'Tony Iommi SG Special', 'SG', true, 'Black Sabbath signature SG with signed Iommi humbuckers.'),
  ('electric_guitar', 'Gibson', 'Angus Young SG', 'SG', true, 'AC DC signature SG with Angus Young bridge humbucker and lightning inlays.'),
  ('electric_guitar', 'Gibson', 'Gary Clark Jr. SG', 'SG', false, 'Signature SG voiced for blues rock with dual humbuckers.'),
  ('electric_guitar', 'Gibson', 'Kirk Douglas SG', 'SG', false, 'Roots signature SG with three pickups and Maestro Vibrola.'),
  ('electric_guitar', 'Gibson', 'ES-335 Figured', 'ES', true, 'Semi hollow ES-335 with figured maple top and Calibrated T-Type humbuckers.'),
  ('electric_guitar', 'Gibson', 'ES-335 Satin', 'ES', false, 'Workhorse ES-335 with thin satin nitro finish.'),
  ('electric_guitar', 'Gibson', 'ES-335 Studio', 'ES', false, 'Stripped down ES-335 with simplified appointments and lower cost.'),
  ('electric_guitar', 'Gibson', 'ES-339 Figured', 'ES', false, 'Compact semi hollow with figured top and 335 style tone.'),
  ('electric_guitar', 'Gibson', 'ES-345', 'ES', true, 'Step up semi hollow with split parallelogram inlays and gold hardware.'),
  ('electric_guitar', 'Gibson', 'ES-355', 'ES', true, 'Top of the line semi hollow with ebony board and multi ply binding.'),
  ('electric_guitar', 'Gibson', 'ES-330', 'ES', false, 'Fully hollow thinline with dual P-90 pickups and trapeze tailpiece.'),
  ('electric_guitar', 'Gibson', 'ES-275', 'ES', false, 'Single cutaway hollowbody archtop for jazz and blues.'),
  ('electric_guitar', 'Gibson', 'ES-235', 'ES', false, 'Affordable full hollow thinline with a Les Paul inspired outline.'),
  ('electric_guitar', 'Gibson', 'ES-333', 'ES', false, 'No frills ES-335 variant from the 2000s with rear access panel.'),
  ('electric_guitar', 'Gibson', 'Tom DeLonge ES-333', 'ES', false, 'Blink 182 signature semi hollow with single Dirty Fingers bridge humbucker.'),
  ('electric_guitar', 'Gibson', 'ES-347', 'ES', false, 'Late 70s semi hollow with coil tap, TP-6 tailpiece and ebony board.'),
  ('electric_guitar', 'Gibson', 'ES-137 Classic', 'ES', false, 'Laminated single cut hollowbody blending archtop and solidbody feel.'),
  ('electric_guitar', 'Gibson', 'ES-137 Custom', 'ES', false, 'Upscale ES-137 with varitone switch and split diamond inlays.'),
  ('electric_guitar', 'Gibson', 'ES-135', 'ES', false, 'Nineties single cutaway thinline hollowbody with P-100 or humbucker pickups.'),
  ('electric_guitar', 'Gibson', 'ES-175', 'ES', true, 'Iconic jazz archtop with florentine cutaway used by countless jazz greats.'),
  ('electric_guitar', 'Gibson', 'ES-295', 'ES', false, 'Gold finished hollowbody with P-90s made famous by Scotty Moore.'),
  ('electric_guitar', 'Gibson', 'B.B. King Lucille', 'ES', true, 'Signature ES-355 style guitar with varitone and no f holes.'),
  ('electric_guitar', 'Gibson', 'Midtown Custom', 'Midtown', false, 'Solid routed semi hollow with 335 looks and compact feel.'),
  ('electric_guitar', 'Gibson', 'L-5 CES', 'Archtop', false, 'Flagship carved top jazz archtop with dual humbuckers.'),
  ('electric_guitar', 'Gibson', 'Super 400 CES', 'Archtop', false, 'Grand 18 inch carved archtop with luxurious appointments.'),
  ('electric_guitar', 'Gibson', 'Byrdland', 'Archtop', false, 'Short scale thinline archtop developed with Billy Byrd and Hank Garland.'),
  ('electric_guitar', 'Gibson', 'Blueshawk', 'Blueshawk', false, 'Compact semi hollow blues guitar with Blues 90 pickups and varitone.'),
  ('electric_guitar', 'Gibson', '70s Explorer', 'Explorer', false, 'Reissue of the 70s Explorer with bold headstock and ceramic humbuckers.'),
  ('electric_guitar', 'Gibson', '80s Explorer', 'Explorer', false, 'Eighties style Explorer with Dirty Fingers humbuckers.'),
  ('electric_guitar', 'Gibson', 'Lzzy Hale Explorerbird', 'Explorer', false, 'Halestorm signature blending Explorer body with Firebird headstock.'),
  ('electric_guitar', 'Gibson', '70s Flying V', 'Flying V', true, 'Reissue of the 70s Flying V with medallion era styling.'),
  ('electric_guitar', 'Gibson', '80s Flying V', 'Flying V', false, 'Eighties style Flying V with hot Dirty Fingers pickups.'),
  ('electric_guitar', 'Gibson', 'Dave Mustaine Flying V EXP', 'Flying V', false, 'Megadeth signature V with explorer style headstock and Seymour Duncan Thrash Factor pickups.'),
  ('electric_guitar', 'Gibson', 'Firebird V', 'Firebird', true, 'Classic neck through Firebird with two mini humbuckers.'),
  ('electric_guitar', 'Gibson', 'Firebird VII', 'Firebird', false, 'Three pickup Firebird with gold hardware and block inlays.'),
  ('electric_guitar', 'Gibson', 'Firebird Studio', 'Firebird', false, 'Simplified set neck Firebird with full size humbuckers.'),
  ('electric_guitar', 'Gibson', 'Firebird Zero', 'Firebird', false, 'Entry level Firebird with slab body and dual humbuckers.'),
  ('electric_guitar', 'Gibson', 'Theodore Standard', 'Theodore', false, 'Production model of the 1957 Ted McCarty prototype design.'),
  ('electric_guitar', 'Gibson', 'RD Artist', 'RD', false, 'Late 70s long scale design with active Moog electronics.'),
  ('electric_guitar', 'Gibson', 'Melody Maker', 'Melody Maker', false, 'Slim slab body student model with single coil pickup.'),
  ('electric_guitar', 'Gibson', 'Marauder', 'Marauder', false, 'Seventies bolt on Gibson with humbucker and blade single coil.'),
  ('electric_guitar', 'Gibson', 'S-1', 'S-1', false, 'Seventies bolt on model with three single coils and rotary switching.'),
  ('electric_guitar', 'Gibson', 'Nighthawk Standard', 'Nighthawk', false, 'Nineties hybrid design with slanted bridge humbucker and five sounds.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Standard', 'Les Paul', true, 'Core Epiphone Les Paul with mahogany body and maple top.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Standard Plustop PRO', 'Les Paul', true, 'Flame top Les Paul with ProBucker pickups and coil tapping.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Modern Figured', 'Les Paul', false, 'Modern weight relieved Les Paul with figured top and ebony board.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Studio E1', 'Les Paul', false, 'Entry Les Paul Studio with bolt on neck and open coil humbuckers.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Special', 'Les Paul', false, 'TV Yellow slab body Special with dual P-90 PRO pickups.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Special Satin E1', 'Les Paul', false, 'Budget friendly Special with satin finish and humbuckers.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Special II', 'Les Paul', true, 'Long running beginner Les Paul with two open coil humbuckers.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Special VE', 'Les Paul', false, 'Vintage Edition Special with poplar body and worn finish.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Junior', 'Les Paul', false, 'Single P-90 slab body Junior with wraparound bridge.'),
  ('electric_guitar', 'Epiphone', 'Les Paul SL', 'Les Paul', false, 'Ultra affordable slim Les Paul with two ceramic single coils.'),
  ('electric_guitar', 'Epiphone', 'Les Paul 100', 'Les Paul', false, 'Entry level bolt on Les Paul with 700T and 650R humbuckers.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Muse', 'Muse', true, 'Lightweight chambered Les Paul with Fishman Fluence pickups.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Prophecy', 'Prophecy', false, 'Modern Les Paul with Fishman Fluence pickups and asymmetrical neck.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Custom Koa', 'Les Paul', false, 'Les Paul Custom variant with koa top and gold hardware.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Custom PRO', 'Les Paul', false, 'Les Paul Custom with ProBucker pickups and coil splitting.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Classic Worn', 'Les Paul', false, 'Worn open grain finish Classic with Alnico Classic PRO humbuckers.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Ultra-III', 'Les Paul', false, 'Chambered Les Paul with NanoMag pickup and USB output.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Tribute Plus', 'Les Paul', false, 'Upscale Les Paul with Gibson 57 Classic pickups and flame top.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Florentine PRO', 'Les Paul', false, 'Semi hollow Les Paul with f hole and ProBucker pickups.'),
  ('electric_guitar', 'Epiphone', 'Power Players Les Paul', 'Power Players', false, 'Short scale three quarter size Les Paul for younger players.'),
  ('electric_guitar', 'Epiphone', 'Power Players SG', 'Power Players', false, 'Short scale three quarter size SG with full accessories bundle.'),
  ('electric_guitar', 'Epiphone', 'SG Muse', 'Muse', false, 'Metallic finish SG with Alnico Classic PRO pickups and coil splitting.'),
  ('electric_guitar', 'Epiphone', 'SG Prophecy', 'Prophecy', false, 'Modern SG with Fishman Fluence pickups and 24 fret ebony board.'),
  ('electric_guitar', 'Epiphone', 'SG Special', 'SG', false, 'Affordable SG with P-90 PRO pickups and wraparound bridge.'),
  ('electric_guitar', 'Epiphone', 'SG Special Satin E1', 'SG', false, 'Entry SG with satin finish and open coil humbuckers.'),
  ('electric_guitar', 'Epiphone', 'SG Special VE', 'SG', false, 'Vintage Edition SG with poplar body and worn finish.'),
  ('electric_guitar', 'Epiphone', 'SG Classic Worn P-90s', 'SG', false, 'Worn finish SG with dual P-90 soapbar pickups.'),
  ('electric_guitar', 'Epiphone', 'SG Modern Figured', 'SG', false, 'Contemporary SG with figured top and coil tapping.'),
  ('electric_guitar', 'Epiphone', 'SG Custom', 'SG', false, 'Ebony SG Custom with gold hardware and block and triangle inlays.'),
  ('electric_guitar', 'Epiphone', 'SG Standard ''61', 'SG', false, 'Vintage spec SG with small pickguard and slim taper neck.'),
  ('electric_guitar', 'Epiphone', 'SG Standard ''61 Maestro Vibrola', 'SG', false, 'SG Standard 61 with the long Maestro Vibrola tailpiece.'),
  ('electric_guitar', 'Epiphone', 'G-400 PRO', 'SG', true, 'Best selling SG with Alnico Classic PRO pickups and coil splitting.'),
  ('electric_guitar', 'Epiphone', 'G-310', 'SG', false, 'Entry level bolt on SG with open coil humbuckers.'),
  ('electric_guitar', 'Epiphone', '1961 Les Paul SG Standard', 'Inspired by Gibson', false, 'Sixty one spec SG with period correct styling and Maestro option.'),
  ('electric_guitar', 'Epiphone', 'Tony Iommi SG Special', 'SG', true, 'Black Sabbath signature SG with Gibson USA Tony Iommi humbuckers.'),
  ('electric_guitar', 'Epiphone', 'Flying V Prophecy', 'Prophecy', false, 'Modern Flying V with Fishman Fluence pickups and ebony board.'),
  ('electric_guitar', 'Epiphone', 'Extura Prophecy', 'Prophecy', false, 'Radical modern body shape with Fishman Fluence pickups.'),
  ('electric_guitar', 'Epiphone', 'ES-339', 'ES', false, 'Compact semi hollow with Alnico Classic PRO humbuckers.'),
  ('electric_guitar', 'Epiphone', 'ES-335 Figured', 'ES', false, 'Semi hollow ES-335 with figured maple veneer top.'),
  ('electric_guitar', 'Epiphone', 'Casino Coupe', 'Casino', true, 'Compact 339 sized version of the fully hollow Casino.'),
  ('electric_guitar', 'Epiphone', 'Casino Worn', 'Casino', false, 'Worn finish Casino with dual P-90 pickups and hollow body.'),
  ('electric_guitar', 'Epiphone', 'USA Casino', 'Casino', false, 'American made Casino with Gibson USA P-90 pickups.'),
  ('electric_guitar', 'Epiphone', 'Riviera', 'Riviera', true, 'Semi hollow with mini humbuckers and Frequensator tailpiece.'),
  ('electric_guitar', 'Epiphone', 'Riviera Custom P93', 'Riviera', false, 'Riviera variant with three P-90 pickups and Bigsby vibrato.'),
  ('electric_guitar', 'Epiphone', 'Wildkat', 'Wildkat', false, 'Compact semi hollow with P-90 pickups and Bigsby vibrato.'),
  ('electric_guitar', 'Epiphone', 'Dot', 'ES', true, 'Long running affordable ES-335 style semi hollow.'),
  ('electric_guitar', 'Epiphone', 'Dot Deluxe', 'ES', false, 'Dot semi hollow with flame maple veneer top.'),
  ('electric_guitar', 'Epiphone', 'Dot Studio', 'ES', false, 'Stripped down Dot with no pickguard and simple controls.'),
  ('electric_guitar', 'Epiphone', 'Sheraton', 'Sheraton', true, 'Upscale semi hollow with block and triangle inlays.'),
  ('electric_guitar', 'Epiphone', 'Broadway', 'Archtop', false, 'Full size hollowbody jazz archtop with floating pickguard.'),
  ('electric_guitar', 'Epiphone', 'Century', 'Archtop', false, 'Reissue of the 1966 thinline hollowbody with single P-90.'),
  ('electric_guitar', 'Epiphone', 'Emperor Swingster', 'Archtop', false, 'Rockabilly ready hollowbody with SwingBucker pickups and Bigsby.'),
  ('electric_guitar', 'Epiphone', 'Joe Pass Emperor-II PRO', 'Archtop', false, 'Jazz signature hollowbody with ProBucker pickups.'),
  ('electric_guitar', 'Epiphone', 'Blueshawk Deluxe', 'Blueshawk', false, 'Semi hollow blues machine with P-90 PRO pickups and varitone.'),
  ('electric_guitar', 'Epiphone', 'Uptown Kat ES', 'Kat', false, 'Sleek semi hollow with mini humbuckers and metallic finishes.'),
  ('electric_guitar', 'Epiphone', 'B.B. King Lucille', 'ES', false, 'Signature 355 style semi hollow with varitone and no f holes.'),
  ('electric_guitar', 'Epiphone', 'Genesis Deluxe PRO', 'Genesis', false, 'Reissue of the late 70s carved top double cutaway design.'),
  ('electric_guitar', 'Epiphone', 'Nighthawk Custom Reissue', 'Nighthawk', false, 'Reissue of the 90s hybrid with slanted bridge humbucker.'),
  ('electric_guitar', 'Epiphone', 'Firebird', 'Firebird', false, 'Reverse body Firebird with mini humbuckers and banjo tuners.'),
  ('electric_guitar', 'Epiphone', 'Firebird Studio', 'Firebird', false, 'Simplified Firebird with full size humbuckers and set neck.'),
  ('electric_guitar', 'Epiphone', '1984 Explorer EX', 'Explorer', false, 'Eighties style Explorer with EMG 81 and 85 active pickups.'),
  ('electric_guitar', 'Epiphone', '1958 Korina Explorer', 'Inspired by Gibson Custom', false, 'Korina bodied recreation of the 1958 Explorer.'),
  ('electric_guitar', 'Epiphone', '1958 Korina Flying V', 'Inspired by Gibson Custom', false, 'Korina bodied recreation of the 1958 Flying V.'),
  ('electric_guitar', 'Epiphone', 'Crestwood Custom', 'Crestwood', false, 'Reissue of the 60s double cutaway with mini humbuckers.'),
  ('electric_guitar', 'Epiphone', 'Wilshire', 'Wilshire', false, 'Reissue of the 60s solidbody with dual P-90 pickups.'),
  ('electric_guitar', 'Epiphone', 'Coronet', 'Coronet', false, 'Reissue of the 60s single P-90 student solidbody.'),
  ('electric_guitar', 'Epiphone', '1959 Les Paul Standard', 'Inspired by Gibson Custom', true, 'Fifty nine spec Les Paul with Gibson BurstBucker pickups.'),
  ('electric_guitar', 'Epiphone', '1963 Les Paul SG Custom', 'Inspired by Gibson Custom', false, 'Three pickup SG Custom recreation with Maestro Vibrola.'),
  ('electric_guitar', 'Epiphone', '1963 Firebird V', 'Inspired by Gibson Custom', false, 'Vintage spec Firebird V with Maestro Vibrola tailpiece.'),
  ('electric_guitar', 'Epiphone', '1959 ES-355', 'Inspired by Gibson Custom', false, 'Fifty nine spec ES-355 with Gibson USA humbuckers.'),
  ('electric_guitar', 'Epiphone', 'Slash Les Paul Standard', 'Les Paul', true, 'Slash signature Les Paul with custom ProBucker pickups.'),
  ('electric_guitar', 'Epiphone', 'Slash AFD Les Paul Special-II', 'Les Paul', false, 'Appetite for Destruction themed starter Les Paul.'),
  ('electric_guitar', 'Epiphone', 'Kirk Hammett Greeny Les Paul Standard', 'Les Paul', true, 'Affordable version of the famous Greeny 1959 burst.'),
  ('electric_guitar', 'Epiphone', 'Kirk Hammett 1979 Flying V', 'Flying V', false, 'Recreation of the 1979 Flying V Hammett has played for decades.'),
  ('electric_guitar', 'Epiphone', 'Matt Heafy Les Paul Custom Origins', 'Les Paul', false, 'Trivium signature Custom with Fishman Fluence Custom pickups.'),
  ('electric_guitar', 'Epiphone', 'Matt Heafy Les Paul Custom Origins 7-String', 'Les Paul', false, 'Seven string version of the Heafy signature Custom.'),
  ('electric_guitar', 'Epiphone', 'Jared James Nichols Gold Glory Les Paul Custom', 'Les Paul', false, 'Single P-90 gold Les Paul Custom signature.'),
  ('electric_guitar', 'Epiphone', 'Joan Jett Olympic Special', 'Olympic', false, 'Signature take on the 60s Olympic with single bridge humbucker.'),
  ('electric_guitar', 'Epiphone', 'Adam Jones Les Paul Custom', 'Les Paul', false, 'Tool signature Silverburst Custom with reversed neck humbucker.'),
  ('electric_guitar', 'Epiphone', 'Jerry Cantrell Wino Les Paul Custom', 'Les Paul', false, 'Alice in Chains signature Custom in dark wine red.'),
  ('electric_guitar', 'Epiphone', 'Alex Lifeson Les Paul Custom Axcess', 'Les Paul Axcess', false, 'Rush signature Axcess with Floyd Rose and piezo bridge option.'),
  ('electric_guitar', 'Epiphone', 'Vivian Campbell Holy Diver Les Paul', 'Les Paul', false, 'Def Leppard signature Les Paul honoring the Holy Diver era.'),
  ('electric_guitar', 'Epiphone', 'Emily Wolfe Sheraton Stealth', 'Sheraton', false, 'Blacked out signature Sheraton with mini humbuckers.'),
  ('electric_guitar', 'Epiphone', 'Dave Grohl DG-335', 'DG', true, 'Foo Fighters signature semi hollow based on the Trini Lopez shape.'),
  ('electric_guitar', 'Epiphone', 'Noel Gallagher Riviera', 'Riviera', false, 'Oasis signature Riviera in dark wine red.'),
  ('electric_guitar', 'Epiphone', 'Brendon Small Thunderhorse Explorer', 'Explorer', false, 'Dethklok signature Explorer with hot ceramic humbuckers.'),
  ('electric_guitar', 'Epiphone', 'Lzzy Hale Explorerbird', 'Explorer', false, 'Halestorm signature Explorer with Firebird headstock in cherry.'),
  ('electric_guitar', 'Epiphone', 'Dave Mustaine Flying V EXP', 'Flying V', false, 'Megadeth signature V with Fishman Fluence signature pickups.'),
  ('electric_guitar', 'Epiphone', 'Richie Faulkner Flying V Custom', 'Flying V', false, 'Judas Priest signature V with Floyd Rose and EMG pickups.'),
  ('electric_guitar', 'Epiphone', 'Gary Clark Jr. Blak & Blu Casino', 'Casino', false, 'Signature Casino with Bigsby option in custom blue finish.'),
  ('electric_guitar', 'Epiphone', 'Joe Bonamassa Amos Korina Flying V', 'Flying V', false, 'Recreation of the famous 1958 korina V named Amos.'),
  ('electric_guitar', 'Epiphone', 'Joe Bonamassa Black Beauty Les Paul Custom', 'Les Paul', false, 'Three pickup black Custom based on the Bonamassa original.'),
  ('electric_guitar', 'Epiphone', 'Billie Joe Armstrong Les Paul Junior', 'Les Paul', false, 'Green Day signature Junior with single P-90 pickup.'),
  ('electric_guitar', 'Kramer', 'Baretta', 'Baretta', true, 'Iconic single humbucker shred machine with Floyd Rose tremolo.'),
  ('electric_guitar', 'Kramer', 'Baretta Special', 'Baretta', false, 'Affordable Baretta with single zebra humbucker and hardtail option.'),
  ('electric_guitar', 'Kramer', 'Baretta Vintage', 'Baretta', false, 'Vintage spec Baretta with beak headstock and Seymour Duncan JB.'),
  ('electric_guitar', 'Kramer', 'Pacer', 'Pacer', false, 'Original 80s hot rod platform that defined the superstrat.'),
  ('electric_guitar', 'Kramer', 'Pacer Classic', 'Pacer', true, 'Classic Pacer with dual humbuckers and Floyd Rose Special.'),
  ('electric_guitar', 'Kramer', 'Pacer Vintage', 'Pacer', false, 'Vintage style Pacer with beak headstock and HSS layout option.'),
  ('electric_guitar', 'Kramer', 'Pacer Carrera', 'Pacer', false, 'Eighties Pacer variant with hot humbucker and slanted single coils.'),
  ('electric_guitar', 'Kramer', 'SM-1', 'SM', false, 'Modern superstrat with three pickups and Floyd Rose 1000.'),
  ('electric_guitar', 'Kramer', 'SM-1 Figured', 'SM', false, 'SM-1 with figured maple top and Seymour Duncan pickups.'),
  ('electric_guitar', 'Kramer', 'SM-1 H', 'SM', false, 'Single humbucker version of the SM-1 with hardtail bridge.'),
  ('electric_guitar', 'Kramer', 'Assault 220', 'Assault', false, 'Single cutaway rocker with dual humbuckers and set neck.'),
  ('electric_guitar', 'Kramer', 'Focus VT-211S', 'Focus', false, 'Affordable HSS double cutaway with vintage style tremolo.'),
  ('electric_guitar', 'Kramer', 'Focus VT-111S', 'Focus', false, 'Entry level Focus with three single coil pickups.'),
  ('electric_guitar', 'Kramer', 'Striker HSS', 'Striker', false, 'Modern Striker with HSS pickups and double locking tremolo.'),
  ('electric_guitar', 'Kramer', 'Striker Figured HSS', 'Striker', false, 'Striker with figured maple veneer and Floyd Rose Special.'),
  ('electric_guitar', 'Kramer', 'The 84', 'Original Collection', true, 'Recreation of the 1984 one humbucker one knob formula.'),
  ('electric_guitar', 'Kramer', 'Jersey Star', 'Original Collection', false, 'Richie Sambora inspired star inlay model with three pickups.'),
  ('electric_guitar', 'Kramer', 'Nightswan', 'Original Collection', true, 'Reissue of the Vivian Campbell era design with polka dot options.'),
  ('electric_guitar', 'Kramer', 'Nite-V', 'Original Collection', false, 'Aggressive V shape with Floyd Rose and hot humbuckers.'),
  ('electric_guitar', 'Kramer', 'Voyager', 'Original Collection', false, 'Radical 80s offset shape reissued with double locking tremolo.'),
  ('electric_guitar', 'Kramer', 'Charlie Parra Vanguard', 'Artist', false, 'Signature V for the Peruvian metal guitarist with EMG pickups.'),
  ('electric_guitar', 'Kramer', 'Dave Snake Sabo Baretta', 'Artist', false, 'Skid Row signature Baretta in green burst.'),
  ('electric_guitar', 'Kramer', 'Tracii Guns Gunstar Voyager', 'Artist', false, 'LA Guns signature Voyager with dual humbuckers and Floyd Rose.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
