begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('electric_guitar', 'PRS', 'Custom 22', 'Core', true, 'Core double cutaway with 22 frets and warmer midrange than the Custom 24.'),
  ('electric_guitar', 'PRS', 'Custom 24-08', 'Core', false, 'Core Custom 24 with eight-way switching for expanded pickup combinations.'),
  ('electric_guitar', 'PRS', 'Custom 24 Piezo', 'Core', false, 'Core Custom 24 with an LR Baggs piezo bridge system for acoustic textures.'),
  ('electric_guitar', 'PRS', 'McCarty', 'McCarty', false, 'Vintage voiced core model with thicker mahogany back and 58/15 LT humbuckers.'),
  ('electric_guitar', 'PRS', 'McCarty 594 Singlecut', 'McCarty', false, 'Single cutaway 594 with dual volume and tone controls and vintage output pickups.'),
  ('electric_guitar', 'PRS', 'McCarty 594 Hollowbody II', 'McCarty', false, 'Fully hollow 594 with figured maple top and back and vintage voiced humbuckers.'),
  ('electric_guitar', 'PRS', 'DGT', 'Core', true, 'David Grissom signature with tall frets and specially wound DGT pickups.'),
  ('electric_guitar', 'PRS', 'Paul''s Guitar', 'Core', true, 'Signature core model with TCI treble and bass pickups and brushstroke inlays.'),
  ('electric_guitar', 'PRS', 'Special Semi-Hollow', 'Core', false, 'Semi hollow core model with Narrowfield middle pickup and 58/15 LT humbuckers.'),
  ('electric_guitar', 'PRS', '509', 'Core', false, 'Five pickup core model delivering nine distinct sounds from one guitar.'),
  ('electric_guitar', 'PRS', 'Studio', 'Core', false, 'Core model pairing two Narrowfield pickups with a 58/15 LT bridge humbucker.'),
  ('electric_guitar', 'PRS', 'Modern Eagle V', 'Core', false, 'Top tier core model with TCI tuned pickups and five way blade switching.'),
  ('electric_guitar', 'PRS', 'Hollowbody II', 'Core', true, 'Fully hollow double cutaway with figured maple top and back.'),
  ('electric_guitar', 'PRS', 'Hollowbody II Piezo', 'Core', false, 'Hollowbody II with LR Baggs piezo system for blending electric and acoustic tones.'),
  ('electric_guitar', 'PRS', 'Santana', 'Signature', false, 'Carlos Santana signature with short scale and Santana III pickups.'),
  ('electric_guitar', 'PRS', 'Santana Retro', 'Signature', false, 'Reissue styled Santana signature based on his early PRS instruments.'),
  ('electric_guitar', 'PRS', 'Swamp Ash Special', 'Core', false, 'Swamp ash bodied core model with hum single hum pickup layout.'),
  ('electric_guitar', 'PRS', 'NF 53', 'Core', false, 'Bolt on swamp ash model with Narrowfield DD pickups and 1953 inspired styling.'),
  ('electric_guitar', 'PRS', 'Myles Kennedy', 'Signature', false, 'Myles Kennedy signature based on the NF 53 platform with custom wound pickups.'),
  ('electric_guitar', 'PRS', 'Tremonti', 'Signature', true, 'Mark Tremonti singlecut signature with tremolo and high output bridge pickup.'),
  ('electric_guitar', 'PRS', 'DW CE 24 Floyd', 'Signature', false, 'Dustie Waring signature CE with Floyd Rose and Mojotone DW Tomahawk pickups.'),
  ('electric_guitar', 'PRS', 'CE 24 Semi-Hollow', 'Core', false, 'Bolt on CE 24 with semi hollow construction and single f-hole.'),
  ('electric_guitar', 'PRS', 'Fiore', 'Signature', false, 'Mark Lettieri signature bolt on with HSS layout and versatile switching.'),
  ('electric_guitar', 'PRS', 'S2 Standard 24', 'S2', false, 'US made all mahogany double cutaway with 85/15 S pickups.'),
  ('electric_guitar', 'PRS', 'S2 Standard 22', 'S2', false, '22 fret S2 Standard with all mahogany body and satin nitro finish.'),
  ('electric_guitar', 'PRS', 'S2 Vela', 'S2', true, 'Offset S2 body with DS-01 bridge humbucker and Type-D single coil neck pickup.'),
  ('electric_guitar', 'PRS', 'S2 Vela Semi-Hollow', 'S2', false, 'Semi hollow version of the offset Vela with added resonance.'),
  ('electric_guitar', 'PRS', 'S2 Starla', 'S2', false, 'Retro styled S2 with DS-02 humbuckers and vintage flair.'),
  ('electric_guitar', 'PRS', 'S2 McCarty 594 Singlecut', 'S2', false, 'US made singlecut 594 with 58/15 LT S pickups.'),
  ('electric_guitar', 'PRS', 'S2 McCarty 594 Thinline', 'S2', false, 'Lightweight thinline 594 with vintage voiced humbuckers.'),
  ('electric_guitar', 'PRS', 'S2 Custom 24-08', 'S2', false, 'S2 Custom 24 with dual mini switches for eight pickup combinations.'),
  ('electric_guitar', 'PRS', 'S2 Custom 22 Semi-Hollow', 'S2', false, 'Semi hollow S2 custom with 22 frets and coil splitting.'),
  ('electric_guitar', 'PRS', 'SE Standard 24-08', 'SE', false, 'Affordable all mahogany SE with eight-way switching.'),
  ('electric_guitar', 'PRS', 'SE Paul''s Guitar', 'SE', true, 'SE version of the signature core model with TCI S pickups and mini toggles.'),
  ('electric_guitar', 'PRS', 'SE Hollowbody II', 'SE', true, 'Fully hollow SE with maple top and back and 58/15 S pickups.'),
  ('electric_guitar', 'PRS', 'SE Hollowbody II Piezo', 'SE', false, 'SE hollowbody with added piezo bridge for acoustic sounds.'),
  ('electric_guitar', 'PRS', 'SE Hollowbody Standard', 'SE', false, 'All mahogany fully hollow SE model with warm voicing.'),
  ('electric_guitar', 'PRS', 'SE Zach Myers', 'SE', true, 'Zach Myers signature semi hollow SE with wide fat neck.'),
  ('electric_guitar', 'PRS', 'SE Mark Holcomb', 'SE', false, 'Mark Holcomb signature SE with Seymour Duncan Alpha and Omega pickups.'),
  ('electric_guitar', 'PRS', 'SE Mark Holcomb SVN', 'SE', false, 'Seven string version of the Mark Holcomb SE signature.'),
  ('electric_guitar', 'PRS', 'SE Paul Allender', 'SE', false, 'Paul Allender signature SE with Floyd Rose and bat inlays.'),
  ('electric_guitar', 'PRS', 'SE Mira', 'SE', false, 'Lightweight SE double cutaway with retro voiced humbuckers.'),
  ('electric_guitar', 'PRS', 'SE Starla', 'SE', false, 'Retro styled SE with two humbuckers and vintage vibe.'),
  ('electric_guitar', 'PRS', 'SE Santana', 'SE', false, 'SE version of the Santana signature with short scale length.'),
  ('electric_guitar', 'PRS', 'SE Swamp Ash Special', 'SE', false, 'SE with swamp ash body and hum single hum pickup layout.'),
  ('electric_guitar', 'PRS', 'SE 277', 'SE', false, 'Baritone SE with 27.7 inch scale tuned B to B.'),
  ('electric_guitar', 'PRS', 'SE Custom 22 Semi-Hollow', 'SE', false, 'Semi hollow SE custom with 22 frets and f-hole.'),
  ('electric_guitar', 'PRS', 'SE Tremonti', 'SE', false, 'Affordable version of the Mark Tremonti singlecut signature.'),
  ('electric_guitar', 'PRS', 'SE NF3', 'SE', false, 'SE bolt on with three Narrowfield pickups for hum free single coil tones.'),
  ('electric_guitar', 'PRS', 'SE CE 24 Standard Satin', 'SE', false, 'Bolt on SE CE with all mahogany body and satin finish.'),
  ('electric_guitar', 'PRS', 'SE 245', 'SE', false, 'Singlecut SE with shorter 24.5 inch scale and 245 S pickups.'),
  ('electric_guitar', 'Gretsch', 'G2210 Streamliner Junior Jet Club', 'Streamliner', false, 'Affordable solid body Jet with Broad Tron BT-2S humbuckers.'),
  ('electric_guitar', 'Gretsch', 'G2215-P90 Streamliner Junior Jet Club', 'Streamliner', false, 'Junior Jet pairing a P90 style neck pickup with a Broad Tron bridge.'),
  ('electric_guitar', 'Gretsch', 'G2420 Streamliner Hollow Body', 'Streamliner', false, 'Full hollow single cutaway Streamliner with Chromatic II tailpiece.'),
  ('electric_guitar', 'Gretsch', 'G2420T Streamliner Hollow Body with Bigsby', 'Streamliner', false, 'Hollow body Streamliner with licensed Bigsby vibrato.'),
  ('electric_guitar', 'Gretsch', 'G2622 Streamliner Center Block', 'Streamliner', true, 'Double cutaway center block Streamliner with Broad Tron pickups.'),
  ('electric_guitar', 'Gretsch', 'G2622T Streamliner Center Block with Bigsby', 'Streamliner', false, 'Center block Streamliner with Bigsby B70 vibrato.'),
  ('electric_guitar', 'Gretsch', 'G2622T-P90 Streamliner Center Block P90', 'Streamliner', false, 'Center block Streamliner with FideliSonic 90 pickups and Bigsby.'),
  ('electric_guitar', 'Gretsch', 'G2655 Streamliner Center Block Jr.', 'Streamliner', false, 'Compact center block Streamliner with smaller body.'),
  ('electric_guitar', 'Gretsch', 'G2655T Streamliner Center Block Jr. with Bigsby', 'Streamliner', false, 'Compact Streamliner with Bigsby vibrato tailpiece.'),
  ('electric_guitar', 'Gretsch', 'G5210-P90 Electromatic Jet Two 90', 'Electromatic', false, 'Solid body Electromatic Jet with two P90 soapbar pickups.'),
  ('electric_guitar', 'Gretsch', 'G5222 Electromatic Double Jet', 'Electromatic', false, 'Double cutaway solid body Jet with Black Top Broad Tron pickups.'),
  ('electric_guitar', 'Gretsch', 'G5230T Electromatic Jet FT', 'Electromatic', false, 'Single cutaway Jet with Bigsby and Black Top Broad Tron pickups.'),
  ('electric_guitar', 'Gretsch', 'G5232T Electromatic Double Jet FT', 'Electromatic', false, 'Double cutaway Jet FT with Bigsby vibrato.'),
  ('electric_guitar', 'Gretsch', 'G5260 Electromatic Jet Baritone', 'Electromatic', false, 'Baritone Jet with long scale for deep tunings.'),
  ('electric_guitar', 'Gretsch', 'G5260T Electromatic Jet Baritone with Bigsby', 'Electromatic', false, 'Baritone Electromatic Jet with Bigsby vibrato.'),
  ('electric_guitar', 'Gretsch', 'G5410T Electromatic Rat Rod', 'Electromatic', false, 'Hot rod styled hollow body with matte finish and Black Top Filtertron pickups.'),
  ('electric_guitar', 'Gretsch', 'G5422T Electromatic Hollow Body Double-Cut', 'Electromatic', false, 'Double cutaway hollow body with Bigsby and Black Top Filtertrons.'),
  ('electric_guitar', 'Gretsch', 'G5422TG Electromatic Hollow Body Double-Cut', 'Electromatic', true, 'Gold hardware version of the double cutaway Electromatic hollow body.'),
  ('electric_guitar', 'Gretsch', 'G5422G-12 Electromatic Hollow Body 12-String', 'Electromatic', false, 'Twelve string Electromatic hollow body with gold hardware.'),
  ('electric_guitar', 'Gretsch', 'G5622 Electromatic Center Block Double-Cut', 'Electromatic', false, 'Center block Electromatic with V stoptail and Broad Tron pickups.'),
  ('electric_guitar', 'Gretsch', 'G5655T Electromatic Center Block Jr.', 'Electromatic', false, 'Compact center block Electromatic with Bigsby.'),
  ('electric_guitar', 'Gretsch', 'G5655TG Electromatic Center Block Jr.', 'Electromatic', false, 'Junior center block Electromatic with gold hardware and Bigsby.'),
  ('electric_guitar', 'Gretsch', 'G6120T Players Edition Nashville', 'Professional Collection', false, 'Modern Nashville hollow body with string through Bigsby and locking tuners.'),
  ('electric_guitar', 'Gretsch', 'G6120T-BSSMK Brian Setzer Signature Nashville', 'Professional Collection', true, 'Brian Setzer signature Nashville with TV Jones Setzer pickups.'),
  ('electric_guitar', 'Gretsch', 'G6128T Players Edition Jet FT', 'Professional Collection', false, 'Professional Jet with Full Tron pickups and string through Bigsby.'),
  ('electric_guitar', 'Gretsch', 'G6128T-89 Vintage Select Duo Jet', 'Professional Collection', true, 'Reissue of the 1989 Duo Jet with Filtertron pickups and Bigsby.'),
  ('electric_guitar', 'Gretsch', 'G6129T-89 Vintage Select Sparkle Jet', 'Professional Collection', false, 'Silver sparkle top Jet reissue with vintage styling.'),
  ('electric_guitar', 'Gretsch', 'G6131-MY Malcolm Young Signature Jet', 'Professional Collection', false, 'Malcolm Young signature Jet with single bridge pickup and pinned bridge.'),
  ('electric_guitar', 'Gretsch', 'G6134T-58 Vintage Select Penguin', 'Professional Collection', false, 'White solid body reissue of the late fifties Penguin with Bigsby.'),
  ('electric_guitar', 'Gretsch', 'G6136T Players Edition Falcon', 'Professional Collection', true, 'Modern White Falcon hollow body with string through Bigsby.'),
  ('electric_guitar', 'Gretsch', 'G6136TG Players Edition Falcon', 'Professional Collection', false, 'Players Edition Falcon with gold hardware appointments.'),
  ('electric_guitar', 'Gretsch', 'G6636T Players Edition Falcon Center Block', 'Professional Collection', false, 'Center block Falcon that resists feedback at stage volume.'),
  ('electric_guitar', 'Gretsch', 'G6122T-62 Vintage Select Country Gentleman', 'Professional Collection', true, 'Reissue of the 1962 Chet Atkins Country Gentleman hollow body.'),
  ('electric_guitar', 'Gretsch', 'G6119T-62 Vintage Select Tennessee Rose', 'Professional Collection', false, 'Deep red 1962 style Tennessee Rose hollow body with Bigsby.'),
  ('electric_guitar', 'Gretsch', 'G6118T Players Edition Anniversary', 'Professional Collection', false, 'Two tone green Anniversary hollow body with Full Tron pickups.'),
  ('electric_guitar', 'Gretsch', 'G6659T Players Edition Broadkaster Jr.', 'Professional Collection', false, 'Compact center block Broadkaster with string through Bigsby.'),
  ('electric_guitar', 'Gretsch', 'G6609TG Players Edition Broadkaster', 'Professional Collection', false, 'Full size center block Broadkaster with gold hardware.'),
  ('electric_guitar', 'Music Man', 'Cutlass RS HSS', 'Cutlass', false, 'Modern Cutlass with roasted maple neck and humbucker single single layout.'),
  ('electric_guitar', 'Music Man', 'Cutlass RS SSS', 'Cutlass', false, 'Triple single coil Cutlass RS with vintage tremolo.'),
  ('electric_guitar', 'Music Man', 'Cutlass SSS', 'Cutlass', false, 'Original relaunch Cutlass with three single coils and oil finished neck.'),
  ('electric_guitar', 'Music Man', 'StingRay RS', 'StingRay', false, 'Modern StingRay guitar with roasted maple neck and dual humbuckers.'),
  ('electric_guitar', 'Music Man', 'Axis Super Sport', 'Axis', true, 'Axis variant with vintage tremolo and figured maple top.'),
  ('electric_guitar', 'Music Man', 'JP16', 'JP', true, 'John Petrucci signature with Floyd Rose and DiMarzio Illuminator pickups.'),
  ('electric_guitar', 'Music Man', 'Luke III', 'Luke', false, 'Steve Lukather signature with DiMarzio Transition pickups and vintage tremolo.'),
  ('electric_guitar', 'Music Man', 'Luke 4', 'Luke', false, 'Fourth generation Steve Lukather signature with updated electronics and body carve.'),
  ('electric_guitar', 'Music Man', 'Albert Lee', 'Albert Lee', false, 'Angular bodied Albert Lee signature favored for country picking.'),
  ('electric_guitar', 'Music Man', 'Valentine', 'Valentine', false, 'James Valentine signature with slab body and humbucker single coil pair.'),
  ('electric_guitar', 'Music Man', 'Mariposa', 'Mariposa', false, 'Omar Rodriguez Lopez signature with sleek offset body.'),
  ('electric_guitar', 'Music Man', 'Sabre', 'Sabre', false, 'Relaunched Sabre with figured maple top and custom humbuckers.'),
  ('electric_guitar', 'Music Man', 'St. Vincent', 'St. Vincent', true, 'Annie Clark signature with angular body and three mini humbuckers.'),
  ('electric_guitar', 'Music Man', 'St. Vincent Goldie', 'St. Vincent', false, 'Gold finished St. Vincent variant with custom wound pickups.'),
  ('electric_guitar', 'Music Man', 'Kaizen', 'Kaizen', false, 'Tosin Abasi signature with multiscale design and modern styling.'),
  ('electric_guitar', 'Music Man', 'Silhouette', 'Silhouette', true, 'Classic compact bodied Music Man design introduced in 1986.'),
  ('electric_guitar', 'Music Man', 'Silhouette Special', 'Silhouette', false, 'Silhouette variant with single coils and vintage tremolo.'),
  ('electric_guitar', 'Music Man', 'Steve Morse Signature', 'Steve Morse', false, 'Steve Morse signature known for its four pickup configuration.'),
  ('electric_guitar', 'Sterling by Music Man', 'Cutlass CT30SSS', 'Cutlass', false, 'Affordable Cutlass with three single coils and vintage tremolo.'),
  ('electric_guitar', 'Sterling by Music Man', 'Cutlass CT30HSS', 'Cutlass', false, 'Cutlass CT30 with humbucker bridge pickup.'),
  ('electric_guitar', 'Sterling by Music Man', 'Cutlass CT50HSS', 'Cutlass', false, 'Step up Cutlass with roasted maple neck and locking tuners.'),
  ('electric_guitar', 'Sterling by Music Man', 'Cutlass CT50 Plus', 'Cutlass', false, 'Premium import Cutlass with figured maple top and upgraded hardware.'),
  ('electric_guitar', 'Sterling by Music Man', 'Axis AX3S', 'Axis', false, 'Affordable version of the Axis with flame maple top veneer.'),
  ('electric_guitar', 'Sterling by Music Man', 'Axis AX40', 'Axis', false, 'Import Axis with figured maple top and locking tremolo.'),
  ('electric_guitar', 'Sterling by Music Man', 'JP60', 'JP', false, 'Import John Petrucci signature with mahogany body and modern tremolo.'),
  ('electric_guitar', 'Sterling by Music Man', 'JP70', 'JP', false, 'Seven string version of the import Petrucci signature.'),
  ('electric_guitar', 'Sterling by Music Man', 'JP150', 'JP', true, 'Flagship import John Petrucci signature with sculpted forearm scoop.'),
  ('electric_guitar', 'Sterling by Music Man', 'Majesty X', 'Majesty', true, 'Import version of the Petrucci Majesty with neck through design.'),
  ('electric_guitar', 'Sterling by Music Man', 'StingRay SR30', 'StingRay', false, 'Import version of the StingRay guitar relaunch.'),
  ('electric_guitar', 'Sterling by Music Man', 'StingRay SR50', 'StingRay', false, 'Upgraded import StingRay guitar with roasted maple neck.'),
  ('electric_guitar', 'Sterling by Music Man', 'Valentine', 'Valentine', false, 'Import James Valentine signature with slab single cutaway body.'),
  ('electric_guitar', 'Sterling by Music Man', 'Mariposa', 'Mariposa', false, 'Import Omar Rodriguez Lopez signature with offset styling.'),
  ('electric_guitar', 'Sterling by Music Man', 'St. Vincent', 'St. Vincent', false, 'Import Annie Clark signature with angular body and mini humbuckers.'),
  ('electric_guitar', 'Sterling by Music Man', 'Sabre', 'Sabre', false, 'Import Sabre with figured top and dual humbuckers.'),
  ('electric_guitar', 'Sterling by Music Man', 'Jason Richardson Cutlass', 'Cutlass', false, 'Jason Richardson signature Cutlass with high output humbuckers.'),
  ('electric_guitar', 'Sterling by Music Man', 'Kaizen', 'Kaizen', false, 'Import Tosin Abasi signature with multiscale fretboard.'),
  ('electric_guitar', 'EVH', 'Wolfgang USA', 'Wolfgang', true, 'US built Wolfgang with custom wound humbuckers and EVH branded Floyd Rose.'),
  ('electric_guitar', 'EVH', 'Wolfgang USA Edward Van Halen Signature', 'Wolfgang', false, 'USA Wolfgang built to the personal specs of Edward Van Halen.'),
  ('electric_guitar', 'EVH', 'Wolfgang Special QM', 'Wolfgang', false, 'Wolfgang Special with quilt maple top veneer.'),
  ('electric_guitar', 'EVH', 'Wolfgang Standard QM', 'Wolfgang', false, 'Wolfgang Standard with quilted maple top.'),
  ('electric_guitar', 'EVH', 'Striped Series', 'Striped Series', true, 'Iconic red white and black striped superstrat with Floyd Rose.'),
  ('electric_guitar', 'EVH', 'Striped Series Frankenstein Frankie', 'Striped Series', true, 'Relic replica of the famous Frankenstein guitar.'),
  ('electric_guitar', 'EVH', 'Striped Series ''78 Eruption', 'Striped Series', false, 'White and black striped model honoring the 1978 era.'),
  ('electric_guitar', 'EVH', 'Striped Series Circles', 'Striped Series', false, 'Striped Series with the white and black circles graphic.'),
  ('electric_guitar', 'EVH', 'Striped Series Shark', 'Striped Series', false, 'Purple burgundy model based on the famous Shark guitar.'),
  ('electric_guitar', 'EVH', 'Striped Series Star', 'Striped Series', false, 'Star graphic model based on a famous stage guitar.'),
  ('electric_guitar', 'EVH', '5150 Series Deluxe', '5150', false, 'Upgraded 5150 with figured top and stainless steel frets.'),
  ('electric_guitar', 'EVH', '5150 Series Deluxe Ash', '5150', false, '5150 Deluxe with swamp ash body and natural finish options.'),
  ('electric_guitar', 'EVH', 'SA-126 Special', 'SA-126', false, 'Semi hollow single cutaway developed with Wolfgang Van Halen.'),
  ('electric_guitar', 'Suhr', 'Classic S Antique', 'Classic', false, 'Classic S with light aging and vintage style appointments.'),
  ('electric_guitar', 'Suhr', 'Classic T Antique', 'Classic', false, 'Classic T with aged finish and vintage voiced pickups.'),
  ('electric_guitar', 'Suhr', 'Standard', 'Standard', true, 'Original Suhr double cutaway with carved maple top.'),
  ('electric_guitar', 'Suhr', 'Standard Plus', 'Standard', false, 'Standard with figured maple top and roasted maple neck.'),
  ('electric_guitar', 'Suhr', 'Modern Terra', 'Modern', false, 'Modern with textured earth tone finish and HH pickup set.'),
  ('electric_guitar', 'Suhr', 'Modern Satin', 'Modern', false, 'Streamlined Modern with satin finish and HSH pickups.'),
  ('electric_guitar', 'Suhr', 'Pete Thorn Signature', 'Signature', true, 'Pete Thorn signature with chambered body and Thornbucker pickups.'),
  ('electric_guitar', 'Suhr', 'Alt T', 'Alt', false, 'Alternative take on the T style with dual humbuckers.'),
  ('electric_guitar', 'Suhr', 'Andy Wood Modern T', 'Signature', false, 'Andy Wood signature T style built for modern country and rock.'),
  ('electric_guitar', 'Suhr', 'Classic JM', 'Classic', false, 'Offset Suhr with modern playability and versatile pickups.'),
  ('electric_guitar', 'G&L', 'ASAT Special', 'ASAT', true, 'ASAT with large Magnetic Field Design single coils for fat clean tones.'),
  ('electric_guitar', 'G&L', 'ASAT Deluxe', 'ASAT', false, 'Carved top ASAT with dual humbuckers.'),
  ('electric_guitar', 'G&L', 'ASAT Classic Bluesboy', 'ASAT', false, 'ASAT Classic with neck humbucker for warmer jazz and blues voices.'),
  ('electric_guitar', 'G&L', 'Comanche', 'Comanche', true, 'Double cutaway with hum canceling Z coil pickups.'),
  ('electric_guitar', 'G&L', 'Fallout', 'Fallout', true, 'Compact student body shape revived with P90 and humbucker combo.'),
  ('electric_guitar', 'G&L', 'Doheny', 'Doheny', false, 'Offset body G&L with vintage style single coils.'),
  ('electric_guitar', 'G&L', 'Legacy HB', 'Legacy', false, 'Legacy with bridge humbucker for added output.'),
  ('electric_guitar', 'G&L', 'Legacy Special', 'Legacy', false, 'Legacy variant with hotter pickups and blade switching.'),
  ('electric_guitar', 'G&L', 'Espada', 'Espada', false, 'Modern G&L solid body with Magnetic Field Design pickups.'),
  ('electric_guitar', 'G&L', 'Rampage', 'Rampage', false, 'Single humbucker shred machine revived from the eighties lineup.'),
  ('electric_guitar', 'G&L', 'SC-2', 'SC', false, 'Compact double cutaway with two MFD single coils.'),
  ('electric_guitar', 'G&L', 'Skyhawk', 'Skyhawk', false, 'Eighties era G&L double cutaway revived with three single coils.'),
  ('electric_guitar', 'G&L', 'Invader', 'Invader', false, 'Superstrat style G&L with humbucker and locking tremolo options.'),
  ('electric_guitar', 'G&L', 'Tribute ASAT Classic', 'Tribute', true, 'Import version of the classic G&L single cutaway.'),
  ('electric_guitar', 'G&L', 'Tribute ASAT Classic Bluesboy', 'Tribute', false, 'Import Bluesboy with neck humbucker and single coil bridge.'),
  ('electric_guitar', 'G&L', 'Tribute ASAT Special', 'Tribute', false, 'Import ASAT Special with jumbo MFD single coils.'),
  ('electric_guitar', 'G&L', 'Tribute ASAT Deluxe Carved Top', 'Tribute', false, 'Import carved top ASAT with dual humbuckers.'),
  ('electric_guitar', 'G&L', 'Tribute Legacy', 'Tribute', false, 'Import Legacy with three vintage style single coils.'),
  ('electric_guitar', 'G&L', 'Tribute Legacy HB', 'Tribute', false, 'Import Legacy with humbucker bridge pickup.'),
  ('electric_guitar', 'G&L', 'Tribute S-500', 'Tribute', false, 'Import S-500 with three MFD single coils.'),
  ('electric_guitar', 'G&L', 'Tribute Comanche', 'Tribute', false, 'Import Comanche with Z coil pickups.'),
  ('electric_guitar', 'G&L', 'Tribute Fallout', 'Tribute', false, 'Import Fallout with P90 neck and humbucker bridge.'),
  ('electric_guitar', 'G&L', 'Tribute Doheny', 'Tribute', false, 'Import offset Doheny with vintage voiced single coils.'),
  ('electric_guitar', 'Rickenbacker', '330/12', '300 Series', true, 'Twelve string version of the 330 with famous jangle.'),
  ('electric_guitar', 'Rickenbacker', '360/12', '300 Series', true, 'Deluxe twelve string semi hollow made famous in sixties pop.'),
  ('electric_guitar', 'Rickenbacker', '360/12C63', '300 Series', false, 'C series twelve string recreating the 1963 specification.'),
  ('electric_guitar', 'Rickenbacker', '620', '600 Series', false, 'Solid body cresting wave design with dual high gain pickups.'),
  ('electric_guitar', 'Rickenbacker', '660', '600 Series', false, 'Vintage styled solid body with toaster top pickups.'),
  ('electric_guitar', 'Rickenbacker', '660/12', '600 Series', false, 'Twelve string version of the 660 solid body.'),
  ('electric_guitar', 'Rickenbacker', '650C Colorado', '600 Series', false, 'Double cutaway solid body with humbucking pickups and chrome hardware.'),
  ('electric_guitar', 'Rickenbacker', '381V69', '300 Series', false, 'Deep carved body reissue of the sixties 381 with vintage appointments.'),
  ('electric_guitar', 'Rickenbacker', '350V63 Liverpool', '300 Series', false, 'Short scale semi hollow reissue with three toaster pickups.'),
  ('electric_guitar', 'Guild', 'Starfire I DC', 'Starfire', false, 'Affordable double cutaway semi hollow with LB-1 humbuckers.'),
  ('electric_guitar', 'Guild', 'Starfire I SC', 'Starfire', false, 'Single cutaway Starfire I with vintage styling.'),
  ('electric_guitar', 'Guild', 'Starfire I Jet 90', 'Starfire', false, 'Starfire variant with dual P90 pickups and stop tail bridge.'),
  ('electric_guitar', 'Guild', 'Starfire II ST', 'Starfire', false, 'Thin hollow body with stop tail and dual humbuckers.'),
  ('electric_guitar', 'Guild', 'Starfire IV ST', 'Starfire', false, 'Center block double cutaway with stop tail bridge.'),
  ('electric_guitar', 'Guild', 'Starfire V', 'Starfire', true, 'Center block Starfire with Guild vibrato tailpiece and master volume.'),
  ('electric_guitar', 'Guild', 'Starfire VI', 'Starfire', false, 'Top of the line Starfire with gold hardware and ebony board.'),
  ('electric_guitar', 'Guild', 'S-100 Polara', 'Polara', true, 'Solid body Guild classic with dual humbuckers and vintage rock pedigree.'),
  ('electric_guitar', 'Guild', 'S-100 Polara Kim Thayil', 'Polara', false, 'Kim Thayil signature Polara inspired by his Soundgarden workhorse.'),
  ('electric_guitar', 'Guild', 'Surfliner', 'Surfliner', true, 'Modern offset Guild with three distinct pickup voices.'),
  ('electric_guitar', 'Guild', 'Surfliner Deluxe', 'Surfliner', false, 'Surfliner with Guild floating vibrato and upgraded pickups.'),
  ('electric_guitar', 'Guild', 'M-75 Aristocrat', 'Aristocrat', false, 'Lightweight hollow single cutaway revived from the fifties catalog.'),
  ('electric_guitar', 'Guild', 'Bluesbird', 'Bluesbird', false, 'Chambered single cutaway with humbuckers and arched top.'),
  ('electric_guitar', 'Guild', 'S-200 T-Bird', 'T-Bird', false, 'Reissue of the sixties T-Bird solid body with dual pickups.'),
  ('electric_guitar', 'Guild', 'X-175 Manhattan', 'Archtop', false, 'Full depth archtop electric with dual humbuckers.'),
  ('electric_guitar', 'Guild', 'A-150 Savoy', 'Archtop', false, 'Vintage styled archtop electric with single pickup elegance.'),
  ('electric_guitar', 'Danelectro', '''59M NOS+', '59', true, 'Reissue of the 1959 double cutaway with NOS style lipstick pickups.'),
  ('electric_guitar', 'Danelectro', '''59XT', '59', true, 'Modified 59 shape with vibrato tailpiece and hotter pickups.'),
  ('electric_guitar', 'Danelectro', '''59 Divine', '59', false, 'Double cutaway 59 reissue with smooth playing feel and lipstick tones.'),
  ('electric_guitar', 'Danelectro', 'Stock ''59', '59', false, 'Faithful stock spec version of the 1959 shorthorn.'),
  ('electric_guitar', 'Danelectro', 'Blackout ''59', '59', false, 'All black 59 with blacked out hardware and hot lipstick pickups.'),
  ('electric_guitar', 'Danelectro', '''66BT', '66', false, 'Baritone version of the 66 body style for low tunings.'),
  ('electric_guitar', 'Danelectro', '''66', '66', false, 'Sixties inspired single cutaway with humbucker and lipstick pairing.'),
  ('electric_guitar', 'Danelectro', '''64', '64', false, 'Reissue of the 1964 body style with vibrato bridge.'),
  ('electric_guitar', 'Danelectro', '''84', '84', false, 'Reissue of a rare 1984 design with modern appointments.'),
  ('electric_guitar', 'Danelectro', 'Longhorn Baritone', 'Longhorn', false, 'Long scale baritone with the iconic Longhorn double cutaway shape.'),
  ('electric_guitar', 'Danelectro', 'Convertible', 'Convertible', false, 'Acoustic electric hybrid reissue with center soundhole design.'),
  ('electric_guitar', 'Danelectro', 'Hodad', 'Hodad', false, 'Surf inspired model with dual lipstick pickups and vibrato.'),
  ('electric_guitar', 'Danelectro', '''57', '57', false, 'Reissue of the 1957 shape with vintage style pickups.'),
  ('electric_guitar', 'Danelectro', 'Fifty Niner', '59', false, 'Fifty nine body with humbucker bridge and lipstick neck pickup.'),
  ('electric_guitar', 'D''Angelico', 'Premier DC', 'Premier', true, 'Affordable double cutaway semi hollow with stairstep tailpiece.'),
  ('electric_guitar', 'D''Angelico', 'Premier SS', 'Premier', false, 'Single cutaway semi hollow Premier with compact body.'),
  ('electric_guitar', 'D''Angelico', 'Premier EXL-1', 'Premier', false, 'Hollow body archtop Premier with floating mini humbucker.'),
  ('electric_guitar', 'D''Angelico', 'Premier Mini DC', 'Premier', false, 'Smaller bodied double cutaway semi hollow.'),
  ('electric_guitar', 'D''Angelico', 'Premier Bedford', 'Premier', false, 'Solid body offset Premier with versatile pickups.'),
  ('electric_guitar', 'D''Angelico', 'Premier Bedford SH', 'Premier', false, 'Semi hollow version of the offset Bedford.'),
  ('electric_guitar', 'D''Angelico', 'Premier Atlantic', 'Premier', false, 'Single cutaway solid body with set neck and humbuckers.'),
  ('electric_guitar', 'D''Angelico', 'Premier Brighton', 'Premier', false, 'Double cutaway solid body Premier with dual humbuckers.'),
  ('electric_guitar', 'D''Angelico', 'Excel DC', 'Excel', false, 'Upscale double cutaway semi hollow with Seymour Duncan pickups.'),
  ('electric_guitar', 'D''Angelico', 'Excel SS', 'Excel', true, 'Refined single cutaway semi hollow with stairstep tailpiece and block inlays.'),
  ('electric_guitar', 'D''Angelico', 'Excel EXL-1', 'Excel', false, 'Signature archtop hollow body with floating pickup and art deco details.'),
  ('electric_guitar', 'D''Angelico', 'Excel 59', 'Excel', false, 'Large hollow body inspired by the late fifties archtop era.'),
  ('electric_guitar', 'D''Angelico', 'Excel Mini DC Tour', 'Excel', false, 'Compact semi hollow designed for travel and stage.'),
  ('electric_guitar', 'D''Angelico', 'Deluxe Atlantic', 'Deluxe', true, 'Flagship solid body single cutaway with premium appointments.'),
  ('electric_guitar', 'D''Angelico', 'Deluxe DC', 'Deluxe', false, 'Top tier double cutaway semi hollow with gold hardware.'),
  ('electric_guitar', 'D''Angelico', 'Deluxe SS', 'Deluxe', false, 'Deluxe single cutaway semi hollow with premium finishes.'),
  ('electric_guitar', 'D''Angelico', 'Deluxe Bedford', 'Deluxe', false, 'Flagship offset solid body with boutique grade parts.'),
  ('electric_guitar', 'Reverend', 'Charger 290', 'Charger', false, 'Slab body Reverend with dual P90 style pickups and bass contour control.'),
  ('electric_guitar', 'Reverend', 'Charger HB', 'Charger', false, 'Charger with dual humbuckers and korina body.'),
  ('electric_guitar', 'Reverend', 'Jetstream 390', 'Jetstream', true, 'Offset Reverend with three P90 style pickups.'),
  ('electric_guitar', 'Reverend', 'Jetstream HB', 'Jetstream', false, 'Offset Jetstream with dual humbuckers and tremolo.'),
  ('electric_guitar', 'Reverend', 'Double Agent OG', 'Double Agent', true, 'Humbucker bridge and P90 neck combo with bass contour knob.'),
  ('electric_guitar', 'Reverend', 'Double Agent W', 'Double Agent', false, 'Double Agent with Wilkinson tremolo and korina body.'),
  ('electric_guitar', 'Reverend', 'Sensei RA', 'Sensei', false, 'Single cutaway Reverend with Railhammer pickups.'),
  ('electric_guitar', 'Reverend', 'Descent RA', 'Descent', false, 'Baritone Reverend with Railhammer pickups for low tunings.'),
  ('electric_guitar', 'Reverend', 'Six Gun HPP', 'Six Gun', false, 'Versatile bolt on with humbucker and dual P90 style pickups.'),
  ('electric_guitar', 'Reverend', 'Contender HB', 'Contender', false, 'Set neck single cutaway with dual humbuckers.'),
  ('electric_guitar', 'Reverend', 'Greg Koch Gristlemaster', 'Signature', true, 'Greg Koch signature T style with Fishman Fluence Gristle-Tone pickups.'),
  ('electric_guitar', 'Reverend', 'Greg Koch Gristle 90', 'Signature', false, 'Koch signature with a trio of P90 style pickups.'),
  ('electric_guitar', 'Reverend', 'Billy Corgan Signature', 'Signature', true, 'Billy Corgan signature with Railhammer Z-One pickups.'),
  ('electric_guitar', 'Reverend', 'Reeves Gabrels Signature', 'Signature', false, 'Reeves Gabrels signature with high output Railhammer pickups.'),
  ('electric_guitar', 'Reverend', 'Pete Anderson Eastsider T', 'Signature', false, 'Pete Anderson signature T style with chambered body.'),
  ('electric_guitar', 'Reverend', 'Pete Anderson Eastsider S', 'Signature', false, 'Pete Anderson signature S style with hot vintage single coils.'),
  ('electric_guitar', 'Reverend', 'Warhawk 390', 'Warhawk', false, 'Sharp edged offset with three P90 style pickups.'),
  ('electric_guitar', 'Reverend', 'Tricky Gomez RT', 'Tricky Gomez', false, 'Semi hollow Reverend with Revtron pickups and Bigsby.'),
  ('electric_guitar', 'Reverend', 'Club King 290', 'Club King', false, 'Lightweight semi hollow with dual P90 style pickups.'),
  ('electric_guitar', 'Reverend', 'Roundhouse', 'Roundhouse', false, 'Single cutaway Reverend with dual humbuckers and bass contour.'),
  ('electric_guitar', 'Reverend', 'Airsonic', 'Airsonic', false, 'Sleek carved top Reverend with dual humbuckers.'),
  ('electric_guitar', 'Reverend', 'Buckshot', 'Buckshot', false, 'Retro styled bolt on with bass contour control.'),
  ('electric_guitar', 'Reverend', 'Crosscut', 'Crosscut', false, 'T inspired Reverend with korina body and raw tone.'),
  ('electric_guitar', 'Godin', 'Session HT', 'Session', true, 'Canadian made S style with hardtail bridge and versatile pickups.'),
  ('electric_guitar', 'Godin', 'Stadium HT', 'Stadium', false, 'T style Godin with hardtail bridge and custom wound pickups.'),
  ('electric_guitar', 'Godin', 'Stadium ''59', 'Stadium', false, 'Vintage styled Stadium with fifties inspired appointments.'),
  ('electric_guitar', 'Godin', 'Summit Classic', 'Summit', false, 'Single cutaway carved top Godin with warm humbucker voicing.'),
  ('electric_guitar', 'Godin', 'xtSA', 'xtSA', false, 'Triple voice Godin with electric piezo and synth access outputs.'),
  ('electric_guitar', 'Godin', '5th Avenue Kingpin', '5th Avenue', true, 'Archtop hollow body with single P90 in the neck position.'),
  ('electric_guitar', 'Godin', '5th Avenue CW Kingpin II', '5th Avenue', false, 'Cutaway archtop with dual P90 pickups.'),
  ('electric_guitar', 'Godin', '5th Avenue Jazz', '5th Avenue', false, 'Jazz focused archtop with floating humbucker and elegant appointments.'),
  ('electric_guitar', 'Godin', 'Radiator', 'Radiator', false, 'Retro styled Godin revived with lipstick style pickups.'),
  ('electric_guitar', 'Godin', 'Montreal Premiere HT', 'Montreal', false, 'Canadian made semi hollow with lightweight construction.'),
  ('electric_guitar', 'Godin', 'LGXT', 'LGX', false, 'Solid body Godin with humbuckers piezo and synth access.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
