begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('guitar_amp', 'Marshall', 'JMP 2203', 'JMP', false, 'Classic 100 watt JMP 2203 master volume head from the late 70s.'),
  ('guitar_amp', 'Marshall', 'AVT50', 'AVT', false, '50 watt Advanced Valvestate Technology combo.'),
  ('guitar_amp', 'Marshall', 'AVT150', 'AVT', false, '150 watt AVT150 hybrid combo.'),
  ('guitar_amp', 'Fender', '68 Custom Pro Reverb', '68 Custom', false, '40 watt 68 Custom Pro Reverb 1x12 combo.'),
  ('guitar_amp', 'Fender', 'Deluxe 85', 'Red Knob', false, '85 watt Deluxe 85 solid-state combo from the late 80s.'),
  ('guitar_amp', 'Fender', 'Princeton Chorus', 'Chorus', false, 'Stereo Princeton Chorus solid-state combo.'),
  ('guitar_amp', 'Fender', 'Ultimate Chorus', 'Chorus', false, 'Stereo Ultimate Chorus 2x12 solid-state combo.'),
  ('guitar_amp', 'Fender', 'Champ 12', 'Champ', false, '12 watt Champ 12 tube combo with overdrive.'),
  ('guitar_amp', 'Fender', 'Stage 112SE', 'Stage', false, '160 watt Stage 112SE solid-state combo.'),
  ('guitar_amp', 'Fender', 'Performer 1000', 'Performer', false, '100 watt Performer 1000 hybrid combo.'),
  ('guitar_amp', 'Peavey', '5150 Head', '5150', true, 'Original Peavey 5150 head developed with Eddie Van Halen.'),
  ('guitar_amp', 'Peavey', '5150 212 Combo', '5150', false, '60 watt 5150 2x12 combo.'),
  ('guitar_amp', 'Peavey', '6534+', '6505', false, '120 watt 6534+ head with EL34 tubes.'),
  ('guitar_amp', 'Peavey', 'JSX', 'JSX', false, 'Joe Satriani JSX head with three channels.'),
  ('guitar_amp', 'Randall', 'RG100ES', 'RG', false, 'Classic RG100ES solid-state head made famous by Dimebag Darrell.'),
  ('guitar_amp', 'Crate', 'Blue Voodoo BV120H', 'Blue Voodoo', false, '120 watt Blue Voodoo tube head.'),
  ('guitar_amp', 'Line 6', 'Flextone III', 'Flextone', false, 'Flextone III modeling combo with tone presets.'),
  ('guitar_amp', 'Line 6', 'Vetta II', 'Vetta', false, 'Flagship Vetta II dual amp modeling combo.'),
  ('guitar_amp', 'Line 6', 'DT50 Head', 'DT', false, '50 watt DT50 tube head with Bogner designed power section.'),
  ('guitar_amp', 'Line 6', 'DT25 Head', 'DT', false, '25 watt DT25 tube head with modeling integration.'),
  ('guitar_amp', 'Line 6', 'DT25 112 Combo', 'DT', false, '25 watt DT25 1x12 combo.'),
  ('guitar_amp', 'Ampeg', 'VT-22', 'VT', false, 'Vintage VT-22 100 watt 2x12 guitar combo.'),
  ('guitar_amp', 'Ampeg', 'GVT52-112', 'GVT', false, '50 watt GVT52 1x12 tube combo.'),
  ('guitar_amp', 'Silvertone', '1484 Twin Twelve', '1484', false, 'Reissued 1484 Twin Twelve with vintage circuit.'),
  ('guitar_amp', 'Sunn', 'Model T', 'Model T', false, 'Reissued Model T 100 watt tube head with doom pedigree.'),
  ('guitar_amp', 'Sunn', 'Beta Lead', 'Beta', false, 'Classic Beta Lead solid-state head.'),
  ('guitar_amp', 'Music Man', 'HD-130', 'HD', false, 'Vintage HD-130 hybrid head with clean headroom.'),
  ('guitar_amp', 'Traynor', 'YCV50 Blue', 'YCV', false, '50 watt YCV50 Blue tube combo.'),
  ('guitar_amp', 'Splawn', 'Quick Rod', 'Quick Rod', false, '100 watt Quick Rod head with hot rodded British voicing.'),
  ('guitar_amp', 'Splawn', 'Nitro', 'Nitro', false, '100 watt Nitro head with aggressive gain.'),
  ('guitar_amp', '65amps', 'London', 'London', false, '18 watt London head with British voicing.'),
  ('guitar_amp', '65amps', 'Empire', 'Empire', false, '22 watt Empire head with chime and touch response.'),
  ('guitar_amp', 'Divided by 13', 'FTR 37', 'FTR', false, '37 watt FTR 37 hand wired head.'),
  ('guitar_amp', 'Divided by 13', 'CJ 11', 'CJ', false, '11 watt CJ 11 hand wired combo.'),
  ('guitar_amp', 'Swart', 'Atomic Space Tone', 'AST', false, 'Atomic Space Tone combo with tube tremolo and reverb.'),
  ('guitar_amp', 'Swart', 'STR-Tremolo', 'STR', false, 'STR-Tremolo hand wired combo.'),
  ('guitar_amp', 'Milkman', 'The Amp 100', 'The Amp', false, '100 watt pedal format The Amp with tube preamp.'),
  ('guitar_amp', 'Milkman', 'Creamer', 'Creamer', false, '20 watt Creamer hand wired combo with reverb.'),
  ('guitar_amp', 'Benson', 'Monarch', 'Monarch', false, '15 watt Monarch hand wired combo.'),
  ('guitar_amp', 'Benson', 'Chimera', 'Chimera', false, '30 watt Chimera hand wired head.'),
  ('guitar_amp', 'Benson', 'Vinny', 'Vinny', false, '1 watt Vinny recording amp.'),
  ('guitar_amp', 'Carr', 'Skylark', 'Skylark', false, '12 watt Skylark combo with attenuator.'),
  ('guitar_amp', 'Two-Rock', 'Bloomfield Drive', 'Bloomfield', false, 'Bloomfield Drive head with vintage American voicing.'),
  ('guitar_amp', 'Two-Rock', 'Traditional Clean', 'Traditional', false, 'Traditional Clean head with pristine headroom.'),
  ('guitar_amp', 'Budda', 'Superdrive 30', 'Superdrive', false, '30 watt Superdrive head with rich harmonic drive.'),
  ('guitar_amp', 'Fuchs', 'Overdrive Supreme 50', 'ODS', false, '50 watt Overdrive Supreme with smooth overdrive voicing.'),
  ('guitar_amp', 'Soldano', 'SLO Mini', 'SLO', false, '30 watt SLO Mini head with SLO-100 voicing.'),
  ('guitar_amp', 'Mesa Boogie', 'TransAtlantic TA-15', 'TransAtlantic', false, '15 watt TransAtlantic TA-15 lunchbox head.'),
  ('guitar_amp', 'Mesa Boogie', 'TransAtlantic TA-30', 'TransAtlantic', false, '30 watt TransAtlantic TA-30 head.'),
  ('guitar_amp', 'Mesa Boogie', 'Royal Atlantic RA-100', 'Royal Atlantic', false, '100 watt Royal Atlantic RA-100 head.'),
  ('guitar_amp', 'Mesa Boogie', 'Blue Angel', 'Blue Angel', false, 'Blue Angel combo with progressive linkage power section.'),
  ('guitar_amp', 'Mesa Boogie', 'Maverick', 'Maverick', false, 'Maverick dual rectifier combo with EL84 tubes.'),
  ('guitar_amp', 'Mesa Boogie', 'Single Rectifier Solo 50', 'Rectifier', false, '50 watt Single Rectifier Solo 50 head.'),
  ('guitar_amp', 'Mesa Boogie', 'Subway Rocket', 'Subway', false, 'Compact Subway Rocket combo from the 90s.'),
  ('guitar_amp', 'Orange', 'Thunderverb 50', 'Thunderverb', false, '50 watt Thunderverb head with two channels.'),
  ('guitar_amp', 'Orange', 'Thunderverb 200', 'Thunderverb', false, '200 watt Thunderverb head.'),
  ('guitar_amp', 'Orange', 'OR50', 'OR', false, '50 watt OR50 head with vintage single channel design.'),
  ('guitar_amp', 'Orange', 'Rocker 30', 'Rocker', false, 'Classic 30 watt Rocker 30 head.'),
  ('guitar_amp', 'Blackstar', 'HT Metal 5', 'HT Metal', false, '5 watt HT Metal 5 head with high gain voicing.'),
  ('guitar_amp', 'Boss', 'Katana-100/212 MkII', 'Katana', false, '100 watt Katana MkII with dual 12 inch speakers.'),
  ('guitar_amp', 'Yamaha', 'THR100H', 'THR', false, '100 watt THR100H modeling head.'),
  ('guitar_amp', 'Yamaha', 'THR100HD', 'THR', false, 'Dual 100 watt THR100HD modeling head.'),
  ('guitar_amp', 'Hughes & Kettner', 'Statesman Dual 6L6', 'Statesman', false, '60 watt Statesman Dual 6L6 combo.'),
  ('guitar_amp', 'Supro', 'Black Magick', 'Black Magick', false, '25 watt Black Magick reissue combo.'),
  ('guitar_amp', 'Vox', 'AC30CH', 'AC', false, '30 watt AC30 Custom head version.'),
  ('guitar_amp', 'DV Mark', 'Triple 6', 'Triple 6', false, '120 watt Triple 6 three channel high gain head.'),
  ('guitar_amp', 'Quilter', 'Tone Block 202', 'Tone Block', false, '200 watt Tone Block 202 compact head.'),
  ('bass_amp', 'Ampeg', 'Heritage B-15N', 'Heritage', false, 'US made Heritage B-15N flip top tube combo.'),
  ('bass_amp', 'Ampeg', 'SVT-2PRO', 'SVT', false, '300 watt SVT-2PRO all tube rack head.'),
  ('bass_amp', 'Eden', 'WT-800', 'World Tour', false, '800 watt WT-800 World Tour bass head.'),
  ('bass_amp', 'Gallien Krueger', '400RB-IV', 'RB', false, '280 watt 400RB-IV classic bass head.'),
  ('bass_amp', 'Gallien Krueger', 'MB210-II', 'MB', false, '500 watt MB210-II ultra light 2x10 combo.'),
  ('bass_amp', 'Gallien Krueger', 'Fusion 550', 'Fusion', false, '500 watt Fusion 550 head with tube preamp.'),
  ('bass_amp', 'SWR', 'SM-900', 'SM', false, '900 watt SM-900 flagship rack bass head.'),
  ('bass_amp', 'Markbass', 'Little Mark Ninja', 'Little Mark', false, 'Richard Bona signature Little Mark Ninja 1000 watt head.'),
  ('bass_amp', 'EBS', 'Fafner II', 'Fafner', false, '750 watt Fafner II dual channel bass head.'),
  ('bass_amp', 'EBS', 'TD660', 'TD', false, '660 watt TD660 bass head with tube preamp.'),
  ('bass_amp', 'TC Electronic', 'BQ250', 'BQ', false, '250 watt BQ250 compact bass head.'),
  ('bass_amp', 'Mesa Boogie', 'Prodigy Four:88', 'Prodigy', false, '250 watt Prodigy Four:88 all tube bass head.'),
  ('bass_amp', 'Mesa Boogie', 'Strategy Eight:88', 'Strategy', false, '465 watt Strategy Eight:88 all tube bass head.'),
  ('electric_guitar', 'Gibson', 'Les Paul Traditional', 'Les Paul', false, 'Les Paul Traditional with 57 Classic humbuckers.'),
  ('electric_guitar', 'Gibson', 'Les Paul 70s Deluxe', 'Les Paul', false, '70s Deluxe with mini humbuckers.'),
  ('electric_guitar', 'Gibson', 'Les Paul Special Tribute Humbucker', 'Les Paul', false, 'Special Tribute with dual humbuckers and satin finish.'),
  ('electric_guitar', 'Gibson', 'SG Tribute', 'SG', false, 'SG Tribute with 490 humbuckers and satin finish.'),
  ('electric_guitar', 'Gibson', '70s Explorer', 'Explorer', false, '70s Explorer with ceramic humbuckers.'),
  ('electric_guitar', 'Gibson', '80s Flying V', 'Flying V', false, '80s Flying V with Dirty Fingers pickups.'),
  ('electric_guitar', 'Gibson', 'ES-339 Figured', 'ES', false, 'ES-339 Figured with maple top and calibrated humbuckers.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Studio', 'Les Paul', false, 'Les Paul Studio with ProBucker style pickups.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Classic', 'Les Paul', false, 'Les Paul Classic with coil splitting.'),
  ('electric_guitar', 'Epiphone', 'Les Paul Custom', 'Les Paul', false, 'Les Paul Custom with gold hardware and ebony board.'),
  ('electric_guitar', 'Epiphone', 'SG Special P-90', 'SG', false, 'SG Special with dual P-90 pickups.'),
  ('electric_guitar', 'Epiphone', 'Dot Deluxe', 'ES', false, 'Dot Deluxe semi hollow with flamed maple veneer.'),
  ('electric_guitar', 'Epiphone', 'Riviera Custom P93', 'Riviera', false, 'Riviera Custom P93 with three P-90 pickups.'),
  ('electric_guitar', 'Epiphone', 'Explorer', 'Explorer', false, 'Epiphone Explorer with ProBucker pickups.'),
  ('electric_guitar', 'Epiphone', 'Firebird', 'Firebird', false, 'Epiphone Firebird with mini humbuckers.'),
  ('electric_guitar', 'Ibanez', 'RG350DXZ', 'RG', false, 'RG350DXZ with Edge Zero II tremolo.'),
  ('electric_guitar', 'Ibanez', 'GRG131DX', 'GIO', false, 'GIO GRG131DX with dual humbuckers.'),
  ('electric_guitar', 'LTD', 'EC-10', 'EC', false, 'Entry level EC-10 with dual ESP designed humbuckers.'),
  ('electric_guitar', 'LTD', 'H-1001', 'H', false, 'H-1001 with EMG 81/85 and neck through construction.'),
  ('electric_guitar', 'LTD', 'M-1001', 'M', false, 'M-1001 with Floyd Rose and single EMG pickup.'),
  ('electric_guitar', 'Schecter', 'Demon-7', 'Demon', false, '7-string Demon with active style humbuckers.'),
  ('electric_guitar', 'Schecter', 'Omen-8', 'Omen', false, '8-string Omen with extended range.'),
  ('electric_guitar', 'PRS', 'SE Standard 24', 'SE', false, 'SE Standard 24 with 85/15 S pickups.'),
  ('electric_guitar', 'PRS', 'SE Mira', 'SE', false, 'SE Mira with dual humbuckers and lightweight body.'),
  ('electric_guitar', 'PRS', 'SE McCarty 594 Singlecut', 'SE', false, 'SE McCarty 594 Singlecut with 58/15 LT S pickups.'),
  ('electric_guitar', 'Charvel', 'Pro-Mod DK24 HH 2PT CM', 'Pro-Mod DK', false, 'Pro-Mod DK24 with dual humbuckers and caramelized maple neck.'),
  ('electric_guitar', 'Jackson', 'JS11 Dinky', 'JS Series', false, 'Entry level JS11 Dinky with dual high output humbuckers.'),
  ('electric_guitar', 'Gretsch', 'G5232T Electromatic Double Jet FT', 'Electromatic', false, 'Electromatic Double Jet FT with Bigsby.'),
  ('electric_guitar', 'Yamaha', 'Revstar Element RSE20', 'Revstar', false, 'Revstar Element RSE20 with dual humbuckers.'),
  ('electric_guitar', 'Yamaha', 'SA2200', 'SA', false, 'Japan made SA2200 semi hollow with coil taps.'),
  ('electric_guitar', 'Harley Benton', 'SC-550 II', 'SC', false, 'SC-550 II with flamed top and Tesla pickups.'),
  ('electric_guitar', 'Harley Benton', 'Amarok-6', 'Amarok', false, 'Amarok-6 with multiscale option and modern styling.'),
  ('electric_guitar', 'Kramer', 'Baretta Special', 'Baretta', false, 'Affordable Baretta Special with single humbucker.'),
  ('electric_guitar', 'G&L', 'Tribute ASAT Classic', 'Tribute', false, 'Tribute ASAT Classic with MFD single-coils.'),
  ('electric_guitar', 'G&L', 'Tribute Legacy', 'Tribute', false, 'Tribute Legacy with vintage style alnico pickups.'),
  ('electric_guitar', 'G&L', 'Tribute S-500', 'Tribute', false, 'Tribute S-500 with three MFD single-coils.'),
  ('electric_guitar', 'EVH', 'Wolfgang WG Standard', 'Wolfgang', false, 'Wolfgang WG Standard with direct mount humbuckers.'),
  ('electric_guitar', 'Fender', 'Tom DeLonge Stratocaster', 'Artist', false, 'Tom DeLonge Strat with single Seymour Duncan Invader humbucker.'),
  ('bass_guitar', 'Ibanez', 'GSR205SM', 'Gio', false, '5-string Gio GSR205 with spalted maple top.'),
  ('bass_guitar', 'Fender', 'Vintera II 60s Bass VI', 'Vintera II', false, 'Vintera II 60s Bass VI with three pickups and short scale.'),
  ('bass_guitar', 'Squier', 'Affinity Bronco Bass', 'Affinity', false, 'Short scale Affinity Bronco Bass for beginners.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
