begin;

with seed(equipment_type, brand, model, series, is_popular, description) as (
  values
  ('electric_guitar', 'Fender', 'American Professional II Stratocaster', 'American Professional II', true, 'USA Stratocaster with V-Mod II single-coils and sculpted neck heel.'),
  ('electric_guitar', 'Fender', 'American Professional II Stratocaster HSS', 'American Professional II', true, 'USA Strat with HSS pickup layout and V-Mod II bridge humbucker.'),
  ('electric_guitar', 'Fender', 'American Professional II Stratocaster Left-Hand', 'American Professional II', false, 'Left-handed USA Stratocaster with V-Mod II pickups.'),
  ('electric_guitar', 'Fender', 'American Professional II Telecaster', 'American Professional II', true, 'USA Telecaster with V-Mod II single-coils and Deep C neck profile.'),
  ('electric_guitar', 'Fender', 'American Professional II Telecaster Deluxe', 'American Professional II', false, 'USA Tele Deluxe with dual V-Mod II humbuckers and modern feel.'),
  ('electric_guitar', 'Fender', 'American Professional II Telecaster Left-Hand', 'American Professional II', false, 'Left-handed USA Telecaster with V-Mod II single-coils.'),
  ('electric_guitar', 'Fender', 'American Professional II Jazzmaster', 'American Professional II', false, 'USA Jazzmaster with V-Mod II pickups and updated bridge.'),
  ('electric_guitar', 'Fender', 'American Professional II Jazzmaster Left-Hand', 'American Professional II', false, 'Left-handed USA Jazzmaster with V-Mod II pickups.'),
  ('electric_guitar', 'Fender', 'American Professional II Jaguar', 'American Professional II', false, 'USA Jaguar with V-Mod II pickups and refined switching.'),
  ('electric_guitar', 'Fender', 'American Professional I Stratocaster', 'American Professional I', false, 'First generation American Professional Strat with V-Mod pickups.'),
  ('electric_guitar', 'Fender', 'American Professional I Telecaster', 'American Professional I', false, 'First generation American Professional Tele with V-Mod pickups.'),
  ('electric_guitar', 'Fender', 'American Ultra Stratocaster', 'American Ultra', true, 'Modern USA Strat with Ultra Noiseless pickups and Modern D neck.'),
  ('electric_guitar', 'Fender', 'American Ultra Stratocaster HSS', 'American Ultra', false, 'Ultra Strat with HSS layout and Ultra Noiseless pickups.'),
  ('electric_guitar', 'Fender', 'American Ultra Telecaster', 'American Ultra', true, 'Modern USA Tele with Ultra Noiseless single-coils and contoured heel.'),
  ('electric_guitar', 'Fender', 'American Ultra Jazzmaster', 'American Ultra', false, 'Ultra Jazzmaster with Ultra Noiseless pickups and S-1 switching.'),
  ('electric_guitar', 'Fender', 'American Ultra II Stratocaster', 'American Ultra II', true, 'Second gen Ultra Strat with Haymaker humbucker option and refined electronics.'),
  ('electric_guitar', 'Fender', 'American Ultra II Stratocaster HSS', 'American Ultra II', false, 'Ultra II Strat HSS with Haymaker bridge humbucker.'),
  ('electric_guitar', 'Fender', 'American Ultra II Telecaster', 'American Ultra II', true, 'Second gen Ultra Tele with Ultra II Noiseless pickups.'),
  ('electric_guitar', 'Fender', 'American Ultra II Jazzmaster', 'American Ultra II', false, 'Ultra II Jazzmaster with modern pickups and S-1 switching.'),
  ('electric_guitar', 'Fender', 'American Ultra Luxe Stratocaster', 'American Ultra Luxe', false, 'Top spec Ultra Strat with Ultra Noiseless Vintage pickups and roasted maple neck.'),
  ('electric_guitar', 'Fender', 'American Ultra Luxe Stratocaster HSS Floyd Rose', 'American Ultra Luxe', false, 'Ultra Luxe Strat with Floyd Rose tremolo and HSS pickup layout.'),
  ('electric_guitar', 'Fender', 'American Ultra Luxe Telecaster', 'American Ultra Luxe', false, 'Top spec Ultra Tele with Ultra Noiseless Vintage single-coils.'),
  ('electric_guitar', 'Fender', 'American Ultra Luxe Telecaster HH Floyd Rose', 'American Ultra Luxe', false, 'Ultra Luxe Tele with dual humbuckers and Floyd Rose bridge.'),
  ('electric_guitar', 'Fender', 'American Vintage II 1957 Stratocaster', 'American Vintage II', true, '1957 spec USA Strat with pure vintage 57 single-coils and V neck.'),
  ('electric_guitar', 'Fender', 'American Vintage II 1961 Stratocaster', 'American Vintage II', false, '1961 spec USA Strat with slab rosewood board and pure vintage 61 pickups.'),
  ('electric_guitar', 'Fender', 'American Vintage II 1973 Stratocaster', 'American Vintage II', false, '1973 spec USA Strat with three bolt neck and bullet truss rod.'),
  ('electric_guitar', 'Fender', 'American Vintage II 1951 Telecaster', 'American Vintage II', true, '1951 spec USA Nocaster style Tele with vintage pickups and U neck.'),
  ('electric_guitar', 'Fender', 'American Vintage II 1963 Telecaster', 'American Vintage II', false, '1963 spec USA Tele with rosewood board and pure vintage 63 pickups.'),
  ('electric_guitar', 'Fender', 'American Vintage II 1975 Telecaster Deluxe', 'American Vintage II', false, '1975 spec Tele Deluxe with wide range humbuckers.'),
  ('electric_guitar', 'Fender', 'American Vintage II 1966 Jazzmaster', 'American Vintage II', false, '1966 spec USA Jazzmaster with pure vintage 66 pickups.'),
  ('electric_guitar', 'Fender', 'American Vintage II 1966 Jaguar', 'American Vintage II', false, '1966 spec USA Jaguar with pure vintage 66 single-coils.'),
  ('electric_guitar', 'Fender', 'American Original 50s Stratocaster', 'American Original', false, '50s spec USA Strat with pure vintage 59 pickups and soft V neck.'),
  ('electric_guitar', 'Fender', 'American Original 60s Stratocaster', 'American Original', false, '60s spec USA Strat with pure vintage 65 pickups.'),
  ('electric_guitar', 'Fender', 'American Original 50s Telecaster', 'American Original', false, '50s spec USA Tele with pure vintage 52 pickups.'),
  ('electric_guitar', 'Fender', 'American Original 60s Telecaster', 'American Original', false, '60s spec USA Tele with pure vintage 64 pickups.'),
  ('electric_guitar', 'Fender', 'American Original 60s Jazzmaster', 'American Original', false, '60s spec USA Jazzmaster with pure vintage 65 pickups.'),
  ('electric_guitar', 'Fender', 'American Original 60s Jaguar', 'American Original', false, '60s spec USA Jaguar with pure vintage 65 single-coils.'),
  ('electric_guitar', 'Fender', 'American Performer Stratocaster', 'American Performer', true, 'Accessible USA Strat with Yosemite single-coils and Greasebucket tone.'),
  ('electric_guitar', 'Fender', 'American Performer Stratocaster HSS', 'American Performer', false, 'USA Performer Strat with HSS pickup layout and DoubleTap humbucker.'),
  ('electric_guitar', 'Fender', 'American Performer Telecaster', 'American Performer', true, 'Accessible USA Tele with Yosemite single-coils and modern feel.'),
  ('electric_guitar', 'Fender', 'American Performer Telecaster Hum', 'American Performer', false, 'USA Performer Tele with DoubleTap neck humbucker.'),
  ('electric_guitar', 'Fender', 'American Performer Jazzmaster', 'American Performer', false, 'USA Performer Jazzmaster with Yosemite single-coils.'),
  ('electric_guitar', 'Fender', 'American Performer Mustang', 'American Performer', false, 'USA Performer Mustang with Yosemite single-coils and modern feel.'),
  ('electric_guitar', 'Fender', 'American Special Stratocaster', 'American Special', false, 'Discontinued USA Strat with Texas Special pickups and satin finish.'),
  ('electric_guitar', 'Fender', 'American Special Telecaster', 'American Special', false, 'Discontinued USA Tele with Texas Special pickups.'),
  ('electric_guitar', 'Fender', 'Player Stratocaster', 'Player', true, 'Mexico built Strat with Alnico V pickups and 22 medium jumbo frets.'),
  ('electric_guitar', 'Fender', 'Player Stratocaster HSS', 'Player', true, 'Mexico Player Strat with HSS layout and Player Series humbucker.'),
  ('electric_guitar', 'Fender', 'Player Stratocaster Plus Top', 'Player', false, 'Player Strat with plain maple flame top and Alnico V pickups.'),
  ('electric_guitar', 'Fender', 'Player Stratocaster HSH', 'Player', false, 'Player Strat with HSH pickup layout.'),
  ('electric_guitar', 'Fender', 'Player Telecaster', 'Player', true, 'Mexico built Tele with Player Series single-coils.'),
  ('electric_guitar', 'Fender', 'Player Telecaster HH', 'Player', false, 'Player Tele with dual Player Series humbuckers.'),
  ('electric_guitar', 'Fender', 'Player Jazzmaster', 'Player', false, 'Player Jazzmaster with Alnico single-coils.'),
  ('electric_guitar', 'Fender', 'Player Jaguar', 'Player', false, 'Player Jaguar with Player Series single-coils.'),
  ('electric_guitar', 'Fender', 'Player Mustang', 'Player', false, 'Player Mustang with Player Series single-coils.'),
  ('electric_guitar', 'Fender', 'Player Mustang 90', 'Player', false, 'Player Mustang with dual P-90 pickups.'),
  ('electric_guitar', 'Fender', 'Player Duo-Sonic', 'Player', false, 'Player Duo-Sonic with dual Player Series single-coils.'),
  ('electric_guitar', 'Fender', 'Player Duo-Sonic HS', 'Player', false, 'Player Duo-Sonic with HS pickup layout.'),
  ('electric_guitar', 'Fender', 'Player Lead II', 'Player', false, 'Player Lead II with two Player Series single-coils.'),
  ('electric_guitar', 'Fender', 'Player Lead III', 'Player', false, 'Player Lead III with dual Player Series humbuckers.'),
  ('electric_guitar', 'Fender', 'Player II Stratocaster', 'Player II', true, 'Updated Player II Strat with rolled fingerboard edges.'),
  ('electric_guitar', 'Fender', 'Player II Stratocaster HSS', 'Player II', false, 'Player II Strat with HSS pickup configuration.'),
  ('electric_guitar', 'Fender', 'Player II Telecaster HH', 'Player II', false, 'Player II Tele with dual humbuckers.'),
  ('electric_guitar', 'Fender', 'Player II Jazzmaster', 'Player II', false, 'Player II Jazzmaster with rolled edges and updated pickups.'),
  ('electric_guitar', 'Fender', 'Player II Jaguar', 'Player II', false, 'Player II Jaguar with modern comfort features.'),
  ('electric_guitar', 'Fender', 'Player II Mustang', 'Player II', false, 'Player II Mustang with rolled edges and modern feel.'),
  ('electric_guitar', 'Fender', 'Player II Modified Stratocaster HSS', 'Player II Modified', false, 'Player II Modified Strat with locking tuners and HSS layout.'),
  ('electric_guitar', 'Fender', 'Player II Modified Telecaster SH', 'Player II Modified', false, 'Player II Modified Tele with SH pickup layout and locking tuners.'),
  ('electric_guitar', 'Fender', 'Player Plus Stratocaster', 'Player Plus', true, 'Upgraded Player Plus Strat with Noiseless pickups and rolled edges.'),
  ('electric_guitar', 'Fender', 'Player Plus Stratocaster HSS', 'Player Plus', false, 'Player Plus Strat HSS with Noiseless single-coils and Fireball humbucker.'),
  ('electric_guitar', 'Fender', 'Player Plus Telecaster', 'Player Plus', true, 'Player Plus Tele with Noiseless single-coils and locking tuners.'),
  ('electric_guitar', 'Fender', 'Player Plus Nashville Telecaster', 'Player Plus', false, 'Player Plus Nashville Tele with three Noiseless pickups.'),
  ('electric_guitar', 'Fender', 'Player Plus Jazzmaster', 'Player Plus', false, 'Player Plus Jazzmaster with Fireball humbucker and single-coil.'),
  ('electric_guitar', 'Fender', 'Player Plus Meteora HH', 'Player Plus', false, 'Player Plus Meteora with dual Fireball humbuckers.'),
  ('electric_guitar', 'Fender', 'Player Plus Meteora SS', 'Player Plus', false, 'Player Plus Meteora with dual Noiseless single-coils.'),
  ('electric_guitar', 'Fender', 'Vintera 50s Stratocaster', 'Vintera', false, '50s spec Mexico Strat with vintage voiced pickups and V neck.'),
  ('electric_guitar', 'Fender', 'Vintera 50s Stratocaster Modified', 'Vintera', false, 'Modified 50s Strat with hot single-coils and modern neck.'),
  ('electric_guitar', 'Fender', 'Vintera 60s Stratocaster', 'Vintera', false, '60s spec Mexico Strat with rosewood board.'),
  ('electric_guitar', 'Fender', 'Vintera 60s Stratocaster Modified', 'Vintera', false, 'Modified 60s Strat with HSS pickup layout.'),
  ('electric_guitar', 'Fender', 'Vintera 70s Stratocaster', 'Vintera', false, '70s spec Mexico Strat with bullet truss rod and large headstock.'),
  ('electric_guitar', 'Fender', 'Vintera 50s Telecaster', 'Vintera', false, '50s spec Mexico Tele with vintage voiced pickups.'),
  ('electric_guitar', 'Fender', 'Vintera 50s Telecaster Modified', 'Vintera', false, 'Modified 50s Tele with hot single-coils and modern neck.'),
  ('electric_guitar', 'Fender', 'Vintera 60s Telecaster', 'Vintera', false, '60s spec Mexico Tele with vintage voiced pickups.'),
  ('electric_guitar', 'Fender', 'Vintera 60s Telecaster Modified', 'Vintera', false, 'Modified 60s Tele with humbuckers and modern neck.'),
  ('electric_guitar', 'Fender', 'Vintera 70s Telecaster Custom', 'Vintera', false, '70s spec Tele Custom with wide range humbucker in the neck.'),
  ('electric_guitar', 'Fender', 'Vintera 70s Telecaster Deluxe', 'Vintera', false, '70s spec Tele Deluxe with dual wide range humbuckers.'),
  ('electric_guitar', 'Fender', 'Vintera 60s Jazzmaster', 'Vintera', false, '60s spec Mexico Jazzmaster with vintage voiced pickups.'),
  ('electric_guitar', 'Fender', 'Vintera 60s Jazzmaster Modified', 'Vintera', false, 'Modified 60s Jazzmaster with hot pickups and adjustomatic bridge.'),
  ('electric_guitar', 'Fender', 'Vintera 60s Jaguar', 'Vintera', false, '60s spec Mexico Jaguar with vintage voiced single-coils.'),
  ('electric_guitar', 'Fender', 'Vintera 60s Jaguar Modified HH', 'Vintera', false, 'Modified 60s Jaguar with dual humbuckers.'),
  ('electric_guitar', 'Fender', 'Vintera 60s Mustang', 'Vintera', false, '60s spec Mexico Mustang with vintage voiced single-coils.'),
  ('electric_guitar', 'Fender', 'Vintera 70s Mustang', 'Vintera', false, '70s spec Mexico Mustang with vintage voiced pickups.'),
  ('electric_guitar', 'Fender', 'Vintera II 50s Stratocaster', 'Vintera II', true, 'Refined Vintera II Strat with 50s specs and modern playability.'),
  ('electric_guitar', 'Fender', 'Vintera II 60s Stratocaster', 'Vintera II', false, 'Vintera II Strat with 60s spec rosewood board and vintage pickups.'),
  ('electric_guitar', 'Fender', 'Vintera II 70s Stratocaster', 'Vintera II', false, 'Vintera II Strat with 70s style bullet truss and hot single-coils.'),
  ('electric_guitar', 'Fender', 'Vintera II 50s Nocaster', 'Vintera II', false, 'Vintera II Nocaster style Tele with vintage voice pickups.'),
  ('electric_guitar', 'Fender', 'Vintera II 60s Telecaster', 'Vintera II', false, 'Vintera II 60s Tele with rosewood board and vintage pickups.'),
  ('electric_guitar', 'Fender', 'Vintera II 70s Telecaster Deluxe', 'Vintera II', false, 'Vintera II 70s Tele Deluxe with wide range humbuckers.'),
  ('electric_guitar', 'Fender', 'Vintera II 70s Telecaster Thinline', 'Vintera II', false, 'Vintera II 70s semi hollow Tele Thinline with wide range humbuckers.'),
  ('electric_guitar', 'Fender', 'Vintera II 50s Jazzmaster', 'Vintera II', false, 'Vintera II 50s spec Jazzmaster with vintage voiced pickups.'),
  ('electric_guitar', 'Fender', 'Vintera II 60s Jazzmaster', 'Vintera II', false, 'Vintera II 60s Jazzmaster with vintage voiced single-coils.'),
  ('electric_guitar', 'Fender', 'Vintera II 70s Jaguar', 'Vintera II', false, 'Vintera II 70s Jaguar with vintage voiced pickups.'),
  ('electric_guitar', 'Fender', 'Vintera II 70s Competition Mustang', 'Vintera II', false, 'Vintera II 70s Mustang with competition stripe and vintage voiced pickups.'),
  ('electric_guitar', 'Fender', 'Aerodyne Special Stratocaster HSS', 'Aerodyne Special', false, 'Modern Aerodyne Strat with contoured body and HSS Noiseless pickups.'),
  ('electric_guitar', 'Fender', 'Aerodyne Special Telecaster', 'Aerodyne Special', false, 'Modern Aerodyne Tele with sculpted heel and Noiseless pickups.'),
  ('electric_guitar', 'Fender', 'Aerodyne Special Jazzmaster', 'Aerodyne Special', false, 'Modern Aerodyne Jazzmaster with contoured body and Noiseless pickups.'),
  ('electric_guitar', 'Fender', 'JV Modified 50s Stratocaster HSS', 'JV Modified', false, 'Japan built JV Modified Strat with HSS layout and updated feel.'),
  ('electric_guitar', 'Fender', 'JV Modified 60s Stratocaster', 'JV Modified', false, 'Japan built JV Modified Strat with 60s spec.'),
  ('electric_guitar', 'Fender', 'JV Modified 60s Custom Telecaster', 'JV Modified', false, 'Japan built JV Modified Custom Tele with humbucker in the neck.'),
  ('electric_guitar', 'Fender', 'Made in Japan Traditional 50s Stratocaster', 'Made in Japan Traditional', false, 'Japan Traditional 50s Strat with vintage voiced pickups.'),
  ('electric_guitar', 'Fender', 'Made in Japan Traditional 60s Stratocaster', 'Made in Japan Traditional', false, 'Japan Traditional 60s Strat with rosewood board.'),
  ('electric_guitar', 'Fender', 'Made in Japan Traditional 70s Stratocaster', 'Made in Japan Traditional', false, 'Japan Traditional 70s Strat with large headstock and hot pickups.'),
  ('electric_guitar', 'Fender', 'Made in Japan Traditional 50s Telecaster', 'Made in Japan Traditional', false, 'Japan Traditional 50s Tele with vintage pickups.'),
  ('electric_guitar', 'Fender', 'Made in Japan Traditional 60s Telecaster', 'Made in Japan Traditional', false, 'Japan Traditional 60s Tele with rosewood board.'),
  ('electric_guitar', 'Fender', 'Made in Japan Traditional 60s Jaguar', 'Made in Japan Traditional', false, 'Japan Traditional 60s Jaguar with vintage voiced pickups.'),
  ('electric_guitar', 'Fender', 'Made in Japan Traditional 60s Jazzmaster', 'Made in Japan Traditional', false, 'Japan Traditional 60s Jazzmaster with vintage voiced pickups.'),
  ('electric_guitar', 'Fender', 'Made in Japan Hybrid II Stratocaster', 'Made in Japan Hybrid II', false, 'Japan Hybrid II Strat combining classic looks with modern feel.'),
  ('electric_guitar', 'Fender', 'Made in Japan Hybrid II Telecaster', 'Made in Japan Hybrid II', false, 'Japan Hybrid II Tele with vintage looks and modern playability.'),
  ('electric_guitar', 'Fender', 'Made in Japan Elemental Stratocaster HH', 'Made in Japan Elemental', false, 'Japan Elemental Strat with dual humbuckers and modern comfort.'),
  ('electric_guitar', 'Fender', 'Made in Japan Elemental Jazzmaster', 'Made in Japan Elemental', false, 'Japan Elemental Jazzmaster with modern hardware and pickups.'),
  ('electric_guitar', 'Fender', 'Made in Japan Elemental Stratocaster', 'Made in Japan Elemental', false, 'Japan Elemental Strat with contoured body and modern pickups.'),
  ('electric_guitar', 'Fender', 'Highway One Stratocaster', 'Highway One', false, 'Discontinued USA Strat with nitro thin skin finish and Alnico V pickups.'),
  ('electric_guitar', 'Fender', 'Highway One Telecaster', 'Highway One', false, 'Discontinued USA Tele with nitro thin skin finish.'),
  ('electric_guitar', 'Fender', 'Blacktop Stratocaster HH', 'Blacktop', false, 'Discontinued Blacktop Strat with dual hot humbuckers.'),
  ('electric_guitar', 'Fender', 'Blacktop Telecaster HH', 'Blacktop', false, 'Discontinued Blacktop Tele with dual hot humbuckers.'),
  ('electric_guitar', 'Fender', 'Blacktop Jaguar HH', 'Blacktop', false, 'Discontinued Blacktop Jaguar with dual hot humbuckers.'),
  ('electric_guitar', 'Fender', 'Blacktop Jazzmaster HS', 'Blacktop', false, 'Discontinued Blacktop Jazzmaster with humbucker and single-coil.'),
  ('electric_guitar', 'Fender', 'Pawn Shop Mustang Special', 'Pawn Shop', false, 'Pawn Shop Mustang Special with dual humbuckers.'),
  ('electric_guitar', 'Fender', 'Pawn Shop 70s Stratocaster Deluxe', 'Pawn Shop', false, 'Discontinued Pawn Shop 70s Deluxe Strat with humbucker and single-coils.'),
  ('electric_guitar', 'Fender', 'Pawn Shop 72', 'Pawn Shop', false, 'Discontinued Pawn Shop 72 with unusual body shape and P-90s.'),
  ('electric_guitar', 'Fender', 'Pawn Shop Bass VI', 'Pawn Shop', false, 'Discontinued Pawn Shop Bass VI baritone guitar.'),
  ('electric_guitar', 'Fender', 'Parallel Universe II Uptown Strat', 'Parallel Universe II', false, 'Parallel Universe Uptown Strat with dual humbuckers and unique appointments.'),
  ('electric_guitar', 'Fender', 'Parallel Universe II Jazz Tele', 'Parallel Universe II', false, 'Parallel Universe Tele with Jazzmaster style body and P-90s.'),
  ('electric_guitar', 'Fender', 'Parallel Universe II Maverick Dorado', 'Parallel Universe II', false, 'Parallel Universe Maverick Dorado with Bigsby and gold hardware.'),
  ('electric_guitar', 'Fender', 'Parallel Universe II Meteora HH', 'Parallel Universe II', false, 'Parallel Universe Meteora with dual humbuckers.'),
  ('electric_guitar', 'Fender', 'Parallel Universe II Troublemaker Tele', 'Parallel Universe II', false, 'Parallel Universe Troublemaker Tele with dual Shawbucker humbuckers.'),
  ('electric_guitar', 'Fender', 'Parallel Universe II Strat Jazz Deluxe', 'Parallel Universe II', false, 'Parallel Universe Strat with Jazz body wings and unique switching.'),
  ('electric_guitar', 'Fender', 'Acoustasonic Stratocaster', 'Acoustasonic', true, 'Acoustasonic Strat blending acoustic voicings with a Shawbucker.'),
  ('electric_guitar', 'Fender', 'Acoustasonic Telecaster', 'Acoustasonic', true, 'Acoustasonic Tele with multiple acoustic voicings and N4 pickup.'),
  ('electric_guitar', 'Fender', 'Acoustasonic Jazzmaster', 'Acoustasonic', false, 'Acoustasonic Jazzmaster with acoustic voicings and Shawbucker.'),
  ('electric_guitar', 'Fender', 'Acoustasonic Player Telecaster', 'Acoustasonic Player', false, 'Mexico built Acoustasonic Player Tele with three acoustic voicings.'),
  ('electric_guitar', 'Fender', 'Acoustasonic Player Jazzmaster', 'Acoustasonic Player', false, 'Mexico built Acoustasonic Player Jazzmaster with acoustic voicings.'),
  ('electric_guitar', 'Fender', 'Jim Root Stratocaster', 'Artist', false, 'Jim Root signature Strat with EMG active humbuckers and ebony board.'),
  ('electric_guitar', 'Fender', 'Jim Root Telecaster', 'Artist', false, 'Jim Root signature Tele with EMG active humbuckers.'),
  ('electric_guitar', 'Fender', 'Jim Root Jazzmaster', 'Artist', false, 'Jim Root signature Jazzmaster with EMG humbuckers.'),
  ('electric_guitar', 'Fender', 'Eric Clapton Stratocaster', 'Artist', true, 'Eric Clapton signature Strat with active mid boost and Vintage Noiseless pickups.'),
  ('electric_guitar', 'Fender', 'Stevie Ray Vaughan Stratocaster', 'Artist', true, 'SRV signature Strat with Texas Special pickups and lefty tremolo.'),
  ('electric_guitar', 'Fender', 'Jeff Beck Stratocaster', 'Artist', true, 'Jeff Beck signature Strat with Hot Noiseless pickups.'),
  ('electric_guitar', 'Fender', 'Yngwie Malmsteen Stratocaster', 'Artist', false, 'Yngwie signature Strat with scalloped fingerboard and DiMarzio pickups.'),
  ('electric_guitar', 'Fender', 'Ritchie Blackmore Stratocaster', 'Artist', false, 'Ritchie Blackmore signature Strat with scalloped board and Noiseless pickups.'),
  ('electric_guitar', 'Fender', 'Buddy Guy Stratocaster', 'Artist', false, 'Buddy Guy signature Strat with polka dot finish and Custom Shop Fat 50s pickups.'),
  ('electric_guitar', 'Fender', 'Eric Johnson Stratocaster', 'Artist', false, 'Eric Johnson signature Strat with quartersawn maple neck and thinner body.'),
  ('electric_guitar', 'Fender', 'Eric Johnson Thinline Stratocaster', 'Artist', false, 'Semi hollow Eric Johnson Strat with resonant chambered body.'),
  ('electric_guitar', 'Fender', 'Eric Johnson Signature Virginia Stratocaster', 'Artist', false, 'Eric Johnson Virginia Strat with sassafras body and gold hardware.'),
  ('electric_guitar', 'Fender', 'Brad Paisley Road Worn Telecaster', 'Artist', false, 'Brad Paisley signature Road Worn Tele with paisley finish and custom pickups.'),
  ('electric_guitar', 'Fender', 'Richie Kotzen Telecaster', 'Artist', false, 'Richie Kotzen signature Tele with DiMarzio pickups and coil split.'),
  ('electric_guitar', 'Fender', 'Richie Kotzen Stratocaster', 'Artist', false, 'Richie Kotzen signature Strat with DiMarzio pickups.'),
  ('electric_guitar', 'Fender', 'Ed OBrien EOB Stratocaster', 'Artist', false, 'Ed OBrien signature Strat with Sustainer system in neck position.'),
  ('electric_guitar', 'Fender', 'H.E.R. Stratocaster', 'Artist', false, 'H.E.R. signature Strat with roasted maple neck and Vintage Noiseless pickups.'),
  ('electric_guitar', 'Fender', 'Tash Sultana Stratocaster', 'Artist', false, 'Tash Sultana signature Strat with roasted maple neck.'),
  ('electric_guitar', 'Fender', 'Mike McCready Stratocaster', 'Artist', false, 'Mike McCready signature 1960 Strat with heavy relic finish.'),
  ('electric_guitar', 'Fender', 'Tom Morello Soul Power Stratocaster', 'Artist', false, 'Tom Morello signature Soul Power Strat with EMG humbucker and single-coils.'),
  ('electric_guitar', 'Fender', 'Kurt Cobain Jaguar', 'Artist', false, 'Kurt Cobain signature Jaguar with DiMarzio humbuckers.'),
  ('electric_guitar', 'Fender', 'Kurt Cobain Jag-Stang', 'Artist', false, 'Kurt Cobain Jag-Stang combining Jaguar and Mustang features.'),
  ('electric_guitar', 'Fender', 'Kurt Cobain Mustang', 'Artist', false, 'Kurt Cobain signature Mustang in vintage white.'),
  ('electric_guitar', 'Fender', 'John Mayer Silver Sky', 'Artist', false, 'John Mayer designed Strat style guitar (predecessor to PRS Silver Sky in Fender era).'),
  ('electric_guitar', 'Fender', 'Robert Cray Stratocaster', 'Artist', false, 'Robert Cray signature Strat with vintage voiced pickups and hardtail bridge.'),
  ('electric_guitar', 'Fender', 'Michael Landau Coma Stratocaster', 'Artist', false, 'Michael Landau signature Coma Strat with heavy relic finish.'),
  ('electric_guitar', 'Fender', 'Vintera 60s Telecaster Bigsby', 'Vintera', false, 'Vintera 60s Tele with factory installed Bigsby vibrato.'),
  ('electric_guitar', 'Fender', 'Meteora Player Plus', 'Player Plus', false, 'Player Plus Meteora with offset body and dual humbuckers.'),
  ('electric_guitar', 'Fender', 'Player Stratocaster Left-Hand', 'Player', false, 'Left-handed Player Stratocaster.'),
  ('electric_guitar', 'Fender', 'Player Telecaster Left-Hand', 'Player', false, 'Left-handed Player Telecaster.'),
  ('electric_guitar', 'Fender', 'American Ultra II Stratocaster Left-Hand', 'American Ultra II', false, 'Left-handed American Ultra II Stratocaster.'),
  ('electric_guitar', 'Squier', 'Sonic Stratocaster', 'Sonic', true, 'Entry level Sonic Strat with ceramic pickups and 2 point tremolo.'),
  ('electric_guitar', 'Squier', 'Sonic Stratocaster HSS', 'Sonic', false, 'Sonic Strat with HSS pickup configuration.'),
  ('electric_guitar', 'Squier', 'Sonic Stratocaster HT', 'Sonic', false, 'Sonic Strat with hardtail bridge.'),
  ('electric_guitar', 'Squier', 'Sonic Stratocaster HT H', 'Sonic', false, 'Sonic Strat with hardtail and single humbucker.'),
  ('electric_guitar', 'Squier', 'Sonic Telecaster', 'Sonic', true, 'Entry level Sonic Tele with ceramic pickups.'),
  ('electric_guitar', 'Squier', 'Sonic Esquire H', 'Sonic', false, 'Sonic Esquire with single humbucker.'),
  ('electric_guitar', 'Squier', 'Sonic Mustang', 'Sonic', false, 'Sonic Mustang with dual ceramic single-coils.'),
  ('electric_guitar', 'Squier', 'Sonic Mustang HH', 'Sonic', false, 'Sonic Mustang with dual humbuckers.'),
  ('electric_guitar', 'Squier', 'Sonic Bronco Stratocaster', 'Sonic', false, 'Short scale Sonic Bronco Strat for smaller players.'),
  ('electric_guitar', 'Squier', 'Affinity Stratocaster', 'Affinity', true, 'Affinity Strat with ceramic single-coils and 2 point tremolo.'),
  ('electric_guitar', 'Squier', 'Affinity Stratocaster HSS', 'Affinity', true, 'Affinity Strat with HSS pickup layout.'),
  ('electric_guitar', 'Squier', 'Affinity Stratocaster HSS Pack', 'Affinity', false, 'Affinity Stratocaster HSS bundled with amp and accessories.'),
  ('electric_guitar', 'Squier', 'Affinity Telecaster', 'Affinity', true, 'Affinity Tele with ceramic single-coils.'),
  ('electric_guitar', 'Squier', 'Affinity Telecaster Deluxe', 'Affinity', false, 'Affinity Tele Deluxe with dual humbuckers.'),
  ('electric_guitar', 'Squier', 'Affinity Telecaster Left-Hand', 'Affinity', false, 'Left-handed Affinity Telecaster.'),
  ('electric_guitar', 'Squier', 'Affinity Jazzmaster', 'Affinity', false, 'Affinity Jazzmaster with dual humbuckers.'),
  ('electric_guitar', 'Squier', 'Affinity Starcaster', 'Affinity', false, 'Semi hollow Affinity Starcaster with dual humbuckers.'),
  ('electric_guitar', 'Squier', 'Bullet Stratocaster HSS', 'Bullet', false, 'Discontinued Bullet Strat with HSS pickup layout.'),
  ('electric_guitar', 'Squier', 'Bullet Mustang HH', 'Bullet', false, 'Discontinued Bullet Mustang with dual humbuckers.'),
  ('electric_guitar', 'Squier', 'Bullet Telecaster', 'Bullet', false, 'Discontinued Bullet Telecaster with ceramic pickups.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 50s Stratocaster', 'Classic Vibe', true, 'Classic Vibe 50s Strat with Alnico single-coils and vintage vibe.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 60s Stratocaster', 'Classic Vibe', true, 'Classic Vibe 60s Strat with Alnico single-coils and 60s spec.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 60s Stratocaster HSS', 'Classic Vibe', false, 'Classic Vibe 60s Strat with HSS pickup layout.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 70s Stratocaster HSS', 'Classic Vibe', false, 'Classic Vibe 70s Strat with large headstock and HSS layout.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 50s Telecaster', 'Classic Vibe', true, 'Classic Vibe 50s Tele with Alnico single-coils and vintage feel.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 60s Telecaster Custom', 'Classic Vibe', false, 'Classic Vibe 60s Tele Custom with bound body and Alnico pickups.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 60s Telecaster Thinline', 'Classic Vibe', false, 'Classic Vibe 60s semi hollow Tele Thinline with Alnico pickups.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 70s Telecaster Custom', 'Classic Vibe', false, 'Classic Vibe 70s Tele Custom with wide range humbucker in the neck.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 70s Telecaster Deluxe', 'Classic Vibe', false, 'Classic Vibe 70s Tele Deluxe with dual wide range humbuckers.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 70s Telecaster Thinline', 'Classic Vibe', false, 'Classic Vibe 70s semi hollow Tele Thinline.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 60s Jazzmaster', 'Classic Vibe', false, 'Classic Vibe 60s Jazzmaster with Alnico pickups and vintage vibe.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 60s Jazzmaster Left-Hand', 'Classic Vibe', false, 'Left-handed Classic Vibe 60s Jazzmaster.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 70s Jaguar', 'Classic Vibe', false, 'Classic Vibe 70s Jaguar with Alnico single-coils.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 60s Custom Esquire', 'Classic Vibe', false, 'Classic Vibe 60s Custom Esquire with single bridge pickup.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 60s Mustang', 'Classic Vibe', false, 'Classic Vibe 60s Mustang with Alnico single-coils.'),
  ('electric_guitar', 'Squier', 'Classic Vibe 60s Competition Mustang', 'Classic Vibe', false, 'Classic Vibe 60s Competition Mustang with racing stripes.'),
  ('electric_guitar', 'Squier', 'Classic Vibe Starcaster', 'Classic Vibe', false, 'Classic Vibe semi hollow Starcaster with dual humbuckers.'),
  ('electric_guitar', 'Squier', 'Contemporary Stratocaster HH FR', 'Contemporary', false, 'Contemporary Strat with dual humbuckers and Floyd Rose tremolo.'),
  ('electric_guitar', 'Squier', 'Contemporary Stratocaster HSS', 'Contemporary', false, 'Contemporary Strat with HSS pickup layout and hot bridge humbucker.'),
  ('electric_guitar', 'Squier', 'Contemporary Stratocaster Special HT', 'Contemporary', false, 'Contemporary Special Strat with hardtail bridge.'),
  ('electric_guitar', 'Squier', 'Contemporary Telecaster RH', 'Contemporary', false, 'Contemporary Tele RH with dual humbuckers and hardtail bridge.'),
  ('electric_guitar', 'Squier', 'Contemporary Active Starcaster', 'Contemporary', false, 'Contemporary semi hollow Starcaster with active humbuckers.'),
  ('electric_guitar', 'Squier', 'Contemporary Active Jazzmaster HH', 'Contemporary', false, 'Contemporary Jazzmaster with active humbuckers.'),
  ('electric_guitar', 'Squier', 'Paranormal Cabronita Telecaster Thinline', 'Paranormal', false, 'Paranormal Cabronita semi hollow Tele Thinline with Fideli-Tron pickups.'),
  ('electric_guitar', 'Squier', 'Paranormal Custom Nashville Stratocaster', 'Paranormal', false, 'Paranormal Custom Nashville Strat with three single-coils and pickguard mounted controls.'),
  ('electric_guitar', 'Squier', 'Paranormal Jazzmaster XII', 'Paranormal', false, 'Paranormal 12-string Jazzmaster with Alnico pickups.'),
  ('electric_guitar', 'Squier', 'Paranormal Baritone Cabronita Telecaster', 'Paranormal', false, 'Paranormal baritone Cabronita Tele with Fideli-Tron pickups.'),
  ('electric_guitar', 'Squier', 'Paranormal Toronado', 'Paranormal', false, 'Paranormal Toronado with dual Atomic humbuckers.'),
  ('electric_guitar', 'Squier', 'Paranormal Offset Telecaster', 'Paranormal', false, 'Paranormal offset body Tele with unusual body contour.'),
  ('electric_guitar', 'Squier', 'Paranormal Super-Sonic', 'Paranormal', false, 'Paranormal Super-Sonic with reversed body and dual humbuckers.'),
  ('electric_guitar', 'Squier', 'Paranormal Esquire Deluxe', 'Paranormal', false, 'Paranormal Esquire Deluxe with single humbucker and modern feel.'),
  ('electric_guitar', 'Squier', 'Paranormal Custom Bass VI', 'Paranormal', false, 'Paranormal Bass VI style baritone with three Jaguar style pickups.'),
  ('electric_guitar', 'Squier', '40th Anniversary Stratocaster Gold Edition', '40th Anniversary', false, '40th Anniversary Strat in Gold Edition with gold hardware.'),
  ('electric_guitar', 'Squier', '40th Anniversary Stratocaster Vintage Edition', '40th Anniversary', false, '40th Anniversary Strat in Vintage Edition with aged finish.'),
  ('electric_guitar', 'Squier', '40th Anniversary Telecaster Gold Edition', '40th Anniversary', false, '40th Anniversary Tele in Gold Edition with gold hardware.'),
  ('electric_guitar', 'Squier', '40th Anniversary Telecaster Vintage Edition', '40th Anniversary', false, '40th Anniversary Tele in Vintage Edition with aged finish.'),
  ('electric_guitar', 'Squier', '40th Anniversary Jazzmaster Gold Edition', '40th Anniversary', false, '40th Anniversary Jazzmaster in Gold Edition.'),
  ('electric_guitar', 'Squier', 'FSR Classic Vibe 60s Competition Mustang', 'Classic Vibe', false, 'Limited FSR Classic Vibe 60s Competition Mustang.'),
  ('electric_guitar', 'Squier', 'FSR Classic Vibe 70s Competition Mustang', 'Classic Vibe', false, 'Limited FSR Classic Vibe 70s Competition Mustang.'),
  ('electric_guitar', 'Squier', 'FSR Bullet Competition Mustang HH', 'Bullet', false, 'Limited FSR Bullet Competition Mustang with dual humbuckers.'),
  ('electric_guitar', 'Squier', 'Affinity Jaguar HH', 'Affinity', false, 'Affinity Jaguar with dual humbuckers.'),
  ('electric_guitar', 'Squier', 'Debut Series Stratocaster', 'Debut', false, 'Beginner Debut Series Strat with ceramic pickups.'),
  ('electric_guitar', 'Squier', 'Debut Series Telecaster', 'Debut', false, 'Beginner Debut Series Tele with ceramic pickups.'),
  ('electric_guitar', 'Squier', 'Debut Series Stratocaster HSS', 'Debut', false, 'Beginner Debut Series Strat with HSS pickup layout.')
)
insert into public.equipment (
  equipment_type, brand, model, series, display_name, description,
  is_popular, sort_order, status, genres, tone_characteristics, search_terms
)
select
  seed.equipment_type::public.equipment_type,
  seed.brand,
  seed.model,
  seed.series,
  concat_ws(' ', seed.brand, seed.model),
  seed.description,
  seed.is_popular,
  row_number() over (partition by seed.equipment_type, seed.brand order by seed.is_popular desc, seed.model asc),
  'active'::public.equipment_status,
  case
    when seed.equipment_type in ('electric_guitar', 'guitar_amp') then array['rock', 'hard_rock', 'blues']::public.equipment_genre[]
    when seed.equipment_type in ('bass_guitar', 'bass_amp') then array['rock', 'pop', 'funk']::public.equipment_genre[]
    else array['rock']::public.equipment_genre[]
  end,
  case
    when seed.equipment_type = 'electric_guitar' then array['balanced', 'dynamic', 'articulate']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_guitar' then array['punchy', 'tight', 'balanced']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'guitar_amp' then array['clean', 'crunch', 'dynamic']::public.equipment_tone_characteristic[]
    when seed.equipment_type = 'bass_amp' then array['clean_headroom', 'punchy', 'tight']::public.equipment_tone_characteristic[]
    else array['balanced']::public.equipment_tone_characteristic[]
  end,
  '{}'::text[]
from seed
on conflict (equipment_type, brand, model) do nothing;

commit;
